### PR TITLE
Fix three bugs found in RRFS test

### LINKED ISSUE #702: The EnKF compiling failed with RRFS option
The "vars2d_landonly" was added in "gridinfo_gfs.f90" but no in other gridinfo files.
When compile EnKF with other gridinfo (for example fv3reg), the enkf will fail.

### LINKED ISSUE #703: Add checking surface terrain to "sfc_var_exist"
The "sfc_var_exist" was added in "gsi_rfv3io_mod.f90" to check if the surface fields are available in fv3lam background.
But it missed the check to the surface terrain field. Need to add surface terrain to the "sfc_var_exist".

### LINKED ISSUE #704: The case selection bug for FED GSI DA
Hongli found a case selection bug for FED GSI DA. It will not affect any current retros with a configuration for operation because it is assimilated along with dbz DA. It will show errors when only fed assimilated. 

The line is here: 
https://github.com/NOAA-EMC/GSI/blob/develop/src/gsi/cplr_get_fv3_regional_ensperts.f90#L432-L433

           ! only if_model_fed is true
           if(.not.l_use_dbz_directDA .and. .not.if_model_dbz .and. .not.if_model_fed) i_caseflag=3

.not.if_model_fed needs to be changed to  if_model_fed.

### PR DESCRIPTION
**Pull request by hu5970**
**DUE DATE for merger of this PR into `develop` is 4/2/2024 (six weeks after PR creation).**

**Description**

We found three bugs in RRFS test:
1) add "vars2d_landonly" to regional gridinfo files for compiling. 
2) add terrain to "sfc_var_exist" check
3) fix case selection bug for FED GSI DA.

Resolves #704 
Resolves #702
Resolves #703 

**Type of change**
 Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
Those fixes are tested with full RRFS cases and with several cycles of RRFS retro.

**Checklist**

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

File: src/gsi/gsi_rfv3io_mod.f90
Comment (xyzemc) [inline src/gsi/gsi_rfv3io_mod.f90:1]: Thanks for catching this important bug.

**Review by xyzemc — APPROVED** [review]

File: src/enkf/gridinfo_nmmb.f90 [hunk 1]
```diff
@@ -25,6 +25,8 @@ module gridinfo
                                                                                 'cw', 'prse', 'ql', 'qr', 'qi',    &
                                                                                 'qli', 'dbz', 'w'/)
 character(len=max_varname_length),public, dimension(2) :: vars2d_supported = (/ 'ps', 'sst' /)
```
Comment (hongli-wang) [inline src/enkf/gridinfo_nmmb.f90:27]: Not related to this PR. But I am curious, here (and gridinfo_wrf.90) the dimension of vars2d_supported is 2, however, it is 3 in gridinfo_fv3reg.f90. 
https://github.com/NOAA-EMC/GSI/pull/705/files#diff-a41d072f43b85f6a5068c61b92effaf58095c81e9a6bd6ea63734389c6e0766aR79-R81

**Review by hongli-wang — APPROVED** [review]
I have comment but it is not related to this PR.  
This PR look good to me.  Approved.

**Review by ShunLiu-NOAA — APPROVED** [review]

File: src/enkf/gridinfo_nmmb.f90 (hunk 1 above)
Comment (hu5970) [reply src/enkf/gridinfo_nmmb.f90:27]: Each model background has their own ways of define the surface fields. I think those variables were defined based on their land surface model.

File: src/enkf/gridinfo_fv3reg.f90
Comment (ClaraDraper-NOAA) [inline src/enkf/gridinfo_fv3reg.f90:1]: This is necessary as inflation.f90 has this line. 

use gridinfo, only: ...  vars2d_landonly

gridinfo_nmmb.f90 and   gridinfo_wrf.f90 wil both fail or the same reason. Can we add the same line as added here to those?

Comment (hu5970) [reply src/enkf/gridinfo_fv3reg.f90:1]: Agree. I added then same line in gridinfo_nmmb.f90 and gridinfo_wrf.f90. Please review.

Comment (ClaraDraper-NOAA) [reply src/enkf/gridinfo_fv3reg.f90:1]: Thanks Ming!

**Review by ClaraDraper-NOAA — APPROVED** [review]

**Comment by ShunLiu-NOAA** [comment]
@xyzemc @ClaraDraper-NOAA @hongli-wang Thank you for reviewing this PR. @hu5970 could you please start regression test?

**Comment by hu5970** [comment]
Thanks for reviewing. I am working on regression tests.

**Comment by hu5970** [comment]
Regression tests from Dogwood:

```
[ming.hu@dlogin08 build] ctest -j7
Test project /lfs/h2/emc/ptmp/Ming.Hu/code/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............***Failed  604.47 sec
2/7 Test #7: global_enkf ......................   Passed  793.08 sec
3/7 Test #3: rrfs_3denvar_glbens ..............***Failed  796.03 sec
4/7 Test #2: rtma .............................   Passed  1267.75 sec
5/7 Test #6: hafs_3denvar_hybens ..............***Failed  1274.49 sec
6/7 Test #5: hafs_4denvar_glbens ..............***Failed  1333.06 sec
7/7 Test #1: global_4denvar ...................   Passed  1622.93 sec

43% tests passed, 4 tests failed out of 7

Total Test time (real) = 1623.03 sec

The following tests FAILED:
	  3 - rrfs_3denvar_glbens (Failed)
	  4 - netcdf_fv3_regional (Failed)
	  5 - hafs_4denvar_glbens (Failed)
	  6 - hafs_3denvar_hybens (Failed)
Errors while running CTest
```

The 4 regional cases failed with the same reason:
```
The results between the two runs (rrfs_3denvar_glbens_loproc_updat and rrfs_3denvar_glbens_loproc_contrl) are not reproducible
The results between the two runs (hafs_3denvar_hybens_loproc_updat and hafs_3denvar_hybens_loproc_contrl) are not reproducible
The results between the two runs (hafs_4denvar_glbens_loproc_updat and hafs_4denvar_glbens_loproc_contrl) are not reproducible
The results (penalty) between the two runs are nonreproducible,
thus the regression test has Failed on cost for netcdf_fv3_regional_loproc_updat and netcdf_fv3_regional_loproc_contrl analyses.
```

The difference is from a bug in the surface field IO. This bug causes the all surface terrain to be 0 in the analysis. So this one line bug fix caused big difference in surface observation analysis. Without the bug fix, the most of the surface pressure observation are tossed. I check the results (fort.201) from two RRFS cases, the surface observation analysis goes back to normal.  The two HAFS cases shows little difference in the fort files. Because HAFS has not surface observations, the small difference in the 2nd and 3rd loop of the O-G are from the small O-B (o-g 01) difference in the radiance observations.

**Comment by hu5970** [comment]
The regression test results from Orion:
```
    Start 1: [=[global_4denvar]=]
    Start 2: [=[rtma]=]
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 4: [=[netcdf_fv3_regional]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 7: [=[global_enkf]=]
1/7 Test #4: [=[netcdf_fv3_regional]=] ........***Failed  484.17 sec
2/7 Test #7: [=[global_enkf]=] ................   Passed  489.17 sec
3/7 Test #3: [=[rrfs_3denvar_glbens]=] ........***Failed  545.78 sec
4/7 Test #2: [=[rtma]=] .......................   Passed  968.98 sec
5/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  1343.27 sec
6/7 Test #1: [=[global_4denvar]=] .............   Passed  1627.37 sec
7/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  1635.75 sec

43% tests passed, 4 tests failed out of 7

Total Test time (real) = 1635.76 sec

The following tests FAILED:
          3 - [=[rrfs_3denvar_glbens]=] (Failed)
          4 - [=[netcdf_fv3_regional]=] (Failed)
          5 - [=[hafs_4denvar_glbens]=] (Failed)
          6 - [=[hafs_3denvar_hybens]=] (Failed)
Errors while running CTest
```
I checked each failed regional cases and they showed the same reason of the crash as explained for the Dogwood regression test results.

**Comment by hu5970** [comment]
The regression results from Hera:

```
Test project /scratch1/BMC/wrfruc/mhu/code/gsi/GSI/build
  Test #1: global_4denvar
  Test #2: rtma
  Test #3: rrfs_3denvar_glbens
  Test #4: netcdf_fv3_regional
  Test #5: hafs_4denvar_glbens
  Test #6: hafs_3denvar_hybens
  Test #7: global_enkf

Total Tests: 7
[Ming.Hu@hfe03 build]$ ctest -j7
Test project /scratch1/BMC/wrfruc/mhu/code/gsi/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf

1/7 Test #7: global_enkf ......................   Passed  2915.68 sec
2/7 Test #3: rrfs_3denvar_glbens ..............***Failed  4453.39 sec
3/7 Test #4: netcdf_fv3_regional ..............***Failed  5651.86 sec
4/7 Test #6: hafs_3denvar_hybens ..............***Failed  7281.55 sec
5/7 Test #5: hafs_4denvar_glbens ..............***Failed  7284.66 sec
6/7 Test #1: global_4denvar ...................   Passed  7368.69 sec
7/7 Test #2: rtma .............................***Failed  10876.84 sec

29% tests passed, 5 tests failed out of 7

Total Test time (real) = 10876.87 sec

The following tests FAILED:
	  2 - rtma (Failed)
	  3 - rrfs_3denvar_glbens (Failed)
	  4 - netcdf_fv3_regional (Failed)
	  5 - hafs_4denvar_glbens (Failed)
	  6 - hafs_3denvar_hybens (Failed)
```

The reason of failure for rtma is:
```
The runtime for rtma_hiproc_updat is 228.858261 seconds.  This has exceeded maximum allowable threshold time of 211.810590 seconds,
resulting in Failure of timethresh2 the regression test.
```
This is not a critical failure.

The reason of failure for RRFS and HAFS is the same as ones on Dogwood and is explained before.

File: src/gsi/cplr_get_fv3_regional_ensperts.f90 [hunk 2]
```diff
@@ -430,7 +430,7 @@ subroutine get_fv3_regional_ensperts_run(this,en_perts,nelen,ps_bar)
            if(.not.l_use_dbz_directDA .and.      if_model_dbz .and. .not.if_model_fed) i_caseflag=2
 
            ! only if_model_fed is true
-           if(.not.l_use_dbz_directDA .and. .not.if_model_dbz .and. .not.if_model_fed) i_caseflag=3
+           if(.not.l_use_dbz_directDA .and. .not.if_model_dbz .and.      if_model_fed) i_caseflag=3
```
Comment (RussTreadon-NOAA) [inline src/gsi/cplr_get_fv3_regional_ensperts.f90:433]: Nitpick comment:  working with python and `pycodestyle` has made me more sensitive to white space.  Since `.not.` has been removed, remove extra white space.  A similar comment applies to logical tests in the block of code between [lines 427 to 439](https://github.com/hu5970/GSI/blob/9b77684b30db0cc8051e12c46845c62f4ed4840f/src/gsi/cplr_get_fv3_regional_ensperts.f90#L427-#L439).  Extra white space is being used to align logical tests.  This has a pleasing visual benefit when developing code but I'd remove the extra white space after the code is confirmed to work correctly.  The extra white space does no harm so this comment isn't requesting a change.

**Comment by RussTreadon-NOAA** [comment]
I do not see an explanation for why `netcdf_fv3_regional` fails?
```
The results (penalty) between the two runs are nonreproducible,
thus the regression test has Failed on cost for netcdf_fv3_regional_loproc_updat and netcdf_fv3_regional_loproc_contrl analyses.
```
Does this test fail for the [same reason](https://github.com/NOAA-EMC/GSI/pull/705#issuecomment-1960282686) as the rrfs and hafs tests?

**Comment by hu5970** [comment]
@RussTreadon-NOAA IN regression results comparison, the rrfs_3denvar_glbens, hafs_4denvar_glbens, hafs_3denvar_hybens have a step to compare the analysis results files, which shows the results as:
"The results between the two runs (rrfs_3denvar_glbens_loproc_updat and rrfs_3denvar_glbens_loproc_contrl) are not reproducible"

But "netcdf_fv3_regional" has no such step. But those four regional regression tests all has information:
"The results (penalty) between the two runs are nonreproducible,"

I think the two (cost difference and the analysis results difference) indicate the same reason of the failure. I manually compared fort files from each cases to confirm the difference are expected.

I did not add "netcdf_fv3_regional" to the step comparing the analysis files because I want to remove this case when I add more RRFS cases.

**Comment by RussTreadon-NOAA** [comment]
Agreed, @hu5970 .  I found the Dogwood directory in which your ctests ran.  The `netcdf_fv3_regional` test should a huge difference in the  number of assimilated ps obs.  The first outer loop of the _contrl_ assimilates 9460 ps obs whereas _updat_ assimilates 56513 ps obs.  Differences are also found in winds, radial winds, and radiances.  Wind and radial wind differences occur for types 224, 227, 280, 281, 284, 287, and 288.  The initial penalties for amsua_n15 differ slightly between _contrl_ and _updat_.  I assume all these differences are expected and explainable by the changes in this PR.  Is this correct?

The intent of `netcdf_fv3_regional` is to mimic the operational NAM, right?  I checked operational NAM analysis log files.  The number of assimilated ps obs in the operational NAM is closer to the _updat_ than the _contrl_.   Does this mean that somewhere along the way a PR introduced a netcdf_fv3_regional bug into the `develop`, a bug we missed?

**Comment by hu5970** [comment]
@Russ, the difference among those observation types are expected because the terrain in the GSI analysis with the bug is all  0. Any observation types that related terrain will show the difference in innovations. This is a bug that hurts all the analysis with fv3lam background. 

The netcdf_fv3_regional was the first GSI case with fv3lam background. I did not know if it tries to mimic the operational NAM or not. But its configuration is quite different from current RRFS and does not help RRFS GSI tests.

**Comment by RussTreadon-NOAA** [comment]
Got it.  I didn't realize that `netcdf_fv3_regional` may not be a ctest for operational NAM.
