### PR TITLE
Complete issue #607 (Optimization of multiscale regional runs)

### LINKED ISSUE #607: Optimization of multiscale regional runs
Code is in converge4 (branch optimize6) in my github repository

Shun Liu reported unexpected slow run times using the multiscale ensemble RRFS North American domain testing.  Runtimes when using dbz observations and conventional observations are reported to be about  943s.

The I/O for the ensembles was the first candidate for optimization.  After looking at it, it appears that this is done about as well as it can be done.  However, it is not clear why there are 2 different methods.  Looks like the slower and more complicated of the two should/could be removed.  Perhaps something for the future.

From there we went on to look at the observation I/O and initial processing.  The first thing that was noted was that there were many arrays allocated without a corresponding deallocate.  Adding these allocates significantly reduced the memory and page faults.

The read_satwnd routine appeared to be one of the slowest.  This is the one that was worked on first with significant changes.  It was noted that the subset (e.g., 'NC005099' ) was tested for every observation multiple times.  This really only needs to be tested once for each message (multiple observations).  The test was changed to be done on messages and the information was communicated to every observation through the tab array (istype).

Also in the satwnd, it was noted that there were 2  pmot options. "0." which passed on all observations which were not removed by the thinning and option "1." that includes all observations including thinned observations.   With the changes described in the following few paragraphs this capability was expanded to 4 options, included in other routines that do thinning and the process optimized.  

As part of the above changes, the convthin routines were modified to use less memory, two of the 4 thinning routines were removed and the algorithm simplified.  The simplified algorithm included removing the setting of the iloc array and set a bit flag in the rthin array if the data was flagged for thinning.  The data were not removed by the thinning if the option save_all was set to true (pmot=1 or 3).  This allows the data to be saved later in the diagnostic file (see new pmot options below). If save_all was false (pmot=0 or 2), some of the thinned data is removed within the convthin routines and the rest removed in the reading routine.  The removal of some of the thinned data in the convthin routines was done to increase the number of data that can be used and reduce computations.  Within the read_ routines that were modified, both the remaining rthin data and rusage data (data that does not pass QC but currently passed to the diagnostic files) may be removed based on the pmot options. 

In the read_ routines which used thinning, the code was modified to to include the pmot option currently in the read_satwnd routine.  Also, there were two new options added for pmot (see below).  

pmot = 0. Pass on all observations that fail the setup quality control, but not those that are thinned.
pmot = 1. Pass on all observations that fail the setup quality control and the obs that are thinned.
pmot = 2. Pass on only the observations that do not fail the quality control and are not thinned.
pmot = 3. Pass on only the observations that do not fail the quality control plus the obs that are thinned.

For pmot=1. and pmot=0. the same processing is used as is done now in read_satwnd.  The input pmot values from the convinfo file could/should be changed to integers, but I did not do this so that working scripts would not fail.

Note that in the above definitions, the "quality control" refers to only the quality control contained in the read routines that currently retains observations for the setup routines.  The idea of expanding to the 4 values of the pmot variable is primarily to include the pmot = 2. option.  In this case, the minimum number of observations will be passed from the read_ routines that would produce the same results.  This would decrease the size of the diagnostic files and decrease the number of observations passed to the setup routines every time they are called and hopefully speed up the code.  The pmot = 2. routine is consistent with what is done for the AVN analysis and the reduce_diag option.  Also, if the reduce_diag option is set and pmot is less than 2 (0. or 1.) then 2 is added to the pmot values  and the value is 2. or 3.

Note that the above options were added only to the routines that thin the data.  A simplified version could be added to other read_ routines to eliminate obs that do not pass the read_* qc. to reduce the amount of data passed on to the other setup* routines.

A list of the routines which the pmot options were added. Except where noted, pmot is defined in convinfo
1. read_dbz_nc.f90 (pmot_dbz hardwired to 2 in obsmod)
2. read_fl_hdob.f90
3. read_goesimgr_skycover.f90
4. read_l2bufr_mod.f90 
5. read_prepbufr.f90
6. read_radar.f90 (pmot_vr hardwired to 0 in obsmod)
7. read_radar_wind_ascii.f90 (pmot_vr hardwired to 0 in obsmod)
8. read_rapidscat.f90
9. read_satmar.f90
10. read_satwnd.f90
11. read_sfcwnd.f90
12. read_wcpbufr.f90

After making these changes, it was noted that the regression tests did not pass exactly (same starting penalty and gradient with small differences in the stepsize and following iterations).  After significant investigation it was found that in some of the current versions of the above routines, the earlier reordering routines were not properly implemented and the data did not retain the same order as they were read.  I was able to modify both the current GSI and the updated GSI to produce exactly the same ordering and was able to get identical results in the regression tests. 

However, the updated GSI used to produce the same ordering uses more memory and requires more processing.  So instead of retaining the ordering in the input data file, the new code orders the data as read in except when there are entries in the convinfo file for data of that type.  When there are entries in the convinfo file, the output data is ordered so that first the data that does not have an entry in the convinfo is output, then the data is output in the order of the convinfo entries.  Within each convinfo type, the order that they are read in is retained.

In addition to the above changes, the following changes were made.

1. Changes to parallelization of control2state routines.
2. The combination of ensctl2state and ensctl2state_ad into a single ensctl2state module with the inclusion of a ensctl2state_set routine to define flags once.  This is done in a way that is consistent with what is done with control2state above and allows the flags to be calculated once rather than repeatedly every time the routines are called.
3. Deallocating arrays in read_* routines that were left allocated. (removed considerable memory)
4. Making some of the muse flags in setup routines dependent on qc mark as well as usage flag.
5. Removing repeated print lines in windht after 10 prints.  Number of times it would have been printed is then output (kcount).  Removes lots of output for one regression test.
6. Removal of code that does nothing.
7. Some changes to parallelization to improve efficiency.
8. Inclusion of some if-then-else's instead of repeated if-then's
9. Some reuse of arrays rather than defining new arrays.
10. Printing full double precision digits for the global norms.
11. Some minor changes to comments and indentation to make them more correct and consistent.

### PR DESCRIPTION
**Pull request by jderber-NOAA**
**Description**

This issue was intended to speed up regional multiscale runs.  The initial parts of these changes were intended to speed up the initial processing of the observations.  Unfortunately, I only able to complete changes to the reading of the observations.

The changes include the addition of the deallocates for many of the allocates in the reading routines, a restructuring of the thinning process and the addition of some new options for input pmot values.  

The restructuring of the thinning process was to set flags for the data that was thinned and flags for data that was qc'ed in the read routine.  Then based on the input pmot value the data was compressed to only retain the desired data.  The pmot values are:

pmot = 0. Pass on all observations that fail the setup quality control, but not those that are thinned.
pmot = 1. Pass on all observations that fail the setup quality control and the obs that are thinned.
pmot = 2. Pass on only the observations that do not fail the quality control and are not thinned.
pmot = 3. Pass on only the observations that do not fail the quality control plus the obs that are thinned.

The pmot = 0 and 1 options are the same was in the read_satwnd routine before, but the change has been included for all routines that thin the input data using the convthin routines.  The intent was to allow an option to minimize the data that is passed on to the setup routines if desired.  This is similar to what is done for the global AVN runs as compared to the FNL runs, except is applicable to individual observation types.

The routines for which the above changes were made to are:

    read_dbz_nc.f90 (pmot_dbz hardwired to 2 in obsmod)
    read_fl_hdob.f90
    read_goesimgr_skycover.f90
    read_l2bufr_mod.f90
    read_prepbufr.f90
    read_radar.f90 (pmot_vr hardwired to 0 in obsmod)
    read_radar_wind_ascii.f90 (pmot_vr hardwired to 0 in obsmod)
    read_rapidscat.f90
    read_satmar.f90
    read_satwnd.f90
    read_sfcwnd.f90
    read_wcpbufr.f90

The values for pmot are defined as real numbers in the convinfo file (except where noted above).

In addition some other minor changes were made:

    1. Changes to parallelization of control2state routines.
    2. The combination of ensctl2state and ensctl2state_ad into a single ensctl2state module with the inclusion of a ensctl2state_set routine to define flags once. This is done in a way that is consistent with what is done with control2state above and allows the flags to be calculated once rather than repeatedly every time the routines are called.
    3. Deallocating arrays in read_* routines that were left allocated. (removed considerable memory)
    4. Making some of the muse flags in setup routines dependent on qc mark as well as usage flag.
    5. Removing repeated print lines in windht after 10 prints. Number of times it would have been printed is then output (kcount). Removes lots of output for one regression test.
    6. Removal of code that does nothing.
    7. Some small changes to parallelization to improve efficiency.
    8. Inclusion of some if-then-else's instead of repeated if-then's
    9. Some reuse of arrays rather than defining new arrays.
    10. Printing full double precision digits for the global norms.
    11. Some minor changes to comments and indentation to make them more correct and consistent.

Please see issue #607 for more details.
Fixes #607

**DUE DATE for merger of this PR into `develop` is 1/25/2024 (six weeks after PR creation).**

**Type of change**

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

These changes have been tested within the context of the global runs to ensure that they reproduce the current results.  

Also, the regression ctests were run.  When running the ctests it was noted that identical results were not found (minor round off level differences).  After extensive debugging it was found that some of the reading routines (read_radar, read_fl_hdob and read_radar_wind_ascii.f90 were not properly implemented to ensure that the observation order was retained.  In addition errors were found in the convthin and convthin_time routines.  The convthin and convthin_time routines probably did not impact the results.  All of the necessary changes are in Hera in /scratch1/NCEPDEV/da/John.Derber/converge4/fixdev.

Note after the control and new code produced ctest results that passed of all tests, the new code was modified to slightly change the order of the observations.  The changes were reorder the observations so that when convinfo entries for the data were available the data was ordered such that the first obs are those which do not have a convinfo entry and then the observations are ordered in the order of the convinfo entries.  Within each of these groups, the order of the reading of the data is retained.  This reordering results in some roundoff changes to the regression tests.

A final run of the ctests on Hera resulted in three of the regression tests not passing, but for those three regression tests only round-off differences were found.

ctest results:

1/7 Test #3: rrfs_3denvar_glbens ..............   Passed  668.02 sec
2/7 Test #4: netcdf_fv3_regional ..............   Passed  967.17 sec
3/7 Test #7: global_enkf ......................   Passed  996.21 sec
4/7 Test #6: hafs_3denvar_hybens ..............***Failed  1288.89 sec
5/7 Test #5: hafs_4denvar_glbens ..............***Failed  1465.38 sec
6/7 Test #2: rtma .............................   Passed  1630.76 sec
7/7 Test #1: global_4denvar ...................***Failed  1746.12 sec

57% tests passed, 3 tests failed out of 7

For the failed regression tests, the differences are very small.

For global_4denvar the difference over the first 5 iterations is:

New:
< Initial gradient norm =  1.700751272515123674E+03
< cost,grad,step,b,step? =   1   0  6.584168406980355503E+05  1.700751272515123674E+03  1.057429134927263981E+00  0.000000000000000000E+00  good
< cost,grad,step,b,step? =   1   1  6.547802752899467014E+05  2.113894264916129487E+03  1.927405067994359289E+00  1.302727127739899959E+00  good
< cost,grad,step,b,step? =   1   2  6.461427496709105326E+05  1.349310521414032110E+03  2.811042534667704373E+00  1.212753185604616535E+00  good
< cost,grad,step,b,step? =   1   3  6.308338990252234507E+05  1.492308135350379871E+03  3.826902315539039368E+00  4.828500088351426189E-01  good
< cost,grad,step,b,step? =   1   4  6.206079687548581278E+05  1.732872322582532661E+03  2.853763847749684945E+00  1.567453853347285486E+00  good
< cost,grad,step,b,step? =   1   5  6.086367270158508327E+05  2.052318345404916272E+03  2.200825030950578132E+00  1.123654808458361520E+00  good
---
Control:
> Initial gradient norm =  1.700751272515123446E+03
> cost,grad,step,b,step? =   1   0  6.584168406980355503E+05  1.700751272515123446E+03  1.057429134927265535E+00  0.000000000000000000E+00  good
> cost,grad,step,b,step? =   1   1  6.547802752899467014E+05  2.113894264916132670E+03  1.927405067994362176E+00  1.302727127739904844E+00  good
> cost,grad,step,b,step? =   1   2  6.461427496709105326E+05  1.349310521414032564E+03  2.811042534667710591E+00  1.212753185604620310E+00  good
> cost,grad,step,b,step? =   1   3  6.308338990252234507E+05  1.492308135350387374E+03  3.826902315539030930E+00  4.828500088351431740E-01  good
> cost,grad,step,b,step? =   1   4  6.206079687548580114E+05  1.732872322582532206E+03  2.853763847749785310E+00  1.567453853347265946E+00  good
> cost,grad,step,b,step? =   1   5  6.086367270158507163E+05  2.052318345404855336E+03  2.200825030951230499E+00  1.123654808458337984E+00  good

The penalties are identical for the first 3 iterations and the rest of the differences are only in the last few digits.
hafs_3denvar_hybens:

Control:
< cost,grad,step,b,step? =   1   0  1.484488764136420796E+05  5.220586731636382865E+03  3.266670310728393423E-01  0.000000000000000000E+00  good
< cost,grad,step,b,step? =   1   1  1.395457213798956072E+05  3.987278541138146920E+03  1.020272669622300121E+00  5.833302794603654196E-01  good
< cost,grad,step,b,step? =   1   2  1.214543780598063022E+05  2.282966557825236123E+03  1.175497927720148050E+00  3.579527393674070690E-01  good
< cost,grad,step,b,step? =   1   3  1.148424922169799393E+05  2.138015369099894997E+03  9.466815484382745671E-01  8.870869467349256077E-01  good
< cost,grad,step,b,step? =   1   4  1.101613679136846185E+05  3.525710978798607357E+03  7.850637926717303205E-01  2.702293955513371593E+00  good
< cost,grad,step,b,step? =   1   5  1.004694635052513186E+05  1.314894254315365288E+03  4.282579905121543185E+00  1.420689505641469230E-01  good
---
New:
> cost,grad,step,b,step? =   1   0  1.484488764136420796E+05  5.220586731636382865E+03  3.266670310728393978E-01  0.000000000000000000E+00  good
> cost,grad,step,b,step? =   1   1  1.395457213798956072E+05  3.987278541138147830E+03  1.020272669622299677E+00  5.833302794603657526E-01  good
> cost,grad,step,b,step? =   1   2  1.214543780598063022E+05  2.282966557825236578E+03  1.175497927720150937E+00  3.579527393674070135E-01  good
> cost,grad,step,b,step? =   1   3  1.148424922169799247E+05  2.138015369099901818E+03  9.466815484382588020E-01  8.870869467349332682E-01  good
> cost,grad,step,b,step? =   1   4  1.101613679136846331E+05  3.525710978798565066E+03  7.850637926717397574E-01  2.702293955513275225E+00  good
> cost,grad,step,b,step? =   1   5  1.004694635052513186E+05  1.314894254315372791E+03  4.282579905120070585E+00  1.420689505641908323E-01  good

The penalties are the same in iterations 1,2 and 5.  Other differences are small

hafs_4denvar_glbens:

Control:
> cost,grad,step,b,step? =   1   0  1.098322171332156431E+05  3.099058770311941316E+03  8.407846553134071810E-01  0.000000000000000000E+00  good
< cost,grad,step,b,step? =   1   1  1.017571823539604084E+05  1.946982757490602580E+03  2.124115380886761439E+00  3.946976915343667347E-01  good
< cost,grad,step,b,step? =   1   2  9.196514028700758354E+04  1.924285054946333275E+03  2.935424561242293784E+00  9.958096626362779036E-01  good
< cost,grad,step,b,step? =   1   3  8.060823346426019270E+04  1.393999917628704225E+03  2.990452695380884762E+00  6.239418852657658832E-01  good
< cost,grad,step,b,step? =   1   4  7.450440407439092814E+04  2.221145790520224182E+03  1.438639498276132356E+00  2.537376742307893895E+00  good
< cost,grad,step,b,step? =   1   5  6.737636465893953573E+04  1.031614475569622755E+03  6.726333681219393235E+00  2.239613119996544666E-01  good
---
New:< cost,grad,step,b,step? =   1   0  1.098322171332156431E+05  3.099058770311941316E+03  8.407846553134072920E-01  0.000000000000000000E+00  good
> cost,grad,step,b,step? =   1   1  1.017571823539604084E+05  1.946982757490602353E+03  2.124115380886762772E+00  3.946976915343667902E-01  good
> cost,grad,step,b,step? =   1   2  9.196514028700758354E+04  1.924285054946334185E+03  2.935424561242303110E+00  9.958096626362797910E-01  good
> cost,grad,step,b,step? =   1   3  8.060823346426019270E+04  1.393999917628710364E+03  2.990452695380865666E+00  6.239418852657728776E-01  good
> cost,grad,step,b,step? =   1   4  7.450440407439094270E+04  2.221145790520220999E+03  1.438639498276145234E+00  2.537376742307857480E+00  good
> cost,grad,step,b,step? =   1   5  6.737636465893956483E+04  1.031614475569631850E+03  6.726333681219014871E+00  2.239613119996727575E-01  good

All values (grad,step,b) are the same in iteration 0.  The penalties are the same in 0,1,2, and 3.  Other differences are small.

Since the code was tested with the same order of observations and produced no differences and the only differences are in the final digits, I conclude that the differences are only round-off due to different ordering of observations from the read_ routines.

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@ShunLiu-NOAA  and @hu5970 , since these changes impact regional GSI, would you one of you mind being the Handling Reviewer for this PR?

**Comment by ShunLiu-NOAA** [comment]
@shoyokota and @TingLei-NOAA Could you please review this PR?

**Comment by RussTreadon-NOAA** [comment]
> @shoyokota and @TingLei-NOAA Could you please review this PR?

Thank you @ShunLiu-NOAA

**Comment by TingLei-NOAA** [comment]
@ShunLiu-NOAA and @RussTreadon-NOAA  Thanks for invitation. I will do my reviewing as soon as possible.

**Comment by shoyokota** [comment]
@ShunLiu-NOAA @RussTreadon-NOAA Thanks for invitation. This PR is mainly for optimization of the part of reading observations rather than the multiscale DA, right? It may take time since I'm not familiar with this part in GSI, but I will try to review it.

**Comment by jderber-NOAA** [comment]
Thanks all for agreeing to do this review.

I may loose access to my noaa.gov email and Hera tomorrow or at a later time.  If there is a problem please e-mail me at mdjderber@gmail.com.

I should keep access on github (maybe under a different name, I will add my other e-mail to ticket so that I can respond to question.

Hope there are no problems!

Thanks again,

John

**Comment by jderber-NOAA** [comment]
Sorry for the change in format in the output from the ctests.  Not sure how to change it!

File: src/gsi/calctends_no_ad.f90 [hunk 1]
```diff
@@ -210,7 +211,7 @@ subroutine calctends_no_ad(st,vp,t,p,mype,u_t,v_t,t_t,p_t,uvflag)
       end do                         
     end if
 
-    call turbl_ad(ges_prsi(1,1,1,it),ges_tv,ges_teta(1,1,1,it),&
+    if(use_pbl)call turbl_ad(ges_prsi(1,1,1,it),ges_tv,ges_teta(1,1,1,it),&
```
Comment (TingLei-NOAA) [inline src/gsi/calctends_no_ad.f90:214]: @jderber-NOAA   If in calctends.f90,  there is no "use_pbl" to decide if its' forward sub (turbl) is called, I am wondering why the condition (if(use_pbl) is added?

Comment (TingLei-NOAA) [inline src/gsi/calctends_no_ad.f90:214]: @jderber-NOAA  a question about why , now use_pbl condition is required to call turbl_ad in calctends_no_ad.f90 and to call turbl_tl in calctends_no.f90  but not used to call turbl in calctends.f90.?  And, seems this change could cause differences in results, right? Will this be able to explain those tiny differences in your regression test?

Comment (jderber-NOAA) [reply src/gsi/calctends_no_ad.f90:214]: This is one of those things that I started to do, but just didn't have time to finish.  The turbl_ad, turbl_tl and turbl routines all had the first executable line saying if(.not.use_pbl)return.  So the use_pbl in the call for turbl_ad and turbl_tl was redundant and results should not change.

I have completed what I was doing and added a "if (use_pbl) call turbl..." for all the calls to the turbl routines (turbl_tl, turbl_ad, and turbl).  This is added in all of the calctends routines.  The use_pbl has been removed from all of the turbl routines.

Regression tests rerun.  Results are identical to above as expected.

Comment (TingLei-NOAA) [reply src/gsi/calctends_no_ad.f90:214]: Thanks for the explanation and clarification!

File: src/gsi/control_vectors.f90 [hunk 2]
```diff
@@ -113,7 +113,7 @@ module control_vectors
 public dot_product  
 public prt_control_norms, axpy, random_cv, setup_control_vectors, &
      write_cv, read_cv, inquire_cv, maxval, qdot_prod_sub, init_anacv, &
-     final_anacv,c2sset_flg
+     final_anacv,c2sset_flg,e2sset_flg
```
Comment (TingLei-NOAA) [inline src/gsi/control_vectors.f90:116]: @jderber-NOAA  ,Shall we add a comment for this new parameter?

File: src/gsi/general_commvars_mod.f90 [hunk 3]
```diff
@@ -49,6 +50,7 @@ module general_commvars_mod
    public :: s2g_cv                  !  structure used in bkerror.f90
    public :: s2g2                    !  structure used in getprs.f90
    public :: s2g4                    !  structure used in get_derivatives2.f90
+   public :: s2g4x                   !  structure used in get_derivatives2.f90
```
Comment (TingLei-NOAA) [inline src/gsi/general_commvars_mod.f90]: This variable : s2g4x , seemingly, is not used in the current GSI,though it is defined. Any planed changes using it?

File: src/gsi/hybrid_ensemble_isotropic.F90 [hunk 4]
```diff
@@ -1881,8 +1881,9 @@ subroutine ensemble_forward_model(cvec,a_en,ibin)
              do ig=1,ntotensgrp
                 iaens=ensgrp2aensgrp(ig,ic2+nc3d,ibin)
                 if(iaens>0) then
-                   do n=1,n_ens
-                      do j=1,jm
+!$omp parallel do schedule(static,1) private(j,n,k,i)
```
Comment (TingLei-NOAA) [inline src/gsi/hybrid_ensemble_isotropic.F90]: What is the benefit of flipping the order of n and j here? Should the n=1,n_ens be on the outer loop for it is on the dimension that changes slower in their storage?

File: src/gsi/hybrid_ensemble_parameters.f90 [hunk 5]
```diff
@@ -428,6 +429,8 @@ module hybrid_ensemble_parameters
   real(r_kind),allocatable:: region_lat_ens(:,:),region_lon_ens(:,:)
   real(r_kind),allocatable:: region_dx_ens(:,:),region_dy_ens(:,:)
 
+  logical sete2s_flg
```
Comment (TingLei-NOAA) [inline src/gsi/hybrid_ensemble_parameters.f90]: This variable is also not used , either.

File: src/gsi/obsmod.F90 [hunk 6]
```diff
@@ -631,7 +631,7 @@ module obsmod
   real(r_kind) ,allocatable,dimension(:):: dval
   real(r_kind) ,allocatable,dimension(:):: time_window
 
-  integer(i_kind) ntilt_radarfiles,tcp_posmatch,tcp_box
+  integer(i_kind) ntilt_radarfiles,tcp_posmatch,tcp_box,pmot_dbz,pmot_vr
```
Comment (TingLei-NOAA) [inline src/gsi/obsmod.F90:634]: seems those variables are added for future use...

File: src/gsi/obsmod.F90 [hunk 7]
```diff
@@ -631,7 +631,7 @@ module obsmod
...
```
Comment (TingLei-NOAA) [inline src/gsi/obsmod.F90:635]: why is pmot_dbz declared and defined here while it is used in read_dbz_nc?

File: src/gsi/control_vectors.f90 (hunk 2 above)
Comment (jderber-NOAA) [reply src/gsi/control_vectors.f90:116]: Not really a new parameter.  Initially set to true and then false after first call to ensctl2state_set so that ensctl2state_set is only called once.  Not specified externally.

File: src/gsi/general_commvars_mod.f90 (hunk 3 above)
Comment (jderber-NOAA) [reply src/gsi/general_commvars_mod.f90]: It is used in the updated version of the same subroutine.

File: src/gsi/hybrid_ensemble_isotropic.F90 (hunk 4 above)
Comment (jderber-NOAA) [reply src/gsi/hybrid_ensemble_isotropic.F90]: It is so that it can be threaded over j.

File: src/gsi/hybrid_ensemble_parameters.f90 (hunk 5 above)
Comment (jderber-NOAA) [reply src/gsi/hybrid_ensemble_parameters.f90]: Correct.  Code has been modified.

File: src/gsi/obsmod.F90 (hunk 7 above)
Comment (jderber-NOAA) [reply src/gsi/obsmod.F90:635]: Both pmot_dbz and pmot_vr are defined here when other variables are initialized.  They can be changed at the same time things like the length scales for the thinning, etc. (rmesh_dbz,rmesh_vr,...)are changed.

File: src/gsi/control_vectors.f90 (hunk 2 above)
Comment (TingLei-NOAA) [reply src/gsi/control_vectors.f90:116]: Yes. I see how it is used.  Maybe, a comment like " internal controlling parameter" would help?  but, it is fine for the current status.

File: src/gsi/general_commvars_mod.f90 (hunk 3 above)
Comment (TingLei-NOAA) [reply src/gsi/general_commvars_mod.f90]: @jderber-NOAA  . still a little confusing to me.  After updating my local copy, s2g4x is only used in " call general_sub2grid_destroy_info" after it is defined in "call general_sub2grid_create_info". It doesn't have any interactions with other variables/processes.  Then, what is the usage of this variable?  Did I still miss something?

File: src/gsi/hybrid_ensemble_isotropic.F90 (hunk 4 above)
Comment (TingLei-NOAA) [reply src/gsi/hybrid_ensemble_isotropic.F90]: Thanks.  In current gsi runs,  the used openmp threads are normally smaller than the standard ensemble size (n_ens=30 for rrfs and 80 for gfs), so, i think using multiple threads on n is fine while avoiding potential issue i mentioned above. 
And, shall we add openmp to other places (not only here for case(ps).)?    but I understand this is a work supposedly planed to be done in the future.   So, just please make sure the flipping does show benefits (theoretically or practically).  Thanks.

File: src/gsi/obsmod.F90 [hunk 8]
```diff
@@ -788,6 +788,14 @@ subroutine init_obsmod_dflts
     static_gsi_nopcp_dbz=0.0_r_kind
     rmesh_dbz=2
     rmesh_vr=2
+!  pmot_dbz values of 0,1,2,3 will save different sets of obs output
```
Comment (TingLei-NOAA) [inline src/gsi/obsmod.F90:791]: @jderber-NOAA  Thanks again for so many new functions/optimization in this PR.  However, a concern I have is that we lack regression tests for so many changes, Though, here,  pmot_dbz is hardwired to 0 , other options 1-3 (and, hence the changes for them) will not be used.  If allowed, I would suggest to put those changes of  options of 1,2,3 in read_dbz_nc  into another future PR while we could have some verification runs for them.  We may discuss more on this off here.

File: src/gsi/read_obs.F90 [hunk 9]
```diff
@@ -1910,7 +1911,7 @@ subroutine read_obs(ndata,mype)
 !         Process satellite lightning observations (e.g. GOES/GLM)                     
           else if(ditype(i) == 'light')then
                if (obstype == 'goes_glm' ) then
-             call read_goesglm(nread,ndata,nodata,infile,obstype,lunout,twind,sis)
```
Comment (TingLei-NOAA) [inline src/gsi/read_obs.F90:1913]: Thanks for spotting this bug!

File: src/gsi/hybrid_ensemble_isotropic.F90 (hunk 4 above)
Comment (jderber-NOAA) [reply src/gsi/hybrid_ensemble_isotropic.F90]: This part of the code cannot be threaded over the number of ensembles (without a lot of extra work) since it is summing into an array that is not dependent on n.

However, this code change probably does not do much in terms of optimization.  So I have removed the threading and put the loop order at n,k,j,i.

File: src/gsi/general_commvars_mod.f90 (hunk 3 above)
Comment (jderber-NOAA) [reply src/gsi/general_commvars_mod.f90]: Ting,

You are correct.  My mistake for looking at this too quickly.  Thanks for pointing this out.  I have removed all references to s2g4x.

File: src/gsi/obsmod.F90 (hunk 8 above)
Comment (jderber-NOAA) [reply src/gsi/obsmod.F90:791]: These changes actually remove some bugs in the original code (e.g., in read_radar, etc. ) where the observations were not returned to the order that they were read in.  I have tested some of the options (I agree to test all the combination of options is difficult).  I don't see where the code could use a different set of observations and thus would not produce a different analysis.  What is more difficult to test is to whether or not the diagnostic files are always correct.  I think they are, but cannot be absolutely sure without running a lot of tests.

I think it is better to get these changes in and if there are problems with the diagnostic files, they can be fixed easily.

Comment (TingLei-NOAA) [reply src/gsi/obsmod.F90:791]: Thanks for the clarification.  I agree.

File: src/gsi/hybrid_ensemble_isotropic.F90 (hunk 4 above)
Comment (TingLei-NOAA) [reply src/gsi/hybrid_ensemble_isotropic.F90]: Thanks. I missed the operation dependency for loop over n_ens.  And, also agree maybe reverting to the original order is better before extra efforts on this , which will be very helpful for optimization of all those "huge" loops for various variables ( methods for  treatment for the above  n_ens dependency is maybe possible).

**Comment by jderber-NOAA** [comment]
The regression tests and a full resolution global analysis were rerun.  Results were the same as above - so no change in the results.

File: src/gsi/read_goesglm.f90 [hunk 10]
```diff
@@ -323,30 +322,7 @@ subroutine read_goesglm(nread,ndata,nodata,infile,obstype,lunout,twindin,sis)
...
 ! Write header record and data to output file for further processing
-  allocate(iloc(ndata))
-  icount=0.
-  do i=1,maxobs
-     if(isort(i) > 0)then
-       icount=icount+1
-       iloc(icount)=isort(i)
-     end if
-  end do
-  if(ndata /= icount)then
```
Comment (TingLei-NOAA) [inline src/gsi/read_goesglm.f90:334]: Why is this test removed?

Comment (jderber-NOAA) [reply src/gsi/read_goesglm.f90:334]: This test was removed because it did nothing because the whole isort, iloc part of the code did nothing.  icntpnt, iout and ndata are incremented by 1 for each observation (after any qc of the data) and should have the same value (unless ndata > maxobs which is handled properly in the code). isort will be equal to 1,2,3,...,ndata. Because of this isort(i) is always > 0, icount will be equal to ndata at the end of the icount loop and iloc will just be equal to 1,2,3,...ndata.  So moving the data from cdata_all to cdata_out is just unnecessary data movement and icount will always be equal to ndata.

Checking to ensure that icount == ndata is unnecessary since they will always be the same for this routine.

File: src/gsi/control_vectors.f90 [hunk 11]
```diff
@@ -415,7 +415,8 @@ subroutine init_anacv
     write(6,*) myname_,': ALL CONTROL VARIABLES    ', nrf_var
 end if
 lcalc_gfdl_cfrac = .false.
-c2sset_flg = .true.
+c2sset_flg = .true.   ! set to true in setup.  set to false after first (only) call to ensctl2state_set
```
Comment (shoyokota) [inline src/gsi/control_vectors.f90]: "to ensctl2state_set" -> "to c2sset"?

File: src/gsi/control_vectors.f90 [hunk 12]
```diff
@@ -415,7 +415,8 @@ subroutine init_anacv
...
+e2sset_flg = .true.   ! set to true in setup.  set to false after first (only) call to init_anacv
```
Comment (shoyokota) [inline src/gsi/control_vectors.f90]: "to init_anacv" -> "to ensctl2state_set"?

File: src/gsi/ensctl2state.f90 [hunk 13]
```diff
@@ -1,4 +1,66 @@
-subroutine ensctl2state(xhat,mval,eval)
+!-------------------------------------------------------------------------
```
Comment (shoyokota) [inline src/gsi/ensctl2state.f90:1]: Since the subroutine ensctl2state_ad is duplicated, the file ensctl2state_ad.f90 should be removed.

File: src/gsi/general_commvars_mod.f90 [hunk 14]
```diff
@@ -123,6 +123,8 @@ subroutine init_general_commvars
       integer(i_kind) lnames2(2,2*nsig+1)
       character(len=64) names3(1,4*nsig+1)
       integer(i_kind) lnames3(1,4*nsig+1)
+      character(len=64) names4(2,nsig)
+      integer(i_kind) lnames4(2,nsig)
```
Comment (shoyokota) [inline src/gsi/general_commvars_mod.f90]: names4 and lnames4 are not used anywhere.

File: src/gsi/glbsoi.f90 [hunk 15]
```diff
@@ -211,6 +211,7 @@ subroutine glbsoi
 ! Set cost function
   call create_jfunc
 
+! stop
```
Comment (shoyokota) [inline src/gsi/glbsoi.f90]: What does "stop" mean?

File: src/gsi/turbl_tl.f90 [hunk 16]
```diff
@@ -59,7 +58,9 @@ subroutine turbl_tl(pges,tges,oges,u,v,prs,t,termu,termv,termt,jstart,jstop)
   real(r_kind),dimension(nsig_hlf):: dudz_bck,dvdz_bck,dodz_bck,ri_bck,rf_bck
   real(r_kind),dimension(nsig_hlf):: rdudz_bck,rdvdz_bck,sm_bck,sh_bck,rdzl_bck,rdzi_bck
   real(r_kind),dimension(nsig_hlf):: u_tl,v_tl,o_tl,zl_tl,t_tl,rssq,rofbck,rshbck
-  real(r_kind),dimension(nsig_hlf+1):: km_bck,kh_bck,p_bck,zi_bck,km_tl,kh_tl,zi_tl,p_tl
+  real(r_kind),dimension(nsig_hlf):: km_bck,kh_bck,zi_bck
+  real(r_kind),dimension(nsig_hlf+1):: p_bck,zi_tl,p_tl
+  real(r_kind),dimension(2:nsig_hlf):: km_tl,kh_tl
```
Comment (shoyokota) [inline src/gsi/turbl_tl.f90]: These changes can be applied also in turbl_ad.f90.

File: src/gsi/turbl_tl.f90 [hunk 17]
```diff
@@ -261,23 +255,26 @@ subroutine turbl_tl(pges,tges,oges,u,v,prs,t,termu,termv,termt,jstart,jstop)
...
-           termt(i,j,k)=termt(i,j,k)-zx*dtdtm(i,j,k)
            kmaz_tl=zero
            khaz_tl=zero
+           kmaz_bck=km_bck(k)*hrdzbk
+           khaz_bck=kh_bck(k)*ardzbk
            if(k<nsig_hlf) then
               kmaz_tl =kmaz_tl+km_tl (k+1)*hrdzbk
               khaz_tl =khaz_tl+kh_tl (k+1)*ardzbk
+              kmaz_bck=kmaz_bck+km_bck(k)*hrdzbk
+              khaz_bck=khaz_bck+kh_bck(k)*ardzbk
```
Comment (shoyokota) [inline src/gsi/turbl_tl.f90]: "(k)" -> "(k+1)"?

File: src/gsi/hdraobmod.f90 [hunk 18]
```diff
@@ -1271,20 +1271,13 @@ subroutine read_hdraob(nread,ndata,nodata,infile,obstype,lunout,twindin,sis,&
...
-  allocate(cdata_out(nreal,ndata))
-  do i=1,ndata
-     do k=1,nreal
-        cdata_out(k,i)=cdata_all(k,i)
-     end do
-  end do
-  deallocate(cdata_all)
 
-  call count_obs(ndata,nreal,ilat,ilon,cdata_out,nobs)
+  call count_obs(ndata,nreal,ilat,ilon,cdata_all,nobs)
```
Comment (shoyokota) [inline src/gsi/hdraobmod.f90:1275]: "cdata_all" -> "cdata_all( : , 1:ndata )"?

File: src/gsi/obs_para.f90 [hunk 19]
```diff
@@ -212,6 +211,7 @@ subroutine disobs(ndata,nobs,mm1,lunout,obsfile,obstypeall)
 !$$$
   use kinds, only: r_kind,i_kind
   use gridmod, only: periodic_s,nlon,nlat,jlon1,ilat1,istart,jstart
+  use mpimod, only: mype
```
Comment (shoyokota) [inline src/gsi/obs_para.f90]: I think it is not needed.

File: src/gsi/read_avhrr.f90 [hunk 20]
```diff
@@ -570,6 +570,7 @@ subroutine read_avhrr(mype,val_avhrr,ithin,rmesh,jsatid,&
      if ( nread > 0 ) then
         write(*,'(a,a10,I3,F6.1,3I10)') 'read_avhrr,satid,imesh,amesh,itxmax,nread,ndata_mesh : ',jsatid,imesh,amesh(imesh),itxmax,nread,ndata_mesh
      endif
+     deallocate(amesh,hsst_thd)
```
Comment (shoyokota) [inline src/gsi/read_avhrr.f90]: I think this deallocate should be put outside "do imesh = 1, nmesh".

File: src/gsi/windht.f90 [hunk 21]
```diff
@@ -149,23 +149,43 @@ subroutine find_wind_height(cprov,csubprov,finalheight)
 
     character(len=8),intent(in)::cprov,csubprov
     real(r_kind),intent(out)::finalheight
+    integer,dimension(3)::kcount
```
Comment (shoyokota) [inline src/gsi/windht.f90]: It is better to put "intent(inout)".

File: src/gsi/stpcalc.f90 [hunk 22]
```diff
@@ -848,60 +838,29 @@ subroutine stpcalc(stpinout,sval,sbias,dirx,dval,dbias, &
...
-        write(iout_iter,199) (stprat(i),i=1,istp_use)
-        write(iout_iter,201) (outstp(i),i=1,nsteptot)
-        write(iout_iter,202) (outpen(i)-outpen(4),i=1,nsteptot)
-     end if
-  end if
 ! Check for final stepsize negative (probable error)
   if(stpinout <= zero)then
      if(mype == minmype)then
-        write(iout_iter,130) final_ii,bx,cx,stp(final_ii)
+        write(iout_iter,130) istp_use,bx,cx,stp(istp_use)
```
Comment (shoyokota) [inline src/gsi/stpcalc.f90]: This modification can change output in iout_iter because itep_use and final_ii are not necessarily the same. Is it as you intended?

File: src/gsi/stpcalc.f90 [hunk 23]
```diff
@@ -848,60 +838,29 @@ subroutine stpcalc(stpinout,sval,sbias,dirx,dval,dbias, &
...
         write(iout_iter,105) (bsum(i),i=1,ipen)
         write(iout_iter,110) (csum(i),i=1,ipen)
         write(iout_iter,101) (pbc(1,i)-pen_est(i),i=1,ipen)
```
Comment (shoyokota) [inline src/gsi/stpcalc.f90:884]: pen_est(i) has not been defined here yet.

File: src/gsi/stpcalc.f90 [hunk 24]
```diff
@@ -914,29 +873,56 @@ subroutine stpcalc(stpinout,sval,sbias,dirx,dval,dbias, &
 202 format(' penalties          = ',(10(e13.6,1x)))
 
 ! If convergence or failure of stepsize calculation return
-  if (end_iter) then
-     call timer_fnl('stpcalc')
-     return
-  endif
+  if (.not. end_iter) then
```
Comment (shoyokota) [inline src/gsi/stpcalc.f90]: pen_est, pjcostnew, and penaltynew are not calculated in end_iter. Is it no problem?

File: src/gsi/setupuwnd10m.f90 [hunk 25]
```diff
@@ -229,7 +229,7 @@ subroutine setupuwnd10m(obsLL,odiagLL,lunin,mype,bwork,awork,nele,nobs,is,conv_d
   goverrd=grav/rd
 
   do i=1,nobs
-     muse(i)=nint(data(iuse,i)) <= jiter
+     muse(i)=nint(data(iuse,i)) <= jiter .and. nint(data(iuse,i)) < 8
```
Comment (shoyokota) [inline src/gsi/setupuwnd10m.f90]: "nint(data(iuse,i)) < 8" -> "nint(data(**iqc**,i)) < 8"?

File: src/gsi/setupw.f90 [hunk 26]
```diff
@@ -420,7 +420,12 @@ subroutine setupw(obsLL,odiagLL,lunin,mype,bwork,awork,nele,nobs,is,conv_diagsav
   end if
 
   do i=1,nobs
-     muse(i)=nint(data(iuse,i)) <= jiter
+     muse(i)=nint(data(iuse,i)) <= jiter .and. nint(data(iqc,i)) < 8
+     if(jiter == 1)then
+       ikx=nint(data(ikxx,i))
+       itype=ictype(ikx)
+!      write(300+mype,*) i,itype,data(ilate,i),data(ilone,i)
+     end if
```
Comment (shoyokota) [inline src/gsi/setupw.f90]: Why did you add this part?

File: src/gsi/setupw.f90 [hunk 27]
```diff
@@ -939,106 +943,98 @@ subroutine setupw(obsLL,odiagLL,lunin,mype,bwork,awork,nele,nobs,is,conv_diagsav
...
+              LNVD_wspd = spdob
+              LNVD_omb = sqrt(dudiff*dudiff + dvdiff*dvdiff)
+              LNVD_ratio = LNVD_omb / log(LNVD_wspd)
+              LNVD_threshold = 3.0_r_kind
+
+              if(LNVD_ratio >= LNVD_threshold .or. &      ! LNVD check
+                  (presw > prsfc-r200 .and. isli /= 0))then ! near surface check
+                 error = zero
+              endif
+           endif                                                  ! end if all satellite winds
```
Comment (shoyokota) [inline src/gsi/setupw.f90:1031]: After this modification, QCs of GOES/MODIS/AVHRR winds are done only in qc_satwnds=true. Is it as you intended?

File: src/gsi/setupmitm.f90 [hunk 28]
```diff
@@ -195,7 +195,7 @@ subroutine setupmitm(obsLL,odiagLL,lunin,mype,bwork,awork,nele,nobs,is,conv_diag
 
 
   do i=1,nobs
-     muse(i)=nint(data(iuse,i)) <= jiter
+     muse(i)=nint(data(iuse,i)) <= jiter .and. nint(data(iuse,i)) < 8
```
Comment (shoyokota) [inline src/gsi/setupmitm.f90]: "nint(data(iuse,i)) < 8" -> "nint(data(**iqc**,i)) < 8"?

File: src/gsi/setupcldch.f90 [hunk 29]
```diff
@@ -196,7 +196,7 @@ subroutine setupcldch(obsLL,odiagLL,lunin,mype,bwork,awork,nele,nobs,is,conv_dia
   isprvd=18   ! index of subprovider
 
   do i=1,nobs
-     muse(i)=nint(data(iuse,i)) <= jiter
+     muse(i)=nint(data(iuse,i)) <= jiter .and. nint(data(iuse,i)) < 8
```
Comment (shoyokota) [inline src/gsi/setupcldch.f90]: "nint(data(iuse,i)) < 8" -> "nint(data(**iqc**,i)) < 8"?

File: src/gsi/convthin.f90 [hunk 30]
```diff
@@ -155,247 +156,108 @@ subroutine make3grids(rmesh,nlevp)
...
-!     iobs  - observation counter
-!     iobsout- location for observation to be put
-!     iuse  - .true. if observation should be used
-!     iiout - counter of data replaced
-!     
+!$$$
+    integer i,j
+    allocate(icount(itxmax,nlevp))
+    allocate(ibest_obs(itxmax,nlevp))
+    allocate(score_crit(itxmax,nlevp))
```
Comment (shoyokota) [inline src/gsi/convthin.f90]: icount -> icount_fore
ibest_obs -> ibest_obs_fore
score_crit -> score_crit_fore

File: src/gsi/convthin_time.f90 [hunk 31]
```diff
@@ -145,238 +147,114 @@ subroutine make3grids_tm(rmesh,nlevp,ntm)
...
-  subroutine map3grids_tm(flg,pflag,pcoord,nlevp,dlat_earth,dlon_earth,&
-                  pob,itm,crit1,iobs,iobsout,iin,iiout,iuse,foreswp,aftswp)
-
+  end subroutine createnormal_tm
+  subroutine createfore_tm
 !$$$  subprogram documentation block
 !                .      .    .                                       .
-! subprogram:    map3grids_tm
-!     prgmmr:    Su     org: np23                date: 2013-11-20
+! subprogram:    createnormal
```
Comment (shoyokota) [inline src/gsi/convthin_time.f90]: createnormal -> createfore

File: src/gsi/convthin.f90 [hunk 32]
```diff
@@ -155,247 +156,108 @@ subroutine make3grids(rmesh,nlevp)
...
+          score_crit_fore(i,j)= 9.99e6_r_kind
+       end do
+    end do
+    setfore=.true.
+    return
+  end subroutine createfore
+  subroutine createaft
+!$$$  subprogram documentation block
+!                .      .    .                                       .
+! subprogram:    createnormal
```
Comment (shoyokota) [inline src/gsi/convthin.f90]: createnormal -> createaft

File: src/gsi/ensctl2state.f90 [hunk 33]
```diff
@@ -297,3 +288,288 @@ subroutine ensctl2state(xhat,mval,eval)
...
+   call gsi_bundlegetpointer (eval(jj),'sst' ,rv_sst, istatus)
+   call gsi_bundleputvar ( wbundle_c, 'sst', rv_sst, istatus )
+   if(wdw_exist)then
+     call gsi_bundlegetpointer (eval(jj),'w' ,rv_w, istatus)
+     call gsi_bundleputvar ( wbundle_c, 'w', rv_w, istatus )
+     if(ls_dw)then
+       call gsi_bundlegetpointer (eval(jj),'dw' ,rv_dw, istatus)
+       call gsi_bundleputvar ( wbundle_c, 'dw', rv_dw, istatus )
+     end if
+   end if
```
Comment (shoyokota) [inline src/gsi/ensctl2state.f90:500]: I think this part should be modified as follows as in the subroutine ensctl2state. (Now observations related to w may not be assimilated correctly unless dw is included in control and state variables.)
```
   call gsi_bundlegetpointer (eval(jj),'sst' ,rv_sst, istatus)
   call gsi_bundleputvar ( wbundle_c, 'sst', rv_sst, istatus )
   if(lc_w.and.ls_w)then
     call gsi_bundlegetpointer (eval(jj),'w' ,rv_w, istatus)
     call gsi_bundleputvar ( wbundle_c, 'w', rv_w, istatus )
     if(lc_dw.and.ls_dw)then
       call gsi_bundlegetpointer (eval(jj),'dw' ,rv_dw, istatus)
       call gsi_bundleputvar ( wbundle_c, 'dw', rv_dw, istatus )
     end if
   end if
```

File: src/gsi/ensctl2state.f90 [hunk 34]
```diff
@@ -239,26 +231,25 @@ subroutine ensctl2state(xhat,mval,eval)
...
    end if
 !  Copy variables
    call gsi_bundlegetvar ( wbundle_c, 'sst', sv_sst, istatus )
    if(lc_w)then
       call gsi_bundlegetvar ( wbundle_c, 'w' , sv_w,  istatus )
-      if(lc_dw.and.nems_nmmb_regional)then
+      if(lc_dw)then
          call gsi_bundlegetvar ( wbundle_c, 'dw' , sv_dw,  istatus )
       end if
    end if
```
Comment (shoyokota) [inline src/gsi/ensctl2state.f90]: I think this part should be modified as follows.
```
   call gsi_bundlegetpointer (eval(jj),'sst' ,sv_sst, istatus)
   call gsi_bundlegetvar ( wbundle_c, 'sst', sv_sst, istatus )
   if(lc_w.and.ls_w)then
     call gsi_bundlegetpointer (eval(jj),'w' ,sv_w, istatus)
     call gsi_bundlegetvar ( wbundle_c, 'w' , sv_w,  istatus )
     if(lc_dw.and.ls_dw)then
       call gsi_bundlegetpointer (eval(jj),'dw' ,sv_dw, istatus)
       call gsi_bundlegetvar ( wbundle_c, 'dw' , sv_dw,  istatus )
     end if
   end if
```

File: src/gsi/read_viirs.f90 [hunk 35]
```diff
@@ -516,7 +516,7 @@ subroutine read_sst_viirs(mype,val_viirs,ithin,rmesh,jsatid,&
   endif
 
 ! Deallocate local arrays
-  deallocate(data_all)
+  deallocate(data_all,amesh,hsst_thd)
```
Comment (shoyokota) [inline src/gsi/read_viirs.f90:520]: deallocate(amesh,hsst_thd) can be put also in the part of earlier return (L201).

File: src/gsi/read_dbz_netcdf.f90 [hunk 36]
```diff
@@ -615,6 +613,8 @@ subroutine read_dbz_mrms_netcdf(nread,ndata,nodata,infile,obstype,lunout,sis,nob
      end do
   end do
   deallocate(strct_in_dbz)
+  deallocate(obdata_nc)
+  deallocate(beamwidth_nc,azimspacing_nc,gatewidth_nc)
```
Comment (shoyokota) [inline src/gsi/read_dbz_netcdf.f90]: I think azimuth_nc can be deallocated, too.

File: src/gsi/read_gfs_ozone_for_regional.f90 [hunk 37]
```diff
@@ -456,7 +455,9 @@ subroutine read_gfs_ozone_for_regional
         write(6,*)'GET_GEFS_FOR_REGIONAL:  ***ERROR*** INVALID value for nvcoord=',nvcoord
         call stop2(85)
      endif
+     deallocate(vcoord)
   end if
+  deallocate(nems_vcoord)
```
Comment (shoyokota) [inline src/gsi/read_gfs_ozone_for_regional.f90]: I think nems_vcoord should be deallocated in the previous else-endif because it is not always allocated.

File: src/gsi/read_gfs_ozone_for_regional.f90 [hunk 38]
```diff
@@ -508,7 +508,6 @@ subroutine read_gfs_ozone_for_regional
 !   vertical levels set to nsig_gfs, but horizontal dimensions set to regional domain.
 
   num_fields=2*nsig_gfs
-  allocate(vector(num_fields))
   vector=.false.
```
Comment (shoyokota) [inline src/gsi/read_gfs_ozone_for_regional.f90]: num_fields=2*nsig_gfs and vector=.false. also can be deleted.

File: src/gsi/read_wcpbufr.f90 [hunk 39]
```diff
@@ -679,35 +687,56 @@ subroutine read_wcpbufr(nread,ndata,nodata,infile,obstype,lunout,twindin,sis,&
...
+     end do
+     nodata=nodata+ndata
+  end if
+
+  deallocate(rusage,rthin)
+
+! Write header record and data to output file for further processing
 
-  call count_obs(ndata,nreal,ilat,ilon,cdata_out,nobs)
+  call count_obs(ndata,nreal,ilat,ilon,cdata_all,nobs)
```
Comment (shoyokota) [inline src/gsi/read_wcpbufr.f90:733]: "cdata_all" -> "cdata_all( : , 1:ndata )"?

File: src/gsi/read_sfcwnd.f90 [hunk 40]
```diff
@@ -729,43 +726,69 @@ subroutine read_sfcwnd(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,sis
...
-     do k=1,nreal
-        cdata_out(k,i)=cdata_all(k,itx)
-     end do
-  end do
-  deallocate(iloc,isort,cdata_all)
 !  deallocate(etabl)
+  close(lunin)
   
-  call count_obs(ndata,nreal,ilat,ilon,cdata_out,nobs)
+  call count_obs(ndata,nreal,ilat,ilon,cdata_all,nobs)
```
Comment (shoyokota) [inline src/gsi/read_sfcwnd.f90:785]: "cdata_all" -> "cdata_all( : , 1:ndata )"?

File: src/gsi/read_satwnd.f90 [hunk 41]
```diff
@@ -1684,51 +1655,72 @@ subroutine read_satwnd(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,sis
...
-  deallocate(iloc,isort,cdata_all,rusage)
+     nodata=nodata+2*ndata
+  end if
+  deallocate(rusage,rthin)
+
+
+  ! Write header record and data to output file for further processing
   
-  call count_obs(ndata,nreal,ilat,ilon,cdata_out,nobs)
+  call count_obs(ndata,nreal,ilat,ilon,cdata_all,nobs)
```
Comment (shoyokota) [inline src/gsi/read_satwnd.f90:1712]: "cdata_all" -> "cdata_all( : , 1:ndata )"?

File: src/gsi/read_satmar.f90 [hunk 42]
```diff
@@ -462,44 +467,67 @@ subroutine read_satmar (nread, ndata, nodata,                                 &
...
+      nodata=nodata+ndata
+   end if
+
 ! Deallocate local arrays
    if (ithin > 0 ) then
       deallocate(DumForThin)
       call del3grids
    end if
+ 
+   call count_obs(ndata,nreal,ilat,ilon,data_all,nobs)
```
Comment (shoyokota) [inline src/gsi/read_satmar.f90:521]: "data_all" -> "data_all( : , 1:ndata )"?

File: src/gsi/read_rapidscat.f90 [hunk 43]
```diff
@@ -675,35 +677,57 @@ subroutine read_rapidscat(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,
...
+              cdata_all(k,ndata)=cdata_all(k,i)
+           end do
+        end if
+     end do
+  end if
+  nodata=nodata+ndata
+  deallocate(rusage,rthin)
 
-  call count_obs(ndata,nreal,ilat,ilon,cdata_out,nobs)
+  call count_obs(ndata,nreal,ilat,ilon,cdata_all,nobs)
```
Comment (shoyokota) [inline src/gsi/read_rapidscat.f90:725]: "cdata_all" -> "cdata_all( : , 1:ndata )"?

File: src/gsi/read_goesimgr_skycover.f90 [hunk 44]
```diff
@@ -211,211 +212,240 @@ subroutine  read_goesimgr_skycover(nread,ndata,nodata,infile,obstype,lunout,gsti
...
-     do k=1,nreal
-        cdata_out(k,i)=cdata_all(k,itx)
-     end do
-  end do
-  deallocate(iloc,isort,cdata_all)
+
+! Write header record and data to output file for further processing
  
-  call count_obs(ndata,nreal,ilat,ilon,cdata_out,nobs)
+  call count_obs(ndata,nreal,ilat,ilon,cdata_all,nobs)
```
Comment (shoyokota) [inline src/gsi/read_goesimgr_skycover.f90:444]: "cdata_all" -> "cdata_all( : , 1:ndata )"?

File: src/gsi/read_goesglm.f90 [hunk 45]
```diff
@@ -361,9 +337,9 @@ subroutine read_goesglm(nread,ndata,nodata,infile,obstype,lunout,twindin,sis)
      allocate(cdata_flash_h(nreal,ndata_flash_h))
 
      call convert_to_flash_rate   &
-              (nreal,ndata,cdata_out,ndata_flash_h,cdata_flash_h,ndata_flash)
+              (nreal,ndata,cdata_all,ndata_flash_h,cdata_flash_h,ndata_flash)
```
Comment (shoyokota) [inline src/gsi/read_goesglm.f90:339]: "cdata_all" -> "cdata_all( : , 1:ndata )"?

File: src/gsi/read_fl_hdob.f90 [hunk 46]
```diff
@@ -1154,31 +1176,76 @@ subroutine read_fl_hdob(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,si
...
-     do i=1,ndata
-        do k=1,nreal
-           cdata_out(k,i)=cdata_all(k,i)
-        end do
-     end do
-     deallocate(cdata_all)
 !     deallocate(etabl)
 
-     call count_obs(ndata,nreal,ilat,ilon,cdata_out,nobs)
+     call count_obs(ndata,nreal,ilat,ilon,cdata_all,nobs)
```
Comment (shoyokota) [inline src/gsi/read_fl_hdob.f90:1226]: "cdata_all" -> "cdata_all( : , 1:ndata )"?

File: src/gsi/read_dbz_nc.f90 [hunk 47]
```diff
@@ -341,12 +342,19 @@ subroutine read_dbz_nc(nread,ndata,nodata,infile,lunout,obstype,sis,hgtl_full,no
   timeb=real(mins_an-iwinbgn,r_kind)  !assume all observations are at the analysis time
  
   ivar = 1
-  
+  pmot=pmot_dbz
+  if(reduce_diag .and. pmot < 2)pmot=pmot+2
+  save_all=.false.
+  if(pmot /= 2 .and. pmot /= 0) save_all=.true.
+  rusage = .true.
+  rthin = .false.
```
Comment (shoyokota) [inline src/gsi/read_dbz_nc.f90:347]: "rusage = .true." and "rthin = .false." are not needed here because they are already given.

File: src/gsi/read_dbz_nc.f90 [hunk 48]
```diff
@@ -550,7 +592,7 @@ subroutine read_dbz_nc(nread,ndata,nodata,infile,lunout,obstype,sis,hgtl_full,no
   
   !---------------DEALLOCATE ARRAYS-------------!
   
-  deallocate(cdata_all)
+  deallocate(cdata_all,rusage,rthin)
```
Comment (shoyokota) [inline src/gsi/read_dbz_nc.f90]: They should be deallocated outside "fileopen: if (if_input_exist)"

File: src/gsi/read_wcpbufr.f90 [hunk 49]
```diff
@@ -610,6 +618,7 @@ subroutine read_wcpbufr(nread,ndata,nodata,infile,obstype,lunout,twindin,sis,&
               if(ncnumgrp(nc)>0 )then                 ! default cross validation on
                  if(mod(ndata+1,ncnumgrp(nc))== ncgroup(nc)-1)usage=ncmiter(nc)
               end if
+              if(pmot >=2 .and. (icuse(nc) <= 0 .or. qm >= 8)) rusage(iout) = .false.
```
Comment (shoyokota) [inline src/gsi/read_wcpbufr.f90]: "pmot >=2 .and." is not needed because rusage is not referred in pmot<2.

File: src/gsi/read_wcpbufr.f90 [hunk 50]
```diff
@@ -294,25 +299,29 @@ subroutine read_wcpbufr(nread,ndata,nodata,infile,obstype,lunout,twindin,sis,&
...
   ilon=2
   ilat=3
+  rusage = .true.
+  rthin = .false.
   loop_convinfo: do nx=1, ntread
 
      use_all = .true.
      ithin=0
+     pmot=0
+     use_all=.true.
```
Comment (shoyokota) [inline src/gsi/read_wcpbufr.f90]: "use_all=.true." is duplicated.

File: src/gsi/read_prepbufr.f90 [hunk 51]
```diff
@@ -2856,7 +2888,10 @@ subroutine read_prepbufr(nread,ndata,nodata,infile,obstype,lunout,twindin,sis,&
                                   low_cldamt,low_cldamt_qc,mid_cldamt,mid_cldamt_qc, &
                                   hig_cldamt,hig_cldamt_qc,tcamt,lcbas,tcamt_qc,lcbas_qc,ceiling,stnelev)
 
-                    if(lcbas_qc==15 .or. lcbas_qc==12 .or. lcbas_qc==9) usage=100._r_kind
+                    if(lcbas_qc >= 8) usage=100._r_kind
+                    if(pmot >=2 .and. usage >= 100.0_r_kind)then
```
Comment (shoyokota) [inline src/gsi/read_prepbufr.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2.

File: src/gsi/read_radar.f90 [hunk 52]
```diff
@@ -845,16 +856,18 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,hgtl_fu
...
            ndata    =min(ndata+1,maxobs)
-           nodata   =min(nodata+1,maxobs)  !number of obs not used (no meaning here)
+           nodata   =min(nodata+1,maxobs)  
            usage = zero
            if(icuse(ikx) < 0)usage=r100
            if(ncnumgrp(ikx) > 0 )then                     ! cross validation on
               if(mod(ndata,ncnumgrp(ikx))== ncgroup(ikx)-1)usage=ncmiter(ikx)
            end if
-
+           if(pmot >=2 .and. usage >= 100._r_kind) rusage(ndata)=.false.
```
Comment (shoyokota) [inline src/gsi/read_radar.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2.

File: src/gsi/read_radar.f90 [hunk 53]
```diff
@@ -1275,15 +1292,17 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,hgtl_fu
...
                       nobs_box(irrr,iaaa,ivadz,ivad)=nobs_box(irrr,iaaa,ivadz,ivad)+1
                       ndata  = min(ndata+1,maxobs)
-                      nodata = min(nodata+1,maxobs)  !number of obs not used (no meaning here)
+                      nodata = min(nodata+1,maxobs)  
                       usage  = zero
                       if(icuse(ikx) < 0)usage=r100
                       if(ncnumgrp(ikx) > 0 )then                     ! cross validation on
                          if(mod(ndata,ncnumgrp(ikx))== ncgroup(ikx)-1)usage=ncmiter(ikx)
                       end if
+                      if(pmot >=2 .and. usage >= 100._r_kind) rusage(ndata)=.false.
```
Comment (shoyokota) [inline src/gsi/read_radar.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2.

File: src/gsi/read_radar.f90 [hunk 54]
```diff
@@ -1957,12 +1980,14 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,hgtl_fu
                                                   re-compile GSI, re-run !!! <-- WARNING*** ***'
                         end if
                         ndata  = min(ndata+1,maxobs)
-                        nodata = min(nodata+1,maxobs)  !number of obs not used (no meaning here)
+                        nodata = min(nodata+1,maxobs)  
                         usage  = zero
                         if(icuse(ikx) < 0)usage=r100
+                        if(pmot >=2 .and. usage >= 100._r_kind) rusage(ndata)=.false.
```
Comment (shoyokota) [inline src/gsi/read_radar.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2.

File: src/gsi/read_radar.f90 [hunk 55]
```diff
@@ -2465,13 +2481,15 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,hgtl_fu
               if(ncnumgrp(ikx) > 0 )then                     ! cross validation on
                  if(mod(ndata,ncnumgrp(ikx))== ncgroup(ikx)-1)usage=ncmiter(ikx)
               end if
+              if(pmot >=2 .and. usage >= 100._r_kind) rusage(ndata)=.false.
```
Comment (shoyokota) [inline src/gsi/read_radar.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2.

File: src/gsi/read_radar.f90 [hunk 56]
```diff
@@ -2991,6 +3003,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,hgtl_fu
                     if(ncnumgrp(ikx) > 0 )then                     ! cross validation on
                        if(mod(ndata,ncnumgrp(ikx))== ncgroup(ikx)-1)usage=ncmiter(ikx)
                     end if
+                    if(pmot >=2 .and. usage >= 100._r_kind) rusage(ndata)=.false.
```
Comment (shoyokota) [inline src/gsi/read_radar.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2.

File: src/gsi/read_fl_hdob.f90 [hunk 57]
```diff
@@ -664,7 +672,10 @@ subroutine read_fl_hdob(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,si
 !          temperature will be used
            if (ltob) then
               qcm = t_qm 
-              if (qcm > 3) usage = r100  
+              if (qcm > 3) then
+                 usage = r100  
+                 if(pmot >= 2 .and. usage >= r100)rusage(ndata+1)=.false.
```
Comment (shoyokota) [inline src/gsi/read_fl_hdob.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2. In addition, in case ndata is not increased due to thinning after here, rusage becomes wrong. Is it no problem?

File: src/gsi/read_fl_hdob.f90 [hunk 58]
```diff
@@ -744,7 +755,10 @@ subroutine read_fl_hdob(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,si
 !          related QC mark and then calculate specific humidity
            if (lqob) then
               qcm = q_qm
-              if (qcm > 3) usage = r100 
+              if (qcm > 3) then
+                 usage = r100 
+                 if(pmot >= 2 .and. usage >= r100)rusage(ndata+1)=.false.
```
Comment (shoyokota) [inline src/gsi/read_fl_hdob.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2. In addition, in case ndata is not increased due to thinning after here, rusage becomes wrong. Is it no problem?

File: src/gsi/read_fl_hdob.f90 [hunk 59]
```diff
@@ -817,7 +831,10 @@ subroutine read_fl_hdob(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,si
 !          Convert wind direction and spped to u and v wind components
            if (luvob) then
               qcm = uv_qm
-              if (qcm > 3) usage=r100 
+              if (qcm > 3) then
+                 usage=r100 
+                 if(pmot >= 2 .and. usage >= r100)rusage(ndata+1)=.false.
```
Comment (shoyokota) [inline src/gsi/read_fl_hdob.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2. In addition, in case ndata is not increased due to thinning after here, rusage becomes wrong. Is it no problem?

File: src/gsi/read_fl_hdob.f90 [hunk 60]
```diff
@@ -829,7 +846,10 @@ subroutine read_fl_hdob(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,si
 !          Read surface wind speed [m/s] and total rain rate [mm/hr] from SFMR 
            if (lspdob) then
               qcm = wspd_qm
-              if (qcm > 3) usage=r100 
+              if (qcm > 3) then
+                 usage=r100 
+                 if(pmot >= 2 .and. usage >= r100)rusage(ndata+1)=.false.
```
Comment (shoyokota) [inline src/gsi/read_fl_hdob.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2. In addition, in case ndata is not increased due to thinning after here, rusage becomes wrong. Is it no problem?

File: src/gsi/read_goesimgr_skycover.f90 [hunk 61]
```diff
@@ -211,211 +212,240 @@ subroutine  read_goesimgr_skycover(nread,ndata,nodata,infile,obstype,lunout,gsti
...
+            if (.not. luse) cycle loop_readsb
+         else  ! - no thinnning
+            ndata=ndata+1
+      endif
+      iout=ndata
+
+      !-  Set usage variable
+      usage = 0 
+      if(iuse <= 0)usage=r100
+      if(usage >= r100 .and. pmot >= 2)rusage(ndata+1)=.false.
```
Comment (shoyokota) [inline src/gsi/read_goesimgr_skycover.f90]: ".and. pmot>=2" is not needed because rusage is not referred in pmot<2. In addition, "ndata+1" -> "ndata"?

File: src/gsi/read_radar_wind_ascii.f90 [hunk 62]
```diff
@@ -443,179 +446,174 @@ subroutine read_radar_wind_ascii(nread,ndata,nodata,infile,lunout,obstype,sis,hg
...
-                 dx1  = one-dx;     dy1  = one-dy
-                 w00=dx1*dy1; w10=dx1*dy; w01=dx*dy1; w11=dx*dy
+                 icntpnt=icntpnt+1
+                 if(icntpnt>maxobs) exit
+                 pmot=pmot_vr
+                 if(reduce_diag .and. pmot < 2)pmot=pmot+2
+                 save_all=.false.
+                 if(pmot /= 2 .and. pmot /= 0) save_all=.true.
+
+                 if(pmot >= 2 .and. abs(icuse(ikx)) /= 1)rusage(ndata+1)=.false.
```
Comment (shoyokota) [inline src/gsi/read_radar_wind_ascii.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2. In addition, in case ndata is not increased due to thinning after here, rusage becomes wrong. Is it no problem?

File: src/gsi/read_rapidscat.f90 [hunk 63]
```diff
@@ -550,6 +558,7 @@ subroutine read_rapidscat(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,
            usage = 0 
            iuse=icuse(nc)
            if(iuse <= 0)usage=r100
+           if(pmot >= 2 .and. usage >= r100)rusage(ndata+1)=.false.
```
Comment (shoyokota) [inline src/gsi/read_rapidscat.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2.

File: src/gsi/read_sfcwnd.f90 [hunk 64]
```diff
@@ -608,6 +611,7 @@ subroutine read_sfcwnd(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,sis
            usage = 0 
            iuse=icuse(nc)
            if(iuse <= 0)usage=r100
+           if(pmot >= 2 .and. usage >= r100)rusage(ndata+1)=.false.
```
Comment (shoyokota) [inline src/gsi/read_sfcwnd.f90]: "pmot>=2 .and." is not needed because rusage is not referred in pmot<2.

File: src/gsi/read_fl_hdob.f90 [hunk 65]
```diff
@@ -1154,31 +1176,76 @@ subroutine read_fl_hdob(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,si
...
+!            numqc=numqc+1
+!         else if(rthin(i))then
+!            numthin=numthin+1
+!         else
+!            numrem=numrem+1
+!         end if
+!       end do
+!       write(6,*) ' fl ',trim(ioctype(nc)),ictype(nc),icsubtype(nc),numall,&
+!              numrem,numqc,numthin
+!   If thinned data set quality mark to 16
```
Comment (shoyokota) [inline src/gsi/read_fl_hdob.f90]: 16 -> 14?

File: src/gsi/read_sfcwnd.f90 [hunk 66]
```diff
@@ -342,15 +339,20 @@ subroutine read_sfcwnd(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,sis
 !!  read satellite winds one type a time
 !   same as in the read_prepbufr.f90 file
 
+  rusage = .true.
+  rthin = .false.
   loop_convinfo: do nx=1,ntread 
      use_all = .true.
      ithin=0
+     pmot=0
+     use_all=.true.
```
Comment (shoyokota) [inline src/gsi/read_sfcwnd.f90]: "use_all=.true." is duplicated.

File: src/gsi/read_dbz_nc.f90 [hunk 67]
```diff
@@ -423,10 +431,12 @@ subroutine read_dbz_nc(nread,ndata,nodata,infile,lunout,obstype,sis,hgtl_full,no
 
         nread = nread + 1
  
+        if(icuse(ikx) < zero)rusage(ndata+1)=.false.
```
Comment (shoyokota) [inline src/gsi/read_dbz_nc.f90]: In case ndata is not increased due to thinning after here, rusage becomes wrong. Is it no problem?

File: src/gsi/read_goesimgr_skycover.f90 [hunk 68]
```diff
@@ -211,211 +212,240 @@ subroutine  read_goesimgr_skycover(nread,ndata,nodata,infile,obstype,lunout,gsti
...
+!          numrem=numrem+1
+!       end if
+!    end do
+!    write(6,*) ' sky ',trim(ioctype(nc)),ictype(nc),icsubtype(nc),numall,numrem,numqc,numthin
+!   If thinned data set usage
+     if (ithin > 0 .and. ithin <5) then
+        do i=1,nxdata
+           if(rthin(i))then
+              cdata_all(9,i)=100._r_kind
+              cdata_all(7,i)=14
```
Comment (shoyokota) [inline src/gsi/read_goesimgr_skycover.f90]: "cdata_all(7,i)=14" -> "cdata_all(**8**,i)=14"?

File: src/gsi/read_radar_wind_ascii.f90 [hunk 69]
```diff
@@ -645,10 +692,10 @@ subroutine read_radar_wind_ascii(nread,ndata,nodata,infile,lunout,obstype,sis,hg
   
   !---------------DEALLOCATE ARRAYS-------------!
  
-  deallocate(cdata_all)
+  deallocate(cdata_all,rusage,rthin)
```
Comment (shoyokota) [inline src/gsi/read_radar_wind_ascii.f90]: They should be deallocated outside "fileopen: if (ierror == 0)"

File: src/gsi/read_radar_wind_ascii.f90 [hunk 70]
```diff
@@ -626,6 +624,55 @@ subroutine read_radar_wind_ascii(nread,ndata,nodata,infile,lunout,obstype,sis,hg
...
+!         numqc=numqc+1
+!      else if(rthin(i))then
+!         numthin=numthin+1
+!      else
+!         numrem=numrem+1
+!      end if
+!    end do
+!    write(6,*) ' asciiradar ',trim(ioctype(ikx)),ikx,numall,&
+!           numrem,numqc,numthin
+!   If thinned data set quality mark to 16
```
Comment (shoyokota) [inline src/gsi/read_radar_wind_ascii.f90]: This comment is wrong.

File: src/gsi/read_radar.f90 [hunk 71]
```diff
@@ -4174,23 +4273,67 @@ subroutine read_radar_l2rw(ndata,nodata,lunout,obstype,sis,nobs,hgtl_full)
...
+!      if(.not. rusage(i))then
+!         numqc=numqc+1
+!      else if(rthin(i))then
+!         numthin=numthin+1
+!      else
+!         numrem=numrem+1
+!      end if
+!    end do
+!    write(6,*) ' radar2 ',numall,numrem,numqc,numthin
+!   If thinned data set quality mark to 16
```
Comment (shoyokota) [inline src/gsi/read_radar.f90]: This comment is wrong.

File: src/gsi/read_radar.f90 [hunk 72]
```diff
@@ -3774,16 +3878,17 @@ subroutine read_radar_l2rw(ndata,nodata,lunout,obstype,sis,nobs,hgtl_full)
...
-  maxdata=0
-  isort=0
   icntpnt=0
   nout=0
   if(loop==0) outmessage='level 2 superobs:'
   rmesh=radar_rmesh
   zmesh=radar_zmesh
   nlevz=nint(16000._r_kind/zmesh)
   xmesh=rmesh
+  pmot=radar_pmot
```
Comment (shoyokota) [inline src/gsi/read_radar.f90:3882]: Why did you use radar_pmot rather than pmot_conv(ikx) here?

File: src/gsi/read_prepbufr.f90 [hunk 73]
```diff
@@ -222,7 +223,7 @@ subroutine read_prepbufr(nread,ndata,nodata,infile,obstype,lunout,twindin,sis,&
   use aircraftobsqc, only: init_aircraft_rjlists,get_aircraft_usagerj,&
                            destroy_aircraft_rjlists
   use adjust_cloudobs_mod, only: adjust_convcldobs,adjust_goescldobs
-  use mpimod, only: npe
+  use mpimod, only: npe,mype
```
Comment (shoyokota) [inline src/gsi/read_prepbufr.f90]: mype is not used in this file.

File: src/gsi/read_prepbufr.f90 [hunk 74]
```diff
@@ -907,9 +962,12 @@ subroutine read_prepbufr(nread,ndata,nodata,infile,obstype,lunout,twindin,sis,&
               endif
            endif
            if(print_verbose) write(6,*)'READ_PREPBUFR: at line 779: obstype,ictype(nc),rmesh,pflag,nlevp,pmesh,pmot,ptime=',&
-              trim(ioctype(nc)),ictype(nc),rmesh,pflag,nlevp,pmesh,pmot,ptime,ithin
+              trim(ioctype(nc)),ictype(nc),rmesh,pflag,nlevp,pmesh,pmot,ptime,ithin,ndata,nc
```
Comment (shoyokota) [inline src/gsi/read_prepbufr.f90:965]: 'READ_PREPBUFR: at line 779: ...' should be also modified.

File: src/gsi/read_prepbufr.f90 [hunk 75]
```diff
@@ -2963,51 +2998,76 @@ subroutine read_prepbufr(nread,ndata,nodata,infile,obstype,lunout,twindin,sis,&
...
-        cdata_out(k,i)=cdata_all(k,itx)
-     end do
-  end do
-  deallocate(iloc,isort,cdata_all)
+  deallocate(rusage,rthin)
+
+! Apply hilbert curve for cross validation if requested
+
+  if(lhilbert) &
+       call apply_hilbertcurve(maxobs,obstype,cdata_all(thisobtype_usage,1:ndata))
```
Comment (shoyokota) [inline src/gsi/read_prepbufr.f90]: "1:ndata" -> "1:maxobs"? And, I suspect that this subroutine should be called before sorting cdata_all according to pmot because accum_hilbertcurve is called before sorting it.

File: src/gsi/read_prepbufr.f90 [hunk 76]
```diff
@@ -475,52 +482,96 @@ subroutine read_prepbufr(nread,ndata,nodata,infile,obstype,lunout,twindin,sis,&
...
+     iqm = 11
+     iuse = 13
   else if(psob) then
      nreal=20
+     iqm=10
+     iuse = 12
   else if(qob) then
      nreal=26
+     iqm = 11
+     iuse = 12
```
Comment (shoyokota) [inline src/gsi/read_prepbufr.f90]: 12 ->13?

File: src/gsi/read_prepbufr.f90 [hunk 77]
```diff
@@ -475,52 +482,96 @@ subroutine read_prepbufr(nread,ndata,nodata,infile,obstype,lunout,twindin,sis,&
...
+     iqm = 9
+     iuse = 11
   else if(metarcldobs) then
      nreal=27
+     iqm = 0
+     iuse = 22
   else if(goesctpobs) then
      nreal=8
+     iqm = 0
+     iuse = 22
```
Comment (shoyokota) [inline src/gsi/read_prepbufr.f90]: 22 -> 8?

File: src/gsi/read_satwnd.f90 [hunk 78]
```diff
@@ -583,38 +649,38 @@ subroutine read_satwnd(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,sis
...
+     pmot=0
+
      if(nx >1) then
         nc=ntx(nx)
         ithin=ithin_conv(nc)
         if (ithin > 0 .and. ithin <5) then
            rmesh=rmesh_conv(nc)
            pmesh=pmesh_conv(nc)
-           pmot=pmot_conv(nc)
+           pmot = pmot_conv(nc)
```
Comment (shoyokota) [inline src/gsi/read_satwnd.f90]: I think it should be put outside "if (ithin > 0 .and. ithin <5)".

File: src/gsi/read_satwnd.f90 [hunk 79]
```diff
@@ -1002,327 +1141,208 @@ subroutine read_satwnd(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,sis
...
 ! Extra block for VIIRS NOAA20: End
 ! Extra block for GOES-R winds: Start
-           else if(trim(subset) == 'NC005030' .or. trim(subset) == 'NC005031' .or. trim(subset) == 'NC005032' .or. &  !IR(LW) / CS WV / VIS  GOES-R like winds
-                   trim(subset) == 'NC005034' .or. trim(subset) == 'NC005039' .or. trim(subset) == 'NC005099') then   !CT WV  / IR(SW) GOES-R like winds
+           else if (istype >= 15 .and. istype <=20)then
 
-              if ( trim(subset) == 'NC005099' ) then
-                hdrdat(10)=61.23 ! set zenith angle for CIMSS AMVs to 67 to pass QC, no value in origional data
-              end if
-              if(hdrdat(1) >=r250 .and. hdrdat(1) <=r299 ) then  ! the range of NESDIS satellite IDs
```
Comment (shoyokota) [inline src/gsi/read_satwnd.f90:1187]: Why did you delete "if(hdrdat(1) >=r250 .and. hdrdat(1) <=r299 )"?

**Comment by CatherineThomas-NOAA** [comment]
I ran some full resolution global tests on WCOSS2, similar to what @jderber-NOAA  ran on Hera with pmot=0 and pmot=2.  I did not use SDL.  All tests were run under similar conditions (non-peak machine time).  

Runtimes:
```
Control   PR_pmot=0   PR_pmot=2
1949.41    1962.6      1945.93
1973.88    1955.51     1946.74
1955.3     1976.16     1936.95
1965.5     1962.82     1939.16
1973.61    1955.5      1940.95

Mean
1963.54    1962.518    1941.946
```


Similar to @jderber-NOAA's Hera tests, the pmot=0 case did not speed up in comparison to the control.  All pmot=2 cases were faster than all control and pmot=0 cases.

I neglected to check the cost functions before losing access to Dogwood.  I will check later this week once the machine is returned.

**Comment by jderber-NOAA** [comment]
Cathy,

Thank you very much!  I am glad the results are as expected.   Of course with pmot = 2, some of the data is removed from the diagnostic files.  So in this case, there is no free lunch.  Just a little more control over what is put into the diagnostic files.  This is a GDAS run.  I wonder if there is any improvement with an AVN run where the diagnostic files are already reduced.  I think there might be a little because the data saved for the setup routines might be a little smaller.  

If I am able, I would like to add something similar for the satellite data.  Might be bigger impact there.

John

**Review by shoyokota — COMMENTED** [review]
@jderber-NOAA I have many questions about your modification. Most are minor, but some may be bugs. Could you confirm my comments?

File: src/gsi/read_satwnd.f90 (hunk 79 above)
Comment (jderber-NOAA) [reply src/gsi/read_satwnd.f90:1187]: Thank you for your thorough review.  I will have to work through your comments one by one over the next few days.

File: src/gsi/control_vectors.f90 (hunk 11 above)
Comment (jderber-NOAA) [reply src/gsi/control_vectors.f90]: Correct. Thank you! I have made correction.

File: src/gsi/control_vectors.f90 (hunk 12 above)
Comment (jderber-NOAA) [reply src/gsi/control_vectors.f90]: Correct!  Fixed.  I think I got mixed up when making the previous 2 changes.

File: src/gsi/general_commvars_mod.f90 (hunk 14 above)
Comment (jderber-NOAA) [reply src/gsi/general_commvars_mod.f90]: Yes!  A potential change that did not work well needed these, but I forgot to remove.  Modified.

File: src/gsi/ensctl2state.f90 (hunk 13 above)
Comment (jderber-NOAA) [reply src/gsi/ensctl2state.f90:1]: Yes!  Done.  Also needed removal of file name from gsi_files.cmake.  Regression tests will be rerun with all changes.

File: src/gsi/turbl_tl.f90 (hunk 16 above)
Comment (jderber-NOAA) [reply src/gsi/turbl_tl.f90]: After looking at the changes more closely in turbl_tl.f90, I am not sure they are right (see comment below).  I have removed all changes to this routine except those involving use_pbl.

File: src/gsi/turbl_tl.f90 (hunk 17 above)
Comment (jderber-NOAA) [reply src/gsi/turbl_tl.f90]: Correct.  But see comment above about removing changes to turbl_tl.f90.

File: src/gsi/hdraobmod.f90 (hunk 18 above)
Comment (jderber-NOAA) [reply src/gsi/hdraobmod.f90:1275]: Correct!  Change made.

File: src/gsi/obs_para.f90 (hunk 19 above)
Comment (jderber-NOAA) [reply src/gsi/obs_para.f90]: Correct!  Removed.

File: src/gsi/stpcalc.f90 (hunk 23 above)
Comment (jderber-NOAA) [reply src/gsi/stpcalc.f90:884]: Correct!  Calculation of pen_est has been moved to point before being used.

File: src/gsi/stpcalc.f90 (hunk 24 above)
Comment (jderber-NOAA) [reply src/gsi/stpcalc.f90]: I think I have corrected issues.  Will rerun regression tests at this point to ensure no unexpected changes in the results occurred.

File: src/gsi/stpcalc.f90 (hunk 22 above)
Comment (jderber-NOAA) [reply src/gsi/stpcalc.f90]: Not seeing this in my code.  Could you check to make sure I am not missing something?

Comment (jderber-NOAA) [reply src/gsi/stpcalc.f90]: OK I see it now.  The final_ii code is in the control, not in new code.  Somehow this code was lost in the upgrading of the code, and was not removed intentionally.  I have put the code into the new code.

File: src/gsi/setupmitm.f90 (hunk 28 above)
Comment (jderber-NOAA) [reply src/gsi/setupmitm.f90]: Correct!  I made this mistake repeatedly.  So sorry.  Thanks for finding this.

File: src/gsi/setupcldch.f90 (hunk 29 above)
Comment (jderber-NOAA) [reply src/gsi/setupcldch.f90]: Correct!  See above.

File: src/gsi/convthin.f90 (hunk 30 above)
Comment (jderber-NOAA) [reply src/gsi/convthin.f90]: Correct!  Fixed.  Not sure how this was working.

File: src/gsi/convthin_time.f90 (hunk 31 above)
Comment (jderber-NOAA) [reply src/gsi/convthin_time.f90]: Correct!  Comment changed.

File: src/gsi/convthin.f90 (hunk 32 above)
Comment (jderber-NOAA) [reply src/gsi/convthin.f90]: Correct!  Comment changed.

File: src/gsi/ensctl2state.f90 (hunk 33 above)
Comment (jderber-NOAA) [reply src/gsi/ensctl2state.f90:500]: Correct!  Modified code.

File: src/gsi/ensctl2state.f90 (hunk 34 above)
Comment (jderber-NOAA) [reply src/gsi/ensctl2state.f90]: I think the code as is, would work.  But I changed the code as suggested to make it consistent between the ad and tl code.

File: src/gsi/read_viirs.f90 (hunk 35 above)
Comment (jderber-NOAA) [reply src/gsi/read_viirs.f90:520]: Deallocate of amesh and hsst_thd added to both locations.

File: src/gsi/read_dbz_netcdf.f90 (hunk 36 above)
Comment (jderber-NOAA) [reply src/gsi/read_dbz_netcdf.f90]: Yes.  Deallocated and moved outside if-then-else.

File: src/gsi/read_gfs_ozone_for_regional.f90 (hunk 38 above)
Comment (jderber-NOAA) [reply src/gsi/read_gfs_ozone_for_regional.f90]: Correct, but num_fields and vector removed after the ones shown.  First specification should be retained.

File: src/gsi/read_wcpbufr.f90 (hunk 39 above)
Comment (jderber-NOAA) [reply src/gsi/read_wcpbufr.f90:733]: Done, but I am not sure it is necessary since it is last dimension.

File: src/gsi/read_sfcwnd.f90 (hunk 40 above)
Comment (jderber-NOAA) [reply src/gsi/read_sfcwnd.f90:785]: Done, but I am not sure it is necessary since it is last dimension.  Also, extra deallocation of cdata_all removed.

File: src/gsi/setupuwnd10m.f90 (hunk 25 above)
Comment (jderber-NOAA) [reply src/gsi/setupuwnd10m.f90]: Correct!  I have made change.

File: src/gsi/setupw.f90 (hunk 26 above)
Comment (jderber-NOAA) [reply src/gsi/setupw.f90]: Removed.  It was used for diagnostics and should have been removed.

File: src/gsi/read_satmar.f90 (hunk 42 above)
Comment (jderber-NOAA) [reply src/gsi/read_satmar.f90:521]: Done, but I am not sure it is necessary since it is last dimension.

File: src/gsi/read_rapidscat.f90 (hunk 43 above)
Comment (jderber-NOAA) [reply src/gsi/read_rapidscat.f90:725]: Done, but I am not sure it is necessary since it is last dimension.  Unused variable icount also removed.

File: src/gsi/read_goesglm.f90 (hunk 45 above)
Comment (jderber-NOAA) [reply src/gsi/read_goesglm.f90:339]: Done, but I am not sure it is necessary since it is last dimension.

File: src/gsi/read_fl_hdob.f90 (hunk 46 above)
Comment (jderber-NOAA) [reply src/gsi/read_fl_hdob.f90:1226]: Done, but I am not sure it is necessary since it is last dimension.

File: src/gsi/read_dbz_nc.f90 (hunk 47 above)
Comment (jderber-NOAA) [reply src/gsi/read_dbz_nc.f90:347]: Correct!  Code removed.

File: src/gsi/read_wcpbufr.f90 (hunk 49 above)
Comment (jderber-NOAA) [reply src/gsi/read_wcpbufr.f90]: Done.

File: src/gsi/read_prepbufr.f90 (hunk 51 above)
Comment (jderber-NOAA) [reply src/gsi/read_prepbufr.f90]: Done.

File: src/gsi/read_radar.f90 (hunk 52 above)
Comment (jderber-NOAA) [reply src/gsi/read_radar.f90]: Done.

File: src/gsi/read_radar.f90 (hunk 54 above)
Comment (jderber-NOAA) [reply src/gsi/read_radar.f90]: Done.

File: src/gsi/read_radar.f90 (hunk 55 above)
Comment (jderber-NOAA) [reply src/gsi/read_radar.f90]: Done.

File: src/gsi/read_radar.f90 (hunk 53 above)
Comment (jderber-NOAA) [reply src/gsi/read_radar.f90]: Done.

File: src/gsi/read_radar.f90 (hunk 56 above)
Comment (jderber-NOAA) [reply src/gsi/read_radar.f90]: Done.

File: src/gsi/read_fl_hdob.f90 (hunk 57 above)
Comment (jderber-NOAA) [reply src/gsi/read_fl_hdob.f90]: Removed pmot >=2.  I don't think the rusage(ndata+1)=.false.  was a problem, but I made a change that should fix it if it was.

File: src/gsi/read_fl_hdob.f90 (hunk 58 above)
Comment (jderber-NOAA) [reply src/gsi/read_fl_hdob.f90]: Removed pmot >=2.  I don't think the rusage(ndata+1)=.false.  was a problem, but I made a change that should fix it if it was.

File: src/gsi/read_fl_hdob.f90 (hunk 59 above)
Comment (jderber-NOAA) [reply src/gsi/read_fl_hdob.f90]: Removed pmot >=2.  I don't think the rusage(ndata+1)=.false.  was a problem, but I made a change that should fix it if it was.

File: src/gsi/read_fl_hdob.f90 (hunk 60 above)
Comment (jderber-NOAA) [reply src/gsi/read_fl_hdob.f90]: Removed pmot >=2.  I don't think the rusage(ndata+1)=.false.  was a problem, but I made a change that should fix it if it was.

File: src/gsi/read_radar_wind_ascii.f90 (hunk 62 above)
Comment (jderber-NOAA) [reply src/gsi/read_radar_wind_ascii.f90]: Removed pmot >=2.  I don't think the rusage(ndata+1)=.false.  was a problem, but I made a change that should fix it if it was.

File: src/gsi/read_rapidscat.f90 (hunk 63 above)
Comment (jderber-NOAA) [reply src/gsi/read_rapidscat.f90]: Removed pmot >=2.  I don't think the rusage(ndata+1)=.false.  was a problem, but I made a change that should fix it if it was.

File: src/gsi/read_sfcwnd.f90 (hunk 64 above)
Comment (jderber-NOAA) [reply src/gsi/read_sfcwnd.f90]: Removed pmot >=2.  I don't think the rusage(ndata+1)=.false.  was a problem, but I made a change that should fix it if it was.

File: src/gsi/read_fl_hdob.f90 (hunk 65 above)
Comment (jderber-NOAA) [reply src/gsi/read_fl_hdob.f90]: Correct!  All data removed due to thinning should have qc mark = 14.

File: src/gsi/read_sfcwnd.f90 (hunk 66 above)
Comment (jderber-NOAA) [reply src/gsi/read_sfcwnd.f90]: Done.

File: src/gsi/read_dbz_nc.f90 (hunk 67 above)
Comment (jderber-NOAA) [reply src/gsi/read_dbz_nc.f90]: I don't think the rusage(ndata+1)=.false. was a problem, but I made a change that should fix it if it was.

File: src/gsi/read_goesimgr_skycover.f90 (hunk 44 above)
Comment (jderber-NOAA) [reply src/gsi/read_goesimgr_skycover.f90:444]: Made change in count_obs to address concern without adding additional data movement.

File: src/gsi/read_rapidscat.f90 (hunk 43 above)
Comment (jderber-NOAA) [reply src/gsi/read_rapidscat.f90:725]: Backed out this change.  Made change in count_obs to address concern without adding additional data movement.

File: src/gsi/read_satwnd.f90 (hunk 41 above)
Comment (jderber-NOAA) [reply src/gsi/read_satwnd.f90:1712]: Made change in count_obs to address concern without adding additional data movement.

File: src/gsi/read_sfcwnd.f90 (hunk 40 above)
Comment (jderber-NOAA) [reply src/gsi/read_sfcwnd.f90:785]: Backed out this change.  Made change in count_obs to address concern without adding additional data movement.

File: src/gsi/hdraobmod.f90 (hunk 18 above)
Comment (jderber-NOAA) [reply src/gsi/hdraobmod.f90:1275]: Backed out this change.  Made change in count_obs to address concern without adding additional data movement.

File: src/gsi/read_fl_hdob.f90 (hunk 46 above)
Comment (jderber-NOAA) [reply src/gsi/read_fl_hdob.f90:1226]: Backed out this change.  Made change in count_obs to address concern without adding additional data movement.

File: src/gsi/read_goesglm.f90 (hunk 45 above)
Comment (jderber-NOAA) [reply src/gsi/read_goesglm.f90:339]: Backed out this change.  Made change in count_obs to address concern without adding additional data movement.

File: src/gsi/read_wcpbufr.f90 (hunk 39 above)
Comment (jderber-NOAA) [reply src/gsi/read_wcpbufr.f90:733]: Backed out this change.  Made change in count_obs to address concern without adding additional data movement.

File: src/gsi/glbsoi.f90 (hunk 15 above)
Comment (jderber-NOAA) [reply src/gsi/glbsoi.f90]: Debugging change.  Commented out "stop" removed.

File: src/gsi/read_avhrr.f90 (hunk 20 above)
Comment (jderber-NOAA) [reply src/gsi/read_avhrr.f90]: Agreed!  Change made.

File: src/gsi/windht.f90 (hunk 21 above)
Comment (jderber-NOAA) [reply src/gsi/windht.f90]: My mistake.  intent added.

File: src/gsi/setupw.f90 (hunk 27 above)
Comment (jderber-NOAA) [reply src/gsi/setupw.f90:1031]: Yes.  For consistency, qc_satwnds now turns off all non-surface satellite winds.

File: src/gsi/read_gfs_ozone_for_regional.f90 (hunk 37 above)
Comment (jderber-NOAA) [reply src/gsi/read_gfs_ozone_for_regional.f90]: Correct!  Change made.

File: src/gsi/read_satmar.f90 (hunk 42 above)
Comment (jderber-NOAA) [reply src/gsi/read_satmar.f90:521]: Backed out this change. Made change in count_obs to address concern without adding additional data movement.

File: src/gsi/read_dbz_nc.f90 (hunk 48 above)
Comment (jderber-NOAA) [reply src/gsi/read_dbz_nc.f90]: Agreed.  Change made.

File: src/gsi/read_wcpbufr.f90 (hunk 50 above)
Comment (jderber-NOAA) [reply src/gsi/read_wcpbufr.f90]: Agreed.  One removed.

File: src/gsi/read_goesimgr_skycover.f90 (hunk 61 above)
Comment (jderber-NOAA) [reply src/gsi/read_goesimgr_skycover.f90]: Removed pmot >=2. I don't think the rusage(ndata+1)=.false. was a problem, but I made a change that should fix it if it was.

**Comment by CatherineThomas-NOAA** [comment]
> I neglected to check the cost functions before losing access to Dogwood. I will check later this week once the machine is returned.

Following up from my previous comment, I looked at the cost functions for the 15 cases that I ran on WCOSS2.  For each case type (develop, pr_pmot=0, pr_pmot=2), the cost functions were identical each time the same case was rerun.  The cost function was also identical between the pmot=0 and pmot=2 cases.  Comparing my develop and PR runs, the cost functions were different, though more different than in @jderber-NOAA's previous tests on Hera.

dev:
>cost,grad,step,b,step? =   1   0  1.989368876627208199E+06  4.925127490984177712E+03  1.683032353341368692E+00  0.000000000000000000E+00  good

PR:
>cost,grad,step,b,step? =   1   0  1.989368745300900890E+06  4.925127300757424564E+03  1.683030814872374714E+00  0.000000000000000000E+00  good

Differences here show up in the 7th digit of the initial cost function and gradient.  Final gradient differences are slightly larger but still small. 
dev:
>cost,grad,step,b,step? =   2 150  1.500715328005512711E+06  1.605423854404476103E+00  1.725986587460151211E+00  8.535462180795753140E-01  good

PR:
>cost,grad,step,b,step? =   2 150  1.500716332645538496E+06  1.602122645439933546E+00  1.735362249388878952E+00  8.507161311393255376E-01  good

File: src/gsi/read_goesimgr_skycover.f90 (hunk 68 above)
Comment (jderber-NOAA) [reply src/gsi/read_goesimgr_skycover.f90]: Correct!  Changed.

File: src/gsi/read_radar_wind_ascii.f90 (hunk 69 above)
Comment (jderber-NOAA) [reply src/gsi/read_radar_wind_ascii.f90]: Correct!  Line moved.

File: src/gsi/read_radar_wind_ascii.f90 (hunk 70 above)
Comment (jderber-NOAA) [reply src/gsi/read_radar_wind_ascii.f90]: Comment changed.

File: src/gsi/read_radar.f90 (hunk 71 above)
Comment (jderber-NOAA) [reply src/gsi/read_radar.f90]: Comment corrected.

File: src/gsi/read_radar.f90 (hunk 72 above)
Comment (jderber-NOAA) [reply src/gsi/read_radar.f90:3882]: As the code was written, the rmesh, zmesh,.. values were taken from radar_rmesh, radar_... values.  So I did the same thing with the pmot values.  It was not clear to me that the pmot_conv, ..._conv values would be defined for these particular observations.  It would be better to use the *_conv values in the convinfo file since it would not require a change to the code to change the values.  I do not completely understand the read_radar.f90 code.  :)

File: src/gsi/read_prepbufr.f90 (hunk 73 above)
Comment (jderber-NOAA) [reply src/gsi/read_prepbufr.f90]: Correct.  Changed.

File: src/gsi/read_prepbufr.f90 (hunk 74 above)
Comment (jderber-NOAA) [reply src/gsi/read_prepbufr.f90:965]: Yes!  Modified to line 964.  Don't really like specifying a specific line since any code change before the line could modify the line number.

Comment (RussTreadon-NOAA) [reply src/gsi/read_prepbufr.f90:965]: Agreed.  Runtime printout should not specify line numbers.  Future edits to the code move lines around rendering the line number incorrect.  I suggest that we remove `at line 964` or replace it with meaningful text which does not include a line number.

File: src/gsi/read_prepbufr.f90 (hunk 75 above)
Comment (jderber-NOAA) [reply src/gsi/read_prepbufr.f90]: At this point, the data should be compressed from 1:maxobs to 1:ndata.  So I think this is OK (at least as correct as the prior code).  However, maxobs in the call should be changed to ndata.

I also thought that the location of the call to apply_hilbertcurve may be in the wrong location.  However, if it is the prior code  is also wrong.  After looking at the routine, I believe the code actually locates the corresponding information from the accum_hilbertcurve.  So I think everything is OK.  It would be good if this were checked again.

File: src/gsi/read_prepbufr.f90 (hunk 76 above)
Comment (jderber-NOAA) [reply src/gsi/read_prepbufr.f90]: Correct.  Change made.

File: src/gsi/read_prepbufr.f90 (hunk 77 above)
Comment (jderber-NOAA) [reply src/gsi/read_prepbufr.f90]: Yes!  Corrected.

File: src/gsi/read_satwnd.f90 (hunk 78 above)
Comment (jderber-NOAA) [reply src/gsi/read_satwnd.f90]: Yes!  Good catch.  Modified.

File: src/gsi/read_satwnd.f90 (hunk 79 above)
Comment (jderber-NOAA) [reply src/gsi/read_satwnd.f90:1187]: I deleted this line because in the new code when the itype is defined, the check is done.  So for those data that do not pass, itype is equal to zero and the data is not used.  (I think I did things correctly).

File: src/gsi/read_prepbufr.f90 (hunk 74 above)
Comment (jderber-NOAA) [reply src/gsi/read_prepbufr.f90:965]: I removed "at line 964"

**Comment by jderber-NOAA** [comment]
Changes based on shoyokota comments and attempted testing based on "debug" run attempts.

Shoyokota Thank you for a very thorough review!  I am very surprised that you found so many of my errors!  I hope I did not make any more errors.

The "debug" runs were not always successful.  I removed those lines indicated in the output of the compilation (e.g. unused variables).  Also, I attempted to make the regression runs using the "debug" compilation.  Several code bugs were removed.  However some of the errors (e.g. undefined variables) were not able to be removed since I could not figure out the correct values.  Also, for some reason some of the runs took so much time that they would not complete.  But the changes are in the right direction.

Redoing regression testing to ensure that the changes resulted in changes to the results.

Code is committed and pushed to GITHUB.

File: src/enkf/letkf.f90 [hunk 80]
```diff
@@ -276,24 +276,24 @@ subroutine letkf_update()
...
+! !$omp                  obloc,corrlengthnh,corrlengthsh,corrlengthtr,&
+! !$omp                  vlocal_evecs,vlocal,oblnp,lnp_chunk,lnsigl,corrlengthsq,&
+! !$omp                  getkf,denkf,getkf_inflation,ensmean_chunk,ob,ensmean_ob, &
+! !$omp                  nproc,numptsperproc,nnmax,r_nanalsm1,kdtree_obs2,kdobs, &
+! !$omp                  mincorrlength_factsq,robs_local,coslats_local, &
+! !$omp                  lupd_obspace_serial,eps,dfs_sort,nanals,index_pres,&
+! !$omp  neigv,nlevs,lonsgrd,latsgrd,nobstot,nens,ncdim,nbackgrounds,indxproc,rad2deg) &
+! !$omp  reduction(+:t1,t2,t3,t4,t5) &
+! !$omp  reduction(max:nobslocal_max) &
+! !$omp  reduction(min:nobslocal_min)
```
Comment (shoyokota) [inline src/enkf/letkf.f90]: Why did you comment out this OMP? I guess the impact of this change is big for LETKF.

File: src/gsi/deter_sfc_mod.f90 [hunk 81]
```diff
@@ -600,7 +600,7 @@ subroutine deter_sfc2(dlat_earth,dlon_earth,obstime,idomsfc,tsavg,ff10,sfcr,zz)
 
 
 !    Get time interpolation factors for surface files
-     if(obstime > hrdifsfc(1) .and. obstime <= hrdifsfc(nfldsfc))then
+     if(obstime > hrdifsfc(1) .and. obstime < hrdifsfc(nfldsfc))then
```
Comment (shoyokota) [inline src/gsi/deter_sfc_mod.f90:603]: Why was it changed?

File: src/gsi/gsdcloudanalysis.F90 [hunk 82]
```diff
@@ -64,8 +64,8 @@ subroutine  gsdcloudanalysis(mype)
 !_____________________________________________________________________
 !
 ! 
-  use constants, only: zero,one,rad2deg,fv
-  use constants, only: rd_over_cp, h1000
```
Comment (shoyokota) [inline src/gsi/gsdcloudanalysis.F90:68]: These constants (rad2deg, fv, and rd_over_cp) look used in this subroutine.

File: src/gsi/mod_fv3_lola.f90 [hunk 83]
```diff
@@ -984,11 +980,11 @@ subroutine definecoef_regular_grids(nxen,nyen,grid_lon,grid_lont,grid_lat,grid_l
...
         rlat=half*(grid_lat(i,j)+grid_lat(i,j+1))
 !        rlon=half*(grid_lon(i,j)+grid_lon(i,j+1))
-        diff=(grid_lon(i,j)-grid_lon(i+1,j))**2
+        diff=(grid_lon(i,j)-grid_lon(i,j+1))**2
         if(diff < sq180)then
-           rlon=half*(grid_lon(i,j)+grid_lon(i+1,j))
+           rlon=half*(grid_lon(i,j)+grid_lon(i,j+1))
         else
-           rlon=half*(grid_lon(i,j)+grid_lon(i+1,j)-360._r_kind)
+           rlon=half*(grid_lon(i,j)+grid_lon(i,j+1)-360._r_kind)
```
Comment (shoyokota) [inline src/gsi/mod_fv3_lola.f90]: Is this bugfix changing the analysis result?

File: src/gsi/read_satwnd.f90 [hunk 84]
```diff
@@ -640,12 +706,17 @@ subroutine read_satwnd(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,sis
                  enddo
               endif
            endif
-           write(6,'(a52,a16,I5,f10.2,2i5,f10.2,i5,2f10.2)') &
+           write(6,*) ioctype(nc),ictype(nc),rmesh,pflag,nlevp,pmesh,nc,pmot,ptime
```
Comment (shoyokota) [inline src/gsi/read_satwnd.f90]: L709 is not needed.

File: src/gsi/read_radar.f90 (hunk 53 above)
Comment (shoyokota) [reply src/gsi/read_radar.f90]: It hasn't done yet.

File: src/gsi/read_prepbufr.f90 [hunk 85]
```diff
@@ -2963,51 +2996,76 @@ subroutine read_prepbufr(nread,ndata,nodata,infile,obstype,lunout,twindin,sis,&
...
-        cdata_out(k,i)=cdata_all(k,itx)
-     end do
-  end do
-  deallocate(iloc,isort,cdata_all)
+  deallocate(rusage,rthin)
+
+! Apply hilbert curve for cross validation if requested
+
+  if(lhilbert) &
+       call apply_hilbertcurve(ndata,obstype,cdata_all(thisobtype_usage,1:ndata))
```
Comment (shoyokota) [inline src/gsi/read_prepbufr.f90]: > I also thought that the location of the call to apply_hilbertcurve may be in the wrong location. However, if it is the prior code is also wrong. After looking at the routine, I believe the code actually locates the corresponding information from the accum_hilbertcurve. So I think everything is OK. It would be good if this were checked again.

In the prior code, apply_hilbertcurve was called before sorting cdata_all, so there was no issue. However, the new code calls apply_hilbertcurve after sorting cdata_all, which may set cdata_all(thisobtype_usage,1:ndata) incorrectly. I think apply_hilbertcurve should be called before sorting cdata_all.

**Comment by jderber-NOAA** [comment]
Regression tests using radial winds still not working.  Working on it.

**Review by shoyokota — COMMENTED** [review]
@jderber-NOAA I checked your modification and found some questions. Could you check them?

By the way, in my ctest (only in hafs_3denvar_hybens), the result was slightly different from that with the code I reviewed at first. I don't know why. Is this difference as you intended?

File: src/gsi/read_prepbufr.f90 (hunk 85 above)
Comment (jderber-NOAA) [reply src/gsi/read_prepbufr.f90]: Sho, Thanks for looking at the code.  But, I have not yet completed the changes.  Still getting different results from the regression tests.  Will try to address your latest set of issues.

File: src/enkf/letkf.f90 (hunk 80 above)
Comment (jderber-NOAA) [reply src/enkf/letkf.f90]: I am not yet done with my changes.  I had turned the threading off for these lines to help debug a "debug" run error.  They are turned back on in my code and will be changed back with the next commit.

File: src/gsi/deter_sfc_mod.f90 (hunk 81 above)
Comment (jderber-NOAA) [reply src/gsi/deter_sfc_mod.f90:603]: It was changed so that when obstime = hrdifsfc(nfldsfc) it would got to the else code.  Within round-off it should be the same, but the else part of the code has fewer calculations.  This way the obstime<=hrdifsfc(1) operates the same way as obstime >=hrdifsfc(nfldsfc).

File: src/gsi/gsdcloudanalysis.F90 (hunk 82 above)
Comment (jderber-NOAA) [reply src/gsi/gsdcloudanalysis.F90:68]: Fixed.  I should not trust the output from the "debug" compilation.

File: src/gsi/mod_fv3_lola.f90 (hunk 83 above)
Comment (jderber-NOAA) [reply src/gsi/mod_fv3_lola.f90]: No.  But is necessary for the "debug" calculation to work.

File: src/gsi/read_satwnd.f90 (hunk 84 above)
Comment (jderber-NOAA) [reply src/gsi/read_satwnd.f90]: Already removed from my version of the code.

File: src/gsi/read_prepbufr.f90 (hunk 85 above)
Comment (jderber-NOAA) [reply src/gsi/read_prepbufr.f90]: I don't understand the one read_radar.f90 comment.
I have moved the hilbertcurve stuff before the compression of the data (no reordering is done with the new code).  I don't think it will make any difference except maybe eliminating a few more unused obs from being passed to the setup routines.  I will check when I rerun the regression tests.

**Comment by jderber-NOAA** [comment]
Most regression tests are the same as the first tests.  Still minor difference in hafs_3d.

File: src/gsi/mod_fv3_lola.f90 (hunk 83 above)
Comment (jderber-NOAA) [reply src/gsi/mod_fv3_lola.f90]: I was wrong.   It actually does impact the results for hafs_3d.

**Comment by jderber-NOAA** [comment]
Finally!  Code now reproduces earlier (top of issue) results.  Differences now are only due to order of observations.  

To reproduce the results it was necessary to remove all of the changes to read_radar.f90 and mod_fv3_lola.f90 that were included to ensure that variables are initialized and do not go outside the array.  These changes are addressed in issue #661 and PR #679 .  My results trying to address the necessary changes and the changes  (Issue #661 and PR #679 ) in the results demonstrate the importance of incorporating these changes into the trunk.

Updated code addressing above comments have been committed and the branch updated.

The code is ready for re-review.

**Comment by TingLei-NOAA** [comment]
@jderber-NOAA   
```
In [src/gsi/mod_fv3_lola.f90](https://github.com/NOAA-EMC/GSI/pull/670#discussion_r1457985228):

>          else
-           rlon=half*(grid_lon(i,j)+grid_lon(i+1,j)-360._r_kind)
+           rlon=half*(grid_lon(i,j)+grid_lon(i,j+1)-360._r_kind)
I was wrong. It actually does impact the results for hafs_3d.
```   You mentioned earlier, this change is needed to avoid index out of bounds issue which caused GSI at debug mode abort.  But, now to reproduce the identical results, you revoked your change now.  If that is the case, would you please point me to your test which (using the original code) encountered the abortion ? I and/or @XuLu-NOAA  would have a look into this.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @jderber-NOAA , for identifying and fixing problems in `read_radar.f90` and `mod_fv3_lola.f90`.    Since problems with these source code files are addressed in  PR #679, your approach (back out the corrections in this PR) is reasonable.  This approach allows this PR to move forward and be merged into `develop`.  PR #679 will follow on to resolve known problems in `read_radar.f90` and `mod_fv3_lola.f90`.   

The due date for this PR is next Thursday, 1/25/2024.  I hope reviews can be completed by then and we can merge this PR into `develop` on 1/25 or 1/26.

@TingLei-NOAA , I believe John encountered non-reproducible results in ctest _hafs_3denvar_hybens_.  Is this true @jderber-NOAA ?   If so, you and/or @XuLu-NOAA can examine the issue by running this ctest yourself.

**Comment by TingLei-NOAA** [comment]
Quote
```
@TingLei-NOAA , I believe John encountered non-reproducible results in ctest hafs_3denvar_hybens. Is this true @jderber-NOAA ? If so, you and/or @XuLu-NOAA can examine the issue by running this ctest yourself.
```
@RussTreadon-NOAA  Thanks .  I will first try this test case to see if I could reproduce this issue. 
And, considering this size of this PR,  that will be great if the due day for this PR could be extended.

**Comment by RussTreadon-NOAA** [comment]
We have a backlog of GSI PRs in the queue. Let's get this big PR into `develop` by the due date.  6 weeks is sufficient time for discussion and review.  John worked through the holidays and has diligently responded to reviewers input throughout the entire process.  I'd like to give him the satisfaction of seeing his hard work enter `develop` sooner rather than later.  Additional changes may enter `develop` via existing or future issues and PRs.

**Comment by jderber-NOAA** [comment]
All,Yes I encountered non-reproducible (not reproducing earlier results) results by running the hafs 3d, hafs 4d and 4denvar regression tests when fixes were made to the read_radar routine and to the mod_fv3_lola routines.  I believe many of the changes in the results when the read_radar changes were introduced occurred with the addition of the calls the subroutines to define zsges and the other output variables.  The fixes to undefined or improperly defined toff, t4dv and t4dvo may also resulted in changes to the results.  So I removed all of the changes to both the toff, t4dv and t4dvo and the additional calls to the subroutines to define the variables zsges etc passed on in the output.  This change made the hafs 4d and 4denvar regression results duplicate those produced earlier (and the hafs 3d results were changed).To make the hafs 3d reproduce earlier regression results I had to remove the mod_fv_lola fix as well.I believe these comments are consistent with Russ's comments.Sorry if I have made any errors in variable names etc. because I do not have the PR or code in front of me right now.Best,JohnSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: TingLei-NOAA ***@***.***> Date: 1/19/24  9:45 AM  (GMT-05:00) To: NOAA-EMC/GSI ***@***.***> Cc: jderber-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NOAA-EMC/GSI] Complete issue #607 (Optimization of multiscale regional runs) (PR #670) 
Quote
@TingLei-NOAA , I believe John encountered non-reproducible results in ctest hafs_3denvar_hybens. Is this true @jderber-NOAA ? If so, you and/or @XuLu-NOAA can examine the issue by running this ctest yourself.

@RussTreadon-NOAA  Thanks .  I will first try this test case to see if I could reproduce this issue.
And, considering this size of this PR,  that will be great if the due day for this PR could be extended.

**Comment by RussTreadon-NOAA** [comment]
@shoyokota and @TingLei-NOAA , please review @jderber-NOAA's recent updates.  We would like to complete this PR by the 1/25/2024 due date.  Let me know if this poses a problem.  We may be able to find different reviewers.   Thank you.

**Comment by jderber-NOAA** [comment]
Russ,Thank you for following through on this while I took a few hours off this morning!  Thought I could do this since I am no longer employed.😁.You have obviously read my comments in the PR since you seem to understand things correctly!Again you are the best!JohnSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: RussTreadon-NOAA ***@***.***> Date: 1/19/24  9:51 AM  (GMT-05:00) To: NOAA-EMC/GSI ***@***.***> Cc: jderber-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NOAA-EMC/GSI] Complete issue #607 (Optimization of multiscale regional runs) (PR #670) 
We have a backlog of GSI PRs in the queue. Let's get this big PR into develop by the due date.  6 weeks is sufficient time for discussion and review.  John worked through the holidays and has diligently responded to reviewers input throughout the entire process.  I'd like to give him the satisfaction of seeing his hard work enter develop sooner rather than later.  Additional changes may enter develop via existing or future issues and PRs.

**Comment by TingLei-NOAA** [comment]
@RussTreadon-NOAA  I will do my reviewing part as soon as possible. However, the Jan 25 , 2024 deadline is still a problem to me. Thanks for your coordination and taking of this.

File: src/gsi/intrw.f90 [hunk 86]
```diff
@@ -127,23 +127,17 @@ subroutine intrw_(rwhead,rval,sval)
...
-  end if
 
   if(ier/=0)return
 
+  include_w=.false.
+  call gsi_bundlegetpointer(sval,'w',sw,istatus)
+  if (if_use_w_vr.and.istatus==0) then
+     call gsi_bundlegetpointer(rval,'w',rw,istatus)
+     if(istatus == 0)include_w=.true.
+  end if
```
Comment (shoyokota) [inline src/gsi/intrw.f90:140]: This modification should be done also in stprw.f90.

File: src/enkf/letkf.f90 [hunk 87]
```diff
@@ -524,7 +524,7 @@ subroutine letkf_update()
    if (allocated(sresults)) deallocate(sresults)
    if (allocated(ens_tmp)) deallocate(ens_tmp)
 end do grdloop
-!$omp end parallel do
+! !$omp end parallel do
```
Comment (shoyokota) [inline src/enkf/letkf.f90]: This comment out also should be turned back.

File: src/gsi/setuprw.f90 [hunk 88]
```diff
@@ -992,8 +993,9 @@ subroutine check_vars_ (proceed, include_w)
   endif
   end subroutine check_vars_ 
 
-  subroutine init_vars_
+  subroutine init_vars_(include_w)
 
+  logical,intent(inout):: include_w
```
Comment (shoyokota) [inline src/gsi/setuprw.f90]: I think it should be intent(in) here.

File: src/gsi/setuprw.f90 [hunk 89]
```diff
@@ -788,120 +788,121 @@ subroutine setuprw(obsLL,odiagLL,lunin,mype,bwork,awork,nele,nobs,is,conv_diagsa
...
+                my_head%raterr2 = ratio_errors**2  
+                my_head%cosazm_costilt = cosazm_costilt
+                my_head%sinazm_costilt = sinazm_costilt
+                my_head%sintilt = sintilt
+                my_head%res     = ddiff
+                my_head%err2    = error**2
+                my_head%time    = dtime
+                my_head%luse    = luse(i)
+                my_head%b       = cvar_b(ikx)
+                my_head%pg      = cvar_pg(ikx)
```
Comment (shoyokota) [inline src/gsi/setuprw.f90]: These indent changes are not needed.

File: src/gsi/deter_sfc_mod.f90 (hunk 81 above)
Comment (shoyokota) [reply src/gsi/deter_sfc_mod.f90:603]: When obstime = hrdifsfc(nfldsfc), (itsfc,itsfcp,dtsfc)=(nfldsfc-1,nfldsfc,zero) in the original code. But after this modification, (itsfc,itsfcp,dtsfc)=(nfldsfc,nfldsfc,one). Doesn't it change the result?

If this modification is no problem, you should modify also in L159,467,824.

File: src/gsi/read_radar.f90 [hunk 90]
```diff
@@ -2154,18 +2176,14 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,hgtl_fu
   ibadstaheight=0
   notgood=0
   notgood0=0
-  nread=0
```
Comment (shoyokota) [inline src/gsi/read_radar.f90]: Why did you remove this zero-clear?

**Review by shoyokota — COMMENTED** [review]
@jderber-NOAA Thank you for thorough modifications based on my comments. Could you confirm a few minor comments for your additional modifications?

File: src/gsi/read_prepbufr.f90 (hunk 85 above)
Comment (shoyokota) [reply src/gsi/read_prepbufr.f90]: Thank you for modification. How was the result of the tests? In my understanfing, apply_hilbertcurve changes  cdata_all(thisobtype_usage,1:ndata) based on the order of calling accum_hilbertcurve, so apply_hilbertcurve should be called before sorting cdata_all. (Please see the argument of cdata_usage in support_2dvar.f90.)

**Comment by RussTreadon-NOAA** [comment]
@jderber-NOAA , your branch `jderber-NOAA:optimize6` is two commits behind the current head of `develop`.  The two commits are minor.  I manually merged `develop` into my working copy of `optimize6` on Cactus.  No conflicts occurred in the merger.  I am currently running ctests on Cactus and will update this PR with results when the tests finish.

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 (Cactus) ctests**
```
russ.treadon@clogin07:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr670/build> ctest -j 7
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr670/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  603.90 sec
2/7 Test #7: global_enkf ......................***Failed  624.80 sec
3/7 Test #3: rrfs_3denvar_glbens ..............   Passed  730.39 sec
4/7 Test #6: hafs_3denvar_hybens ..............***Failed  1214.61 sec
5/7 Test #5: hafs_4denvar_glbens ..............***Failed  1332.69 sec
6/7 Test #2: rtma .............................***Failed  1387.36 sec
7/7 Test #1: global_4denvar ...................***Failed  1445.74 sec

29% tests passed, 5 tests failed out of 7

Total Test time (real) = 1445.75 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          2 - rtma (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
          7 - global_enkf (Failed)
Errors while running CTest
```

`global_4denvar` failed due to non-reproducibility.   The initial step size for the update and control `gsi.x` differs in the 17th digit.

`rtma` failed due to the `maximum allowable threshold time` test.  This is not a fatal fail.

`hafs_4envar_glbens` failed due to non-reproducibility.  The initial step size for the update and control `gsi.x` differ in the 16th digit.

`hafs_3denvar_hybens` failed due to non-reproducibility.  The second iteration total penalty for the update and control `gsi.x` differ in the 17th digit.

`global_enkf` failed due to the `maximum allowable threshold time` test. This is not a fatal fail.

**Comment by jderber-NOAA** [comment]
Russ,Results as expected.  hafs_3d, hafs_4d and global_4denvar are slightly different due to different ordering of data.Not sure why other jobs failed due to time.JohnSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: RussTreadon-NOAA ***@***.***> Date: 1/19/24  6:36 PM  (GMT-05:00) To: NOAA-EMC/GSI ***@***.***> Cc: jderber-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NOAA-EMC/GSI] Complete issue #607 (Optimization of multiscale regional runs) (PR #670) 
WCOSS2 (Cactus) ctests
***@***.***:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr670/build> ctest -j 7
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr670/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  603.90 sec
2/7 Test #7: global_enkf ......................***Failed  624.80 sec
3/7 Test #3: rrfs_3denvar_glbens ..............   Passed  730.39 sec
4/7 Test #6: hafs_3denvar_hybens ..............***Failed  1214.61 sec
5/7 Test #5: hafs_4denvar_glbens ..............***Failed  1332.69 sec
6/7 Test #2: rtma .............................***Failed  1387.36 sec
7/7 Test #1: global_4denvar ...................***Failed  1445.74 sec

29% tests passed, 5 tests failed out of 7

Total Test time (real) = 1445.75 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          2 - rtma (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
          7 - global_enkf (Failed)
Errors while running CTest

global_4denvar failed due to non-reproducibility.   The initial step size for the update and control gsi.x differs in the 17th digit.
rtma failed due to the maximum allowable threshold time test.  This is not a fatal fail.
hafs_4envar_glbens failed due to non-reproducibility.  The initial step size for the update and control gsi.x differ in the 16th digit.
hafs_3denvar_hybens failed due to non-reproducibility.  The second iteration total penalty for the update and control gsi.x differ in the 17th digit.
global_enkf failed due to the maximum allowable threshold time test. This is not a fatal fail.

**Comment by jderber-NOAA** [comment]
Will update by Monday.  Thanks!Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: RussTreadon-NOAA ***@***.***> Date: 1/19/24  5:09 PM  (GMT-05:00) To: NOAA-EMC/GSI ***@***.***> Cc: jderber-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NOAA-EMC/GSI] Complete issue #607 (Optimization of multiscale regional runs) (PR #670) 
@jderber-NOAA , your branch jderber-NOAA:optimize6 is two commits behind the current head of develop.  The two commits are minor.  I manually merged develop into my working copy of optimize6 on Cactus.  No conflicts occurred in the merger.  I am currently running ctests on Cactus and will update this PR with results when the tests finish.

**Comment by RussTreadon-NOAA** [comment]
Thank you @jderber-NOAA for confirming and explaining that the non-reproducible results between the update and control `gsi.x` are expected. 

The timing threshold test needs to be revised.  Jobs can run fast or slow for a variety of reasons not related to `gsi.x` or `enkf.x`.  A check of the wall times from the `rtma` and `global_enkf` ctests did not indicate any egregious behavior.

**Comment by TingLei-NOAA** [comment]
On wcoss2, when running global_4denvar ctest using GSI on debug mode, for the update/this PR, in the stdout , there are error message: 
```
GLBSOI: jiter,jiterstart,jiterlast,jiterend=    1    1    2    1
           0 setuprad: passive obs          57 hirs4_n19            
           0 setuprad: passive obs          73 cris-fsr_npp         
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
gsi.x              0000000007B11BFB  Unknown               Unknown  Unknown
........................
libmpi_intel.so.1  00001466B1A8F231  PMPI_Allreduce        Unknown  Unknown
libmpifort_intel.  00001466B7B9B856  mpi_allreduce_        Unknown  Unknown
gsi.x              0000000000982BE8  m_gpsstats_mp_gen         311  genstats_gps.f90
gsi.x              00000000025FCF4F  setuprhsall_              531  setuprhsall.f90
...
````
The control (current EMC GSI) didn't show this error.  
For hafs_4denvar_glbens_loproc_update, its stdout also shows an error with the mpi_allreduce .
```
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
.....
libmpi_intel.so.1  0000153C7A11A231  PMPI_Allreduce        Unknown  Unknown
libmpifort_intel.  0000153C80226856  mpi_allreduce_        Unknown  Unknown
gsi.x              0000000001C19353  read_obsmod_mp_re        1960  read_obs.F90
gsi.x              000000000172797D  observermod_mp_se         329  observer.F90
```
I will see if I can repeat those behaviors on hera.

**Comment by jderber-NOAA** [comment]
Ting,

The changes do not make the code work in debug mode.  This would require the changes to read_radar.f90 and mod_fv3_lola.f90 plus additional fixes I was not able to uncover.

File: src/gsi/intrw.f90 (hunk 86 above)
Comment (jderber-NOAA) [reply src/gsi/intrw.f90:140]: I did not get to the stp routines before I had to start the PR.  However, I have made the change.

File: src/enkf/letkf.f90 (hunk 87 above)
Comment (jderber-NOAA) [reply src/enkf/letkf.f90]: That line was not really necessary, but you are right it should have been put back.  Done.

File: src/gsi/setuprw.f90 (hunk 88 above)
Comment (jderber-NOAA) [reply src/gsi/setuprw.f90]: Correct!  Done.

**Comment by TingLei-NOAA** [comment]
John, Thanks.  I already use mod_fv3_lola.f90 in https://github.com/NOAA-EMC/GSI/pull/679 with fix from Xu and I am quite sure any remaining errors from that code would be rather straightforward to be fixed.

File: src/gsi/setuprw.f90 (hunk 89 above)
Comment (jderber-NOAA) [reply src/gsi/setuprw.f90]: Indentation fixed!

File: src/gsi/read_radar.f90 (hunk 90 above)
Comment (jderber-NOAA) [reply src/gsi/read_radar.f90]: Comment for deter_sfc_mod.f90:  It will give the same result because for both the value for nfldsfc is multiplied by one.

I have made the other changes.  It reduces the possibility of a small round-off error.

Comment for read_radar.f90: It is set to 0 in the read_obs routine (one level up).  However I will add it back in.  Doesn't really make any difference.

**Comment by jderber-NOAA** [comment]
Regression tests rerun on code with updates and suggestions from Sho.  Results identical, no change.

File: src/gsi/read_prepbufr.f90 (hunk 85 above)
Comment (jderber-NOAA) [reply src/gsi/read_prepbufr.f90]: I tried the regression test for the rtma with both the apply_hilbertcurve called both before and after the compression of the data.  The regression test results were identical.  I looked at all the different variables read in in read_prepbufr.  Again all were the same, with the same number of observations, same number removed in the compression, etc.  

Since I do not understand the hilbert curve stuff well, I will leave the call to hilbertcurve before the regession.

**Comment by TingLei-NOAA** [comment]
An update :  the failure with hafs regression test when gsi is compiled in debug mode was from the undefined toff in read_radar_l2rw_novadqc. The issue existing in the current EMC  GSI and already have a PR for fix https://github.com/NOAA-EMC/GSI/pull/679/files#diff-9237af61f8a4787143a6ef94bfdefcd7a764f8f986e54370beffb92b3f08d2d3.

**Comment by TingLei-NOAA** [comment]
An update : when EnKF is also compiled with debug mode, the current EMC GSI (and, hence, including this PR) would fail the regression test global_enkf .  There are two places  in letkf.f90. The first is easy to find why and fix.
```
call mpi_reduce(tend-tbegin,tmean,1,mpi_real8,mpi_sum,0,mpi_comm_world,ierr)
tmean = tmean/numproc
```
(and the similar lines for tmean),    tmean is only valid on rank 0 after mpi_reduce, but is used in the following line on every mpi rank. 

The second issue is more tricky.  The error message is :
```
41: forrtl: error (75): floating point exception
 41: Image              PC                Routine            Line        Source
 41: enkf.x             0000000004B5152B  Unknown               Unknown  Unknown
 41: libpthread-2.17.s  00002B95C4972630  Unknown               Unknown  Unknown
 41: enkf.x             000000000053D86D  letkf_mp_letkf_up         281  letkf.f90
 41: libiomp5.so        00002B95C4CBEBB3  __kmp_invoke_micr     Unknown  Unknown
 41: libiomp5.so        00002B95C4C3AFAC  __kmp_fork_call       Unknown  Unknown
 41: libiomp5.so        00002B95C4BFCCB5  __kmpc_fork_call      Unknown  Unknown
 41: enkf.x             000000000053701E  letkf_mp_letkf_up         281  letkf.f90
````
The line 281 is the beginning line of a large block of openmp directives :
```
!$omp parallel do schedule(dynamic) default(none) private(npt,nob,nobsl, &
!$omp                  nobsl2,ngrd1,corrlength,ens_tmp,coslat, &
!$omp                  nf,vdist,obens,indxassim,indxob,maxdfs, &
!$omp                  nn,hxens,wts_ensmean,dfs,rdiag,dep,rloc,i, &
....
```
I haven't identified the culprit for this error. 
Since this issue is from EMC GSI, it is not specific to this PR and just an FYI here since it is found when I ran regression tests with debug mode GSI.

**Review by shoyokota — APPROVED** [review]
Thank you for all modifications! I approved now.

**Comment by shoyokota** [comment]
I did the Orion tests as follows.

```
Test project /home/syokota/da/gsi/jderber-NOAA/optimize6/build
    Start 1: global_4denvar
1/7 Test #1: global_4denvar ...................***Failed  1807.53 sec
    Start 2: rtma
2/7 Test #2: rtma .............................   Passed  1150.92 sec
    Start 3: rrfs_3denvar_glbens
3/7 Test #3: rrfs_3denvar_glbens ..............   Passed  668.53 sec
    Start 4: netcdf_fv3_regional
4/7 Test #4: netcdf_fv3_regional ..............   Passed  304.54 sec
    Start 5: hafs_4denvar_glbens
5/7 Test #5: hafs_4denvar_glbens ..............***Failed  1938.86 sec
    Start 6: hafs_3denvar_hybens
6/7 Test #6: hafs_3denvar_hybens ..............***Failed  1342.42 sec
    Start 7: global_enkf
7/7 Test #7: global_enkf ......................   Passed  752.57 sec

57% tests passed, 3 tests failed out of 7

Total Test time (real) = 7965.40 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest
```

Non-reproducibility in global_4denvar, hafs_4denvar_glbens, and hafs_3denvar_hybens is as we expected. There are no fatal issues.

**Comment by CatherineThomas-NOAA** [comment]
>  I wonder if there is any improvement with an AVN run where the diagnostic files are already reduced.

I ran some more full resolution tests on WCOSS2 at b7bdbc4, this time for the early dump.  Here are the timings:
```
Control | pmot=0  | pmot=2

1474.49 | 1432.36 | 1439.71
1471.59 | 1459.48 | 1430.03
1473.16 | 1440.87 | 1451.98
1470.20 | 1435.78 | 1436.15
1473.01 | 1436.50 | 1435.40
   
1472.49 | 1441.00 | 1438.65
```
All PR tests are faster than all control tests.

My findings for the cost function are similar to my previous full resolution tests.  Cost functions are identical within each test (i.e. all pmot=0 are the same).  The pmot=0 and pmot=2 cases have identical cost functions.  The difference between the control and pmot initial cost functions are identical to 7 digits, which is more different than the regression tests:
```
Control: 1   0  1.592669394534466555E+06  4.103124635798992131E+03  2.612806160403545075E+00 
PR:      1   0  1.592669436005641473E+06  4.103124485022790395E+03  2.612806511958422728E+00 
```

**Comment by jderber-NOAA** [comment]
Sho, thanks for the approval.

**Comment by jderber-NOAA** [comment]
Cathy,

Thanks for running this experiment!  Glad you got positive results!  But a bit confused why you got different initial penalties.  What observation types produced a different initial penalty (e.g., radiances, wind, etc.)?  Also, can you send me the diff of the output diagnostic files (fort.2**) for the observation type for the first outer iteration?

Thanks!

**Comment by RussTreadon-NOAA** [comment]
The due date for completion of this PR is Thursday, 1/25/2024.  @shoyokota has approved the PR. @TingLei-NOAA , what outstanding questions or issues do you need answered or resolved before you can complete your review?

**Comment by TingLei-NOAA** [comment]
@RussTreadon-NOAA  As reported previously, a few GSI/EnKF failures in the regression tests when GSI/EnKF are built with debug mode had been investigated . It was finally concluded they are from EMC GSI .( Some already have fix in other PR and, one in EnKF has a simple fix  and another one with the letkf need more efforts ) and shouldn't affect this PR. What I am going to do is to check the rrfs comparison with this PR and then I will do a quick reviewing of the current codes.  That is my plan and still can't guarantee I could make it before your due date.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @TingLei-NOAA , for the update.  By what date do you anticipate completing your review?  Knowing this helps the GSI Handling Review team plan their work as well as help @jderber-NOAA arrange his schedule.

**Comment by TingLei-NOAA** [comment]
@RussTreadon-NOAA  Thanks for all your efforts.   Just hope you also noticed there is a possible reproducibility in the global case @CatherineThomas-NOAA  provided .  On my side, I expect I could finish all my actions in one week if everything is going well.  
I really appreciate John's master 's effort for this large scale GSI optimization and response in this PR ' (Thanks also to Sho's rather complete reviews) and hope I could help finish this PR as good as I can .

**Comment by RussTreadon-NOAA** [comment]
@TingLei-NOAA , as [mentioned last Friday (1/19/2024)](https://github.com/NOAA-EMC/GSI/pull/670#issuecomment-1900785088) would you prefer to be removed as a reviewer from this PR?  

This allows you to continue your tests without needing to work outside of your normal workday schedule.  You have a lot on your plate and we don't want you burning the candle at both ends to complete this PR by due date.

**Comment by TingLei-NOAA** [comment]
@RussTreadon-NOAA  Sure. Please go ahead.   I will give updates on my verification results for this PR.

**Comment by CatherineThomas-NOAA** [comment]
@jderber-NOAA 

The initial difference is in the radiances:
Control:
```
     J term                                     J
excess   moisture            3.8458219840846913E-01
surface pressure             1.1982398576591007E+04
temperature                  8.8339292197175426E+04
wind                         1.9503807419532203E+05
moisture                     8.2165047114701410E+03
sst                          3.3361437026688859E+03
ozone                        1.8475954283744115E+04
gps bending angle            2.5125135570621365E+05
radiance                     1.0160292865790830E+06
-----------------------------------------------------
 J Global                    1.5926693945344666E+06
```
PR:
```
     J term                                     J
excess   moisture            3.8458219840846913E-01
surface pressure             1.1982398576591007E+04
temperature                  8.8339292197175426E+04
wind                         1.9503807419532203E+05
moisture                     8.2165047114701410E+03
sst                          3.3361437026688859E+03
ozone                        1.8475954283744115E+04
gps bending angle            2.5125135570621365E+05
radiance                     1.0160293280502578E+06
 -----------------------------------------------------
 J Global                    1.5926694360056415E+06
```

My original tests have been scrubbed, but I'll rerun a single case of each today and copy over the fort files.

**Comment by jderber-NOAA** [comment]
But...But I didnt change anything with the radiances.  Sigh.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: CatherineThomas-NOAA ***@***.***> Date: 1/23/24  9:54 AM  (GMT-05:00) To: NOAA-EMC/GSI ***@***.***> Cc: jderber-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NOAA-EMC/GSI] Complete issue #607 (Optimization of multiscale regional runs) (PR #670) 
@jderber-NOAA
The initial difference is in the radiances:
Control:
     J term                                     J
excess   moisture            3.8458219840846913E-01
surface pressure             1.1982398576591007E+04
temperature                  8.8339292197175426E+04
wind                         1.9503807419532203E+05
moisture                     8.2165047114701410E+03
sst                          3.3361437026688859E+03
ozone                        1.8475954283744115E+04
gps bending angle            2.5125135570621365E+05
radiance                     1.0160292865790830E+06
-----------------------------------------------------
 J Global                    1.5926693945344666E+06

PR:
     J term                                     J
excess   moisture            3.8458219840846913E-01
surface pressure             1.1982398576591007E+04
temperature                  8.8339292197175426E+04
wind                         1.9503807419532203E+05
moisture                     8.2165047114701410E+03
sst                          3.3361437026688859E+03
ozone                        1.8475954283744115E+04
gps bending angle            2.5125135570621365E+05
radiance                     1.0160293280502578E+06
 -----------------------------------------------------
 J Global                    1.5926694360056415E+06

My original tests have been scrubbed, but I'll rerun a single case of each today and copy over the fort files.

**Comment by jderber-NOAA** [comment]
Cathy,

Will run my full resolution tests again.  Could you send your script (or one of your outputs) to me (or put it on Hera) so that I can make sure I am using the same satellite data types?

John

**Comment by TingLei-NOAA** [comment]
An update :  the current PR produced the identical results, in terms of stats in the stdout, compared  with the EMC GSI Develop branch in a RRFS parallel case using obs including sat and dbz.

**Comment by CatherineThomas-NOAA** [comment]
@jderber-NOAA @TingLei-NOAA 
I got to the root of the initial cost function differences.  @RussTreadon-NOAA ran several cases on WCOSS2 as well and found identical cost functions.  I also found another cycle that had identical cost functions with my same setup.  We explored some of the differences between our configurations but the problem was with my executables.  My clone of develop contained the Dec 20 update to setuprad.f90 while my clone of John's branch did not.  Russ checked out a newer version of John's branch for his tests, which contained John's merge from develop.

My new tests using the latest version of the PR branch now produces identical initial cost functions.

**Comment by jderber-NOAA** [comment]
Thanks Cathy for looking into this and finding the issue!Sorry if I did not keep my branch up to develop and I made you waste time.It is a great relief that there was not a real issue.Best,JohnSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: CatherineThomas-NOAA ***@***.***> Date: 1/24/24  11:48 AM  (GMT-05:00) To: NOAA-EMC/GSI ***@***.***> Cc: jderber-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NOAA-EMC/GSI] Complete issue #607 (Optimization of multiscale regional runs) (PR #670) 
@jderber-NOAA @TingLei-NOAA
I got to the root of the initial cost function differences.  @RussTreadon-NOAA ran several cases on WCOSS2 as well and found identical cost functions.  I also found another cycle that had identical cost functions with my same setup.  We explored some of the differences between our configurations but the problem was with my executables.  My clone of develop contained the Dec 20 update to setuprad.f90 while my clone of John's branch did not.  Russ checked out a newer version of John's branch for his tests, which contained John's merge from develop.
My new tests using the latest version of the PR branch now produces identical initial cost functions.

**Review by RussTreadon-NOAA — APPROVED** [review]
Approve.  Merge pending final peer review.

**Review by CatherineThomas-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
Thank you @shoyokota and @CatherineThomas-NOAA for your approvals.   I'll coordinate with the Handling Review team to merge this PR into `develop`.

**Comment by jderber-NOAA** [comment]
Thank you Russ too!Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: RussTreadon-NOAA ***@***.***> Date: 1/26/24  9:44 AM  (GMT-05:00) To: NOAA-EMC/GSI ***@***.***> Cc: jderber-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NOAA-EMC/GSI] Complete issue #607 (Optimization of multiscale regional runs) (PR #670) 
Thank you @shoyokota and @CatherineThomas-NOAA for your approvals.   I'll coordinate with the Handling Review team to merge this PR into develop.
