### PR TITLE
Assimilate GMI in GSI (#689)

### LINKED ISSUE #689: Assimilate GMI in GSI
The GMI codes existed does not work.

### PR DESCRIPTION
**Pull request by xincjin-NOAA**
**DUE DATE for merger of this PR into `develop` is 3/6/2024 (six weeks after PR creation).**

**Description**
This pull request is to related to #689
Resolves #689

The original code for assimilating GMI in GSI is not working properly.
The main changes are:

- modified / simplified  superobbing algorithm in ssmis_spatial_average_mod.f90  
- various changes in read_gmi.f90, e.g., increase maxobs value;
- remove clw impacts on the bias predictor 6 and 7 in setuprad.f90;
- modified clw impact on the bias predictors in radiance_mod.f90;
- modified the function deter_sfc_gmi so that it can applied to bigger domain;
- added a condition in function gmi_37pol_diff to exclude unreasonable data;

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

The changes have been verified by a few experiments with more than two months running time
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA Could you add @emilyhcliu , @ADCollard , and @azadeh-gh as reviewers?

I have run the regression tests on hera and all 7 tests are passed.

**Comment by RussTreadon-NOAA** [comment]
Please post ctest results in this PR or the originating issue, #689.  Ctests need to be run on WCOSS2, Hera, Orion, and Hercules.  This PR will be returned to closed and returned to the develop if at least two peer reviews with approvals and ctests are completed.

**Comment by xincjin-NOAA** [comment]
1. The ctest on orion is passed.

2. There is one failure on WCOSS2:

The following tests FAILED:

          1 - global_4denvar (Failed)


It seems a few files are not existed, e.g.

amsuabufr_db -> /lfs/h2/emc/da/noscrub/russ.treadon/CASES/regtest/gfs/prod/gdas.20221109/00/atmos/gdas.t00z.amuadb.tm00.bufr_d

The tmpdir is /lfs/h2/emc/ptmp/xin.c.jin/GSI/tmpreg_global_4denvar/global_4denvar_loproc_updat>

3. There are two fails on  Hercules (under review)

**Comment by xincjin-NOAA** [comment]
The two failure for ctest on Hercules are:
1. hafs_3denvar:
The runtime for hafs_3denvar_hybens_loproc_updat is 254.941863 seconds and is within the maximum allowable operational time of 1200 seconds, continuing with regression test.

The runtime for hafs_3denvar_hybens_loproc_updat is 254.941863 seconds and is within the allowable threshold time of 413.289465 seconds, continuing with regression test.

The runtime for hafs_3denvar_hybens_hiproc_updat is 200.579084 seconds and is within the allowable threshold time of 331.662442 seconds, continuing with regression test.

The memory for hafs_3denvar_hybens_loproc_updat is 2532516 KBs and is within the maximum allowable memory of 2780342 KBs, continuing with regression test.

The results (penalty) between the two runs (hafs_3denvar_hybens_loproc_updat and hafs_3denvar_hybens_loproc_contrl) are reproducible.

The fv3_dynvars are reproducible
The fv3_sfcdata are reproducible
The fv3_tracer are reproducible
The results between the two runs (hafs_3denvar_hybens_loproc_updat and hafs_3denvar_hybens_loproc_contrl) are reproducible since the corresponding results are identical.

The results (penalty) between the two runs (hafs_3denvar_hybens_loproc_updat and hafs_3denvar_hybens_hiproc_updat) are reproducible

The fv3_sfcdata are reproducible
The fv3_tracer are reproducible
The results between the two runs (hafs_3denvar_hybens_loproc_updat and hafs_3denvar_hybens_hiproc_updat) are not reproducible Thus, the case has Failed siganl of the regression tests.

2. hafs_4denvar:

The runtime for hafs_4denvar_glbens_loproc_updat is 328.091246 seconds and is within the maximum allowable operational time of 1200 seconds, continuing with regression test.

The runtime for hafs_4denvar_glbens_loproc_updat is 328.091246 seconds.  This has exceeded maximum allowable threshold time of 326.818903 seconds, resulting in Failure time-thresh of the regression test.
 
The runtime for hafs_4denvar_glbens_hiproc_updat is 254.226137 seconds and is within the allowable threshold time of 282.596399 second, continuing with regression test.

The memory for hafs_4denvar_glbens_loproc_updat is 2858764 KBs and is within the maximum allowable memory of 3199819 KBs, continuing with regression test.

The results (penalty) between the two runs (hafs_4denvar_glbens_loproc_updat and hafs_4denvar_glbens_loproc_contrl) are reproducible.

The fv3_dynvars are reproducible
The fv3_sfcdata are reproducible
The fv3_tracer are reproducible
The results between the two runs (hafs_4denvar_glbens_loproc_updat and hafs_4denvar_glbens_loproc_contrl) are reproducible
since the corresponding results are identical.

The results (penalty) between the two runs (hafs_4denvar_glbens_loproc_updat and hafs_4denvar_glbens_hiproc_updat) are reproducible

The fv3_dynvars are reproducible
The fv3_sfcdata are reproducible
The fv3_tracer are reproducible
The results between the two runs (hafs_4denvar_glbens_loproc_updat and hafs_4denvar_glbens_hiproc_updat) are reproducible
since the corresponding results are identical.

Any comments on how to deal with these failure.

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 failure**

`stdout` in `/lfs/h2/emc/ptmp/xin.c.jin/GSI/tmpreg_global_4denvar/global_4denvar_loproc_updat` contains the following traceback
```
forrtl: Permission denied
forrtl: severe (9): permission to access file denied, unit 15, file /lfs/h2/emc/ptmp/xin.c.jin/GSI/tmpreg_global_4denvar/global_4denvar_loproc_up\
dat/prepbufr_profl
Image              PC                Routine            Line        Source
gsi.x              00000000020006BB  Unknown               Unknown  Unknown
gsi.x              000000000201C3E0  Unknown               Unknown  Unknown
gsi.x              00000000008D30AB  read_obsmod_mp_re         201  read_obs.F90
gsi.x              00000000008C75C6  read_obsmod_mp_re        1092  read_obs.F90
gsi.x              00000000007F1C0C  observermod_mp_se         331  observer.F90
gsi.x              00000000010A5223  glbsoi_                   222  glbsoi.f90
gsi.x              00000000006572D7  gsisub_                   200  gsisub.F90
gsi.x              00000000004137FD  gsimod_mp_gsimain        2414  gsimod.F90
```
File `prepbufr_profl` is a restricted access (_rstprod_) file
```
-rw-r----- 1 russ.treadon rstprod 15192992 Nov 11  2022 prepbufr_profl
```
@xincjin-NOAA , you do not belong to the WCOSS2 _rstprod_ group.
```
xin.c.jin : emc da global backupsys
```

You need to request _rstprod_ access.  Please visit [NCO's Restricted Data Information page](https://www.nco.ncep.noaa.gov/pmb/docs/restricted_data/) to learn how to request _rstprod_ access.

**Comment by RussTreadon-NOAA** [comment]
**Hercules failure**

The `hafs_3denvar_hybens` failure is a known problem on Hercules.  On a fairly regular basis the contents of analysis file `fv3_dynvars` vary between the _loproc_ and _hiproc_ runs of `gsi.x`.  Repeating the ctest can yield a _Passed_ or another _Failed_.  GSI issue [#697](https://github.com/NOAA-EMC/GSI/issues/697) was opened to report this reproducibility problem.  The regional DA team is aware of this problem.

The `hafs_4denvar_glbens` failure is not a fatal fail.  A check of the `gsi.x` wall times for the various runs shows
```
hafs_4denvar_glbens_hiproc_contrl/stdout:The total amount of wall time                        = 256.905818
hafs_4denvar_glbens_hiproc_updat/stdout:The total amount of wall time                        = 254.226137
hafs_4denvar_glbens_loproc_contrl/stdout:The total amount of wall time                        = 297.108094
hafs_4denvar_glbens_loproc_updat/stdout:The total amount of wall time                        = 328.091246
```
The _loproc_updat_ ran 31 seconds longer than the _loproc_contrl_.  The `work/` fileset in which the ctests ran is know to suffer from latency issues.  The above range of `gsi.x` times is acceptable on Hercules.

**Comment by RussTreadon-NOAA** [comment]
Please post Hera ctests results when they are available.

Since this PR adds code to assimilate GMI, we need confirmation either in this PR or in the originating issue, #689 , that the changes in this PR result in `gsi.x` and `enkf.x` correctly assimilating GMI.   At some point we should update at least the global ctests to a case which assimilates GMI.  Otherwise, we risk the possibility of future GSI PRs breaking the GMI assimilation capability this PR adds.

**Comment by xincjin-NOAA** [comment]
Results from two  GMI experiments which were Run for 60 days can be found on

https://www.emc.ncep.noaa.gov/users/xjin/v16_gmi_ens_exp/

https://www.emc.ncep.noaa.gov/users/xjin/v16_gmi_test_09_20/

https://www.emc.ncep.noaa.gov/gmb/gdas/radiance/xjin/gmi/gmi_ens_exp/

https://www.emc.ncep.noaa.gov/gmb/gdas/radiance/xjin/gmi/gmi_test_09_20/

Other details can be found on the attached poster.
 
[agu23_gc41m-1294_XinJin_36x48.pdf](https://github.com/NOAA-EMC/GSI/files/14283401/agu23_gc41m-1294_XinJin_36x48.pdf)

**Comment by xincjin-NOAA** [comment]
Ctest on Hera passed 6 tests. The test not passed has the following information:

[Xin.C.Jin@hfe08 regression]$  more hafs_4denvar_glbens_regression_results.txt
The runtime for hafs_4denvar_glbens_loproc_updat is 360.988536 seconds and is within the maximum allowable operational time of 1200 seconds, continuing with regression test.

The runtime for hafs_4denvar_glbens_loproc_updat is 360.988536 seconds.  This has exceeded maximum allowable threshold time of 329.516453 seconds, resulting in Failure time-thresh of the regression test.

The runtime for hafs_4denvar_glbens_hiproc_updat is 263.256873 seconds.  This has exceeded maximum allowable threshold time of 260.885010 seconds, resulting in Failure of timethresh2 the regression test.

The memory for hafs_4denvar_glbens_loproc_updat is 2882748 KBs and is within the maximum allowable memory of 3244072 KBs, continuing with regression test.

The results (penalty) between the two runs (hafs_4denvar_glbens_loproc_updat and hafs_4denvar_glbens_loproc_contrl) are reproducible.

The fv3_dynvars are reproducible
The fv3_sfcdata are reproducible
The fv3_tracer are reproducible
The results between the two runs (hafs_4denvar_glbens_loproc_updat and hafs_4denvar_glbens_loproc_contrl) are reproducible
since the corresponding results are identical.

The results (penalty) between the two runs (hafs_4denvar_glbens_loproc_updat and hafs_4denvar_glbens_hiproc_updat) are reproducible

The fv3_dynvars are reproducible
The fv3_sfcdata are reproducible
The fv3_tracer are reproducible
The results between the two runs (hafs_4denvar_glbens_loproc_updat and hafs_4denvar_glbens_hiproc_updat) are reproducible
since the corresponding results are identical.

**Comment by RussTreadon-NOAA** [comment]
@xincjin-NOAA , both of the failed checks for the Hera `hafs_4denvar_glbens` ctest involved wall time.  Please examine the wall times for all four `hafs_4denvar_glbens` runs to see if any timings look anomalous.

**Comment by xincjin-NOAA** [comment]
The wall time are as below:
hafs_4denvar_glbens_hiproc_contrl/stdout:The total amount of wall time                        = 237.168191
hafs_4denvar_glbens_hiproc_updat/stdout:The total amount of wall time                        = 263.256873
hafs_4denvar_glbens_loproc_contrl/stdout:The total amount of wall time                        = 299.560412
hafs_4denvar_glbens_loproc_updat/stdout:The total amount of wall time                        = 360.988536

The updat runs are slower than the contrl ones

The breakdown for the loproc runs are as below:

hafs_4denvar_glbens_loproc_contrl/stdout
The total amount of wall time                        = 299.560412
The total amount of time in user mode                = 259.579043
The total amount of time in sys mode                 = 27.728789


hafs_4denvar_glbens_loproc_updat/stdout
The total amount of wall time                        = 360.988536
The total amount of time in user mode                = 289.760696
The total amount of time in sys mode                 = 19.428450

I guess I don't have enough knowledge to judge if they are normal or not.

**Comment by RussTreadon-NOAA** [comment]
Some options to consider
1. run ctest `hafs_4denvar_glbens` on Hera at a different time of day (e.g., early morning, late evening) to see if wall clock times improve for _updat_.
2. check `gsi.x` wall times for other ctests on Hera.  Is similar behavior observed? 
3. check `hafs_4denvar_glbens` wall times for `gsi.x` on other machines.  Is similar behavior observed?

**Comment by xincjin-NOAA** [comment]
hafs_4denvar_glbens_hiproc_contrl/stdout:The total amount of wall time                        = 267.771050
hafs_4denvar_glbens_hiproc_updat/stdout:The total amount of wall time                        = 245.148727
hafs_4denvar_glbens_loproc_contrl/stdout:The total amount of wall time                        = 303.032343
hafs_4denvar_glbens_loproc_updat/stdout:The total amount of wall time                        = 340.304098

These are the results from a new ctest in which I EXCHANGED the locations of contrl and updat. This means that the updat represent the GSI codes from develop branch. 

I am not sure if you can check the git branch on the directory of:  /scratch1/NCEPDEV/da/Xin.C.Jin/git/GSI and /scratch1/NCEPDEV/da/Xin.C.Jin/git/develop

It seems that the wall time is related to the order of the test runs

**Comment by xincjin-NOAA** [comment]
Ctest for WCOSS2 is passed.

**Comment by xincjin-NOAA** [comment]
As for updating the global ctests to include  assimilating  GMI. do we need to make ctest after this update. Because the ctest will fail

**Comment by RussTreadon-NOAA** [comment]
Reminder:  Due date for merger of this PR into `develop` is 3/6/2024.  This is two weeks from today (2/21/2024).  @xincjin-NOAA, please reach out to your peer reviewers.  We need at least two peer reviews with approval.  If this PR is not merged into `develop` by 3/6/2024, the PR will be closed and returned to @xincjin-NOAA.

**Comment by RussTreadon-NOAA** [comment]
**ctest note**
 
The ObsProc team may be able to generate GMI bufr dump files for portions of February 2024. If this is possible, we should update ctests `global_4denvar` and `global_enkf` to a near real-time case. Currently these tests use data from 2022110900.

**Comment by RussTreadon-NOAA** [comment]
@xincjin-NOAA , please bring `xincjin-NOAA:gmi_new` up to date with the current head of NOAA-EMC/GSI `develop`.  Your forked branch [`xincjin-NOAA:gmi_new`](https://github.com/xincjin-NOAA/GSI/tree/gmi_new) is 10 commits behind the current head of [`develop`](https://github.com/NOAA-EMC/GSI/tree/develop).

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA , updated xincjin-NOAA:gmi_new, thanks for remind this.

**Review by ADCollard — APPROVED** [review]
Looks good

**Comment by RussTreadon-NOAA** [comment]
**Update global ctest case to 2024022300**

C96C48L127 background files to run `global_4denvar` and `global_enkf` for 2024022300 have been created.  The 2024022300 observations include a non-zero GMI bufr dump file.

The following files were modified in a working copy of `xincjin-NOAA:gmi_new` on Hera
- `regression/global_4denvar.sh` - paths and file prefixes updated to operational naming convention
- `regression/global_enkf.sh` - paths and file prefixes updated to operational naming convention
- `regression/regression_namelists.sh - set `dsfcalc` to 0 for atms_n21
-  `regression/regression_var.sh` - change `global_adate` date from 2022110900 to 2024022300

The `global_4denvar` and `global_enkf` ctests were run with `gmi_new` at a0acbee1 as _updat_ and `develop` at  7c4a5718 as the _contrl_.  Both tests _Passed_ on Hera.
```
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr692/build
    Start 1: global_4denvar
1/1 Test #1: global_4denvar ...................   Passed  3120.35 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 3121.55 sec
```
```
Hera(hfe01):/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr692/build$ ctest -R global_enkf
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr692/build
    Start 7: global_enkf
1/1 Test #7: global_enkf ......................   Passed  1984.88 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 1984.89 sec
```
Files needed to run the 20240223 global case have been rsync'd to the `CASES` directory Orion (Hercules) and WCOSS2 (Cactus and Dogwood).

@xincjin-NOAA , I recommend that you update 
- `global_4denvar.sh`
- `global_enkf.sh`
- `regression_namelists.sh`
- `regression_var.sh`

in your `gmi_new` branch with my modified files in Hera `/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr692/regression`

Tagging @ADCollard since you asked about updating the GSI global ctests.  We may want to tweak global ctest namelist variables in `regressions_namelists.sh`.   Notes:  I did not change `regression_nameslists_db.sh` since I almost never use this file.

**Comment by RussTreadon-NOAA** [comment]
@xincjin-NOAA , thank you for updating `gmi_new` to the current head of `develop`.  I went ahead and updated the CASE for the `global_4denvar` and `global_enkf` ctests at [`8e97f39`](https://github.com/NOAA-EMC/GSI/pull/692/commits/8e97f39a585c6859daa430cb4796c6e054af0386).

With this commit global ctests include gmi data.  Failure to update ctests as new functionality is added may result in future PRs breaking existing functionality.

**Comment by RussTreadon-NOAA** [comment]
Reminder:  This PR will be closed **without merging** and returned to @xincjin-NOAA on 3/6/2024 unless two peer reviews with approval are completed.  Currently PR has one peer review and approval.

@xincjin-NOAA , please follow up with your peer reviewers.

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA  Thanks for updating the ctests.  I have run two ctests global cases on Hera and the tests are passed:  

 [Xin.C.Jin@hfe02 build]$ ctest -R global
Test project /scratch1/NCEPDEV/da/Xin.C.Jin/git/GSI/build
    Start 1: [=[global_4denvar]=]
1/2 Test #1: [=[global_4denvar]=] .............   Passed  3605.66 sec
    Start 7: [=[global_enkf]=]
2/2 Test #7: [=[global_enkf]=] ................   Passed  2219.81 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) = 5825.49 sec

Do I need to run ctests on other machines?

**Comment by RussTreadon-NOAA** [comment]
Thank you @xincjin-NOAA for offering to run ctests on other machines.  Since I'm the one committed changes necessitating ctests, it's my responsibility to run tests.   

New ctests have been run on Cactus, Hera, Orion and Hercules using `gsi_new` at [`8e97f39`](https://github.com/xincjin-NOAA/GSI/commit/8e97f39a585c6859daa430cb4796c6e054af0386).   Results are posted below

**Cactus**
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr692/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............***Failed  483.35 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  486.15 sec
3/7 Test #7: global_enkf ......................   Passed  971.75 sec
4/7 Test #2: rtma .............................   Passed  1209.25 sec
5/7 Test #6: hafs_3denvar_hybens ..............***Failed  1339.49 sec
6/7 Test #5: hafs_4denvar_glbens ..............***Failed  1453.30 sec
7/7 Test #1: global_4denvar ...................***Failed  2102.75 sec

43% tests passed, 4 tests failed out of 7

Total Test time (real) = 2102.83 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          4 - netcdf_fv3_regional (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
```
**_These failures are troublesome._**  Each failure is due to non-reproducible results between _updat_ (`gmi_new`) and _contrl_ (`develop`).  

- `global_4denvar` shows _updat_ and _contrl_ differences in the last few digits of the printed initial step size.
- `netcdf_fv3_regional` shows _updat_ and _contrl_ differences in the last several digits of the printed initial gradient norm.
- `hafs_4devar_glbens` shows _updat_ and _contrl_ differences in the last several digits of the printed initial gradient norm.
- `hafs_3denvar_hybens` shows _updat_ and _contrl_ differences in the last few digits of the printed initial step size.

@xincjin-NOAA , would you please run ctests on Cactus to see if you obtain results similar to my results.  We encountered a similar situation with PR #616.  ctests passed on RDHPCS machines but failed on WCOSS2.  We never found a good reason for the lack of reproducibility on WCOSS2.  In the end we found that refactoring the code restored WCOSS2 reproducibility.
 
**Hera**
```
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr692/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  1206.07 sec
2/7 Test #3: rrfs_3denvar_glbens ..............***Failed  1272.23 sec
3/7 Test #7: global_enkf ......................   Passed  1981.63 sec
4/7 Test #2: rtma .............................   Passed  1990.60 sec
5/7 Test #5: hafs_4denvar_glbens ..............   Passed  2133.72 sec
6/7 Test #6: hafs_3denvar_hybens ..............   Passed  2135.40 sec
7/7 Test #1: global_4denvar ...................   Passed  2933.61 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) = 2933.63 sec

The following tests FAILED:
          3 - rrfs_3denvar_glbens (Failed)
```

`rrfs_3denvar_glbens` failed due a time threshold check
```
The runtime for rrfs_3denvar_glbens_hiproc_updat is 90.829125 seconds.  This has exceeded maximum allowable threshold time of 89.256364 seconds,
resulting in Failure of timethresh2 the regression test.```
```
This is not a fatal failure

**Orion**
```
Test project /work/noaa/da/rtreadon/git/gsi/pr692/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  483.12 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  608.86 sec
3/7 Test #7: global_enkf ......................***Failed  856.72 sec
4/7 Test #2: rtma .............................   Passed  1029.08 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1335.26 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1698.78 sec
7/7 Test #1: global_4denvar ...................   Passed  1924.02 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) = 1924.03 sec

The following tests FAILED:
          7 - global_enkf (Failed)
```
`global_enkf` failed due to a time threshold check.
```
The runtime for global_enkf_hiproc_updat is 148.144994 seconds.  This has exceeded maximum allowable threshold time of 146.820976 seconds,
resulting in Failure timethresh2 of the regression test.
```
This is not a fatal fail.

**Hercules**
ctests were launched on Hercules but remain pending in the queue due to high system usage.  Several tests are expected to fail on Hercules as documented in PR #698.

**Comment by RussTreadon-NOAA** [comment]
**Hercules ctest**
The Hercules ctests finally ran with the following results
```
Test project /work2/noaa/da/rtreadon/git/gsi/pr692/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #3: rrfs_3denvar_glbens ..............***Failed  7095.09 sec
2/7 Test #5: hafs_4denvar_glbens ..............   Passed  7277.44 sec
3/7 Test #6: hafs_3denvar_hybens ..............   Passed  7279.38 sec
4/7 Test #4: netcdf_fv3_regional ..............   Passed  7572.28 sec
5/7 Test #7: global_enkf ......................   Passed  7633.66 sec
6/7 Test #2: rtma .............................   Passed  8467.70 sec
7/7 Test #1: global_4denvar ...................   Passed  8582.74 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) = 8583.07 sec

The following tests FAILED:
          3 - rrfs_3denvar_glbens (Failed)
```
The `rrfs_3denvar_glbens` failure is due to 
```
The results between the two runs (rrfs_3denvar_glbens_loproc_updat and rrfs_3denvar_glbens_loproc_contrl) are not reproducible
Thus, the case has Failed siganl of the regression tests.

The fv3_sfcdata are reproducible
The results between the two runs (rrfs_3denvar_glbens_loproc_updat and rrfs_3denvar_glbens_hiproc_updat) are not reproducible
Thus, the case has Failed siganl of the regression tests.
```
Comparison of the _loproc_ and _hiproc_ output show differences for `fv3_dynvars` and `fv3_tracer`.  This is consistent with PR #698.

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA Started ctests on  WCOSS2 (Cactus)

**Comment by xincjin-NOAA** [comment]
ctests results: 

Test project /lfs/h2/emc/da/noscrub/xin.c.jin/gmi_new/build
    Start 1: global_4denvar
1/7 Test #1: global_4denvar ...................***Failed  3423.86 sec
    Start 2: rtma
2/7 Test #2: rtma .............................   Passed  3431.05 sec
    Start 3: rrfs_3denvar_glbens
3/7 Test #3: rrfs_3denvar_glbens ..............   Passed  727.32 sec
    Start 4: netcdf_fv3_regional
4/7 Test #4: netcdf_fv3_regional ..............***Failed  604.42 sec
    Start 5: hafs_4denvar_glbens
5/7 Test #5: hafs_4denvar_glbens ..............***Failed  1333.32 sec
    Start 6: hafs_3denvar_hybens
6/7 Test #6: hafs_3denvar_hybens ..............***Failed  1213.91 sec
    Start 7: global_enkf
7/7 Test #7: global_enkf ......................   Passed  1032.82 sec

43% tests passed, 4 tests failed out of 7

Total Test time (real) = 11766.80 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          4 - netcdf_fv3_regional (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest

**Comment by RussTreadon-NOAA** [comment]
@xincjin-NOAA , which of the WCOSS2 failures are due to non-reproducible results?

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA They are all failed due to non-reproducible results, details as below:

- global_4denvar:

The results (penalty) between the two runs are nonreproducible, thus the regression test has Failed on cost for global_4denvar_loproc_updat and global_4denvar_loproc_contrl analyses.

-  netcdf_fv3_regional: 

The results (penalty) between the two runs are nonreproducible, thus the regression test has Failed on cost for netcdf_fv3_regional_loproc_updat and netcdf_fv3_regional_loproc_contrl analyses.


- hafs_4denvar_glbens:

The results (penalty) between the two runs are nonreproducible, thus the regression test has Failed on cost for hafs_3denvar_hybens_loproc_updat and hafs_3denvar_hybens_loproc_contrl analyses.

The results between the two runs (hafs_3denvar_hybens_loproc_updat and hafs_3denvar_hybens_loproc_contrl) are not reproducible Thus, the case has Failed siganl of the regression tests.

- hafs_3denvar_hybens

The results (penalty) between the two runs are nonreproducible, thus the regression test has Failed on cost for hafs_3denvar_hybens_loproc_updat and hafs_3denvar_hybens_loproc_contrl analyses.

The results between the two runs (hafs_3denvar_hybens_loproc_updat and hafs_3denvar_hybens_loproc_contrl) are not reproducible
Thus, the case has Failed siganl of the regression tests.

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA Any suggestions on where to look at?  not quite understand why the results are  so different among different machines.

**Comment by RussTreadon-NOAA** [comment]
@xincjin-NOAA , this PR can not be merged into `develop` until the WCOSS2 reproducibility is resolved.  Reach out to your peer reviewers, share with them the issue, and brainstorm.  

This PR alters 6 source code files.  I modified 4 files related to global ctests.  We see reproducibility problems with 3 regional tests and 1 global test.  

Some thoughts:
- Work backward and systematically undo changes in `gmi_new` to find the hash at `gmi_new` and `develop` yield identical results on WCOSS2.  
- The approach above assumes that at some point `gmi_new` and `develop` reproduced each other.  If you already know the `gmi_new` hash for which this is true, you can start from this hash.  First confirm reproducible `gmi_new` and `develop` results for this hash.   Incrementally move forward through `gmi_new` hashes to find the commit or commits at which results diverge.    
- Bofh of the above approaches assume there's an issue in `gmi_new`.    `gmi_new` has been periodically updated with snapshots of `develop`.  Did one of the `develop` updates introduce non-reproducibility?

All the above fall into the category of old fashioned trial and error debugging.  This could be a tedious investigation.

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA I have git rollback to previous commit and found the place where failures are found on  WCOSS2.

- the hashes that yield identical results on WCOSS2 are:

commit 4c005dda5c484bcb4abbfeb399d4ad067bb24eb9 (HEAD -> gmi_new_4c005dda)
Author: xincjin-NOAA <Xin.C.Jin@noaa.gov>
Date:   Wed Jan 24 22:22:11 2024 +0000

     is statement

commit 7f37de38be7b7ad37db96eff570071e91006e1f6 (HEAD -> develop_7f37de38)
Author: Andrew Collard <40322596+ADCollard@users.noreply.github.com>
Date:   Thu Jan 18 11:27:08 2024 -0500

    Remove HIRS from GSI regression tests (#672)


- the hashes  which results diverge on WCOSS2 are: 

the gmi_new is the same as above.

commit 12f8d3ef5c9292e48655365b269833574a81b61d (HEAD -> develop_12f8d3ef)
Author: AmandaBack-NOAA <55004295+AmandaBack-NOAA@users.noreply.github.com>
Date:   Wed Jan 24 12:09:07 2024 -0700

    add clipping treatment for negative values of non-negative tracers (#682)

the test results are:

 hafs_4denvar_glbens

The results between the two runs (hafs_4denvar_glbens_loproc_updat and hafs_4denvar_glbens_loproc_contrl) are not reproducible
Thus, the case has Failed siganl of the regression tests.

 hafs_3denvar_hybens

The results between the two runs (hafs_3denvar_hybens_loproc_updat and hafs_3denvar_hybens_loproc_contrl) are not reproducible
Thus, the case has Failed siganl of the regression tests.

 rrfs_3denvar_glbens

The results between the two runs (rrfs_3denvar_glbens_loproc_updat and rrfs_3denvar_glbens_loproc_contrl) are not reproducible
Thus, the case has Failed siganl of the regression tests.

netcdf_fv3_regional

The memory for netcdf_fv3_regional_loproc_updat is 206252 KBs.  This has exceeded maximum allowable memory of 194092 KBs,
resulting in Failure memthresh of the regression test.

Test project /lfs/h2/emc/da/noscrub/xin.c.jin/gmi_new/build
    Start 2: rtma
    Start 1: global_4denvar
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
    Start 4: netcdf_fv3_regional
    Start 3: rrfs_3denvar_glbens
1/7 Test #4: netcdf_fv3_regional ..............***Failed  724.96 sec
2/7 Test #3: rrfs_3denvar_glbens ..............***Failed  786.64 sec
3/7 Test #7: global_enkf ......................   Passed  856.37 sec
4/7 Test #6: hafs_3denvar_hybens ..............***Failed  1640.21 sec
5/7 Test #5: hafs_4denvar_glbens ..............***Failed  1640.86 sec
6/7 Test #2: rtma .............................   Passed  2111.99 sec
7/7 Test #1: global_4denvar ...................   Passed  2224.41 sec

43% tests passed, 4 tests failed out of 7

Total Test time (real) = 2224.59 sec

The following tests FAILED:
          3 - rrfs_3denvar_glbens (Failed)
          4 - netcdf_fv3_regional (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest

Do you have any ideas on the possible causes?

**Comment by RussTreadon-NOAA** [comment]
Good detective work, @xincjin-NOAA .  You have commits at which results are identical and commits at which they differ. Start from the hashes for which _updat_ and _contrl_ results are identical and move forward one hash at a time to find the hashes at which analysis results first diverge.  Once you have these hashes drill down into changes to understand how / why they alter analysis results.   Emily, Andrew, or others familiar with GSI radiance processing may have useful insights once you identify the specific set of changes responsible for divergent analyses.

**Comment by xincjin-NOAA** [comment]
testing

**Comment by RussTreadon-NOAA** [comment]
FYI @xincjin-NOAA , @ADCollard , @emilyhcliu , and @azadeh-gh :  Today, 3/6/2024 is the 6-week due date for this PR. As per [GSI Code Management Policy](https://github.com/NOAA-EMC/GSI/wiki/GSI---Code-Management-Policy), pull requests not merged into `develop` by the due date will be closed and returned to the developer.  This PR will be closed once the 3/6/2024 due date is passed.  The originating issue, #689, will remain open.

Further work is needed on this PR since the changes alter analysis results on WCOSS2 even though GMI data is not assimilated.  We need to understand as best we can why this happens and, to the extent possible, develop a reproducible implementation of the desired changes.

**Review by azadeh-gh — APPROVED** [review]

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA @ADCollard @emilyhcliu @azadeh-gh After many ctests on WCOSS2 I finally found the commit where the ctest is first failed.  The commit is titled as "a quick fix for Issue:A indexing out of bounds issue shown in the global_4denvar regrâ¦ (#681)".

I have made a few ctests on commits in which I revert the above commit.  They are all passed. I listed one example bellow which is for the final commit.

 Test project /lfs/h2/emc/da/noscrub/xin.c.jin/gmi_new/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  483.91 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  487.23 sec
3/7 Test #7: global_enkf ......................   Passed  851.28 sec
4/7 Test #2: rtma .............................   Passed  1151.46 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1215.01 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1280.68 sec
7/7 Test #1: global_4denvar ...................   Passed  1923.45 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1923.48 sec

**Comment by xincjin-NOAA** [comment]
We have two options now:

one is merge this PR after revert the commit that caused the ctest failures on WCCOS2 and open a new issue to deal with the failure cased by that commit. because 
- the codes removed in that commit had been there for many years and the GSI is under a steady status with them.
- there are many changes in this PR, If we don't merge it into develop. we will have too many things to investigate if ctest failed after many commits merged into develop in the future.
- there will be a clear boundary in this case so that we can focus on solving a specific potential issue.

 The other option is to reject this merge and do more investigation on the failure. This will make things more complicated as stated above.

**Review by emilyhcliu — APPROVED** [review]

**Review by ADCollard — APPROVED** [review]
Re-approving now regression test issues are fixed

**Comment by RussTreadon-NOAA** [comment]
Thank you @xincjin-NOAA for finding a needle in the haystack.  

One question and one comment

1. The change committed at [224cb8d](https://github.com/NOAA-EMC/GSI/pull/692/commits/224cb8d74f185fdd542bc72d1414d4d0ff937763) also needs to be made in `develop` in order for the all ctests to pass, right?   I found this to be true when testing `develop` and `gmi_new`.   Just asking to get confirmation.

2. [224cb8d](https://github.com/NOAA-EMC/GSI/pull/692/commits/224cb8d74f185fdd542bc72d1414d4d0ff937763) adds `abi2km` code back to `setuprad.f90`  This code should not be executed in any ctest because `abi2km` is hardwired to `.false.` in `setuprad.f90`. Yet, we see differences in both regional and global ctests results.  Code that is not executed should not alter analysis results.  Adding the `abi2km` code back to `setuprad.f90` may _cover_ other issue(s).  

    These issues could be 
     - problems in the GSI code (out of bounds array, undefined values, ...)
     - compiler issues.  This is suggested by the fact that `gmi_new` without [224cb8d](https://github.com/NOAA-EMC/GSI/pull/692/commits/224cb8d74f185fdd542bc72d1414d4d0ff937763) reproduces `develop` on NOAA RDHPCS machines.  The GSI build on NOAA RDHPCS machines use later versions of the intel compiler.
     - threading issues

The threading possibility was examined as follows
- leave GSI `develop` as is with no changes
- make the following changes in a working copy of `gmi_new`
  - remove `abi2km` changes added by  [224cb8d](https://github.com/NOAA-EMC/GSI/pull/692/commits/224cb8d74f185fdd542bc72d1414d4d0ff937763)
  - comment out four `!$omp parallel do` directives in `setuprad.f90`
  - build `gsi.x`

All seven ctests passed when using the unaltered `develop` as _contrl_ and the modified `gmi_new` as _updat_.   Some of the `abi2km` code added back in by [224cb8d](https://github.com/NOAA-EMC/GSI/pull/692/commits/224cb8d74f185fdd542bc72d1414d4d0ff937763) was inserted into `!$omp parallel` sections.  Are the gmi changes in this PR behaving strangely in threaded sections of `setuprad.f90`? 

As an aside, since @TingLei-NOAA authored PR #681 we should get his input if we decide to retain [224cb8d](https://github.com/NOAA-EMC/GSI/pull/692/commits/224cb8d74f185fdd542bc72d1414d4d0ff937763),  This commit undoes #681.

**Comment by TingLei-NOAA** [comment]
@RussTreadon-NOAA   Thanks for looping me in.  I re viewed that PR and still think removing those ab2km codes should not cause any differences in GSI runs since abi2km is hardwired .false.    @xincjin-NOAA  I still suspect some other memory related issues in the codes.  Do you have a run with GSI built with debug mode?  What will happen if both control gsi and update gsi are built with debug mode (while, we know hafs regression tests would fail for debug mode , which is fixed by @XuLu-NOAA 's fix in the PR pending merging to EMC GSI develop branch).

**Comment by TingLei-NOAA** [comment]
A following up on the omp directive at Line 1102 of setuprad.f90 ( the current EMC develop branch) on top of that abi2km part,  the declaration of private variables are suspicious to me.  For example,  should pred also be declared as private?     An easy test is just to comment out this omp and see if there are any impacts.

**Comment by xincjin-NOAA** [comment]
I  have run the ctests on Cactus (develop -- fca6bea4e5 -- )compiled with Debug mode) and would like to document following information. I don't call them errors because I am not that familiar with the system yet:


WCOSS2(cactus):

- hafs_4denvar_glbens_loproc_updat

nid002814.cactus.wcoss2.ncep.noaa.gov: rank 14 died from signal 6 and dumped core
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source             
gsi.x              0000000007B4769B  Unknown               Unknown  Unknown
libpthread-2.31.s  000014DA68C158C0  Unknown               Unknown  Unknown
gsi.x              0000000000CE8F65  gridmod_mp_tll2xy        2144  gridmod.F90
gsi.x              0000000004EDA711  read_bufrtovs_            633  read_bufrtovs.f90
gsi.x              0000000001BFF9E8  read_obsmod_mp_re        1706  read_obs.F90
gsi.x              00000000017293E9  observermod_mp_se         329  observer.F90
gsi.x              0000000003EC35F2  glbsoi_                   222  glbsoi.f90
gsi.x              0000000001066648  gsisub_                   200  gsisub.F90
gsi.x              000000000042CA8F  gsimod_mp_gsimain        2414  gsimod.F90
gsi.x              0000000000413D7B  MAIN__                    631  gsimain.f90
gsi.x              0000000000413BD2  Unknown               Unknown  Unknown
libc-2.31.so       000014DA688ED24D  __libc_start_main     Unknown  Unknown
gsi.x              0000000000413AEA  Unknown               Unknown  Unknown


- hafs_3denvar_hybens_loproc_updat

forrtl: severe (408): fort: (2): Subscript #1 of the array GRID_LON has value 362 which is greater than the upper bound of 361

Image              PC                Routine            Line        Source             
gsi.x              0000000007B3EBDF  Unknown               Unknown  Unknown
gsi.x              000000000139636E  mod_fv3_lola_mp_d         983  mod_fv3_lola.f90
gsi.x              0000000000EA704A  gsi_rfv3io_mod_mp         669  gsi_rfv3io_mod.f90
gsi.x              0000000004206154  hybrid_ensemble_i        4131  hybrid_ensemble_isotropic.F90
gsi.x              0000000003EC3192  glbsoi_                   191  glbsoi.f90
gsi.x              0000000001066648  gsisub_                   200  gsisub.F90
gsi.x              000000000042CA8F  gsimod_mp_gsimain        2414  gsimod.F90
gsi.x              0000000000413D7B  MAIN__                    631  gsimain.f90
gsi.x              0000000000413BD2  Unknown               Unknown  Unknown
libc-2.31.so       000014E4F5F4924D  __libc_start_main     Unknown  Unknown
gsi.x              0000000000413AEA  Unknown               Unknown  Unknown

- global_enkf_loproc_updat

forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source             
enkf.x             0000000004BC361B  Unknown               Unknown  Unknown
libpthread-2.31.s  00001517DFA4B8C0  Unknown               Unknown  Unknown
enkf.x             000000000053CF59  letkf_mp_letkf_up         279  letkf.f90
libiomp5.so        00001517E0E943F3  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00001517E0E18937  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00001517E0DDC533  __kmpc_fork_call      Unknown  Unknown
enkf.x             00000000005369C5  letkf_mp_letkf_up         279  letkf.f90
enkf.x             000000000041494E  MAIN__                    210  enkf_main.f90
enkf.x             00000000004132D2  Unknown               Unknown  Unknown
libc-2.31.so       00001517DF72324D  __libc_start_main     Unknown  Unknown
enkf.x             00000000004131EA  Unknown               Unknown  Unknown
nid001999.cactus.wcoss2.ncep.noaa.gov: rank 11 died from signal 6 and dumped core
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source             
enkf.x             0000000004BC361B  Unknown               Unknown  Unknown
libpthread-2.31.s  000014701B18F8C0  Unknown               Unknown  Unknown
enkf.x             0000000000552D52  letkf_mp_letkf_up         492  letkf.f90
libiomp5.so        000014701C5D83F3  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        000014701C55C937  __kmp_fork_call       Unknown  Unknown
libiomp5.so        000014701C520533  __kmpc_fork_call      Unknown  Unknown

enkf.x             00000000005369C5  letkf_mp_letkf_up         279  letkf.f90
enkf.x             000000000041494E  MAIN__                    210  enkf_main.f90
enkf.x             00000000004132D2  Unknown               Unknown  Unknown
libc-2.31.so       000014701AE6724D  __libc_start_main     Unknown  Unknown
enkf.x             00000000004131EA  Unknown               Unknown  Unknown
forrtl: error (78): process killed (SIGTERM)



- global_4denvar_loproc_updat


forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
gsi.x              0000000007B4769B  Unknown               Unknown  Unknown
libpthread-2.31.s  000014D2BF5518C0  Unknown               Unknown  Unknown
gsi.x              0000000006C5B57C  gpsbend_setup_mp_        1106  setupbend.f90
gsi.x              000000000677A43C  gsi_gpsbendoper_m         103  gsi_gpsbendOper.F90
gsi.x              00000000025FFF99  setuprhsall_              491  setuprhsall.f90
gsi.x              0000000003EC4926  glbsoi_                   323  glbsoi.f90
gsi.x              0000000001066648  gsisub_                   200  gsisub.F90
gsi.x              000000000042CA8F  gsimod_mp_gsimain        2414  gsimod.F90
gsi.x              0000000000413D7B  MAIN__                    631  gsimain.f90
gsi.x              0000000000413BD2  Unknown               Unknown  Unknown
libc-2.31.so       000014D2BF22924D  __libc_start_main     Unknown  Unknown
gsi.x              0000000000413AEA  Unknown               Unknown  Unknown

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 ctests**

Install `develop` at fca6bea4 and `gmi_new` at [`224cb8d`](https://github.com/xincjin-NOAA/GSI/commit/224cb8d74f185fdd542bc72d1414d4d0ff937763) on Cactus.  Run ctests with the following results
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr692/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 7: global_enkf
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
1/7 Test #4: netcdf_fv3_regional ..............***Failed  604.39 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  846.24 sec
3/7 Test #7: global_enkf ......................   Passed  1331.27 sec
4/7 Test #6: hafs_3denvar_hybens ..............***Failed  1452.91 sec
5/7 Test #2: rtma .............................   Passed  1515.38 sec
6/7 Test #5: hafs_4denvar_glbens ..............***Failed  1579.41 sec
7/7 Test #1: global_4denvar ...................***Failed  2043.12 sec

43% tests passed, 4 tests failed out of 7

Total Test time (real) = 2043.47 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          4 - netcdf_fv3_regional (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest
```

The failed cases are all due to non-reproducible analysis results between _loproc_updat_ and _loproc_contrl_.

@xincjin-NOAA , do you obtain similar ctest results on Cactus?

This PR can not move forward without resolving WCOSS2 non-reproducibility.  Since the problem only shows up on WCOSS2 it may take a while to sort out what is going on.  I will rebuild `gsi.x` in debug mode to see if this provides any clues.

My recommendation is to close this PR.  A new PR can be opened when the WCOSS2 reproducibility problem is resolved.
 
Tagging @ADCollard , @emilyhcliu , and @CatherineThomas-NOAA for awareness since assimilation of GMI may be one of the planned upgrades in GFS v17.

**Comment by RussTreadon-NOAA** [comment]
Two oversights related to GSI fix
1. `GSI_BINARY_SOURCE_DIR` in all machine specific `modulefiles` points at `fix/20230911`.  The most recent EIB staged GSI binary files are in `fix/20240208`.   We should update `GSI_BINARY_SOURCE_DIR` to `fix/20240208`.
2. `fix/gsi_binary_files.cmake` does **not** include `Rcov_crisn21` even though this file is in `fix/20230911` and `fix/20240208`.   More importantly, files `global_anavinfo.l127.txt` and `global_anavinfo_soilanal.l127.txt` reference `Rcov_crisn21`.  We should add `Rcov_crisn21` to `fix/gsi_binary_files.cmake`.

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA  I got all ctests passed on WCOSS2 after revert the commit on both develop and gmi_new. Therefore, those USELESS codes play a key role on the behavior of GSI code base, even without GMI related changes.

**Comment by RussTreadon-NOAA** [comment]
@xincjin-NOAA , I looked at `lfs/h2/emc/da/noscrub/xin.c.jin/develop`.  Your `develop` adds `abi2km` code to `setuprad.f90`.  I looked in `/lfs/h2/emc/da/noscrub/xin.c.jin/gmi_new`.  `setuprad.f90` in this working copy differs from what is committed to branch `gmi_new`.  Am I looking in the correct directories?

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA Yes, the directory is correct. I am changing this file and doing some other test now

**Comment by RussTreadon-NOAA** [comment]
OK, so my result using `develop` at fca6bea4 and `gmi_new` at 224cb8d7 could possibly be valid.  If true, this is at odds with previous comments in this PR.

**Comment by xincjin-NOAA** [comment]
After refactor the code and apply back the reverted commit, all ctests on WCOSS2 were passed (install develop with fca6bea4 and gmi_new with 8078902a)

Test project /lfs/h2/emc/da/noscrub/xin.c.jin/gmi_new/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  604.42 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  849.27 sec
3/7 Test #7: global_enkf ......................   Passed  1153.56 sec
4/7 Test #2: rtma .............................   Passed  1272.22 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1334.87 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1519.23 sec
7/7 Test #1: global_4denvar ...................   Passed  2104.26 sec

will test on other platform then.

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA @ADCollard @emilyhcliu @TingLei-NOAA After new update of this PR, all ctests are passed on WCOSS2, Hera, and Orion. There is one failure on Hercules: 

Hercules:

Test project /work/noaa/da/xinjin/git/gmi_new/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  486.81 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  606.71 sec
3/7 Test #7: global_enkf ......................   Passed  733.78 sec
4/7 Test #2: rtma .............................   Passed  967.92 sec
5/7 Test #6: hafs_3denvar_hybens ..............***Failed  1095.98 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1335.46 sec
7/7 Test #1: global_4denvar ...................   Passed  1682.78 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) = 1682.79 sec

The following tests FAILED:
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest
Output from these tests are in: /work/noaa/da/xinjin/git/gmi_new/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.

The results between the two runs (hafs_3denvar_hybens_loproc_updat and hafs_3denvar_hybens_hiproc_updat) are not reproducible

I am not sure if this is a known issue.

**Comment by RussTreadon-NOAA** [comment]
Thank you @xincjin-NOAA for refactoring the code.  It's great to see reproducible results once again on WCOSS2.  @TingLei-NOAA is working on the Hercules `hafs_3denvar_hybens` failure.

**Comment by RussTreadon-NOAA** [comment]
@xincjin-NOAA , please request a re-review from the peer reviewers for this PR.  Your refactored changes need to be reviewed.

File: src/gsi/clw_mod.f90 [hunk 1]
```diff
@@ -2019,7 +2019,7 @@ subroutine gmi_37pol_diff(tb37v,tb37h,tsim37v,tsim37h,clw,ierrret)
 
      clw = one - (tb37v-tb37h)/(tsim37v-tsim37h)
      clw=max(zero,clw)
-     if(tb37h > tb37v)  then
+     if ((tb37h > tb37v) .or. (tb37h > 500 )) then
```
Comment (RussTreadon-NOAA) [inline src/gsi/clw_mod.f90]: Need to specify numeric precision on constant `500`.  Use `500_r_kind`.

File: src/gsi/deter_sfc_mod.f90 [hunk 2]
```diff
@@ -1331,7 +1331,7 @@ subroutine deter_sfc_amsre_low(dlat_earth,dlon_earth,isflg,sfcpct)
    end subroutine deter_sfc_amsre_low
 
 
-subroutine deter_sfc_gmi(dlat_earth,dlon_earth,isflg,sfcpct)
```
Comment (RussTreadon-NOAA) [inline src/gsi/deter_sfc_mod.f90:1334]: `sfcpct` has been removed as a subroutine argument.  However, comments on lines 1357 to 1361 still document `sfcpct`.  Remove the comments since they are no longer relevant.

File: src/gsi/deter_sfc_mod.f90 [hunk 3]
```diff
@@ -1407,90 +1403,55 @@ subroutine deter_sfc_gmi(dlat_earth,dlon_earth,isflg,sfcpct)
...
-     else if(sfcpct(2) > 0.99_r_kind)then
-        isflg = 2
-     else if(sfcpct(3) > 0.99_r_kind)then
-        isflg = 3
-     else
-        isflg = 4
-     end if
 
+     grid_dist=rearth * (rlats_sfc(klatp1) - rlats_sfc(klat1))
+     n_grid=int(40 * 1000 / grid_dist) + 1
```
Comment (RussTreadon-NOAA) [inline src/gsi/deter_sfc_mod.f90]: I think fortran order operations will execute `(40 * 1000 / grid_dist)` as `40 * 1000` first with the product then divided by `grid_dist`.  If true, simplify this to `(40000 / grid_dist)`

File: src/gsi/setuprad.f90 [hunk 4]
```diff
@@ -1298,11 +1298,11 @@ subroutine setuprad(obsLL,odiagLL,lunin,mype,aivals,stats,nchanl,nreal,nobs,&
               do i=1,nchanl
                 pred(6,i) = zero
                 pred(7,i) = zero
-                clw_avg = half*(clw_obs+clw_guess_retrieval)
+                clw_avg = half*(clw_obs+clw_guess_retrieval) * zero
```
Comment (RussTreadon-NOAA) [inline src/gsi/setuprad.f90]: Since we multiply `half*(clw_obs+clw_guess_retrieval)` by `zero`, why don't we just set `clw_avg = zero`?

**Review by RussTreadon-NOAA — COMMENTED** [review]
Only minor comments, otherwise the code changes look good from a coding perspective. 

What about the science perspective?  If gmi is assimilated, does the refactored code yield the intended results? The `global_4denvar` test only processes gmi in monitor mode.  It does not yet assimilate gmi data.

File: src/gsi/clw_mod.f90 (hunk 1 above)
Comment (xincjin-NOAA) [reply src/gsi/clw_mod.f90]: Changed.

File: src/gsi/deter_sfc_mod.f90 (hunk 2 above)
Comment (xincjin-NOAA) [reply src/gsi/deter_sfc_mod.f90:1334]: Removed. Thanks.

File: src/gsi/deter_sfc_mod.f90 (hunk 3 above)
Comment (xincjin-NOAA) [reply src/gsi/deter_sfc_mod.f90]: Simplified. Thanks.

File: src/gsi/setuprad.f90 (hunk 4 above)
Comment (xincjin-NOAA) [reply src/gsi/setuprad.f90]: The cloud's impacts are still need to be investigated further, though we set it to zero now.  Therefore we want to keep the formula (or the piece of codes) as it is in the file.

**Comment by xincjin-NOAA** [comment]
@RussTreadon-NOAA, From the science perspective, If gmi is assimilated, the refactored code will yield the intended results.

File: src/gsi/setuprad.f90 (hunk 4 above)
Comment (RussTreadon-NOAA) [reply src/gsi/setuprad.f90]: Thanks for the explanation. My preference is to not see extra computations which eventually wind up being zero.  Code is version controlled so we can always see code from previous versions commits.  Could also rewrite as
```
! Need to investigate clw_avg = half*(clw_obs+clw_guess_retrieval) * zero
clw_avg = zero
```

**Review by RussTreadon-NOAA — COMMENTED** [review]
Thank you @xincjin-NOAA for removing unnecessary computations.

File: src/gsi/setuprad.f90 (hunk 4 above)
Comment (xincjin-NOAA) [reply src/gsi/setuprad.f90]: Changed, thanks.

**Comment by RussTreadon-NOAA** [comment]
@xincjin-NOAA , have you requested re-reviews from Emily, Andrew, and Azadeh?   If not, please do so.  This PR has passed it's due date.

**Review by azadeh-gh — APPROVED** [review]

**Comment by emilyhcliu** [comment]
The code changes due to GMI look good, and they do (should) not change regression results. Approved!
Later, when we have GMI in operation, we should turn on GMI in the regression tests.

**Review by emilyhcliu — APPROVED** [review]

**Review by RussTreadon-NOAA — APPROVED** [review]
Given two peer review approvals and documentation of ctests results on WCOSS2, Hera, Orion, and Hercules, approve and pass this PR onto GSI Handling Review team for merger into `develop`.

**Comment by xincjin-NOAA** [comment]
@all Thanks everyone for making this PR close!
