### PR TITLE
Optimize GSI

### LINKED ISSUE #525: Optimizing GSI (and a few minor bug fixes)
It is important for the GSI to run as fast as possible for operational use.  Changes have been made to the GSI to optimize the code.  Also a few minor bugs found along the way were fixed.  The changes were intended to simplify the code when possible as well as make it run faster.  Many of the changes were simple (such as changing from a series of if-endif blocks to if-else-endif blocks)  Others required significant changes (the combination of the control2state and control2state_ad).  In addition, the code was changed to not produce a observation output file if no observations of that type were used in the analysis.  This change should reduce the number of files on the computers (often a limiting factor) and eliminating the associated memory and run-time costs.

The testing of the run times is difficult on Hera because there is significant run-to-run variability dependent on the machine load.  The wall times below are derived from running the GSI on the same case repeatedly.  This is a global hybrid run similar to what is run in operations.  Much of the improvement in wall times is from the improved reading of the ensembles, so wall time improvements can be expected to be smaller for other applications of the GSI.  

Wall times:

Control
1860. sec
1778. sec 
1832. sec
1843. sec
1821. sec
1855. sec

New
1768. sec
1756. sec
1719. sec
1721. sec
1723. sec
1696. sec

The first three runs for each group were run during the day on Friday and the second three on Sunday.  There is considerable run-to-run variability, but all new code version runs are faster than the fastest control.  

Regression tests were run with only round-off level differences found.

Routines changed:

adjtest.f90 - call c2sset.

adjtest_obs.f90 - call c2sset.

aeroinfo.f90 - remove output to iout_aero.

atms_spatial_average.f90 - add i to private variables in threading.

bicg.f90    - move check out of iteration and put in higher level routine

bicglanczos.f90 - move check out of iteration and put in higher level routine

bkerror.f90  - remove unnecessary data movement

calctends_no_tl.f90 - combine loops together

compact_diffs.f90 - include i=1 and i=nlat within loops

constants.f90 - make maximum name length (max_varname_length) equal to 64

control2state.f90 - combine with control2state_ad.f90 and create initialization routine that checks for variables once rather than every time they are called.  make into module, add c2sset (which initializes variables for control2state and control2state_ad).

control2state_ad.f90 - deleted - see control2state.f90

control_vectors.f90 - improved threading of loops.

convthin.f90 - simplification of if-else-endif structure

convthin_time.f90 - simplification of if-else-endif structure (similar to convthin)

correlated_obsmod.f90 - change from series of if statements to if-else-endif and other reordering of code to optimize.

cplr_gfs_ensmod.f90 - many changes to attempt to speed up reading of ensembles, reduce data movement and reduce memory usage.

cplr_gfs_nstmod.f90 - refactoring code to remove unnecessary data movement and to simplify code.

deter_sfc_mod.f90 - eliminate unnecessary initialization of variable.

genqsat.f90 - remove redundant calculation.  Does result in minor roundoff differences.

get_gefs_ensperts_dualres.f90 - eliminate unnecessary calculations, improve threading, ensure q >= 0 for conversion between virtual and sensible temperature, and change calculation of mean values to use higher precision.  These changes do result in some round-off change differences.

getsiga.f90 - add call to c2sset to initialize for new control2state and control2state_ad. 

gridmod.f90 - add variable minmype which has first processor with smallest domain size

gsi_files.cmake - removes inclusion of control2state_ad routine

gsimod.f90 - print only once if reaches print statement rather than npe times.

hybrid_ensemble_isotropic.f90 - move lsqrt check to higher level so it does not check over and over. remove unused variable.

intall.f90 - use *present routines so that does not have to check for existence of * variable every iteration

intgps.f90 - increase threading

intjcmod.f90 - changes to reduce number of calculations and unnecessary initialization of variables.

intjo.f90 move setrad to pcgsoi.f90

intrad.f90 - remove unnecessary calculations from setrad and add print to show which variables are used in radiance calculations. in intrad make changes to allow threading over channels.  improve threading.

intsst.f90 - simplify calculations to reduce variables and number of calculations.

intt.f90 - simplify calculations to reduce variables and number of calculations.

jgrad.f90 - add call to c2sset.

lightinfo.f90 - modify print so that it does not try to write to file if no lightning data exists.

m_radNode.f90 - add iccerr variable - this variable is used to allow threading of correlated errors for satellite data.

ncepgfs_io.f90 - remove unused variable in call to write_fv3_increment.

obs_sensitivity.f90 - add call to c2sset to initialize control2state routines.

obsmod.F90 - clean up.

pcgsoi.f90 - add calls to c2sset and setrad.  Also check for lsqrt added.  Modify writes to minmype rather than 0.  Small changes to improve efficiency.

pvqc.f90 - change 2 to 2_dp and 1 to 1_dp to eliminate repeated conversion from integer to real.

qdiag.f90 - write to minmype rather than processor 0.

qcmod.f90 - improve efficiency and readability.  Use if-else-endif rather than multiple if-endifs.

radinfo.f90 - remove unnecessary print statement.

read_atms.f90 - remove unnecessary print statements.

read_bufrtovs.f90 - remove unnecessary data1b8x array and associated data movement.

read_gps.f90 - fix bug in print out. use if-else-endiff rather than 2 if-endifs.

read_iasi.f90 - thread conversion from radiance to brightness temperature.  Fix bug (no impact) at end of code. Simplify some code.

read_obs.F90 - simplify if statements and clean code.

read_satwnd.f90 - fix indentation.

setupcldtot.F90 - change indentation of comment

setuppcp.f90 - remove unused variable.

setuprad.f90 - Use if-elseif-endif instead of multiple if-endifs. Initialize iccerr used for threading with correlated errors, simplify code, add threading.

state_vectors.f90 - define *present variables, improve threading of dot-products.

statsconv.f90 - output files only created when observations read.  

statslight.f90 - output file only created when observations read. remove unused variables.

statsrad.f90 - slightly modify output format.

stpcalc.f90 - use *present variables. add parallel directives. change dimensions of some arrays (2d to 1d), simplify some calculations. output to minmype.

stpgps.f90 - add threading.

stpjo.f90 - remove call to setrad (moved to pcgsoi.f90)

stprad.f90 - thread over channels.  Use iccerr to allow threading with correlated error.  Other simplifications.

stpsst.f90 - simplifications.  Removal of bug which made intsst and stpsst inconsistent.  If sst obs used, can make small changes to results.

stpt.f90 - simplification of calculations.

vqc_int.f90 - fix indentations.

vqc_stp.f90 - fix indentations.

write_incr.f90 - remove unused variable in parameter list for  write_fv3_inc_. add call to c2sset.

xhat_vordivmod.f90 - simplify code by moving zeroing of array.

Code is in the repository under jderber-NOAA/GSI/optimize

### PR DESCRIPTION
**Pull request by jderber-NOAA**
This update is intended to optimize the GSI to make it run faster in operations.

The changes are primarily optimization changes (reducing data movement, adding threading, reducing memory) but include a few minor changes when small bugs were present.  For example there was an inconsistency between the intsst and stpsst routines for certain observations.  The difference was very small when sst observations were used.

In addition, there was a change to eliminate the observation output files when no observations of that type were used.  Thus, if no lightning data was used, the observation output file was not created.  This results in the production of fewer files in each run and eliminates the cost of creating the files.

A more complete description of the changes can be found in issue #525.

The code is found in jderber-NOAA/GSI/optimize.

In all of the regression tests and in my testing the differences with between the control and the test were on the order of round-off differences or slightly larger.  All testing was done on Hera since this is the only machine I have access to.

Fixes #525

- [ ] Bug fix (non-breaking change which fixes an issue)?
- [ ] New feature (non-breaking change which adds functionality)?

### CODE REVIEW

**Comment by jderber-NOAA** [comment]
I assume that the issue with the branch conflicts is the lines:

<<<<<<< optimize
  call gsi_bundledestroy(en_bar,istatus)
=======
  if(nsclgrp > 1 .and. global_spectral_filter_sd) then
     do m=1,ntlevs_ens
        do n=1,n_ens
           en_pertstmp1%values=en_perts(n,1,m)%valuesr4
           do ig=1,nsclgrp
              call apply_scaledepwgts(grd_ens,sp_ens,en_pertstmp1,spc_multwgt(:,ig),en_pertstmp2)
              en_perts(n,ig,m)%valuesr4=en_pertstmp2%values
           enddo
        enddo
     enddo
  endif

>>>>>>> develop

I do not see any conflict between the two sets of code.  The first code just deallocates the en_bar bundle.  The second set of code, I have never seen before.  It appears to modify the ensemble perturbations.

Did this code come from a recent update to the GSI?

**Comment by RussTreadon-NOAA** [comment]
@jderber-NOAA , the source code [change](https://github.com/NOAA-EMC/GSI/commit/8857995a2467a2f0c608a10d08ca24fdf8589fcc#diff-33511a4c66335962c2e6f21288a157dea914af8ecbcf07a6e52f38f82505e376) you cite in `src/gsi/get_gefs_ensperts_dualres.f90` was introduced with the merge of PR #504 at [`8857995`](https://github.com/NOAA-EMC/GSI/commit/8857995a2467a2f0c608a10d08ca24fdf8589fcc).

PR #504 was opened by @Wangy1111.  @TingLei-NOAA  and @hu5970 reviewed the changes.

**Comment by jderber-NOAA** [comment]
I see that these changes were added recently.  Should I update my branch to include these changes now? or wait until review completed.  I hate to review code that is changing as I am reviewing it.

**Comment by RussTreadon-NOAA** [comment]
Reviewers can review `jderber-NOAA:optimize` in it's current state.   Approvals can even be given.   

Before we merge `jderber-NOAA:optimize` into `develop`, we need to bring the branch update to date with the current head of `develop`.   When this happens reviews will be marked as _stale_.  Reviewers will need to re-review.   Hopefully the second review won't take as much time as the first review.

**Comment by TingLei-NOAA** [comment]
@jderber-NOAA , the block you pointed out in the current gsi develop branch was added for the recently introduced SDL function (create different ensemble groups on different wave bands  from different filtering ).  To resolve the conflict, seemingly just need to remove " call gsi_bundledestroy(en_bar,istatus)" on your side, ( I assume this line will be seen in a later line in the develop branch.

**Comment by jderber-NOAA** [comment]
As I said before, I don't think either code needs to be removed.  There is no real conflict.

Cathy and Emily, would you like me to update to the head of the trunk?  If you have not started your review, you might want this so it does not need to be reviewed again.  If you have started your review, I can wait.  I don't think there will be much overlap.

John

**Comment by TingLei-NOAA** [comment]
> 
@jderber-NOAA 
Further tracing found that the "call gsi_bundledestroy(en_bar,istatus)" doesn't exist in get_gefs_ensperts_dualres.f90. So seems it is not only "no real conflict"  but this line  is needed to be added into the develop branch.  That is good through  this PR to do this.  Sorry I hadn't found it earlier.

**Comment by jderber-NOAA** [comment]
Updated to head of the trunk.

**Comment by jderber-NOAA** [comment]
Unfortunately when rerunning the regression tests, I noted that I had not run them properly the first time.  Because of this a few minor bugs were noted.  To fix the bugs, several small changes were made.

1. The calls to c2sset (initializing things for control2state and control2state_ad) were moved from before each call to the control2state routines, to inside the two routines.  The calls to c2sset were put on flag so that they are only called once.  This new way of doing it ensures that the routine is called before the rest of the control2state routines, is more efficient and simpler.  This change resulted in the most changes, but all changes are very simple.

2. The setting of diag_print was moved inside the loop in pcgsoi to get the proper behavior.

3. The adjtest routine was modified to get similar results as before.  However, there are issues with this routine noted in issue #548 

4. The control2model and control2model_ad routines were modified to make the loops much more efficient.

Regression tests were rerun.

The differences between the runs appears to be small.  They are a bit larger for the hwrf runs at the end of the runs, but these are close at the beginning of the iterations.  I believe the larger differences in the hwrf runs at the end are due to instability in the minimization from the variational quality control version used in these experiments.

I believe the changes are ready for review.

**Comment by RussTreadon-NOAA** [comment]
@jderber-NOAA , we need to update `jderber-NOAA:optimize` to the current head of `NOAA-EMC:develop`.   Changes in your `src/gsi/cplr_gfs_ensmod.f90` conflict with the current head of develop.    

I don't think @emilyhcliu or @CatherineThomas-NOAA have begun their reviews.  It's good to update your branch to develop prior their reviews.   Changes made to your branch after their reviews means they need to re-review.

**Comment by jderber-NOAA** [comment]
Will do.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: RussTreadon-NOAA ***@***.***> Date: 3/22/23  9:04 AM  (GMT-05:00) To: NOAA-EMC/GSI ***@***.***> Cc: jderber-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NOAA-EMC/GSI] Optimize GSI (PR #527) 
@jderber-NOAA , we need to update jderber-NOAA:optimize to the current head of NOAA-EMC:develop.   Changes in your src/gsi/cplr_gfs_ensmod.f90 conflict with the current head of develop.
I don't think @emilyhcliu or @CatherineThomas-NOAA have begun their reviews.  It's good to update your branch to develop prior their reviews.   Changes made to your branch after their reviews means they need to re-review.

**Comment by RussTreadon-NOAA** [comment]
@jderber-NOAA  , @emilyhcliu , @CatherineThomas-NOAA : Any updates on the status of this PR?

**Comment by CatherineThomas-NOAA** [comment]
@RussTreadon-NOAA I still need some time to finish going through the code but I can update about some testing I've done.

I ran single analysis tests on Hera and found a 20 second reduction in runtime.  Of course the runtime on Hera is rather variable, but it was still shorter with this PR.  

The initial cost functions were identical (18 digits) and the initial gradient was identical out to 11 digits.  In the next iteration, the cost function was identical to 11 digits and the gradient was identical to 9 digits.  It's expected that these very small differences accumulate over the iterations.  Final increments max diffs:
u ~0.02m/s
v ~0.04m/s
T ~0.01K
q ~1e-05kg/kg

A vast majority of the differences were much smaller (~1e-06).

**Comment by RussTreadon-NOAA** [comment]
Thank you @CatherineThomas-NOAA for sharing your findings thus far.

**Comment by RussTreadon-NOAA** [comment]
As per the 4/10/2023 email sent to the GSI subversion email list, PRs must be merged within 6 weeks of creation.  PRs not merged within the 6 week window will be returned to the originating developer (see [GSI Wiki](https://github.com/NOAA-EMC/GSI/wiki/GSI---Code-Management-Policy)).   

This PR was opened before this announcement  .   The due date for this PR is set to **5/22/2023**, six weeks after 4/10/2023.

File: src/gsi/aeroinfo.f90 [hunk 1]
```diff
@@ -285,11 +284,6 @@ subroutine aeroinfo_read
 !      All mpi tasks open and read aerosol information file.
 !      Task mype_aero writes information to aerosol runtime file
   
-       if (mype==mype_aero) then
-          open(iout_aero)
```
Comment (CatherineThomas-NOAA) [inline src/gsi/aeroinfo.f90]: @jderber-NOAA  
I know aerosol DA is moving to JEDI, but it's not operational yet.  Has the removal of this file been cleared with the aerosol developers?

File: src/gsi/constants.f90 [hunk 2]
```diff
@@ -90,7 +90,7 @@ module constants
 
 ! Declare derived constants
   integer(i_kind):: huge_i_kind
-  integer(i_kind), parameter :: max_varname_length=64
+  integer(i_kind), parameter :: max_varname_length=20
```
Comment (CatherineThomas-NOAA) [inline src/gsi/constants.f90:93]: @jderber-NOAA The description in issue #525 says:

> constants.f90 - make maximum name length (max_varname_length) equal to 64

Just want to confirm that you planned to reduce it from 64 to 20.

File: src/gsi/control2state.f90 [hunk 3]
```diff
@@ -1,3 +1,58 @@
...
+use gridmod, only: nems_nmmb_regional
+use gridmod, only: regional, twodvar_regional            
+
+implicit none
+
+private
+public :: do_getprs,do_normal_rh_to_q,do_tv_to_tsen,do_getuv,do_cw_to_hydro
+public :: do_cw_to_hydro_hwrf,nclouds,ngases
+public :: control2state
+public :: control2state_ad
```
Comment (CatherineThomas-NOAA) [inline src/gsi/control2state.f90:45]: @jderber-NOAA 
I don't see the removal of the control2state_ad.f90 file, though I'm fairly sure you intended to remove it, correct?

File: src/gsi/control2state.f90 [hunk 4]
```diff
@@ -1,3 +1,58 @@
...
+module control2state_mod
+
+! !USES:
+
+
+! !DESCRIPTION: module control2state routines and variables
+
+use kinds, only: r_kind,i_kind
+use control_vectors, only: control_vector,c2sset_flg
+use gsi_4dvar, only: nsubwin, l4dvar, lsqrtb,ladtest_obs
```
Comment (CatherineThomas-NOAA) [inline src/gsi/control2state.f90:23]: @jderber-NOAA 
Many of these variables are re-declared at the start of the subroutines.

File: src/gsi/aeroinfo.f90 (hunk 1 above)
Comment (jderber-NOAA) [reply src/gsi/aeroinfo.f90]: Good question.  At this point, nothing is written to this file but some stuff specifying values for the input file aeroinfo (e.g., file name, satellite number, channel, errors, etc, similar to the stuff in the radinfo file).  No information on the fits to the obs, etc. is written to the file.  I was trying to reduce the number of files created by the GSI by removing those files which have no useful information in them.  

I could modify the code so that it only creates this file when there are input values for the aerosol data in the aeroinfo file.  What do you think?  That is probably better and I will do that.

File: src/gsi/constants.f90 (hunk 2 above)
Comment (jderber-NOAA) [reply src/gsi/constants.f90:93]: Yes.  I wanted to do this.  The reason why is that when printed these variables create a lot of blank space and result in less readable output.

File: src/gsi/control2state.f90 (hunk 3 above)
Comment (jderber-NOAA) [reply src/gsi/control2state.f90:45]: Yes.  Removed.  Thanks.

File: src/gsi/control2state.f90 (hunk 4 above)
Comment (jderber-NOAA) [reply src/gsi/control2state.f90:23]: Good catch.  I think I started to check and then got distracted.   Updated.

File: src/gsi/aeroinfo.f90 (hunk 1 above)
Comment (jderber-NOAA) [reply src/gsi/aeroinfo.f90]: Going to put this file back in when there is a aeroinfo file.

Comment (jderber-NOAA) [reply src/gsi/aeroinfo.f90]: But still removes file when no aeroinfo file exists.  Write message to main output file when aeroinfo does not exist.

**Comment by jderber-NOAA** [comment]
Changes based on Cathy's comments completed and pushed to branch. Successful compile.  Will run tests soon.

**Comment by emilyhcliu** [comment]
I checked out the branch and the develop to run single-cycle tests (`exp` and `ctl)` for 2 days (8 cycles). 
The results changed compared to the base since there were bug fixes.
The average run time from exp is shorter (~18 seconds)
I checked the GSI statists for O-F/O-A for radiance data.  They were not very different from the `ctl`. 
For conventional data, I checked the global averaged O-F profiles from the 8 cycles together.  The differences are very small between the `exp` and `ctl`.  

The code changes look good to me.

**Comment by jderber-NOAA** [comment]
Regression tests run.  Look OK.  Also ensured that my trunk is up to date with GSI trunk.  No differences.

I think it is ready to go.

**Review by CatherineThomas-NOAA — APPROVED** [review]
Thanks for your patience @jderber-NOAA.  There's a lot of work in this PR and the timing results are good.  I'll be sure to use that extra time up immediately in GFSv17 :)

Code looks good to me.  Approved.

**Comment by RussTreadon-NOAA** [comment]
**Reminder:**  This review will be closed and returned to the developer if not merged **before 5/23/2023**

**Comment by jderber-NOAA** [comment]
Russ, I thought both Cathy and Emily approved this change.  What do I/we need to do to get it in? John Sent from Mail for Windows From: RussTreadon-NOAASent: Monday, May 8, 2023 9:32 AMTo: NOAA-EMC/GSICc: jderber-NOAA; MentionSubject: Re: [NOAA-EMC/GSI] Optimize GSI (PR #527) Reminder: This review will be closed and returned to the developer if not merged before 5/23/2023—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by RussTreadon-NOAA** [comment]
I do not see an approval from Emily.

**Review by emilyhcliu — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
Given approvals from @CatherineThomas-NOAA and @emilyhcliu this PR can now be processed for merger into `develop`.

**Comment by RussTreadon-NOAA** [comment]
Merge request submitted to GSI Handling Review Team.

**Comment by RussTreadon-NOAA** [comment]
Majority of handling review team concur with merger.  Merge will be completed shortly.

File: src/gsi/constants.f90 (hunk 2 above)
Comment (TingLei-daprediction) [inline src/gsi/constants.f90:93]: @jderber-NOAA In my regional run, I just the max_varname-length=20 is not enough to contain names like" fv3SAR01_ens_mem001-fv3_dynvars" . 
^
character(len=max_varname_length) :: filenamein2
V
 Would you consider changing this to a bigger value like original one? Or I should use a different size (another parameter) for my use? 
````
Thanks.

Comment (jderber-NOAA) [reply src/gsi/constants.f90:93]: Yes.  It is in the list of changes I am currently working on.

**Comment by jderber-NOAA** [comment]
Note this change has already been put into trunk.  A modification will require another PR. Sent from Mail for Windows From: TingLei-NOAASent: Friday, May 12, 2023 7:14 PMTo: NOAA-EMC/GSICc: jderber-NOAA; MentionSubject: Re: [NOAA-EMC/GSI] Optimize GSI (PR ***@***.*** commented on this pull request.In src/gsi/constants.f90:> @@ -90,7 +90,7 @@ module constants  ! Declare derived constants   integer(i_kind):: huge_i_kind-  integer(i_kind), parameter :: max_varname_length=64+  integer(i_kind), parameter :: ***@***.*** In my regional run, I just the max_varname-length=20 is not enough to contain names like" fv3SAR01_ens_mem001-fv3_dynvars" .^character(len=max_varname_length) :: filenamein2VWould you consider changing this to a bigger value like original one? Or I should use a different size (another parameter) for my use?Thanks.   —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

File: src/gsi/constants.f90 (hunk 2 above)
Comment (TingLei-daprediction) [reply src/gsi/constants.f90:93]: John, Thanks a lot!
