### PR TITLE
GitHub Issue NOAA-EMC/GSI#215. Update Jet support, port monitors to Jet and S4.

### LINKED ISSUE #215: Update support for the GSI on Jet
As part of the global workflow support on Jet (NOAA-EMC/global-workflow#357), the Jet build/run scripts and regression tests for the GSI should be updated.  The GSI has successfully built and run using the global workflow based on [commit 9c1fc15d](https://github.com/NOAA-EMC/GSI/commit/9c1fc15d42573b398037319bbf8d5143ad126fb6) on [port_2_jet](https://github.com/DavidHuber-NOAA/gsi/tree/port_2_jet).  Additional work will be required to incorporate these changes into the master and to support regression tests on Jet, including adding the test case dataset.

@MichaelLueken-NOAA I will add the changes to incorporate the build/run script changes.  I'm also willing to make the code changes to enable regression testing on Jet.  Do you know if the regression test data is already hosted on Jet?

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
This updates GSI's Jet support for the build scripts and module file.  It adds new support for regression testing on Jet (kjet only) and the minimization, radiance, and ozone monitors on Jet and S4, including added support for file locations as placed by the global workflow, following @EdwardSafford-NOAA (#223).

Lastly, a modification to the calcanl_gfs.py script was made to spread tasks over two nodes when working on xjet to provide enough memory for the job.

Fixes #215 
References noaa-emc/global-workflow#357

I would appreciate a review from @EdwardSafford-NOAA on the monitors.

### CODE REVIEW

File: util/Radiance_Monitor/image_gen/ush/mk_bcor_plots.sh [hunk 1]
```diff
@@ -181,9 +181,14 @@ elif [[ $MY_MACHINE = "wcoss_c" ]]; then
    $SUB -q $JOB_QUEUE -P $PROJECT -M 80 -o ${logfile} -W ${wall_tm} \
         -J ${jobname} -cwd ${PWD} ./$cmdfile
 
-elif [[ $MY_MACHINE = "hera" ]]; then
+elif [[ $MY_MACHINE = "hera" || $MY_MACHINE = "s4" ]]; then
    $SUB --account ${ACCOUNT} -n $ctr  -o ${logfile} -D . -J ${jobname} \
         --time=2:00:00 --wrap "srun -l --multi-prog ${cmdfile}"
+
+elif [[ $MY_MACHINE = "jer" ]]; then
```
Comment (EdwardSafford-NOAA) [inline util/Radiance_Monitor/image_gen/ush/mk_bcor_plots.sh:188]: Looks like a typo here.

**Review by EdwardSafford-NOAA — COMMENTED** [review]
Looks good to me.  One minor item noted.

File: util/Radiance_Monitor/image_gen/ush/mk_bcor_plots.sh (hunk 1 above)
Comment (DavidHuber-NOAA) [reply util/Radiance_Monitor/image_gen/ush/mk_bcor_plots.sh]: Yep, thanks for the catch.
