### PR TITLE
Iasi debug fix

### LINKED ISSUE #789: IASI combine_radobs failure in debug mode
When the GSI is compiled in  debug mode, it fails in the read_iasi routine at the call to combine_radobs.  A printout of the variables shows several brightness temperatures are "NAN"s.  Also, the nread variable going into combine_radobs is the total observations (profiles * channels) and should be just profiles.

### PR DESCRIPTION
**Pull request by wx20jjung**
**Description**

When the GSI is built in debug mode, the code failed when the read_iasi routine called combine_radobs.  In tracking down this problem several other minor problems were discovered and fixed.  

Resolves #789 

The first group of commits are some write format changes I missed in the output of the runtime directory.  I also found where the maximum channel number was set to 3000.  I changed this array to be dynamic and allocated for each instrument.

The second group of commits resolves 2 errors I found while trying to fix the debug issue.  The first was an error some of the IASI temperature values were "NAN"s.  I traced this back to some of the cscale values (a scaling factor for IASI radiances, in the BUFR file), were missing values.  The missing cscale values are associated with the shortwave side of the water vapor region and the shortwave channels.  None of these channels are currently used.  These were only found in the direct broadcast data.  I did not find an instance where the operational data had missing values.  The second error was an integer overflow problem with the variable nread being passed into combine radobs.  Nread is used in most satellite instrument reads but the main failure was from read_iasing (to be added later).  Nread is a counter and is ultimately number_of_profiles * number_of_channels.   This number exceeded the memory for an integer  and was ultimately a negative number.  In combine_radobs, nread is compared to the total number of elements of the thinning box or itxmax to the number of elements of the task thinning box.  In this case, the task thinning box was negative.  I added logic to the various read_* routines to pass the number of profiles kept on each task.  This makes nread and itxmax consistent.  This change caused the total counts to be different for some instruments.  Here is an example from the gsistat file for IASI.
previous:
o-g 01 rad   metop-b      iasi  331026696      6148957       690460   0.24889E+06  0.24889E+06  0.36047      0.36047
new:
o-g 01 rad   metop-b      iasi    44632896      6148957       690460   0.24889E+06  0.24889E+06  0.36047    0.36047
The total counts after thinning and total counts used are identical along with the other statistics.

The actual failure of read_iasi in debug mode came down to putting an   if() cycle   in a different place.  Read_iasi is now consistent with read_cris.

**Type of change**

- [X ] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

The main testing and cycling experiments were conducted on S4 at C192 resolution.  After a single cycle spinup I setup a "control" and "experiment" and run both independently changing the GSIEXEC variable to point to the gsi master branch (control) and the IASI_debug_fix branch (experiment).  The control and experiment were run through 4 cycle.  Static tests were also conducted on Jet.  

The ctests on Hera all passed:
[Jim.Jung@hfe10 build]$ ctest -j 6
Test project /scratch1/NCEPDEV/jcsda/Jim.Jung/save/ctests/update/build
    Start 1: global_4denvar
    Start 6: global_enkf
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  492.94 sec
2/6 Test #2: rtma .............................   Passed  970.72 sec
3/6 Test #5: hafs_3denvar_hybens ..............   Passed  1043.42 sec
4/6 Test #6: global_enkf ......................   Passed  1118.55 sec
5/6 Test #4: hafs_4denvar_glbens ..............   Passed  1159.69 sec
6/6 Test #1: global_4denvar ...................   Passed  1909.17 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1909.21 sec

The rrfs ctest timed out on jet, all others passed.
Test project /lfs5/HFIP/hfv3gfs/Jim.Jung/noscrub/ctests/update/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #6: global_enkf ......................   Passed  1779.50 sec
2/6 Test #2: rtma .............................   Passed  1938.22 sec
3/6 Test #1: global_4denvar ...................   Passed  1991.97 sec
4/6 Test #5: hafs_3denvar_hybens ..............   Passed  2000.38 sec
5/6 Test #4: hafs_4denvar_glbens ..............   Passed  2310.42 sec

The rrfs test also failed on hercules
[jjung@hercules-login-3 build]$ ctest
Test project /work/noaa/nesdis-rdo1/jjung/noscrub/ctests/update/build
    Start 1: global_4denvar
1/6 Test #1: global_4denvar ...................   Passed  1741.09 sec
    Start 2: rtma
2/6 Test #2: rtma .............................   Passed  965.23 sec
    Start 3: rrfs_3denvar_rdasens
3/6 Test #3: rrfs_3denvar_rdasens .............***Failed  484.58 sec
    Start 4: hafs_4denvar_glbens
4/6 Test #4: hafs_4denvar_glbens ..............   Passed  1161.19 sec
    Start 5: hafs_3denvar_hybens
5/6 Test #5: hafs_3denvar_hybens ..............   Passed  1094.42 sec
    Start 6: global_enkf
6/6 Test #6: global_enkf ......................   Passed  847.14 sec

83% tests passed, 1 tests failed out of 6

Total Test time (real) = 6293.65 sec

The following tests FAILED:
          3 - rrfs_3denvar_rdasens (Failed)
The memory for rrfs_3denvar_rdasens_loproc_updat is 1106724 KBs.  This has exceeded maximum allowable memory of 1098631 KBs, resulting in Failure memthresh of the regression test.

**Checklist**

- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] New and existing tests pass with my changes
- [X ] Any dependent changes have been merged and published

Please add @ADCollard, @DavidHuber-NOAA and @InnocentSouopgui-NOAA  as reviewers.

### CODE REVIEW

File: src/gsi/combine_radobs.f90 [hunk 1]
```diff
@@ -74,7 +74,7 @@ subroutine combine_radobs(mype_sub,mype_root,&
 
      nread=0
      if (mype_sub==mype_root) nread = ncounts1
-     if (ncounts1 == 0)return
+     if (ncounts1 <= 0)return
```
Comment (DavidHuber-NOAA) [inline src/gsi/combine_radobs.f90:77]: I wonder if it would be worth it to change `ncounts1` to an `integer (i_llong)` to help prevent overflow?

File: src/gsi/read_iasi.f90 [hunk 2]
```diff
@@ -759,17 +759,16 @@ subroutine read_iasi(mype,val_iasi,ithin,isfcalc,rmesh,jsatid,gstime,&
...
-!             check that channel number is within reason
-                if (( allchan(2,bufr_chan) > zero .and. allchan(2,bufr_chan) < 99999._r_kind)) then  ! radiance bounds
-                  radiance = allchan(2,bufr_chan)*scalef(bufr_chan)
-                  sc_chan = sc_index(i)
-                  call crtm_planck_temperature(sensorindex_iasi,sc_chan,radiance,temperature(bufr_chan))
-                else
-                   temperature(bufr_chan) = tbmin
-                endif
-              end if
+!           check that channel number is within reason
```
Comment (DavidHuber-NOAA) [inline src/gsi/read_iasi.f90]:
```suggestion
!             check that channel number is within reason
```

**Review by DavidHuber-NOAA — APPROVED** [review]
Looks good, just a couple minor suggestions.

**Comment by wx20jjung** [comment]
@DavidHuber-NOAA 
I have been struggling with this.  I do not know what the true intent of nread is.  Was it developed for 2D (horizontal) observations or 3D data like the radiances?  I interpret the code as being for the former.  My argument is based on the allocate statement for nloc and icrit a few lines down.  Both of these variables use itxmax, which is the total counts of a 2D spatial (horizontal) grid.   To be consistent, I feel ncounts1 (and nread) should also be from a 2D spatial grid and not multiplied by the number of channels.

An alternative would be to add another argument to combine_radobs specifically for ncounts and ncounts1, which would all be long integers from and to the various read routines.

**Comment by DavidHuber-NOAA** [comment]
@wx20jjung I agree with you on the intent; that it was developed for 2D observations and so it is unlikely to every overflow with your changes.  That said, I think I like the alternative approach you proposed just to be safe.

**Comment by wx20jjung** [comment]
As per a conversation with @DavidHuber-NOAA,  I've separated the total channel counts read (nread) from the thinning box (itxmax).  Now, if the channel counts read becomes larger than the integer size, it will only affect the write statements.  I've re-run the ctests on hera.  

Test project /scratch1/NCEPDEV/jcsda/Jim.Jung/scrub/ctests/update/build
    Start 2: rtma
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 1: global_4denvar
    Start 6: global_enkf
    Start 3: rrfs_3denvar_rdasens
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  496.10 sec
2/6 Test #2: rtma .............................   Passed  972.37 sec
3/6 Test #5: hafs_3denvar_hybens ..............   Passed  1106.76 sec
4/6 Test #6: global_enkf ......................   Passed  1159.74 sec
5/6 Test #4: hafs_4denvar_glbens ..............***Failed  1345.07 sec
6/6 Test #1: global_4denvar ...................   Passed  1969.79 sec

83% tests passed, 1 tests failed out of 6

Total Test time (real) = 1969.84 sec

The hafs_4denvar_glbens test failed the time limit test.  I restarted the test and it passed.

ctest --rerun-failed --output-on-failure
Test project /scratch1/NCEPDEV/jcsda/Jim.Jung/scrub/ctests/update/build
    Start 4: hafs_4denvar_glbens
1/1 Test #4: hafs_4denvar_glbens ..............   Passed  1348.48 sec
100% tests passed, 0 tests failed out of 1
Total Test time (real) = 1348.51 sec

I will run the ctests on other machines when I get feedback from the rest of the reviewers.

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 (Dogwood) ctests**

Install `wx20jjung:IASI_debug_fix` at a41a78aa0 on Dogwood.  Use `develop` at 9f44c879 as the control.  ctests results are as follows
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr790/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  729.88 sec
2/6 Test #6: global_enkf ......................   Passed  972.64 sec
3/6 Test #5: hafs_3denvar_hybens ..............   Passed  1153.84 sec
4/6 Test #4: hafs_4denvar_glbens ..............   Passed  1334.73 sec
5/6 Test #1: global_4denvar ...................   Passed  1864.83 sec
6/6 Test #2: rtma .............................   Passed  1869.75 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1869.76 sec
```

**Review by ADCollard — APPROVED** [review]
This looks like a major improvement to me.  
Thanks, Jim.

File: src/enkf/innovstats.f90 [hunk 3]
```diff
@@ -278,7 +278,7 @@ subroutine print_innovstats(obfit,obsprd)
                   sqrt(sumerr_sat(nchan))
      end if
   end do
-9805 format(a20,i4,1x,i5,5(1x,e10.3))
+9805 format(a20,i6,1x,i5,5(1x,e10.3))
```
Comment (RussTreadon-NOAA) [inline src/enkf/innovstats.f90]: `src/enkf/enkf_obs_sensitivity.f90` changed `a20` to `a22`.  Does the same change need to be made here?

File: src/gsi/combine_radobs.f90 (hunk 1 above)
Comment (RussTreadon-NOAA) [reply src/gsi/combine_radobs.f90:77]: @wx20jjung , if this conversation is resolved, please mark it as so.

File: src/enkf/innovstats.f90 (hunk 3 above)
Comment (RussTreadon-NOAA) [reply src/enkf/innovstats.f90]: As I work through this review, I see other instances of `a20`.  A check of `src/gsi/radinfo.f90` shows that `nusis` is `len=20`.   In this case, `a20` in  `src/enkf/innovstats.f90` is correct and `a22` in src/enkf/enkf_obs_sensitivity.f90` is wrong.  Does this make sense @wx20jjung?

File: src/gsi/radinfo.f90 [hunk 4]
```diff
@@ -1135,7 +1135,7 @@ subroutine radinfo_read
                 nusis(j),nuchan(j),' not found in satbias_in file - set to zero '
              endif
           end do
-140       format(i4,1x,a20,12f12.6)
+140       format(i5,1x,a20,12f12.6)
```
Comment (RussTreadon-NOAA) [inline src/gsi/radinfo.f90:1138]: Seems we use `i6` elsewhere for `nusis`  Should `i5` here be `i6`?

File: src/gsi/read_iasi.f90 (hunk 2 above)
Comment (RussTreadon-NOAA) [reply src/gsi/read_iasi.f90]: @wx20jjung , please resolve this conversation if the conversation is indeed completed.

File: src/gsi/read_seviri.f90 [hunk 5]
```diff
@@ -529,7 +529,7 @@ subroutine read_seviri(mype,val_sev,ithin,rmesh,jsatid,&
   close(lnbufr)
 
   call combine_radobs(mype_sub,mype_root,npe_sub,mpi_comm_sub,&
-     nele,itxmax,nread,ndata,data_all,score_crit,nrec)
+     nele,itxmax,nread,nread,ndata,data_all,score_crit,nrec)
```
Comment (RussTreadon-NOAA) [inline src/gsi/read_seviri.f90]: Why doesn't `read_seviri.f90` have `number_profiles` like other radiance read routines?

**Review by RussTreadon-NOAA — COMMENTED** [review]
Looks good, @wx20jjung.  Just a few minor comments.

File: src/enkf/innovstats.f90 (hunk 3 above)
Comment (wx20jjung) [reply src/enkf/innovstats.f90]: @RussTreadon-NOAA  I've changed the format statement from i6 to 1x,i5 to be consistent.  I've also changed the write in enkf_obs_sensitivity.f90 to a20,1x,i5 to be consistent.

File: src/gsi/radinfo.f90 (hunk 4 above)
Comment (wx20jjung) [reply src/gsi/radinfo.f90:1138]: @RussTreadon-NOAA I made the other reads/writes consistent with this one.  No changes were made.

File: src/gsi/read_seviri.f90 (hunk 5 above)
Comment (wx20jjung) [reply src/gsi/read_seviri.f90]: @RussTreadon-NOAA thanks for catching this!  I added the counts statement and changed the variable name to number_profiles in read_seviri.f90 is now consistent with the other satellite instrument reads.

**Comment by wx20jjung** [comment]
I've made the various changes, tested everything both in the current branch (IASI_debug_fix) and in my IASI-NG branch in a single cycle test.  Both results are as expected.  The various satellite parameters in the gsistat (counts, bias, std dev, etc) are identical with (iasi_debug_fix) and without (develop) these changes.  I found no more '****' fields in any of the output.

File: src/gsi/read_seviri.f90 [hunk 6]
```diff
@@ -528,8 +528,10 @@ subroutine read_seviri(mype,val_sev,ithin,rmesh,jsatid,&
   call closbf(lnbufr)
   close(lnbufr)
 
+  number_profiles = count(nrec(:) /= 999999,dim=1)
+
   call combine_radobs(mype_sub,mype_root,npe_sub,mpi_comm_sub,&
-     nele,itxmax,nread,ndata,data_all,score_crit,nrec)
+     nele,itxmax,nread,nread,ndata,data_all,score_crit,nrec)
```
Comment (RussTreadon-NOAA) [inline src/gsi/read_seviri.f90]: Should the second `nread` be replaced with `number_profiles`?  Other read routines have `nread,number_profiles` in the call to `combine_radobs`

**Review by RussTreadon-NOAA — COMMENTED** [review]
Thank you @wx20jjung for the updates.  Question remains for `src/gsi/read_seviri.f90`

File: src/gsi/combine_radobs.f90 [hunk 7]
```diff
@@ -50,6 +51,7 @@ subroutine combine_radobs(mype_sub,mype_root,&
   integer(i_kind)                    ,intent(in   ) :: npe_sub,itxmax
   integer(i_kind)                    ,intent(in   ) :: nele
   integer(i_kind)                    ,intent(in   ) :: mpi_comm_sub
+  integer(i_kind)                    ,intent(in   ) :: number_profiles
```
Comment (DavidHuber-NOAA) [inline src/gsi/combine_radobs.f90]: It doesn't seem that `number_profiles` is being used.  Was this intended to be used in the `allocate` statement on line 88?

File: src/gsi/read_seviri.f90 (hunk 6 above)
Comment (wx20jjung) [reply src/gsi/read_seviri.f90]: I'm not sure what happened.  These changes were were combined with the format changes.  I see the format changes and the number_profiles initialization and declaration are in the commit but not the change in combine_radobs.  I am going to wait on resubmitting this change until I resolve @DavidHuber-NOAA comments.  It is possible number_profiles is not needed.

File: src/gsi/combine_radobs.f90 (hunk 7 above)
Comment (wx20jjung) [reply src/gsi/combine_radobs.f90]: @DavidHuber-NOAA I removed the mins in the allocation statement because the code failed at line 98 ( nloc(ndata) =k ).  This suggests ndata gets larger than number_profiles.  Since number_profiles is called ndata in combine_radobs,  It seems sending in number_profiles is a moot point.  

I am going to restore the various read routines and run some cycled tests but leave the changes involving nread in place.

File: src/gsi/read_avhrr_navy.f90 [hunk 8]
```diff
@@ -255,6 +255,7 @@ subroutine read_avhrr_navy(mype,val_avhrr,ithin,rmesh,jsatid,&
   next=0
 
 ! Read BUFR Navy data
+  nrec = 999999
```
Comment (RussTreadon-NOAA) [inline src/gsi/read_avhrr_navy.f90:258]: @wx20jjung , I forget ... why is array `nrec` initialized to `999999` in this and other readers?

File: src/gsi/read_seviri.f90 [hunk 9]
```diff
@@ -103,7 +103,7 @@ subroutine read_seviri(mype,val_sev,ithin,rmesh,jsatid,&
   integer(i_kind) nchanl,ilath,ilonh,ilzah,iszah,irec,next
   integer(i_kind) nmind,lnbufr,idate,ilat,ilon,nhdr,nchn,ncld,nbrst,jj
   integer(i_kind) ireadmg,ireadsb,iret,nreal,nele,itt
-  integer(i_kind) itx,i,k,isflg,kidsat,n,iscan,idomsfc
+  integer(i_kind) itx,i,k,isflg,kidsat,n,iscan,idomsfc,number_profiles
```
Comment (RussTreadon-NOAA) [inline src/gsi/read_seviri.f90]: `number_profiles` should be removed from `src/gsi/read_seviri.f90`, right?

**Review by RussTreadon-NOAA — COMMENTED** [review]
@wx20jjung, one question and one request for change.

File: src/gsi/read_seviri.f90 (hunk 9 above)
Comment (wx20jjung) [reply src/gsi/read_seviri.f90]: @RussTreadon-NOAA Correct.  I am in the process of removing it.  I will look for others.

**Review by RussTreadon-NOAA — COMMENTED** [review]
Thanks @wx20jjung .  I installed wx20jjung:IASI_debug_fix on Cactus this afternoon with `num_profiles` removed from `read_seviri.f90` in my working copy.  All ctests passed.

File: src/gsi/read_seviri.f90 (hunk 9 above)
Comment (wx20jjung) [reply src/gsi/read_seviri.f90]: All the number_profiles should be removed.  I pushed the commit up to github.
Will close this conversation.

File: src/gsi/combine_radobs.f90 (hunk 7 above)
Comment (wx20jjung) [reply src/gsi/combine_radobs.f90]: @DavidHuber-NOAA I made the various changes with the help of Russ.  My branch is up to date.  My cycled runs on S4 are identical. I'm runn ctests on hera, jet and hercules.
Will resolve this conversation.

**Review by DavidHuber-NOAA — APPROVED** [review]
Changes look good.  Thanks @wx20jjung!

**Comment by wx20jjung** [comment]
ctests on herculese completed as expected
[jjung@hercules-login-4 build]$ ctest -j 6
Test project /work/noaa/nesdis-rdo1/jjung/noscrub/ctests/update/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  613.04 sec
2/6 Test #6: global_enkf ......................   Passed  785.35 sec
3/6 Test #2: rtma .............................   Passed  1084.97 sec
4/6 Test #5: hafs_3denvar_hybens ..............   Passed  1152.51 sec
5/6 Test #4: hafs_4denvar_glbens ..............   Passed  1278.23 sec
6/6 Test #1: global_4denvar ...................   Passed  1741.15 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1741.16 sec

Results from jet had 2 problems:
Test project /lfs5/HFIP/hfv3gfs/Jim.Jung/noscrub/ctests/update/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #6: global_enkf ......................   Passed  1225.07 sec
2/6 Test #2: rtma .............................   Passed  1391.81 sec
3/6 Test #5: hafs_3denvar_hybens ..............   Passed  1637.28 sec
4/6 Test #4: hafs_4denvar_glbens ..............***Failed  1697.58 sec
5/6 Test #1: global_4denvar ...................   Passed  2410.05 sec

The rrfs tests timed out and did not complete.
The runtime for hafs_4denvar_glbens_loproc_updat is 335.324241 seconds.  This has exceeded maximum allowable threshold time of 328.320275 seconds,
resulting in Failure time-thresh of the regression test.

My hera tests have been in the queue for the past 12 hours.  I removed them.

File: src/gsi/read_seviri.f90 (hunk 6 above)
Comment (wx20jjung) [reply src/gsi/read_seviri.f90]: @RussTreadon-NOAA   the number_profiles variable has been removed from the various read routines and combine_radobs subroutine.  In this case, the second nread was removed.

File: src/gsi/radinfo.f90 (hunk 4 above)
Comment (RussTreadon-NOAA) [inline src/gsi/radinfo.f90:1138]: This is a nitpick comment.  Feel free to ignore if you prefer.

Line 808 changes `i4` to `i6` for `j`.  Line 1138 changes `i4` to `i5` for `j`.  Why the difference?  

The first `j` counts the entries in the satinfo file.  The second `j` ranges from 1 to `jpch_rad`.  Variable `jpch_rad` is set to the first `j`.  Given this, it seems should use the same integer field width in the format statements on lines 808 and 1138.

Comment (wx20jjung) [reply src/gsi/radinfo.f90:1138]: @RussTreadon-NOAA I have a GEOXO meeting today and tomorrow.  Not sure if I will get to this tonight.   I would also like to try removing nrec from the read_* and combine_radobs routines.  This would push everything into next week.  Is this acceptable?

Comment (RussTreadon-NOAA) [reply src/gsi/radinfo.f90:1138]: Whatever works for you, works for me @wx20jjung.  Take the time you need to get this PR into the state you want.

Comment (wx20jjung) [reply src/gsi/radinfo.f90:1138]: I made the write statements in radinfo.f90 consistent.  I found 2 instances of initializing nrec in read_gmi.f90.  I removed the first one.

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 (Cactus) ctests**
Install `wx20jjung:IASI_debug_fix` at 74947da50 on Dogwood.  Run ctests with following results:
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr790/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  734.97 sec
2/6 Test #6: global_enkf ......................   Passed  864.32 sec
3/6 Test #2: rtma .............................   Passed  971.09 sec
4/6 Test #5: hafs_3denvar_hybens ..............   Passed  1215.19 sec
5/6 Test #4: hafs_4denvar_glbens ..............   Passed  1334.75 sec
6/6 Test #1: global_4denvar ...................   Passed  1683.76 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1683.77 sec
```

**Review by RussTreadon-NOAA — APPROVED** [review]
Thank you @wx20jjung for working through my comments.  Looks good.

Approve.
