### PR TITLE
Fix bugs found in genstats_gps and read_gps mentioned in Issue#876

### LINKED ISSUE #876: Bug fixes for genstats_gps in regional model
Errors are found in regional HAFS model when assimilating the gnssro observations.
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libpthread-2.31.s  0000147AEE066910  Unknown               Unknown  Unknown
hafs_gsi.x         000000000052FA6D  m_gpsstats_mp_gen         398  genstats_gps.f90
hafs_gsi.x         0000000000B9131A  setuprhsall_              532  setuprhsall.f90
hafs_gsi.x         000000000116916A  glbsoi_                   320  glbsoi.f90
hafs_gsi.x         0000000000681107  gsisub_                   200  gsisub.F90
hafs_gsi.x         00000000004150DD  gsimod_mp_gsimain        2451  gsimod.F90
hafs_gsi.x         0000000000415017  MAIN__                    633  gsimain.f90
hafs_gsi.x         0000000000414FBD  Unknown               Unknown  Unknown
[libc-2.31.so](http://libc-2.31.so/)       0000147AEC9EA24D  __libc_start_main     Unknown  Unknown
hafs_gsi.x         0000000000414EEA  Unknown               Unknown  Unknown
srun: error: c6n0215: task 0: Exited with exit code 174
```
The issue happens in the genstats_gps.f90 when nobs_gps is smaller than nprof_gps .
A fix is provided by xuanli.li@noaa.gov by changing the size of STD4060 from nobs_gps to nprof_gps. 

Another issue is that lsw_flag was previously allocated and got an allocation error at L340 of read_gps.f90. 
A fix is to add a deallocation statement before line# 340:
```
        if (allocated(lsw_flag)) then
           deallocate(lsw_flag)
        endif
```

### PR DESCRIPTION
**Pull request by XuLu-NOAA**
**Description**
This PR relates to issue https://github.com/NOAA-EMC/GSI/issues/876, which is to bugs found during assimilating gnssro observations in the regional HAFS model.

Resolves #876 

**Type of change**
- [X] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
I've tested the fix on GaeaC6
  
**Checklist**
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

File: src/gsi/read_gps.f90 [hunk 1]
```diff
@@ -336,6 +336,11 @@ subroutine read_gps(nread,ndata,nodata,infile,lunout,obstype,twind, &
            if(mod(nmrecs,ncnumgrp(ikx))== ncgroup(ikx)-1)usage=ncmiter(ikx)
         end if
 
+! Deallocate the "array_lsw" array if it is previously allocated
+        if (allocated(array_lsw)) then
```
Comment (XuanliLi-NOAA) [inline src/gsi/read_gps.f90]: I believe the one that needs to be deallocated is _lsw_flag_, not _array_lsw_. Please double check.

File: src/gsi/read_gps.f90 [hunk 2]
```diff
@@ -336,6 +336,11 @@ subroutine read_gps(nread,ndata,nodata,infile,lunout,obstype,twind, &
            if(mod(nmrecs,ncnumgrp(ikx))== ncgroup(ikx)-1)usage=ncmiter(ikx)
         end if
 
+! Deallocate the "array_lsw" array if it is previously allocated
```
Comment (RussTreadon-NOAA) [inline src/gsi/read_gps.f90]: I agree that an array should be deallocated before it is allocated.  

What I don't see is how `array_lsw` could be allocated before it is allocated on line 345.   

`array_lsw` is deallocated on line 380.  The `cycle` on line 354 should take us to the next `i`  Thus, it seems that execution should always reach line 380 and deallocate `array_lsw`.

I'm obviously missing something.  Help me see.

File: src/gsi/read_gps.f90 (hunk 1 above)
Comment (RussTreadon-NOAA) [reply src/gsi/read_gps.f90]: Yes, lines 380-381 do not deallocate `lsw_flag`.  This is a problem.  We don't need the new code on lines 340-343.  Looks like we need to deallocate `lsw_flag` on lines 380-381

Comment (XuanliLi-NOAA) [reply src/gsi/read_gps.f90]: @RussTreadon-NOAA, We can't deallocate on lines 380-381 since _lsw_flag_ is used in Line 398.

File: src/gsi/read_gps.f90 (hunk 2 above)
Comment (RussTreadon-NOAA) [reply src/gsi/read_gps.f90]: I see a `lsw_flag` deallocate further down in `read_gps.f90`.
```
! End of k loop over levs
        end do
        deallocate(lsw_flag)
     enddo read_loop        ! subsets
  enddo                     ! messages
```
Is this deallocate misplaced?

Comment (XuanliLi-NOAA) [reply src/gsi/read_gps.f90]: I don’t think it’s misplaced. In the global case, the k loop completes, and then lsw_flag is deallocated. For the next i in the read_loop, a new array is allocated. However, for regional case, if the obs is outside the domain, the read_loop exits early at line 444—skipping the deallocate right before it.

Comment (RussTreadon-NOAA) [reply src/gsi/read_gps.f90]: OK.  The following should work.
```
              if(regional)then
                 call tll2xy(dlon_earth,dlat_earth,dlon,dlat,outside)
                 if (outside) then
                    deallocate(lsw_flag)
                    cycle read_loop
                 endif
              else
```
Alternatively, the proposed bug fix is changed to 
```
! New LSW Check 
        if (allocated(lsw_flag)) deallocate(lsw_flag)
        allocate(array_lsw(levs),array_fraclsw(levs),array_impact(levs), &
                 sorted_lsw(levs),sorted_fraclsw(levs),sorted_impact(levs), &
                 indices(levs),lsw_flag(levs),sorted_lswflag(levs))
```

Comment (XuanliLi-NOAA) [reply src/gsi/read_gps.f90]: @RussTreadon-NOAA Thanks for the suggestions!

**Comment by XuLu-NOAA** [comment]
Hi, @RussTreadon-NOAA and @XuanliLi-NOAA , Thanks for finding the typo, I've fixed the variable in aaeae57

**Review by RussTreadon-NOAA — APPROVED** [review]
Looks good.  Thank you @XuLu-NOAA 

Approve.

**Review by XuanliLi-NOAA — APPROVED** [review]
Changes look good to me.

**Comment by RussTreadon-NOAA** [comment]
**WCOSS ctests**

Install `XuLu-NOAA:feature/genstat_fix` at aaeae572 and `develop` at 0f8647aa on Cactus.  Run ctests with following results
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr877/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  731.57 sec
2/6 Test #6: global_enkf ......................   Passed  861.08 sec
3/6 Test #2: rtma .............................   Passed  1035.75 sec
4/6 Test #5: hafs_3denvar_hybens ..............   Passed  1220.64 sec
5/6 Test #4: hafs_4denvar_glbens ..............   Passed  1280.80 sec
6/6 Test #1: global_4denvar ...................   Passed  1864.02 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1864.08 sec
```

**Hera ctests**

Install `XuLu-NOAA:feature/genstat_fix` at aaeae572 and `develop` at 0f8647aa on Hera.  Run ctests with following results
```
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr877/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  739.38 sec
2/6 Test #6: global_enkf ......................   Passed  1600.22 sec
3/6 Test #1: global_4denvar ...................   Passed  2469.00 sec
4/6 Test #5: hafs_3denvar_hybens ..............   Passed  2723.19 sec
5/6 Test #4: hafs_4denvar_glbens ..............   Passed  2846.94 sec
6/6 Test #2: rtma .............................   Passed  2958.13 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 2958.17 sec
```

@XuLu-NOAA , two items
1. GSI PRs require developers to run ctests on at least WCOSS2 and Hera.  I did so for you.  If you submit future PRs, please run ctests and document results as I did above.
2. GSI PRs require two peer reviews and approvals.  @XuanliLi-NOAA's review and approval counts as one peer review.  My review and approval does not count as a peer review.  I am a member of the _GSI handling review team_.  A team member's review and approval is required for merger but it does not count as a peer review.  Who else would you like to peer review this PR?

**Comment by XuLu-NOAA** [comment]
> 1. GSI PRs require developers to run ctests on at least WCOSS2 and Hera.  I did so for you.  If you submit future PRs, please run ctests and document results as I did above.
> 2. GSI PRs require two peer reviews and approvals.  @XuanliLi-NOAA's review and approval counts as one peer review.  My review and approval does not count as a peer review.  I am a member of the _GSI handling review team_.  A team member's review and approval is required for merger but it does not count as a peer review.  Who else would you like to peer review this PR?

Thanks, @RussTreadon-NOAA ! I think @JingCheng-NOAA can help.

**Review by JingCheng-NOAA — APPROVED** [review]
These changes look good to me
