### PR TITLE
nread bug in read_radar.f90

### LINKED ISSUE #737: nread bug in read_radar.f90
1. nread is zero after reading-in radar level2 data. The value of nread should be nsuper2_kept.
2. when processing tail Doppler radar data, nread shouldn't be reset as zero.

### PR DESCRIPTION
**Pull request by ShunLiu-NOAA**
**Description**
In read_radar.f90, the value of nread should be "nsuper2_kept" and shouldn't be reset to zero after processing TDR data.

Resolves #737

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

File: src/gsi/read_radar.f90 [hunk 1]
```diff
@@ -907,6 +907,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,hgtl_fu
      end do superobs
 
      close(lnbufr)     ! A simple unformatted fortran file should not be mixed with a bufr I/O
+     nread=nsuper2_kept
```
Comment (XuLu-NOAA) [inline src/gsi/read_radar.f90:910]: nread should be the total # of obs that read in (corresponds to nsuper2_in), not the actual # of obs that is kept. Additionally, it makes more sense to use nread=nread+1 inside the superobs loop near nsuper2_in instead of outside the loop.

File: src/gsi/read_radar.f90 [hunk 2]
```diff
@@ -2190,6 +2192,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,hgtl_fu
   naftswp=0
   nfore=0
   naft=0
+  end if
```
Comment (XuLu-NOAA) [inline src/gsi/read_radar.f90]: If the infile is neither 'tldplrbufr' nor 'tldplrso', then integers like noutside would not be initialized (e.g. L2861).

**Comment by JingCheng-NOAA** [comment]
There is already an if condition `if (trim(infile) /= 'tldplrbufr' .and. trim(infile) /= 'tldplrso') then` line 368 to line 2152 to exclude those two types of data. Do we need to check it again on line 2155 `  if (trim(infile) == 'tldplrbufr' .and. trim(infile) == 'tldplrso') then`?

File: src/gsi/read_radar.f90 [hunk 3]
```diff
@@ -2151,6 +2152,7 @@ subroutine read_radar(nread,ndata,nodata,infile,lunout,obstype,twind,sis,hgtl_fu
 
   end if
 
+  if (trim(infile) == 'tldplrbufr' .and. trim(infile) == 'tldplrso') then
   erad = rearth
```
Comment (hu5970) [inline src/gsi/read_radar.f90]: this "and" should be "or"?

**Comment by ShunLiu-NOAA** [comment]
> There is already an if condition `if (trim(infile) /= 'tldplrbufr' .and. trim(infile) /= 'tldplrso') then` line 368 to line 2152 to exclude those two types of data. Do we need to check it again on line 2155 ` if (trim(infile) == 'tldplrbufr' .and. trim(infile) == 'tldplrso') then`?

Yes. line 368 is to process level2 radar data. Without line255, nread is reset to zero even there is no TDR data. This is one of reason that the value of nread is incorrect after read_radar.

File: src/gsi/read_radar.f90 (hunk 3 above)
Comment (ShunLiu-NOAA) [reply src/gsi/read_radar.f90]: "or" is better.

**Comment by JingCheng-NOAA** [comment]
> > There is already an if condition `if (trim(infile) /= 'tldplrbufr' .and. trim(infile) /= 'tldplrso') then` line 368 to line 2152 to exclude those two types of data. Do we need to check it again on line 2155 ` if (trim(infile) == 'tldplrbufr' .and. trim(infile) == 'tldplrso') then`?
> 
> Yes. line 368 is to process level2 radar data. Without line255, nread is reset to zero even there is no TDR data. This is one of reason that the value of nread is incorrect after read_radar.

Understand. Then I have no issue with this change.

**Review by XuLu-NOAA — COMMENTED** [review]
nread should be the total # of obs that read in (corresponds to nsuper2_in), not the actual # of obs that is kept. Additionally, it makes more sense to use nread=nread+1 inside the superobs loop near nsuper2_in instead of outside the loop.
Additionally, for the if statement, even if using or in the if condition. If the infile is neither 'tldplrbufr' nor 'tldplrso', then integers like noutside would not be initialized (e.g. L2861).

File: src/gsi/read_radar.f90 (hunk 1 above)
Comment (ShunLiu-NOAA) [reply src/gsi/read_radar.f90:910]: since there is a QC for level2 rw with VAD wind, nsuper2_in is not the actual number in setuprw. nread should be the sum of nsuper2_kept, nsuper2_5_kept and nsuper3_kept. However, since there is no level2.5 and level2 data, nread is set to nsuper_level2_kept.

Comment (XuLu-NOAA) [reply src/gsi/read_radar.f90:910]: > since there is a QC for level2 rw with VAD wind, nsuper2_in is not the actual number in setuprw. nread should be the sum of nsuper2_kept, nsuper2_5_kept and nsuper3_kept. However, since there is no level2.5 and level2 data, nread is set to nsuper_level2_kept.

According to the convention from tldpbufr and tldplrso, nread should be the total # after read in. Not the used data after QC. (e.g. L2252-2264)

**Review by XuLu-NOAA — APPROVED** [review]

File: src/gsi/read_radar.f90 (hunk 1 above)
Comment (ShunLiu-NOAA) [reply src/gsi/read_radar.f90:910]: Agree. If-condition is removed. Also in TDR block, "else if (trim(infile) == 'tldplrbufr' ) " is added to cover the two types of TDR files.

**Review by JingCheng-NOAA — APPROVED** [review]

**Comment by ShunLiu-NOAA** [comment]
Regression tests passed on both Hera and WCOSS2.

Hera:
Test project /scratch2/NCEPDEV/fv3-cam/noscrub/Shun.Liu/gsi/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  487.53 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  489.97 sec
3/7 Test #7: global_enkf ......................   Passed  807.93 sec
4/7 Test #2: rtma .............................   Passed  968.86 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1100.45 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1415.11 sec
7/7 Test #1: global_4denvar ...................   Passed  1866.52 sec

100% tests passed, 0 tests failed out of 7

WCOSS2
Test project /lfs/h2/emc/da/noscrub/Shun.Liu/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  484.44 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  607.88 sec
3/7 Test #2: rtma .............................   Passed  970.13 sec
4/7 Test #6: hafs_3denvar_hybens ..............   Passed  1214.62 sec
5/7 Test #5: hafs_4denvar_glbens ..............   Passed  1334.32 sec
6/7 Test #7: global_enkf ......................   Passed  1411.76 sec
7/7 Test #1: global_4denvar ...................   Passed  1735.00 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1735.02 sec

**Review by hu5970 — APPROVED** [review]
