### PR TITLE
Fix HAFS GSI debug build and run issues

### LINKED ISSUE #661: Address debug build and run issues for HAFS GSI
The HAFS application regression tests failed at the GSI level on the Jet platform and upon debugging, it appears that the variables **toff** and **t4dv** in the subroutine read_radar_l2rw_novadqc(read_radar.f90) were uninitialized and get assigned NaN values. Not totally sure that these are the reasons for HAFS RT failures on 
Jet, but it would be helpful if these variables could be properly initialized.

### PR DESCRIPTION
**Pull request by XuLu-NOAA**
**DUE DATE for merger of this PR into `develop` is 2/19/2024 (six weeks after PR creation).**
**DUE DATE for this PR is extended to 3/19/2024 because @XuLu-NOAA is on leave.**
**Description**

Xu Lu (xu.lu@noaa.gov) and Biju Thomas (biju.thomas@noaa.gov) fixed bugs regarding HAFS GSI debug build and run issues.  This is in corresponding to issue #661 

Fixes #661

        1. In read_radar.f90, uninitialized toff is making all the ground-based radar observations be placed at -3h instead of 0h, which creates wrong increments for FGAT and 4DEnVar.
        2. In read_radar.f90, uninitialized zsges will crash the debug mode.
        3. In read_radar.f90, t4dvo should be used instead of t4dv in the read_radar_l2rw_novadqc subroutine.
        4. In radinfo.90, maxscan should be increased to at least 252 to allow more scans, or it will crash the debug mode.
        5. In read_fl_hdob.f90, dlnpsob is replaced with 1000. since the SFMR does not sample surface pressure, and the uninitialized dlnpsob creates issues later in setupspd.f90 in the debug mode.
        6. In mod_fv3_lola.f90, (i,j+1) should be used instead of (i+1,j) in searching for V edges. 
        7. In stpcalc.f90, when tried to find the best stepsize from outpen around L838-864, the minimum outstp(i) is stored in stp(ii), but the istp_use is asigned with i instead of ii. Create inconsistency when assigning stp(istp_use) to stpinout at L872. Should use istp_use=ii instead.

**Type of change**
- [Yes] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
Regression test on Orion:
```
Test project /work/noaa/hwrf/save/xulu/mergeversions/GSI/build
CMake Warning (dev) at CTestTestfile.cmake:9 (subdirs):  Syntax Warning in cmake code at /work/noaa/hwrf/save/xulu/mergeversions/GSI/build/regression/CTestTestfile.cmake:7:10
1/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  365.11 sec
2/7 Test #7: [=[global_enkf]=] ................   Passed  430.29 sec
3/7 Test #3: [=[rrfs_3denvar_glbens]=] ........   Passed  605.35 sec
4/7 Test #2: [=[rtma]=] .......................   Passed  969.78 sec
5/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  1455.47 sec
6/7 Test #1: [=[global_4denvar]=] .............   Passed  1682.40 sec
7/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  1758.90 sec
```

The failed hafs_3denvar and 4denvar are within expectation due to the fix for toff. As demonstrated in the single observation tests in the following figure, the uninitialized toff can result in increment degradations due to wrongly assigned observation times:
image

### CODE REVIEW

File: src/gsi/read_fl_hdob.f90 [hunk 1]
```diff
@@ -1121,7 +1121,7 @@ subroutine read_fl_hdob(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,si
               cdata_all( 1,iout)=woe                    ! wind error
               cdata_all( 2,iout)=dlon                   ! grid relative longitude             
               cdata_all( 3,iout)=dlat                   ! grid relative latitude                  
-              cdata_all( 4,iout)=dlnpsob                ! ln(surface pressure in cb)
+              cdata_all( 4,iout)=1000.                  ! ln(surface pressure in cb) !Since dlnpsob is not provided by SFMR, force it to be 1000hPa. Not used in setupspd.f90
```
Comment (TingLei-NOAA) [inline src/gsi/read_fl_hdob.f90]: @XuLu-NOAA if it is not defined in this sub (and, supposedly, will not be used),  would it be better to assign r_missing to it?  This will help the code reading and avoid future use of this value by accident.

Comment (XuLu-NOAA) [reply src/gsi/read_fl_hdob.f90]: Yes, @TingLei-NOAA , I think you are right, I will use the missing value

File: src/gsi/read_fl_hdob.f90 [hunk 2]
```diff
@@ -1121,7 +1121,7 @@ subroutine read_fl_hdob(nread,ndata,nodata,infile,obstype,lunout,gstime,twind,si
               cdata_all( 1,iout)=woe                    ! wind error
               cdata_all( 2,iout)=dlon                   ! grid relative longitude             
               cdata_all( 3,iout)=dlat                   ! grid relative latitude                  
-              cdata_all( 4,iout)=dlnpsob                ! ln(surface pressure in cb)
+              cdata_all( 4,iout)=missing                ! ln(surface pressure in cb) !Since dlnpsob is not provided by SFMR, force it to be missing. Not used in setupspd.f90
```
Comment (TingLei-NOAA) [inline src/gsi/read_fl_hdob.f90]: where is "missing" defined?  Could we directly use r_missing defined in the constants module?

Comment (XuLu-NOAA) [reply src/gsi/read_fl_hdob.f90]: Hi, @TingLei-NOAA , missing is defined at L150 of this read_fl_hdob.f90. 
` 150      real(r_kind), parameter :: missing = 1.0e+11_r_kind`
Do you still want me to use the r_missing from constants module in this case?

Comment (TingLei-NOAA) [reply src/gsi/read_fl_hdob.f90]: @XuLu-NOAA Thanks for explanation.   Yes, I prefer to using one single missing value if possible.

Comment (XuLu-NOAA) [reply src/gsi/read_fl_hdob.f90]: Sure @TingLei-NOAA , I've just modified the missing to r_missing from the constants module.

**Review by TingLei-NOAA — APPROVED** [review]

File: src/gsi/read_fl_hdob.f90 (hunk 2 above)
Comment (TingLei-NOAA) [reply src/gsi/read_fl_hdob.f90]: @XuLu-NOAA  Thanks.

**Comment by ShunLiu-NOAA** [comment]
@yonghuiweng Could you please review this PR? Thanks.

**Review by yonghuiweng — APPROVED** [review]

**Comment by ShunLiu-NOAA** [comment]
@XuLu-NOAA Could you please run regression test on WCOSS and HERA?

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA Could you please run regression test on WCOSS and HERA?

@ShunLiu-NOAA I can do it on Hera, but no WCOSS2 account yet. @yonghuiweng Can you help run it on WCOSS2? Thanks!

**Comment by yonghuiweng** [comment]
5 test failed on wcoss2. I will re-test later.
Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............***Failed  483.53 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  725.68 sec
3/7 Test #7: global_enkf ......................   Passed  1076.69 sec
4/7 Test #2: rtma .............................***Failed  1150.46 sec
5/7 Test #6: hafs_3denvar_hybens ..............***Failed  1213.19 sec
6/7 Test #5: hafs_4denvar_glbens ..............***Failed  1453.97 sec
7/7 Test #1: global_4denvar ...................***Failed  1554.23 sec

29% tests passed, 5 tests failed out of 7

Total Test time (real) = 1554.23 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          2 - rtma (Failed)
          4 - netcdf_fv3_regional (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest

**Comment by XuLu-NOAA** [comment]
Thanks, Yonghui! Here are my tests on Hera:
```
Test project /scratch1/NCEPDEV/hwrf/scrub/Xu.Lu/regression/GSI/build
    Start 1: [=[global_4denvar]=]
    Start 2: [=[rtma]=]
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 4: [=[netcdf_fv3_regional]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 7: [=[global_enkf]=]
1/7 Test #7: [=[global_enkf]=] ................   Passed  1359.20 sec
2/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  2545.41 sec
3/7 Test #3: [=[rrfs_3denvar_glbens]=] ........   Passed  2545.47 sec
4/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  4761.09 sec
5/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  4763.34 sec
6/7 Test #1: [=[global_4denvar]=] .............   Passed  5586.05 sec
7/7 Test #2: [=[rtma]=] .......................   Passed  22761.94 sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) = 22761.99 sec

The following tests FAILED:
          5 - [=[hafs_4denvar_glbens]=] (Failed)
          6 - [=[hafs_3denvar_hybens]=] (Failed)
Errors while running CTest
```

**Comment by yonghuiweng** [comment]
After re-built the code, and tried serval times, I still only passed 3 tests (one more than the 1st try):

Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............***Failed  664.86 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  727.66 sec
3/7 Test #7: global_enkf ......................   Passed  1106.25 sec
4/7 Test #2: rtma .............................   Passed  1276.90 sec
5/7 Test #6: hafs_3denvar_hybens ..............***Failed  1277.65 sec
6/7 Test #5: hafs_4denvar_glbens ..............***Failed  1463.64 sec
7/7 Test #1: global_4denvar ...................***Failed  1615.82 sec

43% tests passed, 4 tests failed out of 7

Total Test time (real) = 1615.83 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          4 - netcdf_fv3_regional (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest

**Comment by XuLu-NOAA** [comment]
> After re-built the code, and tried serval times, I still only passed 3 tests (one more than the 1st try):
> 
> Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/GSI/build Start 1: global_4denvar Start 2: rtma Start 3: rrfs_3denvar_glbens Start 4: netcdf_fv3_regional Start 5: hafs_4denvar_glbens Start 6: hafs_3denvar_hybens Start 7: global_enkf 1/7 Test #4: netcdf_fv3_regional ..............***Failed 664.86 sec 2/7 Test #3: rrfs_3denvar_glbens .............. Passed 727.66 sec 3/7 Test #7: global_enkf ...................... Passed 1106.25 sec 4/7 Test #2: rtma ............................. Passed 1276.90 sec 5/7 Test #6: hafs_3denvar_hybens ..............***Failed 1277.65 sec 6/7 Test #5: hafs_4denvar_glbens ..............***Failed 1463.64 sec 7/7 Test #1: global_4denvar ...................***Failed 1615.82 sec
> 
> 43% tests passed, 4 tests failed out of 7
> 
> Total Test time (real) = 1615.83 sec
> 
> The following tests FAILED: 1 - global_4denvar (Failed) 4 - netcdf_fv3_regional (Failed) 5 - hafs_4denvar_glbens (Failed) 6 - hafs_3denvar_hybens (Failed) Errors while running CTest

Hi, @yonghuiweng , can you run with --rerun-failed --output-on-failure, and put the log on Orion? Then I can check if 1 & 4 failed due to run time or something else.

**Comment by yonghuiweng** [comment]
> > After re-built the code, and tried serval times, I still only passed 3 tests (one more than the 1st try):
> > Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/GSI/build Start 1: global_4denvar Start 2: rtma Start 3: rrfs_3denvar_glbens Start 4: netcdf_fv3_regional Start 5: hafs_4denvar_glbens Start 6: hafs_3denvar_hybens Start 7: global_enkf 1/7 Test #4: netcdf_fv3_regional ..............***Failed 664.86 sec 2/7 Test #3: rrfs_3denvar_glbens .............. Passed 727.66 sec 3/7 Test #7: global_enkf ...................... Passed 1106.25 sec 4/7 Test #2: rtma ............................. Passed 1276.90 sec 5/7 Test #6: hafs_3denvar_hybens ..............***Failed 1277.65 sec 6/7 Test #5: hafs_4denvar_glbens ..............***Failed 1463.64 sec 7/7 Test #1: global_4denvar ...................***Failed 1615.82 sec
> > 43% tests passed, 4 tests failed out of 7
> > Total Test time (real) = 1615.83 sec
> > The following tests FAILED: 1 - global_4denvar (Failed) 4 - netcdf_fv3_regional (Failed) 5 - hafs_4denvar_glbens (Failed) 6 - hafs_3denvar_hybens (Failed) Errors while running CTest
> 
> Hi, @yonghuiweng , can you run with --rerun-failed --output-on-failure, and put the log on Orion? Then I can check if 1 & 4 failed due to run time or something else.

Yes, this test result is from the run with --rerun-failed. 
I copied the whole folder as: orion:/work2/noaa/hwrf/noscrub/yweng/regression/GSI.

**Comment by XuLu-NOAA** [comment]
Thanks, Yonghui!
After checking the log files for the global 4DEnVar. The initial grady and cost functions are the same but the b of the first iteration is different. 
Since this is global 4D, so it should have nothing to do with the dual_res fix. 
And the rw & spd in the convinfo are -1 in this configuration, so it should have nothing to do with the read_radar and read_fl_hdob fixes.  
The only possible change is the increased maxscan that expands the satellite channels. I suspect that the original configuration was using some random values, but not sure how to isolate it as we do not know what sat obs exceeds the 250 default configuration. Also, I'm not sure why it's not showing in Orion/Hera. It will be difficult for me to identify the issue. Does anyone have clues or suggestions on the issue?
Thanks!

**Comment by TingLei-NOAA** [comment]
Xu
Tnanks a lot for those informative analysis of the possible cause for the
failure of the global ens4dvar test.
I will take a look at them on wcoss2  next week and will first to see if it
is from the changed maxscan as you suspected

Regards
Ting

______________________________

Ting Lei

Physical Scientist, Contractor with Lynker in support of

EMC/NCEP/NWS/NOAA

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.***

301-683-3624

**Comment by TingLei-NOAA** [comment]
Guys. the wcoss2 is still unavailable to me and I will give an update later.

**Comment by TingLei-NOAA** [comment]
@yonghuiweng @XuLu-NOAA   I just finished global_4denvar test and it passed( see output : c.out in /lfs/h2/emc/da/noscrub/Ting.Lei/dr-xu/GSI/build .  Yonghui, would you please have a look to see what the differences are between your and my run?   Thanks.

**Comment by XuLu-NOAA** [comment]
> @yonghuiweng @XuLu-NOAA I just finished global_4denvar test and it passed( see output : c.out in /lfs/h2/emc/da/noscrub/Ting.Lei/dr-xu/GSI/build . Yonghui, would you please have a look to see what the differences are between your and my run? Thanks.

Hi, @yonghuiweng , would you mind rerunning the regression test to see if you can reproduce the error on WCOSS2? Since Ting appears not able to reproduce.

**Comment by yonghuiweng** [comment]
@XuLu-NOAA  and @TingLei-NOAA, I did a start-over test,  passed 5 out of 7 tasks and only 2 tests failed (Start 5: hafs_4denvar_glbens and Start 6: hafs_3denvar_hybens). The result is saved at /lfs/h2/emc/hur/noscrub/yonghui.weng/noscrub/regression.
I realize the error I made for the last test is that I did not check out https://github.com/NOAA-EMC/GSI, I used the previous version when I did dualres tests.
Thanks.

**Comment by yonghuiweng** [comment]
> @XuLu-NOAA and @TingLei-NOAA, I did a start-over test, passed 5 out of 7 tasks and only 2 tests failed (Start 5: hafs_4denvar_glbens and Start 6: hafs_3denvar_hybens). The result is saved at /lfs/h2/emc/hur/noscrub/yonghui.weng/noscrub/regression. I realize the error I made for the last test is that I did not check out https://github.com/NOAA-EMC/GSI, I used the previous version when I did dualres tests. Thanks.

The 2nd test shows:
Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/GSI/build
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 1: global_4denvar
    Start 7: global_enkf
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
1/7 Test #4: netcdf_fv3_regional ..............***Failed  484.02 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  665.67 sec
3/7 Test #2: rtma .............................   Passed  1029.06 sec
4/7 Test #7: global_enkf ......................   Passed  1078.96 sec
5/7 Test #6: hafs_3denvar_hybens ..............***Failed  1210.73 sec
6/7 Test #5: hafs_4denvar_glbens ..............***Failed  1329.76 sec
7/7 Test #1: global_4denvar ...................   Passed  1489.98 sec

57% tests passed, 3 tests failed out of 7

Total Test time (real) = 1489.99 sec

The following tests FAILED:
          4 - netcdf_fv3_regional (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest

**Comment by ShunLiu-NOAA** [comment]
@yonghuiweng could you give the path of your test on WCOSS2? @TingLei-NOAA will take a look at into the detail of failure.

**Comment by yonghuiweng** [comment]
Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/GSI/build

**Comment by TingLei-NOAA** [comment]
@ShunLiu-NOAA and @yonghuiweng check the netcdf test output, it showed :
```

The memory for netcdf_fv3_regional_loproc_updat is 270452 KBs.  This has exceeded maximum allowable memory of 201564 KBs,
resulting in Failure memthresh of the regression test.
```
Since this PR has nothing to do with GSI memory "setup",  this "failure" could be safely ignored.

**Review by ShunLiu-NOAA — DISMISSED** [review]

**Comment by ShunLiu-NOAA** [comment]
@TingLei-NOAA  Thank you. @XuLu-NOAA Could you please rerun regression test on ORION and HEAR?

**Comment by XuLu-NOAA** [comment]
> @TingLei-NOAA Thank you. @XuLu-NOAA Could you please rerun regression test on ORION and HEAR?

Sure, but Hera is currently full. I'll try it as soon as the disk is available.

**Comment by XuLu-NOAA** [comment]
I've finished the ctest on Orion, the result is strange:
```
Test project /work/noaa/hwrf/save/xulu/mergeversions/GSI/build
...
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 7: [=[global_enkf]=]
    Start 1: [=[global_4denvar]=]
    Start 2: [=[rtma]=]
    Start 4: [=[netcdf_fv3_regional]=]
1/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  1204.43                                                                      sec
2/7 Test #2: [=[rtma]=] .......................   Passed  1389.41                                                                      sec
3/7 Test #7: [=[global_enkf]=] ................   Passed  4688.38                                                                      sec
4/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  6074.50                                                                      sec
5/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  8050.84                                                                      sec
6/7 Test #1: [=[global_4denvar]=] .............   Passed  9364.04                                                                      sec
7/7 Test #3: [=[rrfs_3denvar_glbens]=] ........***Failed  10086.12                                                                      sec

57% tests passed, 3 tests failed out of 7

Total Test time (real) = 10086.22 sec

The following tests FAILED:
          3 - [=[rrfs_3denvar_glbens]=] (Failed)
          5 - [=[hafs_4denvar_glbens]=] (Failed)
          6 - [=[hafs_3denvar_hybens]=] (Failed)

```

So hafs3d and 4d failures are expected, rrfs one is not.
The /work/noaa/hwrf/save/xulu/mergeversions/test/noscrub/regression/rrfs_3denvar_glbens_regression_results.txt indicates the error is due to:
`The results between the two runs (rrfs_3denvar_glbens_loproc_updat and rrfs_3denvar_glbens_loproc_contrl) are not reproducible
Thus, the case has Failed siganl of the regression tests.
`

But when I check the /work/noaa/hwrf/save/xulu/mergeversions/test/test/tmpreg_rrfs_3denvar_glbens/rrfs_3denvar_glbens_loproc_contrl/stdout
and 
/work/noaa/hwrf/save/xulu/mergeversions/test/test/tmpreg_rrfs_3denvar_glbens/rrfs_3denvar_glbens_loproc_updat/stdout
For details, the output is identical

Not sure what happened, and I've repeated the ctest for 3 times.

Xu

**Comment by TingLei-NOAA** [comment]
Hi Xu
I think this is because the emc branch has just an update to enforce
nonnegative qr and so on.
This enforcing is done in the write out step
So you see identical results in the stout while the updated fields are
different.
You can merge the current emc Gsi to your branch to resolve this issue
Ting

______________________________

Ting Lei

Physical Scientist, Contractor with Lynker in support of

EMC/NCEP/NWS/NOAA

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.***

301-683-3624

**Comment by ShunLiu-NOAA** [comment]
> I've finished the ctest on Orion, the result is strange:
> 
> ```
> Test project /work/noaa/hwrf/save/xulu/mergeversions/GSI/build
> ...
>     Start 3: [=[rrfs_3denvar_glbens]=]
>     Start 5: [=[hafs_4denvar_glbens]=]
>     Start 6: [=[hafs_3denvar_hybens]=]
>     Start 7: [=[global_enkf]=]
>     Start 1: [=[global_4denvar]=]
>     Start 2: [=[rtma]=]
>     Start 4: [=[netcdf_fv3_regional]=]
> 1/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  1204.43                                                                      sec
> 2/7 Test #2: [=[rtma]=] .......................   Passed  1389.41                                                                      sec
> 3/7 Test #7: [=[global_enkf]=] ................   Passed  4688.38                                                                      sec
> 4/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  6074.50                                                                      sec
> 5/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  8050.84                                                                      sec
> 6/7 Test #1: [=[global_4denvar]=] .............   Passed  9364.04                                                                      sec
> 7/7 Test #3: [=[rrfs_3denvar_glbens]=] ........***Failed  10086.12                                                                      sec
> 
> 57% tests passed, 3 tests failed out of 7
> 
> Total Test time (real) = 10086.22 sec
> 
> The following tests FAILED:
>           3 - [=[rrfs_3denvar_glbens]=] (Failed)
>           5 - [=[hafs_4denvar_glbens]=] (Failed)
>           6 - [=[hafs_3denvar_hybens]=] (Failed)
> ```
> 
> So hafs3d and 4d failures are expected, rrfs one is not. The /work/noaa/hwrf/save/xulu/mergeversions/test/noscrub/regression/rrfs_3denvar_glbens_regression_results.txt indicates the error is due to: `The results between the two runs (rrfs_3denvar_glbens_loproc_updat and rrfs_3denvar_glbens_loproc_contrl) are not reproducible Thus, the case has Failed siganl of the regression tests. `
> 
> But when I check the /work/noaa/hwrf/save/xulu/mergeversions/test/test/tmpreg_rrfs_3denvar_glbens/rrfs_3denvar_glbens_loproc_contrl/stdout and /work/noaa/hwrf/save/xulu/mergeversions/test/test/tmpreg_rrfs_3denvar_glbens/rrfs_3denvar_glbens_loproc_updat/stdout For details, the output is identical
> 
> Not sure what happened, and I've repeated the ctest for 3 times.
> 
> Xu

Do you sync "develop" with your branch before ctest?

**Comment by XuLu-NOAA** [comment]
Thanks, @TingLei-NOAA and @ShunLiu-NOAA , I rerun the ctest after merge with the develop branch, now the result makes sense on Orion. I'll do it on Hera when disk is available.
`Test project /work/noaa/hwrf/save/xulu/mergeversions/GSI/build
    Start 1: [=[global_4denvar]=]
    Start 2: [=[rtma]=]
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 4: [=[netcdf_fv3_regional]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 7: [=[global_enkf]=]
1/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  1083.86 sec
2/7 Test #2: [=[rtma]=] .......................   Passed  1269.44 sec
3/7 Test #7: [=[global_enkf]=] ................   Passed  2721.00 sec
4/7 Test #1: [=[global_4denvar]=] .............   Passed  3304.52 sec
5/7 Test #3: [=[rrfs_3denvar_glbens]=] ........   Passed  3366.63 sec
6/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  4214.60 sec
7/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  4753.83 sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) = 4753.87 sec

The following tests FAILED:
          5 - [=[hafs_4denvar_glbens]=] (Failed)
          6 - [=[hafs_3denvar_hybens]=] (Failed)
Errors while running CTest
`

**Comment by XuLu-NOAA** [comment]
Further test on Hera:
```
Test project /scratch1/NCEPDEV/hwrf/scrub/Xu.Lu/regression/GSI/build
...
    Start 1: [=[global_4denvar]=]
    Start 2: [=[rtma]=]
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 4: [=[netcdf_fv3_regional]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 7: [=[global_enkf]=]
1/7 Test #3: [=[rrfs_3denvar_glbens]=] ........   Passed  792.94 s                                                                     ec
2/7 Test #7: [=[global_enkf]=] ................   Passed  816.01 s                                                                     ec
3/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  908.99 s                                                                     ec
4/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  1404.69                                                                      sec
5/7 Test #1: [=[global_4denvar]=] .............   Passed  3426.76                                                                      sec
6/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  3443.57                                                                      sec
7/7 Test #2: [=[rtma]=] .......................   Passed  3792.18                                                                      sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) = 3792.19 sec

The following tests FAILED:
          5 - [=[hafs_4denvar_glbens]=] (Failed)
          6 - [=[hafs_3denvar_hybens]=] (Failed)
Errors while running CTest
```
The results are consistent with those on Orion.
Best,
Xu

**Comment by RussTreadon-NOAA** [comment]
@ShunLiu-NOAA and @XuLu-NOAA 

With the merger of PR #670 into `develop` changes to `read_radar.f90` now conflict with the updated `develop`.  I cloned `hafs-community:feature/toff_fix` on Cactus in `/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr679` and merged `develop` into the working copy.   I looked at the conflicting sections in `src/gsi/read_radar.f90`.   Unfortunately, I do not know enough about `read_radar.f90` to confidently resolve the conflicts.

Since you, @XuLu-NOAA , made the changes to `read_radar.f90` in this PR, you may be able to more quickly resolve the conflicts than me.  Feel free to look at `/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr679/src/gsi/read_radar.f90` see the four sections with conflicts.

**Comment by XuLu-NOAA** [comment]
> @ShunLiu-NOAA and @XuLu-NOAA
> 
> With the merger of PR #670 into `develop` changes to `read_radar.f90` now conflict with the updated `develop`. I cloned `hafs-community:feature/toff_fix` on Cactus in `/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr679` and merged `develop` into the working copy. I looked at the conflicting sections in `src/gsi/read_radar.f90`. Unfortunately, I do not know enough about `read_radar.f90` to confidently resolve the conflicts.
> 
> Since you, @XuLu-NOAA , made the changes to `read_radar.f90` in this PR, you may be able to more quickly resolve the conflicts than me. Feel free to look at `/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr679/src/gsi/read_radar.f90` see the four sections with conflicts.

Thanks, @RussTreadon-NOAA , can you put it on Hera or Orion? I don't have the access to Cactus or WCOSS2 at the moment.

**Comment by RussTreadon-NOAA** [comment]
@XuLu-NOAA , look in Hera `/scratch2/NCEPDEV/stmp1/Russ.Treadon/pr679`

**Comment by TingLei-NOAA** [comment]
@XuLu-NOAA  the easy way is , on any machine, you just sync/merge the emc/develop branch again:) and resolve the conflict as you would usually do .

**Comment by RussTreadon-NOAA** [comment]
Thank you @XuLu-NOAA for synching your branch with the head of `develop`.   It would be good to cross check your changes to `src/gsi/stpcalc.f90` with @jderber-NOAA .

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA the easy way is , on any machine, you just sync/merge the emc/develop branch again:) and resolve the conflict as you would usually do .

Thanks, @TingLei-NOAA and @RussTreadon-NOAA , I've addressed the conflict and added another new bug fix in stpcalc.f90 regarding a debug failure we recently found. I modified the description of this PR.  New regression test is ongoing.

**Comment by XuLu-NOAA** [comment]
> Thank you @XuLu-NOAA for synching your branch with the head of `develop`. It would be good to cross check your changes to `src/gsi/stpcalc.f90` with @jderber-NOAA .

Thanks, @RussTreadon-NOAA , it looks to me that we are dealing with a different issue. The bug still exists after his changes. I modified after synching the develop branch. @TingLei-NOAA and @yonghuiweng would you mind reviewing the new fix and letting me know what you think?

**Comment by RussTreadon-NOAA** [comment]
@XuLu-NOAA , I agree that bugs should be fixed when identified.  I still think it would be good to have @jderber-NOAA look at the bug fix to `stpcalc.f90`.  I think he would like to know given the amount of time an energy he has put into GSI and especially the minimization.

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA , I agree that bugs should be fixed when identified. I still think it would be good to have @jderber-NOAA look at the bug fix to `stpcalc.f90`. I think he would like to know given the amount of time an energy he has put into GSI and especially the minimization.

I see, yes. @jderber-NOAA please help take a look at this issue when you are available. Thanks!

**Comment by jderber-NOAA** [comment]
Sorry I was outside diggig up rocks from the back yard.Will try to look at it before Monday.JSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Xu Lu ***@***.***> Date: 1/26/24  4:52 PM  (GMT-05:00) To: NOAA-EMC/GSI ***@***.***> Cc: jderber-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NOAA-EMC/GSI] Fix HAFS GSI debug build and run issues (PR #679) 

@XuLu-NOAA , I agree that bugs should be fixed when identified. I still think it would be good to have @jderber-NOAA look at the bug fix to stpcalc.f90. I think he would like to know given the amount of time an energy he has put into GSI and especially the minimization.

I see, yes. @jderber-NOAA please help take a look at this issue when you are available. Thanks!

**Comment by yonghuiweng** [comment]
@XuLu-NOAA  I tested it on wcoss2, here is the result,
Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  544.50 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  726.65 sec
3/7 Test #7: global_enkf ......................   Passed  1075.48 sec
4/7 Test #6: hafs_3denvar_hybens ..............***Failed  1391.88 sec
5/7 Test #5: hafs_4denvar_glbens ..............***Failed  1692.14 sec
6/7 Test #2: rtma .............................   Passed  1867.98 sec
7/7 Test #1: global_4denvar ...................   Passed  2392.69 sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) = 2392.78 sec

The following tests FAILED:
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA I tested it on wcoss2, here is the result, Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/GSI/build Start 1: global_4denvar Start 2: rtma Start 3: rrfs_3denvar_glbens Start 4: netcdf_fv3_regional Start 5: hafs_4denvar_glbens Start 6: hafs_3denvar_hybens Start 7: global_enkf 1/7 Test #4: netcdf_fv3_regional .............. Passed 544.50 sec 2/7 Test #3: rrfs_3denvar_glbens .............. Passed 726.65 sec 3/7 Test #7: global_enkf ...................... Passed 1075.48 sec 4/7 Test #6: hafs_3denvar_hybens ..............***Failed 1391.88 sec 5/7 Test #5: hafs_4denvar_glbens ..............***Failed 1692.14 sec 6/7 Test #2: rtma ............................. Passed 1867.98 sec 7/7 Test #1: global_4denvar ................... Passed 2392.69 sec
> 
> 71% tests passed, 2 tests failed out of 7
> 
> Total Test time (real) = 2392.78 sec
> 
> The following tests FAILED: 5 - hafs_4denvar_glbens (Failed) 6 - hafs_3denvar_hybens (Failed) Errors while running CTest

Thanks, Yonghui!
And here are my ctest on Hera:
```
Test project /scratch1/NCEPDEV/hwrf/scrub/Xu.Lu/regression/GSI/build
...

    Start 1: [=[global_4denvar]=]
    Start 2: [=[rtma]=]
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 4: [=[netcdf_fv3_regional]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 7: [=[global_enkf]=]
1/7 Test #7: [=[global_enkf]=] ................   Passed  4701.41
sec
2/7 Test #3: [=[rrfs_3denvar_glbens]=] ........   Passed  5234.24
sec
3/7 Test #1: [=[global_4denvar]=] .............   Passed  5527.26
sec
4/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  5893.19
sec
5/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  5920.98
sec
6/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  6385.17
sec
7/7 Test #2: [=[rtma]=] .......................   Passed  7758.24
sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) = 7758.31 sec

The following tests FAILED:
          5 - [=[hafs_4denvar_glbens]=] (Failed)
          6 - [=[hafs_3denvar_hybens]=] (Failed)
Errors while running CTest
```

And on Orion:
```
Test project /work/noaa/hwrf/save/xulu/mergeversions/GSI/build
...
    Start 1: [=[global_4denvar]=]
    Start 2: [=[rtma]=]
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 4: [=[netcdf_fv3_regional]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 7: [=[global_enkf]=]
1/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  1083.06
2/7 Test #2: [=[rtma]=] .......................   Passed  2230.00
3/7 Test #7: [=[global_enkf]=] ................   Passed  3253.16 sec
4/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  3497.27 sec
5/7 Test #1: [=[global_4denvar]=] .............***Failed  5043.93 sec
6/7 Test #3: [=[rrfs_3denvar_glbens]=] ........   Passed  5106.52 sec
7/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  6075.65 sec

57% tests passed, 3 tests failed out of 7

Total Test time (real) = 6075.68 sec

The following tests FAILED:
          1 - [=[global_4denvar]=] (Failed)
          5 - [=[hafs_4denvar_glbens]=] (Failed)
          6 - [=[hafs_3denvar_hybens]=] (Failed)
Errors while running CTest
```

The failure on global_4denvar is due to runtime issue, /work/noaa/hwrf/save/xulu/mergeversions/test/noscrub/regression/global_4denvar_regression_results.txt
```
The runtime for global_4denvar_loproc_updat is 460.338683 seconds.
  This has exceeded maximum allowable threshold time of 433.277029
 seconds,
resulting in Failure time-thresh of the regression test.

```

So it should be fine.

**Comment by jderber-NOAA** [comment]
I will note that at least one of the hafs failures is due to fixing the bug in mod_fv3_lola.f90.  Fixing this bug changes the results.

In addition, it will be necessary at some time to ensure that zsges,idomsfc,skint,ff10,sfcr are all properly defined when filling the cdata arrays for all the different options of data in read_radar.f90.  Now they are not.  Of course this can change the results when radar data is used so if this is done, it will not reproduce the regression tests.

Still examining stpcalc.f90 to ensure that the changes are correct.

File: src/gsi/stpcalc.f90 [hunk 3]
```diff
@@ -844,10 +844,10 @@ subroutine stpcalc(stpinout,sval,sbias,dirx,dval,dbias, &
            if(outpen(i) < outpensave)then
               stp(ii)=outstp(i)
               outpensave=outpen(i)
-              istp_use=i
+              istp_use=ii
            end if
         end do
-        if(istp_use /= istp_iter) then
+        if(istp_use /= nsteptot) then
```
Comment (TingLei-NOAA) [inline src/gsi/stpcalc.f90:850]: @XuLu-NOAA  Thanks for identifying the issue in , I believe, rarely occurring situations, I am also waiting for John 's thorough reviewing of this issue.  For being now, would you give some details what the issue is you identified when GSI debug mode is used.    From my current understanding of this part,  your change on line 850 looks "probably" right (when the step size at one previous step is selected, exit this loop), but the change on line 847 is suspicious. Just consider the "coding" itself (don't consider what the algorithm should be), only the change on line 850 could not resolve the problem encountered using debug mode GSI?

Comment (XuLu-NOAA) [reply src/gsi/stpcalc.f90:850]: Yes, @TingLei-NOAA . 
The error happens in an extreme situation where the optimal stepsize is not found after ii loop from 1 to istp_iter (which is set to 5). 

Then it will go into this part of code to look for the historical minimum outpen, and use the corresponding stp to be the final output for this search. 

In the original code, ii=istp_iter (which is 5) according to the if statement at L839. 
Yet L847 assigns istp_use=i (7 in this case; i loops from 1 to nsteptot, where nsteptot = ii*3+1 according to L704-710), while storing the minimum outstp(i) to stp(ii) at L845.
Then at L872, it tries to assign stp(istp_use) to stpinout, an error happened as stp is defined to be the size of istp_iter at L276, but istp_use is 7 in this case.

I believe the right logic is that since the minimum outstp is assigned to stp(ii), then istp_use should be ii as well. So the output stpinout can be using the right value at L872, even when i<istp_iter.

Comment (jderber-NOAA) [reply src/gsi/stpcalc.f90:850]: @XuLu-NOAA 

After looking at the code carefully, I agree with your 2 changes.  Thanks for finding an issue that I probably introduced.

**Comment by jderber-NOAA** [comment]
@XuLu-NOAA 

After looking at the code carefully, I agree with your 2 changes.  Thanks for finding an issue that I probably introduced.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @jderber-NOAA, for carefully reviewing the proposed changes to `stpcalc.f90`.  Your input as _the expert_ is much appreciated.

**Comment by jderber-NOAA** [comment]
"the expert" = "maker of errors"

**Comment by XuLu-NOAA** [comment]
> "the expert" = "maker of errors"

@jderber-NOAA , thanks for your review! I think the issue was there before your newest commits. It is just a very rare occasion that most situations won't come to this part of the code. We just identified it in a debug mode.

**Review by TingLei-NOAA — APPROVED** [review]

**Comment by ShunLiu-NOAA** [comment]
@XuLu-NOAA Could you please sync with develop and run regression test again?

**Comment by RussTreadon-NOAA** [comment]
@ShunLiu-NOAA , this PR is past it's 2/19/2024 due date.  As per our policy we should close this PR and returned it to @XuLu-NOAA .  However, I recall that you saying that @XuLu-NOAA is on leave until early March.  

What remains to be done before this PR can be scheduled for merger into `develop`?

**Comment by ShunLiu-NOAA** [comment]
we need @XuLu-NOAA's help to sync his branch with _develop_ and  rerun ctest . Could we extend the PR until @XuLu-NOAA comes to office? I don't think we need another round of review for this PR.

**Comment by RussTreadon-NOAA** [comment]
Agreed.  As long as there are no changes to code, there is no need for reviewers to re-review.   

I just merged the current head of NOAA-EMC/GSI `develop` into a working copy of `hafs-community:feature/toff_fix` on Hercules.  There were no merge conflicts.  I'm not sure, though, if I can push to `hafs-community:feature/toff_fix`.  Shall I try?

**Comment by ShunLiu-NOAA** [comment]
@RussTreadon-NOAA Thank you. I think @XuLu-NOAA need to rerun ctests anyway. We could wait for @XuLu-NOAA to merge _develop_ into hafs-community:feature/toff_fix.

**Comment by RussTreadon-NOAA** [comment]
OK, I'll delete my updated copy of `hafs-community:feature/toff_fix`.  Does a revised due date of 3/19/2024 work?  If so, please update the PR description block accordingly.

**Comment by ShunLiu-NOAA** [comment]
Thank you @RussTreadon-NOAA. PR description block is updated.

**Comment by ShunLiu-NOAA** [comment]
@XuLu-NOAA Could you please sync with _develop_ and rerun ctest? Thank you.

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA Could you please sync with _develop_ and rerun ctest? Thank you.

Yes, Shun. I've synced with develop and am running ctest on Orion. Hera is in maintenance, I'll try it as soon as it's back. @yonghuiweng Yonghui, would you mind helping running the ctest on WCOSS2 again?

**Comment by XuLu-NOAA** [comment]
Here're the ctest results on Orion:
```
Test project /work/noaa/aoml-hafsda/xlu/newtrunk/regression/GSI/build
......
    Start 1: [=[global_4denvar]=]
    Start 2: [=[rtma]=]
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 4: [=[netcdf_fv3_regional]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 7: [=[global_enkf]=]
1/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  243.89 sec
2/7 Test #7: [=[global_enkf]=] ................   Passed  248.29 sec
3/7 Test #3: [=[rrfs_3denvar_glbens]=] ........   Passed  605.56 sec
4/7 Test #2: [=[rtma]=] .......................   Passed  968.36 sec
5/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  1214.15 sec
6/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  1395.41 sec
7/7 Test #1: [=[global_4denvar]=] .............   Passed  1501.69 sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) = 1501.69 sec

The following tests FAILED:
          5 - [=[hafs_4denvar_glbens]=] (Failed)
          6 - [=[hafs_3denvar_hybens]=] (Failed)
Errors while running CTest
```

**Comment by TingLei-NOAA** [comment]
@XuLu-NOAA , so what are the cause  for failed tests? Are they ignorable or further investigation is needed?

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA , so what are the cause for failed tests? Are they ignorable or further investigation is needed?

Hi, Ting, the failures in HAFS 3d/4d are expected due to the fixes in toff & mod_fv3_lola. This is the old pull request that has been frozen due to my absence in the merging with the newest develop branch.

**Comment by TingLei-NOAA** [comment]
@Xu Lu - NOAA Affiliate ***@***.***>  Great . Thanks. for this
note/clarification.
Ting

_____________________________

Ting Lei

Physical Scientist, Contractor with Lynker in support of

EMC/NCEP/NWS/NOAA

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.***

301-683-3624

**Comment by XuLu-NOAA** [comment]
Here's the RT_test results on Hera:
```
Test project /scratch1/NCEPDEV/hwrf/scrub/Xu.Lu/regression/GSI/build
......
    Start 1: [=[global_4denvar]=]
    Start 2: [=[rtma]=]
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 4: [=[netcdf_fv3_regional]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 7: [=[global_enkf]=]
1/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  484.31 s                                                                     ec
2/7 Test #3: [=[rrfs_3denvar_glbens]=] ........   Passed  487.22 s                                                                     ec
3/7 Test #7: [=[global_enkf]=] ................   Passed  497.44 s                                                                     ec
^[[A4/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  1098                                                                     .63 sec
5/7 Test #2: [=[rtma]=] .......................   Passed  1148.34                                                                      sec
6/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  1335.69                                                                      sec
7/7 Test #1: [=[global_4denvar]=] .............   Passed  1625.53                                                                      sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) = 1625.56 sec

The following tests FAILED:
          5 - [=[hafs_4denvar_glbens]=] (Failed)
          6 - [=[hafs_3denvar_hybens]=] (Failed)
Errors while running CTest
```

**Comment by XuLu-NOAA** [comment]
Hi, @TingLei-NOAA or @yonghuiweng , could any of you help run the ctest on WCOSS2 machines? I would imagine that's the last step of this PR. Thanks!

**Comment by yonghuiweng** [comment]
> Hi, @TingLei-NOAA or @yonghuiweng , could any of you help run the ctest on WCOSS2 machines? I would imagine that's the last step of this PR. Thanks!

Here is the test on wcoss2:

Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/toff_fix/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............***Failed  487.23 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  671.29 sec
3/7 Test #2: rtma .............................   Passed  1031.69 sec
4/7 Test #7: global_enkf ......................   Passed  1129.97 sec
5/7 Test #6: hafs_3denvar_hybens ..............***Failed  1215.04 sec
6/7 Test #5: hafs_4denvar_glbens ..............***Failed  1460.97 sec
7/7 Test #1: global_4denvar ...................***Failed  1504.06 sec

43% tests passed, 4 tests failed out of 7

Total Test time (real) = 1504.07 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          4 - netcdf_fv3_regional (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest

**Comment by XuLu-NOAA** [comment]
> > Hi, @TingLei-NOAA or @yonghuiweng , could any of you help run the ctest on WCOSS2 machines? I would imagine that's the last step of this PR. Thanks!
> 
> Here is the test on wcoss2:
> 
> Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/toff_fix/build Start 1: global_4denvar Start 2: rtma Start 3: rrfs_3denvar_glbens Start 4: netcdf_fv3_regional Start 5: hafs_4denvar_glbens Start 6: hafs_3denvar_hybens Start 7: global_enkf 1/7 Test #4: netcdf_fv3_regional ..............***Failed 487.23 sec 2/7 Test #3: rrfs_3denvar_glbens .............. Passed 671.29 sec 3/7 Test #2: rtma ............................. Passed 1031.69 sec 4/7 Test #7: global_enkf ...................... Passed 1129.97 sec 5/7 Test #6: hafs_3denvar_hybens ..............***Failed 1215.04 sec 6/7 Test #5: hafs_4denvar_glbens ..............***Failed 1460.97 sec 7/7 Test #1: global_4denvar ...................***Failed 1504.06 sec
> 
> 43% tests passed, 4 tests failed out of 7
> 
> Total Test time (real) = 1504.07 sec
> 
> The following tests FAILED: 1 - global_4denvar (Failed) 4 - netcdf_fv3_regional (Failed) 5 - hafs_4denvar_glbens (Failed) 6 - hafs_3denvar_hybens (Failed) Errors while running CTest

Hi, @yonghuiweng , by any chance, can you take a look at the results and see if the failures in 1&4 are due to the time limit? If not, would you mind copy over the error messages on Orion? Appreciated!

**Comment by yonghuiweng** [comment]
@XuLu-NOAA Both them are failed due to nonreproducible issue of loproc_updat and loproc_control. The files are copied to: /work2/noaa/hwrf/noscrub/yweng/regression/toff_fix_wcoss2.

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA Both them are failed due to nonreproducible issue of loproc_updat and loproc_control. The files are copied to: /work2/noaa/hwrf/noscrub/yweng/regression/toff_fix_wcoss2.

Thanks, @yonghuiweng! I checked the global 4denvar dir. The error is back to what we saw around Jan 13, where you failed but Ting cannot reproduce. The initial gradient & cost functions are the same, but the first b is somehow slightly different. My guess is still the maxscan in the original configurations are outbounded in some special occasions. But @TingLei-NOAA would you mind reproducing the error as before when you got time? Thanks for the help from both of you!

**Comment by TingLei-NOAA** [comment]
@XuLu-NOAA  there are some problems with global_4denvar test on wcoss2. You could find comments from @RussTreadon-NOAA over several issues/PRs.   I have also an update on this : https://github.com/NOAA-EMC/GSI/issues/712.

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA there are some problems with global_4denvar test on wcoss2. You could find comments from @RussTreadon-NOAA over several issues/PRs. I have also an update on this : #712.

Thanks, @TingLei-NOAA , How about the netcdf_fv3? The loproc & hiproc stdout for each updat & contrl are consistent. But the initial gradients are different between updat & contrl. Can you reproduce those errors on WCOSS2 as well?

**Comment by TingLei-NOAA** [comment]
@XuLu-NOAA I will see netcdf_fv3 right away.

**Comment by TingLei-NOAA** [comment]
@XuLu-NOAA  using debug mode GSI,  netcdf_fv3 regression test passed on wcoss2.  Shall we dig more to see what the differences are between mine and @yonghuiweng 's runs?

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA using debug mode GSI, netcdf_fv3 regression test passed on wcoss2. Shall we dig more to see what the differences are between mine and @yonghuiweng 's runs?

A quick question, in the old rerun of Jan 13 case, did you run in debug mode as well? Can you repeat his failure in non-debug mode?

**Comment by TingLei-NOAA** [comment]
> > @XuLu-NOAA using debug mode GSI, netcdf_fv3 regression test passed on wcoss2. Shall we dig more to see what the differences are between mine and @yonghuiweng 's runs?
> 
> A quick question, in the old rerun of Jan 13 case, did you run in debug mode as well? Can you repeat his failure in non-debug mode?

No, the previous re-run was  using optimized GSI.   When I have a chance, I will try optimized one for this time.

**Comment by ShunLiu-NOAA** [comment]
@XuLu-NOAA,  With @TingLei-NOAA's PR#698 merged into develop, is it a good time to revisit this PR?

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA, With @TingLei-NOAA's PR#698 merged into develop, is it a good time to revisit this PR?

Hi, @ShunLiu-NOAA I , I've synced the lastest develop branch and tried the regression tests on Orion & Hera:
Hera:
```
Test project /scratch1/NCEPDEV/hwrf/save/Xu.Lu/regression/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #3: rrfs_3denvar_glbens ..............   Passed  428.21 sec
2/7 Test #4: netcdf_fv3_regional ..............   Passed  485.33 sec
3/7 Test #7: global_enkf ......................   Passed  745.08 sec
4/7 Test #2: rtma .............................   Passed  969.41 sec
5/7 Test #5: hafs_4denvar_glbens ..............***Failed  1218.28 sec
6/7 Test #6: hafs_3denvar_hybens ..............***Failed  1279.63 sec
7/7 Test #1: global_4denvar ...................   Passed  1867.09 sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) = 1867.11 sec

The following tests FAILED:
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest
Output from these tests are in: /scratch1/NCEPDEV/hwrf/save/Xu.Lu/regression/GSI/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

Orion:
```
Test project /work/noaa/hwrf/save/xulu/mergeversions/GSI/build
...
    Start 1: [=[global_4denvar]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 2: [=[rtma]=]
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 4: [=[netcdf_fv3_regional]=]
    Start 7: [=[global_enkf]=]
1/7 Test #1: [=[global_4denvar]=] .............***Failed  420.28 sec
2/7 Test #7: [=[global_enkf]=] ................   Passed  1267.86 sec
3/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  1382.99 sec
4/7 Test #3: [=[rrfs_3denvar_glbens]=] ........   Passed  1446.05 sec
5/7 Test #2: [=[rtma]=] .......................   Passed  1867.99 sec
6/7 Test #6: [=[hafs_3denvar_hybens]=] ........***Failed  1936.05 sec
7/7 Test #5: [=[hafs_4denvar_glbens]=] ........***Failed  2237.03 sec

57% tests passed, 3 tests failed out of 7

Total Test time (real) = 2237.15 sec

The following tests FAILED:
          1 - [=[global_4denvar]=] (Failed)
          5 - [=[hafs_4denvar_glbens]=] (Failed)
          6 - [=[hafs_3denvar_hybens]=] (Failed)
Errors while running CTest
```

The HAFS 4d & 3d failed as expected. The global 4denvar failed on Orion due to the maximum time issue:
/work/noaa/hwrf/save/xulu/mergeversions/test/noscrub/regression/global_4denvar_regression_results.txt

So everything looks fine on Orion & Hera.

@yonghuiweng or @TingLei-NOAA Would you mind having a try with this latest version on WCOSS2 and see if the previous failure still persists?

Thanks,
Xu

**Comment by ShunLiu-NOAA** [comment]
@XuLu-NOAA and @TingLei-NOAA Thank you for regression test. With Sho's PR#700 merged, do you mind rerun regression test on Orion and WCOSS2? Sorry for this inconvenience.

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA and @TingLei-NOAA Thank you for regression test. With Sho's PR#700 merged, do you mind rerun regression test on Orion and WCOSS2? Sorry for this inconvenience.

Hi, @ShunLiu-NOAA , Here're my ctest on Hera:
```
Test project /scratch1/NCEPDEV/hwrf/save/Xu.Lu/regression/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #3: rrfs_3denvar_glbens ..............   Passed  427.49 sec
2/7 Test #4: netcdf_fv3_regional ..............   Passed  544.45 sec
3/7 Test #7: global_enkf ......................   Passed  805.65 sec
4/7 Test #2: rtma .............................   Passed  968.66 sec
5/7 Test #6: hafs_3denvar_hybens ..............***Failed  1042.71 sec
6/7 Test #5: hafs_4denvar_glbens ..............***Failed  1282.48 sec
7/7 Test #1: global_4denvar ...................   Passed  1925.60 sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) = 1925.63 sec

The following tests FAILED:
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest
Output from these tests are in: /scratch1/NCEPDEV/hwrf/save/Xu.Lu/regression/GSI/buil
d/Testing/Temporary/LastTest.log
```
And on Orion:
```
Test project /work/noaa/hwrf/save/xulu/mergeversions/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #1: global_4denvar ...................***Failed  120.82 s
ec
2/7 Test #4: netcdf_fv3_regional ..............   Passed  1687.09
sec
3/7 Test #7: global_enkf ......................   Passed  1852.08
sec
4/7 Test #3: rrfs_3denvar_glbens ..............   Passed  1930.60
sec
5/7 Test #6: hafs_3denvar_hybens ..............***Failed  2247.16
sec
6/7 Test #2: rtma .............................   Passed  2538.01 sec
7/7 Test #5: hafs_4denvar_glbens ..............***Failed  2726.58 sec

57% tests passed, 3 tests failed out of 7

Total Test time (real) = 2727.01 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
Errors while running CTest
Output from these tests are in: /work/noaa/hwrf/save/xulu/mergeversions/GSI/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

The failures in hafs 4d/3d are expected. The failure in global 4d on Orion was due to the data access permission issue. Let's see what Ting found out with his test on WCOSS2.

Best,
Xu

**Comment by RussTreadon-NOAA** [comment]
@XuLu-NOAA , if you routinely use Orion or Hercules you should request `rstprod` access.  A similar suggestion applies to @JingCheng-NOAA who faced the same problem in GSI PR #698.

Here's a blurb about [Restricted Data access](https://oriondocs.rdhpcs.noaa.gov/wiki/index.php?title=Protecting_Restricted_Data) on Orion

> Restricted data (rstprod) is allowed on the MSU-HPC system. Be sure to follow all of NOAA's restricted data policies when using MSU-HPC.
> 
> Request access via AIM (https://aim.rdhpcs.noaa.gov/) > Request access to a new project > rstprod.
> 
> Provide the following information in your justification:
> 
> The machine(s) where you will need rstprod access on (i.e. Hercules, Orion).
> The project(s) you will be using rstprod data for.

We can not loosen restrictions on `rstprod` data in the global_4denvar case.  I'm surprised that the regional GSI cases do not use `rstprod` data.  I assume the operational regional systems used `rstprod` data.   

@ShunLiu-NOAA and @hu5970 , would you please check the files in CASES/regtest` to ensure all files are properly labeled.  All `rstprod` data must belong to the `rstprod` group with appropriate permission restrictions.  Thanks.

**Comment by TingLei-NOAA** [comment]
On wcoss2,  hafs 3d/4d regression tests failed as expected while all other tests passed.

**Review by yonghuiweng — APPROVED** [review]

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA , if you routinely use Orion or Hercules you should request `rstprod` access. A similar suggestion applies to @JingCheng-NOAA who faced the same problem in GSI PR #698.
> 
> Here's a blurb about [Restricted Data access](https://oriondocs.rdhpcs.noaa.gov/wiki/index.php?title=Protecting_Restricted_Data) on Orion
> 
> > Restricted data (rstprod) is allowed on the MSU-HPC system. Be sure to follow all of NOAA's restricted data policies when using MSU-HPC.
> > Request access via AIM (https://aim.rdhpcs.noaa.gov/) > Request access to a new project > rstprod.
> > Provide the following information in your justification:
> > The machine(s) where you will need rstprod access on (i.e. Hercules, Orion).
> > The project(s) you will be using rstprod data for.
> 
> We can not loosen restrictions on `rstprod` data in the global_4denvar case. I'm surprised that the regional GSI cases do not use `rstprod` data. I assume the operational regional systems used `rstprod` data.
> 
> @ShunLiu-NOAA and @hu5970 , would you please check the files in CASES/regtest`to ensure all files are properly labeled. All`rstprod`data must belong to the`rstprod` group with appropriate permission restrictions. Thanks.

Hi, @RussTreadon-NOAA , we already have the rstprod access in the AIM system for Hera/Jet etc, so we cannot choose it again. Do you have any clue who should we contact in this case?

**Comment by RussTreadon-NOAA** [comment]
I would contact your task lead(s) and have them contact your federal oversight manager(s).

**Comment by RussTreadon-NOAA** [comment]
According to `groups` you both belong to the `hurricane` project.
```
Orion-login-3:~$ groups xulu
xulu : noaa-hpc stmp aoml-hafs1 aoml-hafsda hurricane hwrf
Orion-login-3:~$ groups jcheng
jcheng : noaa-hpc hurricane hwrf da-cpu da
```
According to the AIM [View a list of projects](https://aim.rdhpcs.noaa.gov/cgi-bin/project.pl) link, Vijay Tallapragada is the portfolio manager and PI for the `hurricane` project.

**Comment by JingCheng-NOAA** [comment]
Thank you Russ!

**Review by ShunLiu-NOAA — APPROVED** [review]
