### PR TITLE
Fix bug in calculation of Windborne and Saildrone Obs Errors

### LINKED ISSUE #900: Fix obs errors for Windborne and Saildrones.
Following on from #849.  There are a couple of bugs with the error assignments due to issues with unit mismatches.  This applies to 'read_gsb.f90` and `read_saildrones.f90`.

The first issue is for pressure.   `Prepbufr` uses the `POB` local descriptor which is in `mb`, while the saildrone and windborne dump files use `PRLC` which is in `Pa`.   `prepobs_errtable.global` also uses `mb`.  So in copying the vertical interpolation code for the observation error from `read_prepbufr.f90` we need to divide the observation pressure by 100.   In effect, right now the surface observation error is being assigned to the whole profile.

The second issue is that the values in humidity column in `prepobs_errtable.global` are divided by ten in `read_prepbufr.f90`

```
                 qoe=obserr(2,k)*one_tenth*errout
```

I am not sure why we do this.  But for consistency, we will add the same scaling to `read_gsb.f90` and `read_saildrones.f90`.  Right now the humidity errors are ten times higher than expected.

### PR DESCRIPTION
**Pull request by ADCollard**
This addresses the issues with the specification of obs errors for saildrone and windborne noted in #900.

Resolves #900 

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

Run in v16.3.26 configuration.  Obserrors are correct for Windborne, Saildrone.
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

File: src/gsi/read_gsb.f90 [hunk 1]
```diff
@@ -459,7 +459,7 @@ subroutine read_gsb(nread,ndata,nodata,infile,obstype,lunout,gstime,twindin,sis,
            obsdat(1,1) > zero .AND. obsdat(1,1) < 1.4e5_r_kind) then
 
            ! Assign obs error from error table
-           ppb=obsdat(1,1)
+           ppb=obsdat(1,1)/r100
```
Comment (emilyhcliu) [inline src/gsi/read_gsb.f90:462]: Does this change the unit of observation pressure to get the pressure obs error from the error table? 

So, the unit of ppb (to be consistent with the error table) is hPa? I guess.

Comment (emilyhcliu) [reply src/gsi/read_gsb.f90:462]: Does this change the assimilation result?

Comment (ADCollard) [reply src/gsi/read_gsb.f90:462]: > Does this change the unit of observation pressure to get the pressure obs error from the error table?
> 
> So, the unit of ppb is hPa? I guess.

@emilyhcliu Prepbufr uses the POB local descriptor which is in mb, while the saildrone and windborne dump files use PRLC which is in Pa. prepobs_errtable.global also uses mb. So in copying the vertical interpolation code for the observation error from read_prepbufr.f90 we need to divide the observation pressure by 100. In effect, right now the surface observation error is being assigned to the whole profile.

Comment (ADCollard) [reply src/gsi/read_gsb.f90:462]: > Does this change the assimilation result?

Yes it does.   The develop version is currently inconsistent with GFSv16.3.26.

Comment (emilyhcliu) [reply src/gsi/read_gsb.f90:462]: OK.  Got it.  It has to be fixed anyway. Good catch!

**Review by emilyhcliu — APPROVED** [review]

File: src/gsi/read_gsb.f90 (hunk 1 above)
Comment (ADCollard) [reply src/gsi/read_gsb.f90:462]: @emilyhcliu Thank you!

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 Ctests**

Install `ADCollard:develop` at 99e68800 and `develop` at dba718e25 on Cactus. Run ctests with the following results
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr923/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  1156.20 sec
2/6 Test #6: global_enkf ......................   Passed  1528.09 sec
3/6 Test #5: hafs_3denvar_hybens ..............   Passed  1585.76 sec
4/6 Test #2: rtma .............................   Passed  1759.11 sec
5/6 Test #4: hafs_4denvar_glbens ..............   Passed  1887.88 sec
6/6 Test #1: global_4denvar ...................   Passed  1924.64 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1924.78 sec
```

All tests _Passed_.

**Comment by RussTreadon-NOAA** [comment]
**Gaea C6 Ctests**

Install `ADCollard:develop` at 99e68800 and `develop` at dba718e25 on Gaea C6. Run ctests with the following results
```
Test project /gpfs/f6/ira-sti/scratch/Russ.Treadon/git/gsi/pr923/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  484.44 sec
2/6 Test #6: global_enkf ......................   Passed  486.31 sec
3/6 Test #2: rtma .............................   Passed  728.63 sec
4/6 Test #5: hafs_3denvar_hybens ..............   Passed  847.87 sec
5/6 Test #4: hafs_4denvar_glbens ..............   Passed  970.12 sec
6/6 Test #1: global_4denvar ...................   Passed  1264.40 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1264.43 sec
```
All tests _Passed_.

**Review by RussTreadon-NOAA — APPROVED** [review]
GSI ctests pass on WCOSS2 (Cactus) and Gaea C6.  

Confirm `read_gsb.f90` and `read_saildrone.f90` in Cactus `/lfs/h1/ops/prod/packages/gfs.v16.3.26/sorc/global_gsi.fd` are identical to the same named source code files in this PR.
```
russ.treadon@clogin06:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr923/src/gsi> diff /lfs/h1/ops/prod/packages/gfs.v16.3.26/sorc/global_gsi.fd/read_gsb.f90 ./read_gsb.f90 
russ.treadon@clogin06:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr923/src/gsi> diff /lfs/h1/ops/prod/packages/gfs.v16.3.26/sorc/global_gsi.fd/read_saildrone.f90 ./read_saildrone.f90 
```

Approve.

**Review by nicholasesposito — APPROVED** [review]
Looks good. Thanks!

File: src/gsi/setupbend.f90
Comment (ShunLiu-NOAA) [inline src/gsi/setupbend.f90:1]: Is it the expected change for this PR

**Review by XuanliLi-NOAA — APPROVED** [review]
The change in setupbend looks good. Approve.

File: src/gsi/setupbend.f90
Comment (RussTreadon-NOAA) [reply src/gsi/setupbend.f90:1]: Good question @ShunLiu-NOAA .  This write statement was added during GFS v17 optimization.  The line is in gfs.v16.3.26 and generates about 2200 lines of output per GDAS run and 1400 lines per GFS run.  We want to remove this extraneous output from GFS v17.  Hence @ADCollard 's change to `src/gsi/setupbend.f90`.

Comment (ADCollard) [reply src/gsi/setupbend.f90:1]: What @RussTreadon-NOAA said.   The suggested change came from @XuanliLi-NOAA
