### PR TITLE
Fix for runtime failure when disabling thinning for ATMS and bufrtovs data (Issue #917)

### LINKED ISSUE #917: GSI aborts when processing atms data WITHOUT thinning
During the single-cycle test, gsi.x stops after printing out the following lines:

_read_atms: max number of obs in any bin        278
read_atms: number of bins with any obs      11230
read_atms: max number of obs in any bin        304
read_atms: number of bins with any obs      11370
CAL_TZTR compute   0.00000      0.370146       0.00000      0.569009       0.00000       0.00000      0.314928     -0.115137       0.00000       10.8163      0.150000E-04   1.85082      RESET tztr to 0.5 .or. 1.5_

and the stderr output shows:

h14c20:183904:0:183904] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))nil))
         backtrace (tid:1645044)
 0 0x0000000000053519 ucs_debug_print_backtrace()  ???:0
 1 0x0000000000012990 __funlockfile()  :0
 2 0x00000000005b30d6 grdcrd1_()  /scratch3/NCEPDEV/da/Xuanli.Li/git/global-workflow_v17/global-workflow/sorc/gsi_enkf.fd/src/gsi/grdcrd.f90:119
 3 0x0000000000baf6bc satthin_mp_binit_()  /scratch3/NCEPDEV/da/Xuanli.Li/git/global-workflow_v17/global-workflow/sorc/gsi_enkf.fd/src/gsi/satthin.F90:1246
 4 0x00000000013ae389 read_atms_()  /scratch3/NCEPDEV/da/Xuanli.Li/git/global-workflow_v17/global-workflow/sorc/gsi_enkf.fd/src/gsi/read_atms.f90:586
 5 0x0000000000966b46 read_obsmod_mp_read_obs_()  /scratch3/NCEPDEV/da/Xuanli.Li/git/global-workflow_v17/global-workflow/sorc/gsi_enkf.fd/src/gsi/read_obs.F90:1767
 6 0x0000000000875c0f observermod_mp_set__()  /scratch3/NCEPDEV/da/Xuanli.Li/git/global-workflow_v17/global-workflow/sorc/gsi_enkf.fd/src/gsi/observer.F90:329
 7 0x0000000001091793 glbsoi_()  /scratch3/NCEPDEV/da/Xuanli.Li/git/global-workflow_v17/global-workflow/sorc/gsi_enkf.fd/src/gsi/glbsoi.f90:221
 8 0x000000000069664f gsisub_()  /scratch3/NCEPDEV/da/Xuanli.Li/git/global-workflow_v17/global-workflow/sorc/gsi_enkf.fd/src/gsi/gsisub.F90:200
 9 0x000000000041548d gsimod_mp_gsimain_run_()  /scratch3/NCEPDEV/da/Xuanli.Li/git/global-workflow_v17/global-workflow/sorc/gsi_enkf.fd/src/gsi/gsimod.F90:2459
10 0x00000000004153cf MAIN__()  /scratch3/NCEPDEV/da/Xuanli.Li/git/global-workflow_v17/global-workflow/sorc/gsi_enkf.fd/src/gsi/gsimain.f90:633
11 0x000000000041536d main()  ???:0
12 0x000000000003a7e5 __libc_start_main()  ???:0
13 0x000000000041528e _start()  ???:0

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libpthread-2.28.s  0000154DA2046990  Unknown               Unknown  Unknown
gsi.x              00000000005B30D6  grdcrd1_                  119  grdcrd.f90
gsi.x              0000000000BAF6BC  satthin_mp_binit_        1246  satthin.F90
gsi.x              00000000013AE389  read_atms_                586  read_atms.f90
gsi.x              0000000000966B46  read_obsmod_mp_re        1767  read_obs.F90
gsi.x              0000000000875C0F  observermod_mp_se         329  observer.F90
gsi.x              0000000001091793  glbsoi_                   221  glbsoi.f90
gsi.x              000000000069664F  gsisub_                   200  gsisub.F90
gsi.x              000000000041548D  gsimod_mp_gsimain        2459  gsimod.F90
gsi.x              00000000004153CF  MAIN__                    633  gsimain.f90
gsi.x              000000000041536D  Unknown               Unknown  Unknown
libc-2.28.so       0000154DA1C977E5  __libc_start_main     Unknown  Unknown
gsi.x              000000000041528E  Unknown               Unknown  Unknown
srun: error: h19c19: task 147: Exited with exit code 174

### PR DESCRIPTION
**Pull request by dkokron**
**Description**
This PR resolves issue 917 which revolves around a runtime failure when observation thinning is disabled for ATMS and BUFRTOVS data types.

Resolves #917 

**Type of change**

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
I ran a GSI case on acorn with and without thinning of all ATMS and BUFRTOVS data types (see list below).  No runtime failures were encountered.

atms_npp
atms_n20
atms_n21
amsua_metop-c
amsua_n18
amsua_n15
amsua_n19
amsua_metop-b
mhs_n19
mhs_n19
mhs_metop-b
mhs_metop-b
mhs_metop-c
mhs_metop-c
amsua_metop-b
amsua_n19
amsua_n18
amsua_metop-c

I also ran the GSI regression suite to compare with a stock develop branch (16c19a2bc).  All tests passed.

Test project /lfs/h1/hpc/support/daniel.kokron/Projects/GSI/GFSv17/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  727.85 sec
2/6 Test #2: rtma .............................   Passed  969.81 sec
3/6 Test #4: hafs_4denvar_glbens ..............   Passed  1215.07 sec
4/6 Test #5: hafs_3denvar_hybens ..............   Passed  1215.45 sec
5/6 Test #6: global_enkf ......................   Passed  1340.34 sec
6/6 Test #1: global_4denvar ...................   Passed  1853.49 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1853.50 sec
  
**Checklist**

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] New and existing tests pass with my changes
- [X] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 ctests**

Install `dkokron:dkokron/GFSv17_Thinning` at c530f48b as _updat_ and `develop` at 16c19a2bc as _contrl_.  Run ctests with following results
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr920/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  2775.94 sec
2/6 Test #6: global_enkf ......................   Passed  2850.21 sec
3/6 Test #5: hafs_3denvar_hybens ..............   Passed  4118.80 sec
4/6 Test #4: hafs_4denvar_glbens ..............   Passed  4373.57 sec
5/6 Test #2: rtma .............................   Passed  4398.97 sec
6/6 Test #1: global_4denvar ...................   Passed  5047.55 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 5047.57 sec
```

**Comment by dkokron** [comment]
That difference in performance between acorn and cactus is troubling.

**Comment by RussTreadon-NOAA** [comment]
Yesterday's (8/26) inflated GSI ctest run times are not reflected in the `gsi.x` or `enkf.x` wall times.   

For example, while ctest rrfs_3denvar_rdasens took 2775.94 sec to complete, the sum of the `gsi.x` wall times across all four jobs represents a small fraction of the 2775.94 seconds.
```
rrfs_3denvar_rdasens_hiproc_contrl/stdout:The total amount of wall time                        = 119.290528
rrfs_3denvar_rdasens_hiproc_updat/stdout:The total amount of wall time                        = 196.437235
rrfs_3denvar_rdasens_loproc_contrl/stdout:The total amount of wall time                        = 118.266161
rrfs_3denvar_rdasens_loproc_updat/stdout:The total amount of wall time                        = 120.470909
``` 
After the four jobs complete the ctest runs a script to check results.  These checks include grepping values of files as well as comparing binary files.  These checks run serially on the login node from which the ctests was launched.  Perhaps the login node used for yesterdays ctests had a high load due to many currently running processes.  

A rerun of the ctests today (8/27) returned
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr920/build
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 6: global_enkf
    Start 1: global_4denvar
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  731.86 sec
2/6 Test #6: global_enkf ......................   Passed  919.74 sec
3/6 Test #2: rtma .............................   Passed  1097.85 sec
4/6 Test #5: hafs_3denvar_hybens ..............   Passed  1233.79 sec
5/6 Test #4: hafs_4denvar_glbens ..............   Passed  1530.94 sec
6/6 Test #1: global_4denvar ...................   Passed  1925.37 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1925.59 sec
```

These Cactus ctest timings are more consistent with what has been observed in other PRs.  The `gsi.x` wall times from today's run rrfs_3denvar_rdasens are lower than yesterday's timings
```
rrfs_3denvar_rdasens_hiproc_contrl/stdout:The total amount of wall time                        = 112.726138
rrfs_3denvar_rdasens_hiproc_updat/stdout:The total amount of wall time                        = 111.482869
rrfs_3denvar_rdasens_loproc_contrl/stdout:The total amount of wall time                        = 96.726984
rrfs_3denvar_rdasens_loproc_updat/stdout:The total amount of wall time                        = 106.387943
```

File: src/gsi/read_atms.f90 [hunk 1]
```diff
@@ -195,7 +195,7 @@ subroutine read_atms(mype,val_tovs,ithin,isfcalc,&
   real(r_kind)    :: ptime,timeinflat,crit0,score
   integer(i_kind) :: ithin_time,n_tbin
   integer(i_kind),pointer :: it_mesh => null()
-  integer(kind=4) :: good,bin,bin2,Obindx,maxPerBin,numBinsWithObs
+  integer(kind=4) :: good,bin,bin2,Obindx,maxPerBin,numBinsWithObs,numobs
```
Comment (RussTreadon-NOAA) [inline src/gsi/read_atms.f90]: Didn't notice this before.  We prefer to **not** use a number to specify the variable `kind`.  

`src/gsi/kinds.F90` has parameter
```
i_long    - specification kind for long (4-byte) integer variable
```
Can we replace `integer(kind=4)` with `integer(kind=i_long)`?  Doing so requires adding `i_long` to the `use kinds` statement on line 75.

File: src/gsi/read_atms.f90 [hunk 2]
```diff
@@ -582,30 +583,42 @@ subroutine read_atms(mype,val_tovs,ithin,isfcalc,&
...
 
+  ! Map between physical bin index and Packed index
   allocate(hash(itxmax))
   hash=0
   do bin = 1,numBinsWithObs
     hash(binsWithObs(bin)) = bin
   enddo
 
+  !write(6,'("read_atms: numobs passing first scan" I10)') numobs
+  !write(6,'("read_atms: itx_all " I10)') itx_all
```
Comment (RussTreadon-NOAA) [inline src/gsi/read_atms.f90]: Are lines 608 and 609 for debugging / testing?  If we no longer need these lines, we can remove them unless we think we have need of them in the future.

File: src/gsi/read_atms.f90 [hunk 3]
```diff
@@ -655,14 +668,20 @@ subroutine read_atms(mype,val_tovs,ithin,isfcalc,&
...
-!    Map obs to thinning grid
-     call binit(dlat_earth*deg2rad,dlon_earth*deg2rad,itx2,it_mesh)
+!    Map obs to thinning grid or return immediately if ithin<=0
+     call binit(dlat_earth*deg2rad,dlon_earth*deg2rad,itx2,ithin,sis,it_mesh)
      binCount(itx2) = binCount(itx2)+1
      binObs(binCount(itx2),hash(itx2)) = iob
   end do ObsLoop2
   deallocate(hash)
+  !numobs=sum(binCount)
+  !write(6,'("read_atms: numobs passing second scan" I10)') numobs
```
Comment (RussTreadon-NOAA) [inline src/gsi/read_atms.f90]: Similar comment / question as for lines 608 and 609.

File: src/gsi/satthin.F90 [hunk 4]
```diff
@@ -1142,13 +1142,15 @@ subroutine map2tgrid2(dlat_earth,dlon_earth,dist1,crit1,itx,ithin,itt,iuse,sis,
        iuse=.true.
        itt=1
        dist1=one
+       !$omp critical
```
Comment (RussTreadon-NOAA) [inline src/gsi/satthin.F90:1147]: Curious:  Why do we place this `if-then-else` block inside an omp directive?

**Review by RussTreadon-NOAA — COMMENTED** [review]
Minor comments.  Looks good.  Most importantly we can process radiance data without thinning with these changes.

**Review by ADCollard — APPROVED** [review]
Looks good to me apart from the minor issues highlighted by Russ.  Thanks, @dkokron

**Comment by RussTreadon-NOAA** [comment]
@XuanliLi-NOAA , when you have time would you please review this PR.  This PR resolves the problem you reported in issue #917

**Review by XuanliLi-NOAA — APPROVED** [review]
Changes look good. Approve.

**Comment by RussTreadon-NOAA** [comment]
@dkokron :  This PR  has been peer reviewed and approved.  I have a few comments / questions.  This PR can move forward once these conversations are resolved.

**Comment by dkokron** [comment]
I will review and answer by late next week.

**Comment by dkokron** [comment]
I updated read_atms.f90 and satthin.F90 to address comments from @RussTreadon-NOAA.  Regression tests all pass.

```
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  727.87 sec
2/6 Test #2: rtma .............................   Passed  1029.67 sec
3/6 Test #5: hafs_3denvar_hybens ..............   Passed  1214.13 sec
4/6 Test #4: hafs_4denvar_glbens ..............   Passed  1274.22 sec
5/6 Test #6: global_enkf ......................   Passed  1326.31 sec
6/6 Test #1: global_4denvar ...................   Passed  1852.66 sec
```

**Comment by dkokron** [comment]
Do I need to do anything further in order to move this PR along?

File: src/gsi/read_atms.f90 (hunk 1 above)
Comment (RussTreadon-NOAA) [reply src/gsi/read_atms.f90]: Resolved by [bef4ece](https://github.com/NOAA-EMC/GSI/pull/920/commits/bef4ececc7b6190f18ac7c16611997f2bdc99028)

File: src/gsi/read_atms.f90 (hunk 2 above)
Comment (RussTreadon-NOAA) [reply src/gsi/read_atms.f90]: Resolved by [bef4ece](https://github.com/NOAA-EMC/GSI/pull/920/commits/bef4ececc7b6190f18ac7c16611997f2bdc99028)

File: src/gsi/read_atms.f90 (hunk 3 above)
Comment (RussTreadon-NOAA) [reply src/gsi/read_atms.f90]: Resolved by [bef4ece](https://github.com/NOAA-EMC/GSI/pull/920/commits/bef4ececc7b6190f18ac7c16611997f2bdc99028)

File: src/gsi/satthin.F90 (hunk 4 above)
Comment (RussTreadon-NOAA) [reply src/gsi/satthin.F90:1147]: Resolved by [bef4ece](https://github.com/NOAA-EMC/GSI/pull/920/commits/bef4ececc7b6190f18ac7c16611997f2bdc99028)

**Comment by RussTreadon-NOAA** [comment]
@dkokron:  The developer resolves reviewer conversations as (s)he responds to the reviewer comments.  I didn't see resolutions so I didn't act.  I now see that you addressed my comments.  I went ahead and noted this in the review comments.  After this I resolved the conversations.  Did you run ctests on Acorn or Cactus?

**Comment by dkokron** [comment]
I ran ctests on acorn.

**Comment by RussTreadon-NOAA** [comment]
OK.  Acorn ctests are useful but operations runs on WCOSS2.  I'll run the ctests on Cactus.

**Comment by RussTreadon-NOAA** [comment]
@dkokron , Cactus ctests found differences in the analysis results.  I checked and see that [`dkokron:dkokron/GFSv17_Thinning`](https://github.com/dkokron/GSI/tree/dkokron/GFSv17_Thinning) is [six commits behind](https://github.com/dkokron/GSI/compare/dkokron/GFSv17_Thinning...NOAA-EMC%3AGSI%3Adevelop) the head of `NOAA-EMC:develop`.  Your Acorn test was likely using an old `develop`.

Please update `dkokron:dkokron/GFSv17_Thinning` up to the current head of `NOAA-EMC:develop`

**Comment by dkokron** [comment]
I merged with develop and reran the GSI case with unthinned ATMS and BUFRTOVS as well as ctests on acorn.  No issues encountered.

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 ctests**

Install `dkokron:dkokron/GFSv17_Thinning` at 4a688ee8 as _updat_ and `NOAA-EMC:develop` at 731859c60 as _contrl_ on Cactus.  Run GSI ctests with the following results
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr920/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  731.68 sec
2/6 Test #6: global_enkf ......................   Passed  918.60 sec
3/6 Test #2: rtma .............................   Passed  1221.84 sec
4/6 Test #5: hafs_3denvar_hybens ..............   Passed  1291.50 sec
5/6 Test #4: hafs_4denvar_glbens ..............   Passed  1463.18 sec
6/6 Test #1: global_4denvar ...................   Passed  1924.52 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1924.67 sec
```

**Hera ctests**

Repeat the WCOSS2 installation on Hera.  Run ctests with the following results
```
Test project /scratch3/NCEPDEV/da/Russ.Treadon/git/gsi/pr920/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_rdasens
    Start 4: hafs_4denvar_glbens
    Start 5: hafs_3denvar_hybens
    Start 6: global_enkf
1/6 Test #3: rrfs_3denvar_rdasens .............   Passed  490.26 sec
2/6 Test #6: global_enkf ......................   Passed  730.83 sec
3/6 Test #2: rtma .............................   Passed  1090.35 sec
4/6 Test #5: hafs_3denvar_hybens ..............   Passed  1094.33 sec
5/6 Test #4: hafs_4denvar_glbens ..............   Passed  1153.17 sec
6/6 Test #1: global_4denvar ...................   Passed  1564.13 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1564.16 sec
```

All ctests _Passed_ on WCOSS2 (Cactus) and Hera.

**Review by RussTreadon-NOAA — APPROVED** [review]
Ctests pass on Cactus and Hera.

Approve.
