### PR TITLE
Issue with global mean weight for multiscale ensemble runs for ig > 1 plus changes to make code work for multiscale (bugs introduced in trunk).

### LINKED ISSUE #569: Issues with weights in multiscale ensemble analysis
While making some optimization changes to the multiscale ensemble analysis, an error in the weights was noticed.  For the global mean (0,ig) weights, all of the values were set to the default of 1.0.  Apparently the correct code was lost in the process of incorporating code into the GSI.  The values should be 1.0 for ig=1 and 0.0 for all other values of ig.

The values were updated for the global mean in the init_mult_spc_wgts routine (apply_scaledepwgts.f90).  Some other minor changes to this routine were done including setting proper variable type for constants, removing unnecessary arrays, using logical rather than 1 and 0.  Also noted was a line that said spc_multwgt=max(spc_multwgt,0.0_r_kind).    This max was moved inside the i and ig loops and a min included to ensure that the weight is not greater than one.  Finally, a message is printed out if rtem2 < 0. and spc_multwgt(i,2) is set to zero.

The code is being put into my multiscalebug branch.

Tests on the values of spc_multwgt are being performed.  Identical results are produced for the spc_multwgt values except for the global mean (0,ig>1).

### PR DESCRIPTION
**Pull request by jderber-NOAA**
**Description**

While looking to optimize the use of multiscale ensembles, it was noted that the global mean wgt was not changed from the default (1.0) for all values of ig.  The sum of the weights over all ig should be equal to 1 for the case being used.  It was found that for all ig =1 the value of the weight should remain 1., but for all ig > 1 the value should be equal to zero.  The original OU code had this in it.  Somehow when being put into the GSI, the code doing this was removed.  

Tests using the multiscale ensemble are starting and this needs to be fixed.  

The only routine changed was init_mult_spc_wgts in apply_scaledepwgts.

Also, some cleanup of the routine in which the weights are set was included (e.g., 0 used for real zero, unused arrays removed, etc.)

When change was updated to the head of the trunk, two additional issues were found.  The multiscale ensemble  no longer worked and the regression test for the netcdf_fv3_regional no longer scaled between the low processor count and the high processor count.  Both of these errors are present in the head of the trunk, not just in this branch. 

The source of these two additional issues were found by running in debug mode and adding a lot of print statements.  The solution to make it run the multiscale ensemble required a change to state_vectors.f90.  Note a few small changes were also found to get the code to run completely in debug mode.  To remove the processor scaling issue, a code section was removed from a later loop where it was put by the previous change (by me, sorry) and put in it's previous location before the cloud liquid water calculation in setuprad.f90.

After the previous two changes, the multiscale ensemble and the regression tests worked properly.

 Fixes #569

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

Weights produced by this routine were printed and only the global mean values for ig >1 were changed.

Regression tests were run.  No differences were found (but I don't think any regression tests change the one routine changed by this update).

Results were compared to optimization tests (which also had this change, but a lot more) to ensure the results were similar (expected round off differences).

All tests were performed on Hera

  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

**DUE DATE for this PR is 6/16/2023.** If this PR is not merged into `develop` by this date, the PR will be closed and returned to the developer.

### CODE REVIEW

File: src/gsi/apply_scaledepwgts.f90 [hunk 1]
```diff
@@ -59,53 +59,57 @@ subroutine init_mult_spc_wgts(jcap_in)
...
   real(r_kind) rwv0,rtem1,rtem2
   real (r_kind):: fwgtofwvlen
-  integer(i_kind) :: l_sum_spc_weights
+  real(r_kind) :: totwvlength
+  logical :: l_sum_spc_weights
 
   ! Spectral scale decomposition is differernt between SDL-cross and SDL-nocross
   if( r_ensloccov4scl < tiny_r_kind )then
-     l_sum_spc_weights = 1
+     l_sum_spc_weights = .false.
```
Comment (TingLei-NOAA) [inline src/gsi/apply_scaledepwgts.f90:65]: @jderber-NOAA  l_sum_spc_weights is supposed to indicate two options: =1, required the summation of their squared values =1;  when =0, required   the summation of the values of themselves =1 .   Will there be any benefits to change to the current false/true form?

File: src/gsi/apply_scaledepwgts.f90 [hunk 2]
```diff
@@ -59,53 +59,57 @@ subroutine init_mult_spc_wgts(jcap_in)
...
   else
-     l_sum_spc_weights = 0
+     l_sum_spc_weights = .true.
   end if
 
-  allocate(totwvlength(jcap_in))
+  spc_multwgt(0,1)=one
+  do ig=2,nsclgrp
+    spc_multwgt(0,ig)=zero
+  end do
```
Comment (TingLei-NOAA) [inline src/gsi/apply_scaledepwgts.f90:73]: Again, Thanks for identifying this "tiny" while important bug introduced in various developing stages.

Comment (jderber-NOAA) [reply src/gsi/apply_scaledepwgts.f90:73]: Your welcome.  Like to be useful.

**Comment by shoyokota** [comment]
@jderber-NOAA Thank you for creating this PR. This code fix looks good to me, but I'm not familiar with how to run the global DA test using this option. Could you share the result of your test (before and after this fix)? I expect the difference of the analysis increment is small unless global mean of ensemble perturbations is large. I'd like to approve this PR once I confirm if the difference is reasonable.

File: src/gsi/apply_scaledepwgts.f90 (hunk 1 above)
Comment (jderber-NOAA) [reply src/gsi/apply_scaledepwgts.f90:65]: Looks like my earlier reply was lost.  Probably forgot to hit  the comment button.

For things that only have two options, it is probably better to have true/false with one being the default and one being the option.  When you use true/false only 1 bit is used.  Also, we can avoid the use of "xxxx == 0" (or ==1) in if statements a bit more efficient. May be good to change the name of the true option to be something like "Use_nonsquared_weight" or something like that.

**Comment by jderber-NOAA** [comment]
Sho,

Cannot seem to reply to your comment.

The results of my experiment and control are in
/scratch1/NCEPDEV/stmp2/John.Derber/tmp766/optimize.gfs.bugfix1.2021112906
and
/scratch1/NCEPDEV/stmp2/John.Derber/tmp766/optimize.gfs.bugfixcon.2021112906
for the control.

In the stdout there was a print statement added which prints out the weights for each wavenumber.  In the control, it is printed twice.  

If you want anything else, let me know.

John

File: src/gsi/apply_scaledepwgts.f90 (hunk 1 above)
Comment (TingLei-NOAA) [reply src/gsi/apply_scaledepwgts.f90:65]: @jderber-NOAA  Thanks for the explanation. Though I don't totally agree with this change, it seems more about the "style" . So, I would go ahead to approve this PR. 
Thanks.

**Review by TingLei-NOAA — DISMISSED** [review]
Approved. Thanks!

**Comment by shoyokota** [comment]
@jderber-NOAA Thank you, but I don't have Hera account. Is it possible to draw the analysis increment of your experiment and control and show it to us? Or, could you copy the data to Orion?

**Comment by jderber-NOAA** [comment]
Sho,

I agree it would be good to have a comparison of the difference between the results.  Unfortunately, I can no longer access Orion and I don't have the skill to produce analysis differences.  When I look at the output, the fit to the obs. looks pretty close.  However, that does not mean the analysis is similar everywhere.

I have been trying to come up with a good solution.

1. You could add a copy of this routine to your code on Orion and rerun the control and experiment and then look at the differences.  A bit more work for you (sorry), but maybe the simplest solution.  Also, would probably test a different configuration than what I was using (My configuration was probably not the best).
2. With someone else's help (maybe Ting), he/she could transfer the output to Orion and then you could compare the results.
3. I could find someone (maybe Ting again) that could help produce difference maps.

What do you think?

**Comment by TingLei-NOAA** [comment]
@shoyokota  as you know , I have no access to orion too:) .   
And, I think the right one has been used  from the global SDL implementation  at EMC and later application and possible further development at OU .   The bug is only introduced through recent PRs.   So, more details on the impact of the bug may be of some marginal benefits (and, sure, it is definitely interesting out of curiosity).    
If you need, I can plot some difference map as John mentioned. 
Anyway, please let me know how I can help!

**Comment by shoyokota** [comment]
@jderber-NOAA Thank you. I don't have the skill to run the global DA test, so your option 1 is difficult for me. If it is difficult to draw the analysis increments soon, could you upload only the log file here? I'd just like to confirm if the impact of this PR is small. I may confirm it possibly from the difference between two log files.

**Comment by jderber-NOAA** [comment]
>  CONTROL
<  EXPERIMENT
< Initial gradient norm =  4.450210758778163836E+03
< cost,grad,step,b,step? =   1   0  1.257323161233956460E+06  4.450210758778163836E+03  1.058485572054012502E+00  0.000000000000000000E+00  good 
< cost,grad,step,b,step? =   1   1  1.222715546486796811E+06  2.552277717438277250E+03  2.678051317465482306E+00  3.397148639747650245E-01  good 
< cost,grad,step,b,step? =   1   2  1.192968911885651760E+06  3.395306760945491078E+03  2.628611692141982203E+00  1.796640383476928005E+00  good 
< cost,grad,step,b,step? =   1   3  1.140503532574499724E+06  1.930527947311911930E+03  1.290485459821706371E+00  7.213370134320454818E-01  good 
< cost,grad,step,b,step? =   1   4  1.121918605993145145E+06  2.272322959408096722E+03  1.993086292015797900E+00  4.531137680717529648E-01  good 
< cost,grad,step,b,step? =   1   5  1.108909554159975145E+06  2.306956110940243434E+03  2.471444906739815206E+00  1.403344181956563741E+00  good 
< cost,grad,step,b,step? =   1   6  1.086269848739590729E+06  2.909491446129691212E+03  1.547856632186894510E+00  1.520860286427905272E+00  good 
< cost,grad,step,b,step? =   1   7  1.064702789064741693E+06  1.639972981967810711E+03  1.619196402247006228E+00  4.167321896498363265E-01  good 
< cost,grad,step,b,step? =   1   8  1.055298664228024660E+06  1.658330645390544532E+03  2.442364807713848673E+00  7.071976044215833035E-01  good 
< cost,grad,step,b,step? =   1   9  1.045265339246997959E+06  1.205201831965701786E+03  1.962414639173522435E+00  1.591801645447375124E+00  good 
< cost,grad,step,b,step? =   1  10  1.032431424471882870E+06  1.523544156927913491E+03  1.701757597506178499E+00  7.975473141357187767E-01  good 
< cost,grad,step,b,step? =   1  11  1.023553972256532405E+06  1.237647755947131373E+03  2.236124984276380179E+00  6.347531406060602510E-01  good 
< cost,grad,step,b,step? =   1  12  1.016149188385405461E+06  1.449631973469283139E+03  2.873465986717774534E+00  1.286524507032389852E+00  good 
< cost,grad,step,b,step? =   1  13  1.003906778418824193E+06  9.975015804000722710E+02  1.476460867842254832E+00  1.425197793837185145E+00  good 
< cost,grad,step,b,step? =   1  14  9.949398425887004705E+05  1.262877412937372810E+03  1.635885093980593341E+00  4.740453401747419249E-01  good 
< cost,grad,step,b,step? =   1  15  9.902309847552671563E+05  9.548701961482074694E+02  2.615158292150411956E+00  7.638167757097293897E-01  good 
< cost,grad,step,b,step? =   1  16  9.844799485210999846E+05  1.168681188717830082E+03  2.254685140532664889E+00  1.356926267007854792E+00  good 
< cost,grad,step,b,step? =   1  17  9.777505298089943826E+05  1.058929870469316711E+03  2.329716565632362180E+00  7.282880264388370550E-01  good 
< cost,grad,step,b,step? =   1  18  9.726871487156703370E+05  9.748082162199533514E+02  1.967265146206877091E+00  1.071973380411701982E+00  good 
< cost,grad,step,b,step? =   1  19  9.681033506903267698E+05  8.398006147187858232E+02  1.861285955818986482E+00  8.197407786456669676E-01  good 
< cost,grad,step,b,step? =   1  20  9.645472175876522670E+05  9.678065076432105798E+02  2.421703313199267793E+00  9.538159828378240945E-01  good 
< cost,grad,step,b,step? =   1  21  9.601333836914328858E+05  7.998247749497207906E+02  1.925757169151222969E+00  1.350160037440411243E+00  good 
< cost,grad,step,b,step? =   1  22  9.553943275000712601E+05  7.904102217154211303E+02  1.460813929388866006E+00  6.000008428851631992E-01  good 
< cost,grad,step,b,step? =   1  23  9.532370001817940501E+05  6.862266280890431744E+02  2.580981278563381220E+00  5.682731425627424171E-01  good 
< cost,grad,step,b,step? =   1  24  9.510704949570911704E+05  7.111609195467749487E+02  2.155427158455529568E+00  1.776706747397963859E+00  good 
< cost,grad,step,b,step? =   1  25  9.478557756435426418E+05  7.167408686061775143E+02  1.693093925135446209E+00  8.584488229362144951E-01  good 
< cost,grad,step,b,step? =   1  26  9.456881506837906782E+05  7.906003619180879696E+02  2.387993446359116145E+00  7.517967135339882478E-01  good 
< cost,grad,step,b,step? =   1  27  9.433896100201989757E+05  8.366879529329534080E+02  1.542418623370727770E+00  1.300859122087036246E+00  good 
< cost,grad,step,b,step? =   1  28  9.414582447962180013E+05  7.658669147386054874E+02  1.477951771360002775E+00  7.036161911114748868E-01  good 
< cost,grad,step,b,step? =   1  29  9.401555518540567718E+05  5.836135834341441750E+02  2.616979556205421886E+00  6.444542455847321882E-01  good 
< cost,grad,step,b,step? =   1  30  9.386686842464690562E+05  5.662885929420193634E+02  2.306160686714536112E+00  1.486422681718879701E+00  good 
< cost,grad,step,b,step? =   1  31  9.367210684608549345E+05  5.275240475483656155E+02  1.728377654450059309E+00  9.051971390194722966E-01  good 
< cost,grad,step,b,step? =   1  32  9.353998014089495409E+05  5.106399657074961169E+02  2.149813720104121195E+00  6.991898900564350594E-01  good 
< cost,grad,step,b,step? =   1  33  9.342506754250881495E+05  4.627251313119354563E+02  2.411510619407220002E+00  9.980083003651355478E-01  good 
< cost,grad,step,b,step? =   1  34  9.329642119154523825E+05  4.880681410012242054E+02  1.864274889541736480E+00  1.156684543389971287E+00  good 
< cost,grad,step,b,step? =   1  35  9.318137481944989413E+05  4.350338270822873596E+02  1.955362076246300429E+00  7.198647346411611858E-01  good 
< cost,grad,step,b,step? =   1  36  9.309450656019430608E+05  3.907611062182347155E+02  2.106516439225011972E+00  8.573496461240465161E-01  good 
< cost,grad,step,b,step? =   1  37  9.301427046030597994E+05  3.945141233793255537E+02  2.176791871212185203E+00  9.160907924016601367E-01  good 
< cost,grad,step,b,step? =   1  38  9.293831457244803896E+05  3.590238513634507171E+02  2.199613411245953998E+00  9.557894223519992627E-01  good 
< cost,grad,step,b,step? =   1  39  9.286496377067583380E+05  3.948140121648951890E+02  2.200963994714077554E+00  9.861049326505118007E-01  good 
< cost,grad,step,b,step? =   1  40  9.279259043204468908E+05  3.768642522918144664E+02  1.884236069808959746E+00  1.046649041312390560E+00  good 
< cost,grad,step,b,step? =   1  41  9.272774213345533935E+05  3.788963174696284000E+02  1.671141040590245153E+00  7.943980916424882022E-01  good 
< cost,grad,step,b,step? =   1  42  9.268204549758490175E+05  3.788664099908623939E+02  1.769201143257477460E+00  7.838973861735030191E-01  good 
< cost,grad,step,b,step? =   1  43  9.264411587558182655E+05  3.896970290460457136E+02  2.283269627301690807E+00  1.084907736560323910E+00  good 
< cost,grad,step,b,step? =   1  44  9.259100804315247806E+05  3.557514766621319495E+02  1.808271369110343363E+00  1.238066878846545871E+00  good 
< cost,grad,step,b,step? =   1  45  9.253893394487826154E+05  3.101304013637040384E+02  1.795184530882505181E+00  6.657585521227341596E-01  good 
< cost,grad,step,b,step? =   1  46  9.250451577371113235E+05  2.428535270476068604E+02  1.964229807232752423E+00  7.419233945989477386E-01  good 
< cost,grad,step,b,step? =   1  47  9.247657455165408319E+05  2.531123261453812461E+02  2.293896305800501967E+00  1.018070764258638405E+00  good 
< cost,grad,step,b,step? =   1  48  9.244335419393704506E+05  2.491396343780870097E+02  1.810394107746186698E+00  1.234398277813050671E+00  good 
< cost,grad,step,b,step? =   1  49  9.241099043041345431E+05  2.256916686029020127E+02  1.851254064172574321E+00  7.841424187436122351E-01  good 
< cost,grad,step,b,step? =   1  50  9.238503961602860363E+05  2.193010686579649757E+02  2.253761141943128266E+00  7.345825424248191293E-01  good 
---
> Initial gradient norm =  4.453790700564620238E+03
> cost,grad,step,b,step? =   1   0  1.257323161233956460E+06  4.453790700564620238E+03  1.059203247663353054E+00  0.000000000000000000E+00  good 
> cost,grad,step,b,step? =   1   1  1.222658322128833970E+06  2.556290373858516887E+03  2.678909105141880520E+00  3.405312750000701882E-01  good 
> cost,grad,step,b,step? =   1   2  1.192801575078515336E+06  3.398669999087518590E+03  2.621456624009387060E+00  1.794991741115769868E+00  good 
> cost,grad,step,b,step? =   1   3  1.140350327507925685E+06  1.927633087970659062E+03  1.292891190518993705E+00  7.171770713919072282E-01  good 
> cost,grad,step,b,step? =   1   4  1.121792616183822509E+06  2.268941083889849779E+03  2.007962745059546528E+00  4.544217012901879404E-01  good 
> cost,grad,step,b,step? =   1   5  1.108692316263149958E+06  2.303675971528637092E+03  2.471196685480210764E+00  1.411396126026111197E+00  good 
> cost,grad,step,b,step? =   1   6  1.085935150885381969E+06  2.913437427378568827E+03  1.537119873996478647E+00  1.512207878776679504E+00  good 
> cost,grad,step,b,step? =   1   7  1.064526879747807747E+06  1.640509636533752882E+03  1.624337383836512494E+00  4.142307816562572076E-01  good 
> cost,grad,step,b,step? =   1   8  1.055153531811563764E+06  1.660182459495179273E+03  2.455789852126325723E+00  7.115065083037438454E-01  good 
> cost,grad,step,b,step? =   1   9  1.045068836795417592E+06  1.206737250218039662E+03  1.952095137681008286E+00  1.596794910801936362E+00  good 
> cost,grad,step,b,step? =   1  10  1.032267175409999909E+06  1.525819551465918039E+03  1.700228087698087753E+00  7.936485499477292649E-01  good 
> cost,grad,step,b,step? =   1  11  1.023416698595269118E+06  1.239155552670741372E+03  2.244903898930359354E+00  6.370537041685712110E-01  good 
> cost,grad,step,b,step? =   1  12  1.015971810601242236E+06  1.451658936935166366E+03  2.865819134098706478E+00  1.292474402240430642E+00  good 
> cost,grad,step,b,step? =   1  13  1.003687316369917477E+06  9.981417451463421457E+02  1.470135080318861753E+00  1.409312775136696283E+00  good 
> cost,grad,step,b,step? =   1  14  9.948043992032407550E+05  1.259675382404923312E+03  1.640854687919948374E+00  4.728130777385153860E-01  good 
> cost,grad,step,b,step? =   1  15  9.901174467339061666E+05  9.540783334982924089E+02  2.621297004670111619E+00  7.717475425861989313E-01  good 
> cost,grad,step,b,step? =   1  16  9.843378083203521091E+05  1.171010894415684561E+03  2.247202818366751398E+00  1.360939636907550598E+00  good 
> cost,grad,step,b,step? =   1  17  9.775931590989182005E+05  1.059616281825138685E+03  2.328549144111061953E+00  7.243372838292220228E-01  good 
> cost,grad,step,b,step? =   1  18  9.725316679609023267E+05  9.727558114256718227E+02  1.968493255436674971E+00  1.067952899267498923E+00  good 
> cost,grad,step,b,step? =   1  19  9.679616592465853319E+05  8.423903295123618591E+02  1.870266983656969417E+00  8.210320439565230721E-01  good 
> cost,grad,step,b,step? =   1  20  9.643957774920111988E+05  9.684211859947477024E+02  2.418976520205493586E+00  9.614327053952699265E-01  good 
> cost,grad,step,b,step? =   1  21  9.599609566676199902E+05  7.991760854697862442E+02  1.910204119344367069E+00  1.341529839399210777E+00  good 
> cost,grad,step,b,step? =   1  22  9.552627022347915918E+05  7.884470323120541480E+02  1.467042039037851353E+00  5.934546759913327252E-01  good 
> cost,grad,step,b,step? =   1  23  9.531209483985098777E+05  6.868679188752797700E+02  2.603194070525873371E+00  5.764453694420930141E-01  good 
> cost,grad,step,b,step? =   1  24  9.509297418496405007E+05  7.114278247470564338E+02  2.137295267362888218E+00  1.787782788811815626E+00  good 
> cost,grad,step,b,step? =   1  25  9.477132488363139564E+05  7.176015339534891382E+02  1.696523567048257020E+00  8.478945150020011923E-01  good 
> cost,grad,step,b,step? =   1  26  9.455485912356786430E+05  7.878839185382896630E+02  2.404136031452074551E+00  7.559645014950227004E-01  good 
> cost,grad,step,b,step? =   1  27  9.432295305923940614E+05  8.296007395202368571E+02  1.541125457464644244E+00  1.290784304450932174E+00  good 
> cost,grad,step,b,step? =   1  28  9.413106226433627307E+05  7.660244563243963967E+02  1.475818562712531090E+00  7.009848089325623199E-01  good 
> cost,grad,step,b,step? =   1  29  9.400219878664907301E+05  5.870909051621463277E+02  2.628295762120554713E+00  6.546297949984928310E-01  good 
> cost,grad,step,b,step? =   1  30  9.385193479447969003E+05  5.684219437408377189E+02  2.285250068167349546E+00  1.491478573024898502E+00  good 
> cost,grad,step,b,step? =   1  31  9.365707209573211148E+05  5.283463987716976362E+02  1.726798341340596510E+00  8.897614166900338351E-01  good 
> cost,grad,step,b,step? =   1  32  9.352606097822600277E+05  5.093198625568570037E+02  2.160464083145933856E+00  7.022429073705879210E-01  good 
> cost,grad,step,b,step? =   1  33  9.341094833225333132E+05  4.630927038310866806E+02  2.409052087716039292E+00  1.005342801192782520E+00  good 
> cost,grad,step,b,step? =   1  34  9.328190337977588642E+05  4.876491877011202405E+02  1.857655381506752024E+00  1.148880382792016430E+00  good 
> cost,grad,step,b,step? =   1  35  9.316757018543102313E+05  4.341629957401609090E+02  1.958323489175054499E+00  7.181622618357340615E-01  good 
> cost,grad,step,b,step? =   1  36  9.308100704991879174E+05  3.898717641072720426E+02  2.106125829050253362E+00  8.597699522832723540E-01  good 
> cost,grad,step,b,step? =   1  37  9.300096256958516315E+05  3.950124435221681551E+02  2.185096653559052360E+00  9.181690497647249094E-01  good 
> cost,grad,step,b,step? =   1  38  9.292471288857407635E+05  3.591309744986476744E+02  2.199937083517859993E+00  9.623494587288855540E-01  good 
> cost,grad,step,b,step? =   1  39  9.285084275954756886E+05  3.943832243147632539E+02  2.195167692453649178E+00  9.798904327591591024E-01  good 
> cost,grad,step,b,step? =   1  40  9.277861811410664814E+05  3.728050096886103688E+02  1.896633860501562241E+00  1.036272750548375532E+00  good 
> cost,grad,step,b,step? =   1  41  9.271395284631112590E+05  3.736118648248695422E+02  1.695565458405315473E+00  7.969394089630127409E-01  good 
> cost,grad,step,b,step? =   1  42  9.266787443618121324E+05  3.762272389676143689E+02  1.785345795992157480E+00  7.892130366750238490E-01  good 
> cost,grad,step,b,step? =   1  43  9.262957685673353262E+05  3.941661010812074437E+02  2.252215686601706235E+00  1.099256042319914695E+00  good 
> cost,grad,step,b,step? =   1  44  9.257646849155803211E+05  3.611823579080750619E+02  1.784267889259229189E+00  1.221513504280491658E+00  good 
> cost,grad,step,b,step? =   1  45  9.252507317010506522E+05  3.108000503888801518E+02  1.797710625495613668E+00  6.592714596669042582E-01  good 
> cost,grad,step,b,step? =   1  46  9.249093437747892458E+05  2.431241636968128148E+02  1.984977648790542393E+00  7.440013865258039427E-01  good 
> cost,grad,step,b,step? =   1  47  9.246288808470725780E+05  2.545727536348573778E+02  2.304984287320798853E+00  1.031586843736764791E+00  good 
> cost,grad,step,b,step? =   1  48  9.242929163231047569E+05  2.491540681987294761E+02  1.790387331802413939E+00  1.229242228514867419E+00  good 
> cost,grad,step,b,step? =   1  49  9.239721335474873194E+05  2.258096644040610386E+02  1.843767977374821232E+00  7.790885267799394498E-01  good 
> cost,grad,step,b,step? =   1  50  9.237147622492795344E+05  2.197515103404336685E+02  2.263778471052365404E+00  7.409728895268197224E-01  good 
7413,7419c8947,8953
< analysis U      1.535092505329E+00  -1.033605689991E+02   1.486886217518E+02
< analysis V      3.495200773380E-02  -9.353424937273E+01   9.357099789365E+01
< analysis TV     6.107948880076E+01   1.638727228232E+02   3.158472295085E+02
< analysis Q      4.406839549977E-04   1.000000000000E-07   2.135321052966E-02
< analysis TSEN   6.100307461278E+01   1.638724550282E+02   3.150953086187E+02
< analysis OZ     4.979190197258E-07   1.000000000000E-15   1.730708978559E-05
< analysis CW     1.409298062838E-06   0.000000000000E+00   1.549023160373E-03
---
> analysis U      1.535227007726E+00  -1.033602036201E+02   1.487094350466E+02
> analysis V      3.498001140601E-02  -9.341857786346E+01   9.378061403783E+01
> analysis TV     6.107952916995E+01   1.638594035035E+02   3.158488569058E+02
> analysis Q      4.406884302987E-04   1.000000000000E-07   2.135272614388E-02
> analysis TSEN   6.100311413303E+01   1.638591359596E+02   3.150965434191E+02
> analysis OZ     4.979199408479E-07   1.000000000000E-15   1.731080147738E-05
> analysis CW     1.410142314686E-06   0.000000000000E+00   1.548404639207E-03
7421,7422c8955,8956
< analysis DIV   -4.649010801610E-09  -2.258024841247E-03   1.923024955960E-03
< analysis VOR    2.151906866687E-07  -1.972696542979E-03   2.325194963185E-03
---
> analysis DIV   -4.643320194760E-09  -2.258822137582E-03   1.924129368044E-03
> analysis VOR    2.150021958229E-07  -1.975972164899E-03   2.330535196081E-03
7424c8958
< analysis PS     2.415920352472E+01   4.852446815050E+01   1.060508031499E+02
---
> analysis PS     2.415919859454E+01   4.852513319323E+01   1.060521633578E+02
7426c8960
< analysis radb   6.305589863046E-02  -1.301172960000E+02   2.609153460000E+02
---
> analysis radb   6.305100379769E-02  -1.301172960000E+02   2.609153460000E+02
7428c8962
< analysis aftb   3.546447971150E-02  -6.126166000000E+00   4.727525000000E+00
---
> analysis aftb   3.546447514884E-02  -6.126166000000E+00   4.727525000000E+00
7430,7440c8964,8974
< increment u                                                                 -8.768051693740E-03  -2.468496074731E+01   3.097355164265E+01
< increment v                                                                 -1.340174556058E-03  -2.208499424771E+01   2.137121805763E+01
< increment tv                                                                 6.269270723259E-04  -9.266226596002E+00   1.373567628587E+01
< increment tsen                                                              -4.824417470377E-04  -9.266227569724E+00   1.373571030363E+01
< increment q                                                                  6.293858210562E-06  -5.624698563268E-03   5.726248547645E-03
< increment oz                                                                 5.527764203552E-10  -2.071894487713E-06   3.184392526539E-06
< increment ql                                                                 9.428472923448E-08  -5.295960246170E-04   5.091502004704E-04
< increment qi                                                                 2.344147242474E-08  -3.440821039380E-04   3.214012790220E-04
< increment prse                                                              -2.857952518616E-04  -2.216658904254E-01   2.186055779657E-01
< increment ps                                                                -8.134212786640E-04  -2.216658904254E-01   2.186055779657E-01
< increment sst                                                                2.674613510057E-02  -9.138899262362E+00   7.087311367250E+00
---
> increment u                                                                 -7.787095608919E-03  -2.465150759252E+01   3.088547711523E+01
> increment v                                                                 -1.083227785623E-03  -2.202079360076E+01   2.148934267874E+01
> increment tv                                                                 7.416835927182E-04  -9.314055551758E+00   1.378373495359E+01
> increment tsen                                                              -3.712493364243E-04  -9.314057146683E+00   1.378376867041E+01
> increment q                                                                  6.312598140566E-06  -5.619277978027E-03   5.706209075987E-03
> increment oz                                                                 5.592794806880E-10  -2.024777731091E-06   3.288611576005E-06
> increment ql                                                                 9.432902886427E-08  -5.275801493165E-04   5.106695804297E-04
> increment qi                                                                 2.465155553182E-08  -3.450784209980E-04   3.189349997946E-04
> increment prse                                                              -2.988573679482E-04  -2.215269581568E-01   2.180166818584E-01
> increment ps                                                                -8.505982544885E-04  -2.215269581568E-01   2.180166818584E-01
> increment sst                                                                2.670942506510E-02  -9.146712748411E+00   7.087333175051E+00
< background              6.710850E+04  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00
< excess   moisture       1.035655E-01  1.040289E-01  1.042477E-01  1.068380E-01  1.085272E-01  1.040946E-01  9.867415E-02
< surface pressure        1.884221E+03  1.059383E+03  1.041226E+03  2.262969E+03  1.106363E+03  1.095306E+03  2.321311E+01
< temperature             1.901342E+03  3.581804E+03  3.312492E+03  3.055250E+03  2.212825E+03  1.584372E+03  1.815406E+02
< wind                    8.860963E+03  1.456607E+04  1.398356E+04  1.155432E+04  9.165121E+03  6.290440E+03  2.672317E+02
< moisture                1.647665E+02  3.819019E+02  3.490985E+02  2.036761E+02  1.298666E+02  9.638975E+01  9.569733E+00
< sst                     2.554371E+02  2.039916E+02  1.611721E+02  3.092453E+02  2.043346E+02  2.363111E+02  2.122585E+00
< ozone                   9.172531E+02  2.043618E+03  1.908801E+03  1.193766E+03  1.808972E+03  0.000000E+00  0.000000E+00
< gps bending angle       1.564307E+04  3.313781E+04  3.067188E+04  3.029608E+04  1.935532E+04  9.126535E+03  0.000000E+00
< radiance                6.036407E+04  1.530996E+05  1.457485E+05  1.287711E+05  1.010292E+05  8.972031E+04  2.012046E+03
---
> background              6.706399E+04  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00
> excess   moisture       1.036117E-01  1.038984E-01  1.043282E-01  1.070554E-01  1.086594E-01  1.042728E-01  9.888011E-02
> surface pressure        1.883717E+03  1.059195E+03  1.040973E+03  2.262236E+03  1.106162E+03  1.095193E+03  2.320872E+01
> temperature             1.901392E+03  3.581915E+03  3.312352E+03  3.055050E+03  2.212434E+03  1.584794E+03  1.815604E+02
> wind                    8.859221E+03  1.456760E+04  1.398750E+04  1.155433E+04  9.164894E+03  6.287017E+03  2.670541E+02
> moisture                1.648205E+02  3.818756E+02  3.491313E+02  2.036686E+02  1.297680E+02  9.639862E+01  9.570864E+00
> sst                     2.554287E+02  2.039434E+02  1.611232E+02  3.091975E+02  2.043212E+02  2.363300E+02  2.122670E+00
> ozone                   9.169212E+02  2.042865E+03  1.908569E+03  1.193823E+03  1.807976E+03  0.000000E+00  0.000000E+00
> gps bending angle       1.565285E+04  3.313148E+04  3.064739E+04  3.029566E+04  1.932275E+04  9.105928E+03  0.000000E+00
> radiance                6.035557E+04  1.530867E+05  1.457418E+05  1.287075E+05  1.010097E+05  8.969773E+04  2.011558E+03
11715,11724c13249,13258
< background                   6.7108502337529892E+04
< excess   moisture            7.2997612762013264E-01
< surface pressure             8.4726805949329901E+03
< temperature                  1.5829625725226078E+04
< wind                         6.4687706582925784E+04
< moisture                     1.3352691055175403E+03
< sst                          1.3726144324780789E+03
< ozone                        7.8724097270511520E+03
< gps bending angle            1.3823069544585119E+05
< radiance                     6.8074480178009463E+05
---
> background                   6.7063993051161728E+04
> excess   moisture            7.3070603990059568E-01
> surface pressure             8.4706842262061200E+03
> temperature                  1.5829497584452114E+04
> wind                         6.4687614845902448E+04
> moisture                     1.3352333911054161E+03
> sst                          1.3724666623649903E+03
> ozone                        7.8701530830337251E+03
> gps bending angle            1.3815606286619077E+05
> radiance                     6.8061046913416951E+05
11726c13260
<  J Global                    9.8565503570773499E+05
---
>  J Global                    9.8539690555062681E+05
11728,11830c13262,13364
< Initial cost function =  9.856550357077349909E+05
< Initial gradient norm =  3.019113240824133754E+03
< cost,grad,step,b,step? =   2   0  9.856550357077349909E+05  3.019113240824133754E+03  9.283200897798100648E-01  0.000000000000000000E+00  good 
< cost,grad,step,b,step? =   2   1  9.810031829503983026E+05  6.963902890888178945E+02  1.092994127841970808E+00  1.768953533789040522E-01  good 
< cost,grad,step,b,step? =   2   2  9.800343173135255929E+05  1.157089039719978018E+03  6.825501062304787370E-01  1.239049992139185763E+00  good 
< cost,grad,step,b,step? =   2   3  9.792846448392111342E+05  1.054431929802138256E+03  2.794674534542238131E+00  8.718532066856599094E-01  good 
< cost,grad,step,b,step? =   2   4  9.766085391214593546E+05  8.016029002840731437E+02  1.829672981555619193E+00  8.647232451162374378E-01  good 
< cost,grad,step,b,step? =   2   5  9.750934859120004112E+05  5.663007925360583386E+02  1.457609106330954862E+00  7.428631747090924664E-01  good 
< cost,grad,step,b,step? =   2   6  9.741968764931872720E+05  5.949493763144854483E+02  4.135936207672607168E+00  9.034574444132421611E-01  good 
< cost,grad,step,b,step? =   2   7  9.718983565577333793E+05  6.364211975930660401E+02  1.267644968345302825E+00  2.005090849649880269E+00  good 
< cost,grad,step,b,step? =   2   8  9.704857935023590690E+05  4.621450746270481318E+02  2.003438790271123704E+00  3.492289807231176435E-01  good 
< cost,grad,step,b,step? =   2   9  9.697061484189180192E+05  4.624347816444027899E+02  2.306793055263316461E+00  1.104890736672738072E+00  good 
< cost,grad,step,b,step? =   2  10  9.687142684340536362E+05  5.764477831048931193E+02  6.898957562009918609E-01  1.279767867834944228E+00  good 
< cost,grad,step,b,step? =   2  11  9.683346359844404506E+05  6.807009944883542403E+02  1.010964468151797968E+00  9.941934292530295592E-01  good 
< cost,grad,step,b,step? =   2  12  9.677815388250530232E+05  4.077176678946223092E+02  2.254909404078229151E+00  6.313755028893570653E-01  good 
< cost,grad,step,b,step? =   2  13  9.670026481725381454E+05  3.618980212955872844E+02  1.741881974565260949E+00  1.124755496603169425E+00  good 
< cost,grad,step,b,step? =   2  14  9.663258904572330648E+05  3.295560556217717476E+02  1.616445990023898327E+00  7.261398613432100690E-01  good 
< cost,grad,step,b,step? =   2  15  9.658698714004353387E+05  3.235910698032230925E+02  2.438409615998860858E+00  7.293378762711311136E-01  good 
< cost,grad,step,b,step? =   2  16  9.653681308547301451E+05  2.880508907007756534E+02  2.071849522323882642E+00  1.198208883158065730E+00  good 
< cost,grad,step,b,step? =   2  17  9.648573304392352002E+05  3.225692984758127295E+02  1.885906714326320399E+00  9.580853449820411205E-01  good 
< cost,grad,step,b,step? =   2  18  9.644118587165314239E+05  4.087162029725452044E+02  7.906929191138715174E-01  1.175697644652404339E+00  good 
< cost,grad,step,b,step? =   2  19  9.641922702912077075E+05  4.991574965596984725E+02  8.426339362196690885E-01  1.121828220125501430E+00  good 
< cost,grad,step,b,step? =   2  20  9.639297459713186836E+05  2.721183715776451209E+02  2.164960568872686508E+00  5.144287958035291819E-01  good 
< cost,grad,step,b,step? =   2  21  9.635827716276188148E+05  2.399548289812076121E+02  2.102625791225552820E+00  9.365285858092635696E-01  good 
< cost,grad,step,b,step? =   2  22  9.632671752400217811E+05  2.520298228614468599E+02  2.347468910973393275E+00  9.368101701151062555E-01  good 
< cost,grad,step,b,step? =   2  23  9.629370933433169266E+05  2.216635156520885914E+02  1.722782774992177801E+00  1.131612343082505356E+00  good 
< cost,grad,step,b,step? =   2  24  9.626629609732717508E+05  2.397243361407219879E+02  1.907442607791137723E+00  8.541524723446737299E-01  good 
< cost,grad,step,b,step? =   2  25  9.624037157903669868E+05  2.053153885538694112E+02  1.779345585798499885E+00  7.973844094051844023E-01  good 
< cost,grad,step,b,step? =   2  26  9.622108731590303360E+05  3.623432332063060812E+02  6.182581671250338973E-01  1.529479793228603057E+00  good 
< cost,grad,step,b,step? =   2  27  9.621083841292265570E+05  3.013573091894588174E+02  1.518647848779223430E+00  8.076546227445609016E-01  good 
< cost,grad,step,b,step? =   2  28  9.619050565959595842E+05  2.135171679950325938E+02  2.294293676542755733E+00  7.739897068182257645E-01  good 
< cost,grad,step,b,step? =   2  29  9.616673111973539926E+05  1.885114252718380783E+02  1.809697240941713803E+00  1.218802118740782037E+00  good 
< cost,grad,step,b,step? =   2  30  9.614387516587810824E+05  1.935996507549419334E+02  2.108893070650796897E+00  6.520073390070870722E-01  good 
< cost,grad,step,b,step? =   2  31  9.612650874254797818E+05  1.711556009346859923E+02  2.303269633089021440E+00  8.870958025168577121E-01  good 
< cost,grad,step,b,step? =   2  32  9.610968289446968120E+05  1.705219080944365828E+02  1.802007976466932115E+00  1.111956356876484309E+00  good 
< cost,grad,step,b,step? =   2  33  9.609504514571585460E+05  2.723638444166003296E+02  6.750838528905983571E-01  1.257926234590389436E+00  good 
< cost,grad,step,b,step? =   2  34  9.608814695952413604E+05  2.761889435453617807E+02  1.213150086513508086E+00  9.688732979747199936E-01  good 
< cost,grad,step,b,step? =   2  35  9.607613636345320847E+05  1.653580356386781318E+02  2.096495945744664358E+00  7.706833310915947033E-01  good 
< cost,grad,step,b,step? =   2  36  9.606014048259437550E+05  1.493336376123795333E+02  1.533672603903881271E+00  8.200132590369760832E-01  good 
< cost,grad,step,b,step? =   2  37  9.605054539761488559E+05  1.473811649713704810E+02  2.487240903591388719E+00  7.327319998734463935E-01  good 
< cost,grad,step,b,step? =   2  38  9.603914381581171183E+05  1.274768645922544295E+02  1.912860462188836097E+00  1.112209467997617773E+00  good 
< cost,grad,step,b,step? =   2  39  9.602939061352226418E+05  1.433336345855570073E+02  1.906110622652214426E+00  8.754799205167181908E-01  good 
< cost,grad,step,b,step? =   2  40  9.602088201716166222E+05  2.196584267989092041E+02  6.922917404420640963E-01  1.522168840184618732E+00  good 
< cost,grad,step,b,step? =   2  41  9.601617781983186724E+05  2.173536245043993631E+02  1.201033744916354395E+00  9.941906756095000297E-01  good 
< cost,grad,step,b,step? =   2  42  9.600806384424669668E+05  1.220798893307227360E+02  1.708127842573570421E+00  5.904167808193018230E-01  good 
< cost,grad,step,b,step? =   2  43  9.600125146416918142E+05  1.181793455456641766E+02  2.409989111598771938E+00  7.766836035419772966E-01  good 
< cost,grad,step,b,step? =   2  44  9.599378591103339568E+05  1.072390594750430921E+02  1.915967663405706567E+00  1.130430600211834280E+00  good 
< cost,grad,step,b,step? =   2  45  9.598707645541417878E+05  9.885025028672626490E+01  1.919312065366648001E+00  7.726974659197721751E-01  good 
< cost,grad,step,b,step? =   2  46  9.598188331375395646E+05  1.102083355644896869E+02  1.588843393788713421E+00  8.757716211158418362E-01  good 
< cost,grad,step,b,step? =   2  47  9.597811821880075149E+05  2.109604845948454113E+02  6.648826002054378792E-01  2.152359363938275649E+00  good 
< cost,grad,step,b,step? =   2  48  9.597472667944018031E+05  1.229062002497742299E+02  1.810188422039034517E+00  6.625420563741279967E-01  good 
< cost,grad,step,b,step? =   2  49  9.596860961640197784E+05  9.365560890013337314E+01  1.794632857181333696E+00  6.077373183958478808E-01  good 
< cost,grad,step,b,step? =   2  50  9.596492407452336047E+05  9.088741461864529469E+01  2.475655058039660794E+00  9.385290676780165819E-01  good 
< cost,grad,step,b,step? =   2  51  9.596015210769441910E+05  7.237678297072721989E+01  1.853469414729663978E+00  1.112709900149718045E+00  good 
< cost,grad,step,b,step? =   2  52  9.595617667782203062E+05  8.444219352223744579E+01  1.963726319669055531E+00  6.140707705393366744E-01  good 
< cost,grad,step,b,step? =   2  53  9.595359040110503556E+05  1.198487933233051876E+02  7.909196608390201000E-01  1.655738422618274086E+00  good 
< cost,grad,step,b,step? =   2  54  9.595186548176795477E+05  1.361074852432891760E+02  1.124477635777932250E+00  1.246759799138707381E+00  good 
< cost,grad,step,b,step? =   2  55  9.594880791434263811E+05  6.915907885953127732E+01  1.679681549432004095E+00  4.601418222973659433E-01  good 
< cost,grad,step,b,step? =   2  56  9.594670707410087343E+05  7.001381912666244034E+01  3.098843584006970353E+00  7.583253596921142314E-01  good 
< cost,grad,step,b,step? =   2  57  9.594376771107276436E+05  6.186230937434000765E+01  1.940582467894579999E+00  1.719311526178770810E+00  good 
< cost,grad,step,b,step? =   2  58  9.594060262468680739E+05  6.295919464808363841E+01  1.644302169165947181E+00  6.273411664333160553E-01  good 
< cost,grad,step,b,step? =   2  59  9.593892057929310249E+05  7.614635230277289679E+01  9.045562794404885532E-01  9.003726248419601230E-01  good 
< cost,grad,step,b,step? =   2  60  9.593808731793427141E+05  1.083735361104768202E+02  1.015464043769763069E+00  1.508939855263023766E+00  good 
< cost,grad,step,b,step? =   2  61  9.593667559510836145E+05  6.057323996916620246E+01  1.829988721607976654E+00  7.775872194261209680E-01  good 
< cost,grad,step,b,step? =   2  62  9.593469795717837987E+05  5.150879429855694269E+01  1.657454745321231382E+00  7.355423296277716627E-01  good 
< cost,grad,step,b,step? =   2  63  9.593338055051037809E+05  5.334395777538518502E+01  2.647822772649723433E+00  7.164336862807764161E-01  good 
< cost,grad,step,b,step? =   2  64  9.593187267722865799E+05  4.797829303765774966E+01  1.818400233430378599E+00  1.627607907621531735E+00  good 
< cost,grad,step,b,step? =   2  65  9.593018711058410117E+05  6.119769903682114176E+01  7.992428496501285951E-01  7.626164489017573933E-01  good 
< cost,grad,step,b,step? =   2  66  9.592962217185073532E+05  8.348211242519707298E+01  8.308195223942870244E-01  1.150470141782831135E+00  good 
< cost,grad,step,b,step? =   2  67  9.592894655212198850E+05  4.697075286117329540E+01  1.969543980305161979E+00  5.948659346281863769E-01  good 
< cost,grad,step,b,step? =   2  68  9.592799380212975666E+05  3.777942818799384384E+01  1.940116089806596111E+00  1.077888660004552968E+00  good 
< cost,grad,step,b,step? =   2  69  9.592698215778984595E+05  3.729397521635277712E+01  2.010876848576876430E+00  8.121819464668339483E-01  good 
< cost,grad,step,b,step? =   2  70  9.592613067996402970E+05  3.941625686198452883E+01  2.173607433300810410E+00  9.244054596309925209E-01  good 
< cost,grad,step,b,step? =   2  71  9.592527983036817750E+05  4.644187392856415642E+01  9.374555736361160907E-01  1.188129161229203312E+00  good 
< cost,grad,step,b,step? =   2  72  9.592484377444430720E+05  7.215026285212833557E+01  7.234098674542203122E-01  1.346173232099308281E+00  good 
< cost,grad,step,b,step? =   2  73  9.592439075322105782E+05  3.575514307815162596E+01  2.255190808099707400E+00  4.468666690979601896E-01  good 
< cost,grad,step,b,step? =   2  74  9.592375986181249609E+05  3.326397976297318593E+01  1.947914571288634322E+00  1.073978519080127425E+00  good 
< cost,grad,step,b,step? =   2  75  9.592317444628832163E+05  3.144017752069224159E+01  1.959869658034981477E+00  8.481409547321082654E-01  good 
< cost,grad,step,b,step? =   2  76  9.592267492704365868E+05  3.069887518487654887E+01  2.163804215807352715E+00  9.685119043673495742E-01  good 
< cost,grad,step,b,step? =   2  77  9.592214079618308460E+05  4.535502364018799426E+01  7.222151604356392696E-01  1.351898896946382544E+00  good 
< cost,grad,step,b,step? =   2  78  9.592189975646253442E+05  5.258115593054086645E+01  9.889417255196922829E-01  1.067201556262882933E+00  good 
< cost,grad,step,b,step? =   2  79  9.592154752757214010E+05  2.740228642321647712E+01  2.504099419198103416E+00  5.042870661763378948E-01  good 
< cost,grad,step,b,step? =   2  80  9.592109774163673865E+05  2.263352052315290663E+01  1.762330294573599021E+00  1.004589925584408627E+00  good 
< cost,grad,step,b,step? =   2  81  9.592077978172667790E+05  2.400634427944166305E+01  1.939091209885012823E+00  7.801468532903153008E-01  good 
< cost,grad,step,b,step? =   2  82  9.592050685418409994E+05  2.287410345249189803E+01  2.076001896218967246E+00  1.067956497746970657E+00  good 
< cost,grad,step,b,step? =   2  83  9.592019481940426631E+05  3.940668228127105976E+01  6.778740072311103537E-01  1.701991757906280656E+00  good 
< cost,grad,step,b,step? =   2  84  9.592002139832881512E+05  3.806621603226687967E+01  9.865310535218395627E-01  8.857370947307964260E-01  good 
< cost,grad,step,b,step? =   2  85  9.591979785493247909E+05  2.122738659410480722E+01  1.845862315421574085E+00  4.214723657083072617E-01  good 
< cost,grad,step,b,step? =   2  86  9.591962156975006219E+05  1.914455430936782321E+01  2.686454584981854410E+00  1.118668926620976611E+00  good 
< cost,grad,step,b,step? =   2  87  9.591933458602163009E+05  1.844274721112292070E+01  1.921276738476874302E+00  1.105104317058377861E+00  good 
< cost,grad,step,b,step? =   2  88  9.591910772788934410E+05  1.996934964039341409E+01  1.553315568893547827E+00  6.654151332390292328E-01  good 
< cost,grad,step,b,step? =   2  89  9.591898569502830505E+05  3.081633215487806154E+01  6.787603339003450698E-01  1.494301771622922326E+00  good 
< cost,grad,step,b,step? =   2  90  9.591890600934822578E+05  2.647610765329116944E+01  1.579886697083121794E+00  9.402719648084438830E-01  good 
< cost,grad,step,b,step? =   2  91  9.591873160912799649E+05  1.760574525171132265E+01  1.664635230788149567E+00  7.669846068289635221E-01  good 
< cost,grad,step,b,step? =   2  92  9.591859065763683757E+05  1.748525218036679973E+01  2.364373287621964081E+00  6.564110054836898023E-01  good 
< cost,grad,step,b,step? =   2  93  9.591845928026906913E+05  1.519987359901783641E+01  2.242016082383201159E+00  1.303224069416023312E+00  good 
< cost,grad,step,b,step? =   2  94  9.591829692190544447E+05  1.487638343008146968E+01  1.212142129260427970E+00  9.317324779931953627E-01  good 
< cost,grad,step,b,step? =   2  95  9.591821512894524494E+05  2.444815052434297797E+01  5.942929973019772660E-01  1.012127177432245784E+00  good 
< cost,grad,step,b,step? =   2  96  9.591817454701961251E+05  1.865533974632500858E+01  2.036967869469481052E+00  7.421942937038914501E-01  good 
< cost,grad,step,b,step? =   2  97  9.591807130815470591E+05  1.189001055916412497E+01  1.765692227083621502E+00  1.304078214804710756E+00  good 
< cost,grad,step,b,step? =   2  98  9.591795460162420059E+05  1.184731214959133716E+01  1.510464474845722327E+00  5.761218801964218539E-01  good 
< cost,grad,step,b,step? =   2  99  9.591789708471433260E+05  1.190858172315127739E+01  2.861597191119947592E+00  7.029406170168259749E-01  good 
< cost,grad,step,b,step? =   2 100  9.591782048211150104E+05  1.186791418623982430E+01  1.671438753798121013E+00  1.770476009949142338E+00  good 
---
> Initial cost function =  9.853969055506268051E+05
> Initial gradient norm =  3.017963815207926473E+03
> cost,grad,step,b,step? =   2   0  9.853969055506268051E+05  3.017963815207926473E+03  9.278332255749299762E-01  0.000000000000000000E+00  good 
> cost,grad,step,b,step? =   2   1  9.807470899836310418E+05  6.948206437812285685E+02  1.093422641948616159E+00  1.763263761061444335E-01  good 
> cost,grad,step,b,step? =   2   2  9.797808784605580149E+05  1.152421735052953636E+03  6.825486458787598520E-01  1.232519294951816224E+00  good 
> cost,grad,step,b,step? =   2   3  9.790374926758283982E+05  1.051143791995747279E+03  2.791461840599470445E+00  8.745021667630655804E-01  good 
> cost,grad,step,b,step? =   2   4  9.763788190190518508E+05  7.991530494865702394E+02  1.823996271434516814E+00  8.691264691981289703E-01  good 
> cost,grad,step,b,step? =   2   5  9.748689312494270271E+05  5.678769641760547984E+02  1.453050630251714326E+00  7.449233732635465177E-01  good 
> cost,grad,step,b,step? =   2   6  9.739729221136852866E+05  5.934267599677007183E+02  4.156469433732419283E+00  8.941006536026290252E-01  good 
> cost,grad,step,b,step? =   2   7  9.716812783224002924E+05  6.375673604873016984E+02  1.271599925703272627E+00  2.022331884242377420E+00  good 
> cost,grad,step,b,step? =   2   8  9.702634389509067405E+05  4.608327441350529625E+02  1.994805233595292826E+00  3.480798828236691400E-01  good 
> cost,grad,step,b,step? =   2   9  9.694892363939404022E+05  4.581705581465663499E+02  2.381258720286644426E+00  1.092052187430634369E+00  good 
> cost,grad,step,b,step? =   2  10  9.684799499890329316E+05  4.874825335497830565E+02  8.884546331093171601E-01  1.114644567399333486E+00  good 
> cost,grad,step,b,step? =   2  11  9.680602124862717465E+05  7.547261679669395562E+02  7.966212134340583395E-01  1.306941679045014792E+00  good 
> cost,grad,step,b,step? =   2  12  9.675683255168884061E+05  4.283194090009836259E+02  2.144770211479489763E+00  5.840271986374647728E-01  good 
> cost,grad,step,b,step? =   2  13  9.667948999565179693E+05  3.614096089633228530E+02  1.730008079120318953E+00  1.074479234632063074E+00  good 
> cost,grad,step,b,step? =   2  14  9.661245666824987857E+05  3.294984515655570476E+02  1.629121114667388959E+00  7.208493781261378075E-01  good 
> cost,grad,step,b,step? =   2  15  9.656695504283816554E+05  3.236223017937954296E+02  2.455826952702114596E+00  7.362943043890487482E-01  good 
> cost,grad,step,b,step? =   2  16  9.651644846150177764E+05  2.888171615809400237E+02  2.059415476121206900E+00  1.208111961419050306E+00  good 
> cost,grad,step,b,step? =   2  17  9.646528159984402591E+05  3.252971407364018432E+02  1.815637778008111436E+00  9.563207860082773015E-01  good 
> cost,grad,step,b,step? =   2  18  9.642214163809199817E+05  4.547842992871122192E+02  6.929124066447871488E-01  1.284814478965667695E+00  good 
> cost,grad,step,b,step? =   2  19  9.640098860251206206E+05  4.586899401233659432E+02  9.781848741529652891E-01  9.398369437939331217E-01  good 
> cost,grad,step,b,step? =   2  20  9.637292325046269689E+05  2.649931063331214887E+02  2.213736458726510925E+00  5.450149439092090153E-01  good 
> cost,grad,step,b,step? =   2  21  9.633830711846901104E+05  2.398602951161299472E+02  2.114500736710340334E+00  9.569435551459490874E-01  good 
> cost,grad,step,b,step? =   2  22  9.630666631072005257E+05  2.523897760651958322E+02  2.338069476790721968E+00  9.477061471982214380E-01  good 
> cost,grad,step,b,step? =   2  23  9.627350942996939411E+05  2.209364010936878628E+02  1.704357985045273916E+00  1.124848821370128649E+00  good 
> cost,grad,step,b,step? =   2  24  9.624632125837724889E+05  2.395808354039351684E+02  1.896760614557443825E+00  8.401044848298935275E-01  good 
> cost,grad,step,b,step? =   2  25  9.622090216846396215E+05  2.271088666561721823E+02  1.332569852736915417E+00  8.587006847380844743E-01  good 
> cost,grad,step,b,step? =   2  26  9.620556685643260134E+05  4.356748603174267487E+02  6.451172233892851215E-01  1.843373328188977478E+00  good 
> cost,grad,step,b,step? =   2  27  9.619188098806383787E+05  2.385856042466479892E+02  1.962465475228739820E+00  5.155777492062599832E-01  good 
> cost,grad,step,b,step? =   2  28  9.617041629010793986E+05  2.108071937015644437E+02  2.311693411016891631E+00  9.339312536887141025E-01  good 
> cost,grad,step,b,step? =   2  29  9.614680235951710492E+05  1.885396189559801883E+02  1.823599039446976100E+00  1.226150392291196711E+00  good 
> cost,grad,step,b,step? =   2  30  9.612396179178447928E+05  1.940340262965668217E+02  2.109266249009063010E+00  6.621460513446651985E-01  good 
> cost,grad,step,b,step? =   2  31  9.610646846614751266E+05  1.718689269892120706E+02  2.248957359978871029E+00  8.812050413181546915E-01  good 
> cost,grad,step,b,step? =   2  32  9.609003216831645695E+05  1.992560032455553767E+02  1.211619587532833497E+00  1.201014292718312282E+00  good 
> cost,grad,step,b,step? =   2  33  9.607939725326895714E+05  3.672166393617337690E+02  6.609581319305387614E-01  1.707175956628220526E+00  good 
> cost,grad,step,b,step? =   2  34  9.606949287819190649E+05  1.945497458388761345E+02  1.884283352904664532E+00  4.772559409454225632E-01  good 
> cost,grad,step,b,step? =   2  35  9.605601753010490211E+05  1.576852903823792360E+02  2.133517019269422388E+00  1.039862102024590396E+00  good 
> cost,grad,step,b,step? =   2  36  9.604015104963334743E+05  1.492693005577023371E+02  1.561159031962783272E+00  8.082239995998197202E-01  good 
> cost,grad,step,b,step? =   2  37  9.603076809799856273E+05  1.465859548584003278E+02  2.475205780536867017E+00  7.759863564750226761E-01  good 
> cost,grad,step,b,step? =   2  38  9.601922426103322068E+05  1.278797412061829561E+02  1.851889411858624435E+00  1.101543758945216167E+00  good 
> cost,grad,step,b,step? =   2  39  9.600970984100861242E+05  1.581198051845961743E+02  1.321232422489535763E+00  9.247066317973476890E-01  good 
> cost,grad,step,b,step? =   2  40  9.600343279475126183E+05  2.837412476395127214E+02  6.830167719045979746E-01  1.894333150568526136E+00  good 
> cost,grad,step,b,step? =   2  41  9.599728533955964958E+05  1.529451392582680569E+02  1.767471304486750938E+00  5.639005848549710764E-01  good 
> cost,grad,step,b,step? =   2  42  9.598831593345011352E+05  1.184230721365668586E+02  1.713161388768604354E+00  7.865516539782816396E-01  good 
> cost,grad,step,b,step? =   2  43  9.598147763651527930E+05  1.179238815421278730E+02  2.377210989412875453E+00  7.751806491680379718E-01  good 
> cost,grad,step,b,step? =   2  44  9.597412174357898766E+05  1.068997729166589465E+02  1.928258548021280827E+00  1.121726564567768536E+00  good 
> cost,grad,step,b,step? =   2  45  9.596742861669368576E+05  1.002663639117802745E+02  1.853763159929779469E+00  7.969878922305220215E-01  good 
> cost,grad,step,b,step? =   2  46  9.596230056641283445E+05  1.322985476537293721E+02  9.399610865512484370E-01  1.009945494372831432E+00  good 
> cost,grad,step,b,step? =   2  47  9.595967436623438261E+05  1.977299012444631785E+02  9.844128768407166552E-01  1.615065841392670398E+00  good 
> cost,grad,step,b,step? =   2  48  9.595523194608316990E+05  1.001460760886841541E+02  2.106031682944052630E+00  6.513270447822824272E-01  good 
> cost,grad,step,b,step? =   2  49  9.594904291904147249E+05  9.425900517504804554E+01  1.788767434414188617E+00  7.169528552937259880E-01  good 
> cost,grad,step,b,step? =   2  50  9.594527414714372717E+05  9.103396983962191769E+01  2.383845955896883861E+00  9.289446130701720650E-01  good 
> cost,grad,step,b,step? =   2  51  9.594060816639078548E+05  7.374166342123699280E+01  1.831602430863179309E+00  1.061729116356771252E+00  good 
> cost,grad,step,b,step? =   2  52  9.593680172222211258E+05  9.415442476586639486E+01  1.262084985786933844E+00  7.225322519040729974E-01  good 
> cost,grad,step,b,step? =   2  53  9.593490664457645034E+05  1.620669112596978323E+02  7.571762261074510558E-01  1.936593566223846929E+00  good 
> cost,grad,step,b,step? =   2  54  9.593270460806107149E+05  8.667196121877758230E+01  1.683519660394679152E+00  6.767542709793109568E-01  good 
> cost,grad,step,b,step? =   2  55  9.592939179958393797E+05  6.683185279491968345E+01  1.651359141739295877E+00  6.326393191059209720E-01  good 
> cost,grad,step,b,step? =   2  56  9.592733612903796602E+05  6.966699743163600544E+01  2.808465219407021873E+00  7.829985847420377620E-01  good 
> cost,grad,step,b,step? =   2  57  9.592459852408143925E+05  6.150483714683251435E+01  1.893868204285077628E+00  1.746598426358139999E+00  good 
> cost,grad,step,b,step? =   2  58  9.592137386576803401E+05  6.781021265548734789E+01  1.264779752904866994E+00  6.980763770170332894E-01  good 
> cost,grad,step,b,step? =   2  59  9.591987088344272925E+05  1.082254203050081145E+02  6.115507934138907364E-01  1.164057157950858734E+00  good 
> cost,grad,step,b,step? =   2  60  9.591902479428537190E+05  7.938211107880636064E+01  1.582390864641740835E+00  7.180201249352993198E-01  good 
> cost,grad,step,b,step? =   2  61  9.591745285068186931E+05  5.452960989909121992E+01  2.183024877928999352E+00  9.445452126141762328E-01  good 
> cost,grad,step,b,step? =   2  62  9.591540463972218568E+05  5.295039959757262693E+01  1.697041820523442990E+00  8.708372085199580503E-01  good 
> cost,grad,step,b,step? =   2  63  9.591401813962466549E+05  5.420854131857617375E+01  2.208577043579617261E+00  7.774706318582236264E-01  good 
> cost,grad,step,b,step? =   2  64  9.591261523226069985E+05  5.140533316108491846E+01  1.834533502490417023E+00  1.381300065533276111E+00  good 
> cost,grad,step,b,step? =   2  65  9.591100549476511078E+05  9.180891623391087819E+01  5.239818720928519635E-01  1.248199886133817715E+00  good 
> cost,grad,step,b,step? =   2  66  9.591043161818326917E+05  6.510693943292135089E+01  1.364658374977345545E+00  5.716888914504603125E-01  good 
> cost,grad,step,b,step? =   2  67  9.590957718602950918E+05  4.412751667910565345E+01  2.344433635133408522E+00  7.673524228923344070E-01  good 
> cost,grad,step,b,step? =   2  68  9.590845085296867182E+05  3.802986548021343793E+01  2.009239359814305459E+00  1.022296562470763837E+00  good 
> cost,grad,step,b,step? =   2  69  9.590746394889091607E+05  3.983401972991988771E+01  2.280981017898827901E+00  7.545874605801459190E-01  good 
> cost,grad,step,b,step? =   2  70  9.590661866685420973E+05  4.248864175471810967E+01  1.859961184288322356E+00  1.162423500472745896E+00  good 
> cost,grad,step,b,step? =   2  71  9.590581739556562388E+05  8.185081662334131636E+01  5.560576325175885515E-01  1.946544753441315612E+00  good 
> cost,grad,step,b,step? =   2  72  9.590535102992790053E+05  4.611968314445033457E+01  1.322178981678268528E+00  5.068451762886420076E-01  good 
> cost,grad,step,b,step? =   2  73  9.590478906845238525E+05  3.411140026191306873E+01  2.575618963729246591E+00  5.665534826445108862E-01  good 
> cost,grad,step,b,step? =   2  74  9.590416888832052937E+05  3.253570296101533899E+01  2.048557271847710304E+00  1.300073509356506340E+00  good 
> cost,grad,step,b,step? =   2  75  9.590352736093439162E+05  3.058925419749741437E+01  1.830797683865160730E+00  8.658024650095349495E-01  good 
> cost,grad,step,b,step? =   2  76  9.590303106719880598E+05  3.295859145936540813E+01  1.690868706001415811E+00  8.919392032705667495E-01  good 
> cost,grad,step,b,step? =   2  77  9.590262224260892253E+05  6.316388251497148332E+01  5.916150906541787213E-01  1.961372327894843837E+00  good 
> cost,grad,step,b,step? =   2  78  9.590234165358456085E+05  3.702361665808718527E+01  1.600187450578555826E+00  5.618586369949658543E-01  good 
> cost,grad,step,b,step? =   2  79  9.590191526709010359E+05  2.504967675915296255E+01  2.396769316413660977E+00  7.007139436940083010E-01  good 
> cost,grad,step,b,step? =   2  80  9.590146776078408584E+05  2.301478171843509557E+01  1.753156390827539157E+00  9.117402432780403743E-01  good 
> cost,grad,step,b,step? =   2  81  9.590116935539108235E+05  2.359204517963409131E+01  2.013416472836965454E+00  8.304016755612513290E-01  good 
> cost,grad,step,b,step? =   2  82  9.590088479066790314E+05  2.345653106527455023E+01  1.650887944983533639E+00  1.179637920314720478E+00  good 
> cost,grad,step,b,step? =   2  83  9.590060956595138414E+05  4.993425273272888631E+01  6.023241207595284585E-01  1.916510718864286700E+00  good 
> cost,grad,step,b,step? =   2  84  9.590041711353795836E+05  2.862927173333002528E+01  1.297007430291124530E+00  5.538400608724435292E-01  good 
> cost,grad,step,b,step? =   2  85  9.590018758973473450E+05  2.084854199413338094E+01  2.009881286468212735E+00  5.316790258634401800E-01  good 
> cost,grad,step,b,step? =   2  86  9.589999849794351030E+05  1.859771761983399330E+01  2.566742833492140718E+00  1.227682879291652540E+00  good 
> cost,grad,step,b,step? =   2  87  9.589970204882129328E+05  1.867958221006610486E+01  1.852904796457200520E+00  9.701620843725669019E-01  good 
> cost,grad,step,b,step? =   2  88  9.589949439417725662E+05  2.081236423999509100E+01  1.334938053990585960E+00  7.213327603167049018E-01  good 
> cost,grad,step,b,step? =   2  89  9.589938648559155408E+05  3.513592211766918183E+01  6.914478615694035213E-01  1.762724857239261533E+00  good 
> cost,grad,step,b,step? =   2  90  9.589928796008315403E+05  2.234385225916975415E+01  1.739018042248716256E+00  7.164232783289098405E-01  good 
> cost,grad,step,b,step? =   2  91  9.589911043208547635E+05  1.654780280066427522E+01  1.613694443410316426E+00  8.021039263204413627E-01  good 
> cost,grad,step,b,step? =   2  92  9.589897828893751139E+05  1.672959571474569884E+01  2.331780834022707971E+00  6.966948787425005785E-01  good 
> cost,grad,step,b,step? =   2  93  9.589884529269267805E+05  1.439266507180434829E+01  2.075194748202053407E+00  1.371633034123184380E+00  good 
> cost,grad,step,b,step? =   2  94  9.589868294500650372E+05  1.552350824887864533E+01  1.182702239010981371E+00  8.857004680815188102E-01  good 
> cost,grad,step,b,step? =   2  95  9.589860098249493167E+05  2.517475556267600467E+01  5.795132746456727046E-01  1.023929171898596335E+00  good 
> cost,grad,step,b,step? =   2  96  9.589855986682426883E+05  1.820668299564120218E+01  2.175938406328941532E+00  6.780853451413348942E-01  good 
> cost,grad,step,b,step? =   2  97  9.589845518441573950E+05  1.328323177758046469E+01  1.873492052152327059E+00  1.381719786052189702E+00  good 
> cost,grad,step,b,step? =   2  98  9.589833064247672446E+05  1.210145453877457022E+01  1.545117595460477222E+00  5.578269161838007584E-01  good 
> cost,grad,step,b,step? =   2  99  9.589827334413304925E+05  1.185109521067236393E+01  2.970091670432489561E+00  7.070610349348975809E-01  good 
> cost,grad,step,b,step? =   2 100  9.589819546260812785E+05  1.162859847104355993E+01  1.589812356229981960E+00  1.900015961101811701E+00  good 
11834,11840c13368,13374
< analysis U      1.534976005329E+00  -1.035567898927E+02   1.500159117152E+02
< analysis V      3.497560841476E-02  -9.379648072676E+01   9.357507798201E+01
< analysis TV     6.107891742779E+01   1.635585954659E+02   3.158773112584E+02
< analysis Q      4.408638789111E-04   1.000000000000E-07   2.148971623748E-02
< analysis TSEN   6.100246979068E+01   1.635583281121E+02   3.151252278377E+02
< analysis OZ     4.979246220522E-07   1.000000000000E-15   1.730652901545E-05
< analysis CW     1.434006606705E-06   0.000000000000E+00   1.530500603571E-03
---
> analysis U      1.535118840554E+00  -1.035714540681E+02   1.500498397119E+02
> analysis V      3.499257331275E-02  -9.370271084913E+01   9.378766618380E+01
> analysis TV     6.107896154768E+01   1.635537366874E+02   3.158800853360E+02
> analysis Q      4.408697519538E-04   1.000000000000E-07   2.149234704481E-02
> analysis TSEN   6.100251279056E+01   1.635534695983E+02   3.151275073128E+02
> analysis OZ     4.979258783944E-07   1.000000000000E-15   1.731054718944E-05
> analysis CW     1.434935741805E-06   0.000000000000E+00   1.530285877610E-03
11842,11845c13376,13379
< analysis DIV   -4.480691792002E-09  -2.257331154069E-03   1.923711462134E-03
< analysis VOR    2.149541006520E-07  -2.003875145712E-03   2.233804819200E-03
< analysis PRSL   9.982469350342E+00   1.293517349355E-03   1.059197154098E+02
< analysis PS     2.415916601979E+01   4.852142501465E+01   1.060558446025E+02
---
> analysis DIV   -4.481001540771E-09  -2.258499152081E-03   1.923995839428E-03
> analysis VOR    2.147032685547E-07  -2.008305617962E-03   2.234921173601E-03
> analysis PRSL   9.982467623935E+00   1.293517349355E-03   1.059210739364E+02
> analysis PS     2.415916015247E+01   4.852196281624E+01   1.060571517060E+02
11847c13381
< analysis radb   6.359662734836E-02  -1.301172960000E+02   2.609153460000E+02
---
> analysis radb   6.359712733997E-02  -1.301172960000E+02   2.609153460000E+02
11849c13383
< analysis aftb   3.546535453233E-02  -6.126166000000E+00   4.727525000000E+00
---
> analysis aftb   3.546532570899E-02  -6.126166000000E+00   4.727525000000E+00
11851,11861c13385,13395
< increment u                                                                 -8.395192017975E-04  -6.514178778446E+00   9.609660744507E+00
< increment v                                                                 -2.928874443297E-05  -5.646279896883E+00   6.306564238476E+00
< increment tv                                                                -6.549500602475E-04  -2.425268281877E+00   2.707275067014E+00
< increment tsen                                                              -7.770590470358E-04  -2.425264454699E+00   2.707268986838E+00
< increment q                                                                  6.615594952978E-07  -2.200872607740E-03   1.978349774677E-03
< increment oz                                                                 1.102307387767E-11  -4.656474634232E-07   3.986778535464E-07
< increment ql                                                                 8.433149084512E-09  -2.255971463830E-04   2.300647854693E-04
< increment qi                                                                 4.425968623852E-09  -1.092649237173E-04   1.267337126170E-04
< increment prse                                                              -2.974302196461E-05  -6.068615289965E-02   7.471387432476E-02
< increment ps                                                                -8.465363507682E-05  -6.068615289965E-02   7.471387432476E-02
< increment sst                                                               -3.516110018641E-03  -6.559770164426E+00   8.290930841808E+00
---
> increment u                                                                 -9.222808027302E-04  -6.521518912683E+00   9.593466860849E+00
> increment v                                                                 -3.715513740652E-05  -5.653766804245E+00   6.266188830142E+00
> increment tv                                                                -6.610296216112E-04  -2.473864367181E+00   2.728128679010E+00
> increment tsen                                                              -7.830637822539E-04  -2.473860709082E+00   2.728122343086E+00
> increment q                                                                  6.608043434734E-07  -2.256682035889E-03   1.962738537866E-03
> increment oz                                                                 1.244302196676E-11  -4.646184546342E-07   3.995846706062E-07
> increment ql                                                                 8.181025747576E-09  -2.272252372597E-04   2.291495211470E-04
> increment qi                                                                 4.523974187353E-09  -1.090003578273E-04   1.284416473576E-04
> increment prse                                                              -2.991929090619E-05  -6.085818100746E-02   7.489481238763E-02
> increment ps                                                                -8.515532608434E-05  -6.085818100746E-02   7.489481238763E-02
> increment sst                                                               -3.498114304475E-03  -6.560157790998E+00   8.292694576785E+00

**Comment by shoyokota** [comment]
@jderber-NOAA Thank you. The difference between these log files indicates that the impact of this PR is very small in the 2-scale SDL test. Since this result is reasonable, I approve this PR.

**Review by shoyokota — DISMISSED** [review]

**Comment by jderber-NOAA** [comment]
Unfortunately when the code was updated to the head of the trunk, the multiscale option no longer worked.  The problem came from the head of the trunk, but was my error in a different update.

Using debug mode, a few small errors were found along with the main problem in control_vectors.f90 where an array was improperly dimensioned.  These small errors were fixed, the large error in control_vectors.f90 was fixed and a bunch of unused variables were deleted from some of the routines (identifying these unused variables is a side effect of using debug mode).

The code will require rereviewing when all tests are completed.

**Comment by jderber-NOAA** [comment]
Regession test and a few full tests are being run to ensure the code works properly before re-review.

**Comment by RussTreadon-NOAA** [comment]
**Hera ctests**
```
Hera(hfe05):/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr570/build$ ctest -j 9
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr570/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #7: rrfs_3denvar_glbens ..............   Passed  548.72 sec
2/9 Test #8: netcdf_fv3_regional ..............***Failed  606.16 sec
3/9 Test #4: hwrf_nmm_d2 ......................   Passed  607.77 sec
4/9 Test #5: hwrf_nmm_d3 ......................   Passed  616.48 sec
5/9 Test #9: global_enkf ......................   Passed  978.71 sec
6/9 Test #6: rtma .............................   Passed  2233.92 sec
7/9 Test #3: global_4denvar ...................   Passed  2392.58 sec
8/9 Test #2: global_4dvar .....................   Passed  2583.52 sec
9/9 Test #1: global_3dvar .....................   Passed  2809.94 sec

89% tests passed, 1 tests failed out of 9

Total Test time (real) = 2809.95 sec

The following tests FAILED:
          8 - netcdf_fv3_regional (Failed)
Errors while running CTest
Output from these tests are in: /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr570/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

The `netcdf_fv3_regional` failure is due to the update not reproducing the control.  This is actually good.  The control loproc and hiproc runs do not reproduce each other.   
```
netcdf_fv3_regional_hiproc_contrl/stdout:cost,grad,step,b,step? =   2  50  2.513330136110721505E+05  8.053483449856881293E+01  9.063002155657639003E-01  1.367897503402542014E+00  good
netcdf_fv3_regional_loproc_contrl/stdout:cost,grad,step,b,step? =   2  50  2.513335096150324098E+05  8.481579789728569096E+01  7.872822540849946371E-01  1.454825511636303803E+00  good
```
The update loproc and hiproc reproduce each other.
```
netcdf_fv3_regional_hiproc_updat/stdout:cost,grad,step,b,step? =   2  50  2.512413765488890640E+05  5.856789165400194008E+01  1.362521391069690724E+00  9.656029364727340969E-01  good
netcdf_fv3_regional_loproc_updat/stdout:cost,grad,step,b,step? =   2  50  2.512413765488890640E+05  5.856789165400194008E+01  1.362521391069690724E+00  9.656029364727340969E-01  good
```

**Comment by jderber-NOAA** [comment]
Yes.  I think it ready to go.  Will ask for rereview.JohnSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: RussTreadon-NOAA ***@***.***> Date: 5/23/23  6:54 AM  (GMT-05:00) To: NOAA-EMC/GSI ***@***.***> Cc: jderber-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NOAA-EMC/GSI] Issue with global mean weight for multiscale ensemble runs for ig > 1 plus changes to make code work for multiscale (bugs introduced in trunk). (PR #570) 
Hera ctests
Hera(hfe05):/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr570/build$ ctest -j 9
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr570/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #7: rrfs_3denvar_glbens ..............   Passed  548.72 sec
2/9 Test #8: netcdf_fv3_regional ..............***Failed  606.16 sec
3/9 Test #4: hwrf_nmm_d2 ......................   Passed  607.77 sec
4/9 Test #5: hwrf_nmm_d3 ......................   Passed  616.48 sec
5/9 Test #9: global_enkf ......................   Passed  978.71 sec
6/9 Test #6: rtma .............................   Passed  2233.92 sec
7/9 Test #3: global_4denvar ...................   Passed  2392.58 sec
8/9 Test #2: global_4dvar .....................   Passed  2583.52 sec
9/9 Test #1: global_3dvar .....................   Passed  2809.94 sec

89% tests passed, 1 tests failed out of 9

Total Test time (real) = 2809.95 sec

The following tests FAILED:
          8 - netcdf_fv3_regional (Failed)
Errors while running CTest
Output from these tests are in: /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr570/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.

The netcdf_fv3_regional failure is due to the update not reproducing the control.  This is actually good.  The control loproc and hiproc runs do not reproduce each other.
netcdf_fv3_regional_hiproc_contrl/stdout:cost,grad,step,b,step? =   2  50  2.513330136110721505E+05  8.053483449856881293E+01  9.063002155657639003E-01  1.367897503402542014E+00  good
netcdf_fv3_regional_loproc_contrl/stdout:cost,grad,step,b,step? =   2  50  2.513335096150324098E+05  8.481579789728569096E+01  7.872822540849946371E-01  1.454825511636303803E+00  good

The update loproc and hiproc reproduce each other.
netcdf_fv3_regional_hiproc_updat/stdout:cost,grad,step,b,step? =   2  50  2.512413765488890640E+05  5.856789165400194008E+01  1.362521391069690724E+00  9.656029364727340969E-01  good
netcdf_fv3_regional_loproc_updat/stdout:cost,grad,step,b,step? =   2  50  2.512413765488890640E+05  5.856789165400194008E+01  1.362521391069690724E+00  9.656029364727340969E-01  good

**Comment by jderber-NOAA** [comment]
Regression tests have passed.  Only difference is as expected in the regional test where the control was wrong.  Sent out for re-review.

**Review by TingLei-NOAA — DISMISSED** [review]
Thanks for the developer's work, especially for such a quick identification and fix for the reproducibility issue between loproc vs hiproc runs as shown in the netcdf_fv3_regional test failure . 
Approved.

**Comment by jderber-NOAA** [comment]
Ting, Thank you!  Could you please check with Sho to make sure he understands what is going on and what he needs to do?  Also, I don’t think he properly marked the PR approved last time. John Sent from Mail for Windows From: TingLei-NOAASent: Tuesday, May 23, 2023 10:25 AMTo: NOAA-EMC/GSICc: jderber-NOAA; MentionSubject: Re: [NOAA-EMC/GSI] Issue with global mean weight for multiscale ensemble runs for ig > 1 plus changes to make code work for multiscale (bugs introduced in trunk). (PR ***@***.*** approved this pull request.Thanks for the developer's work, especially for such a quick identification and fix for the reproducibility issue between loproc vs hiproc runs as shown in the netcdf_fv3_regional test failure .Approved.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by RussTreadon-NOAA** [comment]
**Orion ctests**
```
Orion-login-1:/work2/noaa/da/rtreadon/git/gsi/pr570/build$ ctest -j 9
Test project /work2/noaa/da/rtreadon/git/gsi/pr570/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #9: global_enkf ......................   Passed  491.78 sec
2/9 Test #7: rrfs_3denvar_glbens ..............   Passed  548.99 sec
3/9 Test #8: netcdf_fv3_regional ..............***Failed  607.08 sec
4/9 Test #5: hwrf_nmm_d3 ......................   Passed  621.19 sec
5/9 Test #4: hwrf_nmm_d2 ......................   Passed  1030.59 sec
6/9 Test #6: rtma .............................   Passed  1214.08 sec
7/9 Test #3: global_4denvar ...................   Passed  1567.50 sec
8/9 Test #2: global_4dvar .....................   Passed  1864.06 sec
9/9 Test #1: global_3dvar .....................   Passed  1925.44 sec

89% tests passed, 1 tests failed out of 9

Total Test time (real) = 1925.46 sec

The following tests FAILED:
          8 - netcdf_fv3_regional (Failed)
Errors while running CTest
Output from these tests are in: /work2/noaa/da/rtreadon/git/gsi/pr570/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

Same results as on Hera.   The _Failed_ result for `netcdf_fv3_regional` is due to
```
The results (penalty) between the two runs are nonreproducible,
thus the regression test has Failed on cost for netcdf_fv3_regional_loproc_updat and netcdf_fv3_regional_loproc_contrl analyses.
```
The problem is with the control, not the update.   The control loproc and hiproc do not reproduce one another.   
```
netcdf_fv3_regional_hiproc_contrl/stdout:cost,grad,step,b,step? =   2  50  2.513330136122719268E+05  8.053483507562135912E+01  9.063001870007716398E-01                          1.367897569499701538E+00  good
netcdf_fv3_regional_loproc_contrl/stdout:cost,grad,step,b,step? =   2  50  2.513335096232317737E+05  8.481580531485451502E+01  7.872820543951116745E-01                          1.454826030922940605E+00  good
```

The update loproc and hiproc update reproduce one another.   
```
netcdf_fv3_regional_hiproc_updat/stdout:cost,grad,step,b,step? =   2  50  2.512470278697943140E+05  5.458785892630358205E+01  7.628029147578401226E-01  1.575448945756806385E+00  good
netcdf_fv3_regional_loproc_updat/stdout:cost,grad,step,b,step? =   2  50  2.512470278697943140E+05  5.458785892630358205E+01  7.628029147578401226E-01  1.575448945756806385E+00  good

```

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 (Cactus) ctests**
```
russ.treadon@clogin09:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr570/build> ctest -j 9
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr570/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #9: global_enkf ......................   Passed  629.49 sec
2/9 Test #8: netcdf_fv3_regional ..............***Failed  724.63 sec
3/9 Test #4: hwrf_nmm_d2 ......................   Passed  733.45 sec
4/9 Test #5: hwrf_nmm_d3 ......................   Passed  765.22 sec
5/9 Test #7: rrfs_3denvar_glbens ..............   Passed  931.99 sec
6/9 Test #6: rtma .............................***Failed  1587.73 sec
7/9 Test #3: global_4denvar ...................   Passed  1687.99 sec
8/9 Test #1: global_3dvar .....................   Passed  1688.46 sec
9/9 Test #2: global_4dvar .....................   Passed  1815.61 sec

78% tests passed, 2 tests failed out of 9

Total Test time (real) = 1815.62 sec

The following tests FAILED:
          6 - rtma (Failed)
          8 - netcdf_fv3_regional (Failed)
Errors while running CTest
```

The `rtma` failure is due to
```
The runtime for rtma_loproc_updat is 333.132360 seconds.  This has exceeded maximum allowable threshold time of 331.575127 seconds,
resulting in Failure time-thresh of the regression test.
```
The wall time for the hiproc control is noticeably higher than that for other configurations
```
rtma_hiproc_contrl/stdout:The total amount of wall time                        = 377.030674
rtma_hiproc_updat/stdout:The total amount of wall time                        = 289.828372
rtma_loproc_contrl/stdout:The total amount of wall time                        = 301.431934
rtma_loproc_updat/stdout:The total amount of wall time                        = 333.132360
```
This appears to be a system issue.   It is not a fatal fail.

The `netcdf_fv3_regional` failure is that same as on Hera and Orion.  The control loproc and hiproc results differ
```
netcdf_fv3_regional_hiproc_contrl/stdout:cost,grad,step,b,step? =   2  50  2.513792629697102821E+05  1.218146719443801800E+02  1.483041822791324460E+00  1.365513291674969709E+00  good 
netcdf_fv3_regional_loproc_contrl/stdout:cost,grad,step,b,step? =   2  50  2.513266106706903956E+05  8.017932344121642529E+01  1.304800549919090669E+00  1.063194161430877527E+00  good 
```
whereas the loproc and hiproc update results are identical
```
netcdf_fv3_regional_hiproc_updat/stdout:cost,grad,step,b,step? =   2  50  2.512419725616740179E+05  6.046083394810837319E+01  8.290106289009062657E-01  1.269187958189923915E+00  good 
netcdf_fv3_regional_loproc_updat/stdout:cost,grad,step,b,step? =   2  50  2.512419725616740179E+05  6.046083394810837319E+01  8.290106289009062657E-01  1.269187958189923915E+00  good 
```

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 ctest**

Rerun rtma with _Passed_ result

```
russ.treadon@clogin09:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr570/build> ctest -R rtma
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr570/build
    Start 6: rtma
1/1 Test #6: rtma .............................   Passed  1527.15 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 1527.58 sec
```

File: src/gsi/control_vectors.f90 [hunk 3]
```diff
@@ -895,7 +895,7 @@ real(r_quad) function qdot_prod_sub(xcv,ycv)
      m3d=xcv%step(1)%n3d
      m2d=xcv%step(1)%n2d
      itot=max(m3d,0)+max(m2d,0)
-     if(l_hyb_ens)itot=itot+n_ens
+     if(l_hyb_ens)itot=itot+n_ens*naensgrp
```
Comment (shoyokota) [inline src/gsi/control_vectors.f90:898]: Only this part is the modification to solve the issue of not working the option of scale/variable/time-dependent localization with the current trunk, right? (This is just confirmation.)

File: src/gsi/setuprad.f90 [hunk 4]
```diff
@@ -1456,6 +1461,7 @@ subroutine setuprad(obsLL,odiagLL,lunin,mype,aivals,stats,nchanl,nreal,nobs,&
            do i=1,nchanl
               m=ich(i)
               if (icld_det(m)>0 .and. varinv(i) >= tiny_r_kind) then
+!             if (icld_det(m)>0 .or. varinv(i) >= tiny_r_kind) then
```
Comment (shoyokota) [inline src/gsi/setuprad.f90]: Why did you add this comment?

File: src/gsi/control_vectors.f90 (hunk 3 above)
Comment (jderber-NOAA) [reply src/gsi/control_vectors.f90:898]: I think so.  But when running in debug mode, there were several small changes that were necessary to get to this point in the code.  Better to fix those issues as well.

File: src/gsi/setuprad.f90 (hunk 4 above)
Comment (jderber-NOAA) [reply src/gsi/setuprad.f90]: I will delete this comment.  I thought there was an issue with the code, so I added this commented line.  I was wrong.  It was correct with the .and..  

Thank you for looking at it closely.

**Comment by jderber-NOAA** [comment]
Unable to update code right now due to lack of disk space.

**Comment by RussTreadon-NOAA** [comment]
> Unable to update code right now due to lack of disk space.

Email sent to top 20 users of `/scratch1/NCEPDEV/da`

**Comment by jderber-NOAA** [comment]
Commented out line was removed from setuprad.  Will have no impact on runs.  Regression tests resubmitted to ensure no change in results.

As expected, regression tests passed with the exception of the expected regional difference since the final change is the removal of an unused comment.  

Just need (re-)approval button to be pushed from Ting and Sho.

**Review by TingLei-NOAA — DISMISSED** [review]

**Comment by shoyokota** [comment]
I compared the following four tests of RRFS using Scale- and Variable-Dependent Localization (SDL: nsclgrp=2 and VDL: ngvarloc=2).

1. The past develop branch before introducing the bug in control_vectors.f90 ([1661c15](https://github.com/NOAA-EMC/GSI/commit/1661c15183a388742d67baf70621c93773f5830f))
2. The current develop branch ([726cc8d](https://github.com/NOAA-EMC/GSI/commit/726cc8dc16279b204deb146b584296246a7eb182))
3. 2 + modification of the bug in control_vectors.f90 only
4. The branch of this PR ([889d2e9](https://github.com/jderber-NOAA/GSI/commit/889d2e96e7fdbecccf6afd20bcb2bd129e286bf2))

As results, 2 was stopped by segmentation fault but 3 is completed. The result of 3 was slightly different from 1 because of the changes by [PR#527](https://github.com/NOAA-EMC/GSI/pull/527). However, 4 was completely the same as 3, which indicates this PR does not affect the regional SDL/VDL except for the bug fix. All of these results are as we expected. I approve this PR.

**Review by shoyokota — DISMISSED** [review]

**Comment by jderber-NOAA** [comment]
Thank you and Ting.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: shoyokota ***@***.***> Date: 5/25/23  2:52 PM  (GMT-05:00) To: NOAA-EMC/GSI ***@***.***> Cc: jderber-NOAA ***@***.***>, Mention ***@***.***> Subject: Re: [NOAA-EMC/GSI] Issue with global mean weight for multiscale ensemble runs for ig > 1 plus changes to make code work for multiscale (bugs introduced in trunk). (PR #570) 
@shoyokota approved this pull request.

File: src/gsi/convthin.f90 [hunk 5]
```diff
@@ -464,7 +464,7 @@ subroutine map3grids_m(flg,pflag,pcoord,nlevp,dlat_earth,dlon_earth,pob,crit1,io
 
     real(r_kind) dlat1,dlon1,pob1
     real(r_kind) dx,dy,dp
-    real(r_kind) dxx,dyy,dpp
+!   real(r_kind) dxx,dyy,dpp
```
Comment (RussTreadon-NOAA) [inline src/gsi/convthin.f90]: If this line is not needed, we should remove it.

File: src/gsi/stprad.f90 [hunk 6]
```diff
@@ -313,7 +313,7 @@ subroutine stprad(radhead,dval,xval,rpred,spred,out,sges,nstep)
 
         endif
 
-!$omp parallel do schedule(dynamic,1) private(nn,ic,mm,ncr,k,kk,rad,val,val2,cg_rad,wnotgross,wgross)
+! !$omp parallel do schedule(dynamic,1) private(nn,ic,mm,ncr,k,kk,rad,val,val2,cg_rad,wnotgross,wgross)
```
Comment (RussTreadon-NOAA) [inline src/gsi/stprad.f90:316]: We turn off threading here.   Can we fix the threading or should we totally remove it for this section?

**Review by RussTreadon-NOAA — COMMENTED** [review]
One comment and one question.

File: src/gsi/convthin.f90 (hunk 5 above)
Comment (jderber-NOAA) [reply src/gsi/convthin.f90]: Removed.

File: src/gsi/stprad.f90 (hunk 6 above)
Comment (jderber-NOAA) [reply src/gsi/stprad.f90:316]: Russ,

We may be able to fix this threading, so I would prefer to leave it in for a later update.  Not updating now because I think we should get the other changes in ASAP to fix the trunk.

Comment (RussTreadon-NOAA) [reply src/gsi/stprad.f90:316]: Got it.  Commented out line retained for future work.

File: src/gsi/convthin.f90 (hunk 5 above)
Comment (RussTreadon-NOAA) [reply src/gsi/convthin.f90]: Thanks!

**Comment by RussTreadon-NOAA** [comment]
@TingLei-NOAA and @shoyokota , thank you for reviewing the changes in this PR.  

I asked John to remove a commented out line of code.  He did so.   Your reviews are now stale.   I requested new reviews from each of you.   Thank you for your prompt attention to this.  We want to get John's bug fixes into `develop` sooner rather than later.

FYI, when you review code and leave comments, please remember to resolve your comments after the developer responds and you are satisfied with the response.  I resolved your comments this morning to move this PR forward.  I shouldn't do this since I don't know if John's response is satisfactory to you.

**Review by TingLei-NOAA — APPROVED** [review]

**Comment by TingLei-NOAA** [comment]
@RussTreadon-NOAA   I had given my approval of this PR.  About "resolving "the conversation, I think, as we had discussed/verificed before, we have no "access/permission " to do this except for  persons like you who have writing access to the trunk can do it.  Is this github policy changed?  I still failed to see that "resolving " button" .

**Review by shoyokota — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
@TingLei-NOAA , if a reviewer does not have a button to click _resolve_, the reviewer should enter text in the comment window stating that the developer's response is satisfactory.   This allows others to close a comment with certainty.

**Review by RussTreadon-NOAA — APPROVED** [review]
Two peer review approvals given.   Ctests run and documented.

**Comment by RussTreadon-NOAA** [comment]
@jderber-NOAA , I clicked all the checkboxes except the first.   Would you please confirm that you can check `Bug fix (non-breaking change which fixes an issue)` as complete?

I think you can do so as the PR author.

**Comment by jderber-NOAA** [comment]
Box checked.

**Comment by jderber-NOAA** [comment]
oops.

**Comment by RussTreadon-NOAA** [comment]
Cross check with GSI Handling Review team.    This PR is ready to merge!

**Comment by TingLei-NOAA** [comment]
> @TingLei-NOAA , if a reviewer does not have a button to click _resolve_, the reviewer should enter text in the comment window stating that the developer's response is satisfactory. This allows others to close a comment with certainty.

Thanks for this clarification!
