### PR TITLE
Cads for andrew

### LINKED ISSUE #428: Develop and test new infrared cloud detection routines
We plan to test two different techniques to identify clear/cloudy infrared channels within the GSI.  The two targeted are CO2_slicing (Wylie and Menzel) and dual regression (McNally and Watts).

### PR DESCRIPTION
**Pull request by wx20jjung**
**Description**

Fixes #428 

**Type of change**

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

**DUE DATE for this PR is 10/12/2023.** If this PR is not merged into `develop` by this date, the PR will be closed and returned to the developer.

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@wx20jjung , who would you like as peer reviewers for this PR?

**Comment by wx20jjung** [comment]
Russ
I suggest Andrew Collard and/or anyone interested in this new IR cloud detection software.  There is a lot of code here for one person.  I would hope NASA would also be interested in reviewing.

This is issue #428

**Comment by RussTreadon-NOAA** [comment]
> Russ I suggest Andrew Collard and/or anyone interested in this new IR cloud detection software. There is a lot of code here for one person. I would hope NASA would also be interested in reviewing.
> 
> This is issue #428

I added Andrew as a reviewer.  We need one additional peer reviewer as documented in the [_GSI code management policy_](https://github.com/NOAA-EMC/GSI/wiki/GSI---Code-Management-Policy).  I can be the handling reviewer.  I can't be a peer reviewer.

**Comment by RussTreadon-NOAA** [comment]
Please run GSI ctests and post results, along with explanation of findings, in either this PR or issue #428.

**Comment by wx20jjung** [comment]
Russ,

This is my first time through this process.  What are the crests I need to
run?  Are they the 4 tests that ran when I opened this PR?  If they are
something else,  I will need instructions.

Jim

**Comment by RussTreadon-NOAA** [comment]
Please read through [GSI Ctests (regression tests)](https://github.com/NOAA-EMC/GSI/wiki/GSI-Ctests-(regression-tests)) for guidance on how to run ctests.

**Comment by wx20jjung** [comment]
My ctests are failing with this error:
 SpcCoeff_ReadFile(Binary)(FAILURE) : File ./viirs-m_j1.SpcCoeff.bin not found.
application called MPI_Abort(MPI_COMM_WORLD, 71) - process 24
 CRTM_SpcCoeff_Load(FAILURE) : Error reading SpcCoeff file #2, ./viirs-m_j1.SpcCoeff.bin
 READ_CRIS:  ***ERROR*** crtm_spccoeff_load error_status=           3
    TERMINATE PROGRAM EXECUTION

This is VIIRS for N20.  I am surprised it is not in your CRTM version.  This code will also need VIIRS for N21 (viirs-m_j2).  This is part of CADS so I can put the namelist variable in front of it but the NSST should also be using VIIRS radiances.

Jim

**Comment by RussTreadon-NOAA** [comment]
Which ctest is the error you reported from?    I checked the run directory for the global_3dvar ctest.   I see `viirs-m_j1.SpcCoeff.bin ` in the `crtm_coeffs` sub-directory in the job run directory.

On which machine you running ctests?

**Comment by wx20jjung** [comment]
I am finding them in
 hwrf_nmm_d2_loproc_updat 

Some of the other ctest directories have the viirs crtm files copied into them.  I am in a different group.  Could I have permission problems for this test?  Another possibility is that CrIS radiances are used but not VIIRS radiances so the setup script is not copying VIIRS spccoef files to the working directory.

Similar problems should be happening with IASI but I am not finding them.  The read_iasi now needs AVHRR files similar to read_cris needing VIIRS.

**Comment by RussTreadon-NOAA** [comment]
You identified the problem.   

The CRTM coefficients copied to the run directory are based on the satinfo file as shown by the following extract from `hwrf_nmm_d2.sh`
```
# Copy CRTM coefficient files based on entries in satinfo file                                                                  
for file in `awk '{if($1!~"!"){print $1}}' ./satinfo | sort | uniq` ;do                                                         
    $ncp $fixcrtm/${file}.SpcCoeff.bin ./
    $ncp $fixcrtm/${file}.TauCoeff.bin ./
done
```
The hwrf_nmm_d2 ctest uses `hwrf_satinfo.txt`.   This satinfo file does not include viirs.   

While we can add viirs to the hwrf satinfo file, this alone won't get this test to pass.   The CASES directory for the `hwrf_nmm_d2` test does NOT include viirs dump files.   Can the requirement for viirs be placed on a namelist flag?

**Comment by wx20jjung** [comment]
I think I can (famous last words).

I will make the sensorlist allocatable based on the cris_cads flag.  The rest should be able to be wrapped around if statements.  Should I do the same for IASI, to keep them consistent? 

This means hwrf will not be able to use CADS for CrIS.

**Comment by RussTreadon-NOAA** [comment]
> I think I can (famous last words).
> 
> I will make the sensorlist allocatable based on the cris_cads flag. The rest should be able to be wrapped around if statements. Should I do the same for IASI, to keep them consistent?
> 
> This means hwrf will not be able to use CADS for CrIS.

Yes, I think a similar change for IASI for consistency is desirable.   As an aside, what happens if there is a GFS cycle in which we have CrIS and/or IASI dumps but the VIIRS dump is missing?

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 ctest**
Install `wx20jjung:CADS_for_Andrew` on WCOSS2 (Cactus).  Encounter problem with fix.   `git status` after recursive clone indicates that `fix` has been modified.  `git submodule sync` followed by `git submodule update` fails with the message

```
Synchronizing submodule url for 'fix'
russ.treadon@clogin07:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616> git submodule update
fatal: remote error: upload-pack: not our ref 99f147cc7a55032b329bcd4f738cabd28b129295
fatal: Fetched in submodule path 'fix', but it did not contain 99f147cc7a55032b329bcd4f738cabd28b129295. Direct fetching of that commit failed.
fatal: 
```
Ignore this for the time being and build `wx20jjung:CADS_for_Andrew`.  Run ctests with the following results
```
russ.treadon@clogin08:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616/build> ctest -j 9
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #4: hwrf_nmm_d2 ......................***Failed  240.52 sec
2/9 Test #8: netcdf_fv3_regional ..............***Failed  543.81 sec
3/9 Test #9: global_enkf ......................   Passed  674.98 sec
4/9 Test #5: hwrf_nmm_d3 ......................   Passed  678.67 sec
5/9 Test #7: rrfs_3denvar_glbens ..............   Passed  786.33 sec
6/9 Test #6: rtma .............................   Passed  1272.58 sec
7/9 Test #3: global_4denvar ...................***Failed  1562.93 sec
8/9 Test #1: global_3dvar .....................***Failed  1622.78 sec
9/9 Test #2: global_4dvar .....................   Passed  1622.76 sec

56% tests passed, 4 tests failed out of 9

Total Test time (real) = 1622.83 sec

The following tests FAILED:
          1 - global_3dvar (Failed)
          3 - global_4denvar (Failed)
          4 - hwrf_nmm_d2 (Failed)
          8 - netcdf_fv3_regional (Failed)
Errors while running CTest
```

The reason for the `hwrf_nmm_d2` failure has already been explained.   

The `netcdf_fv3_regional` failure is due to non-reproducible results
```
The results (penalty) between the two runs are nonreproducible,
thus the regression test has Failed on cost for netcdf_fv3_regional_loproc_updat and netcdf_fv3_regional_loproc_contrl analyses.
```
The initial radiance penalties differ in the last 2 of 17 printed digits
contrl:  `1.8612244671704459E+04`
updat: `1.8612244671704462E+04`
This difference is at the level of double precision round off.

The `global_3dvar` failure is also due to non-reproducible results between _updat_ and _contrl_.  The initial step size differs in the 14th of 19 printed digits.   This difference is at double precision round off level.

The `global_4denvar` failure also due to non-reproducible results between _updat_ and _contrl_.  The initial step size differs in the 15th of 19 printed digits.  This difference is at double precision round off level.

I do not know if the above differences are expected given the changes in this PR.

**Comment by wx20jjung** [comment]
The VIIRS information (or AVHRR for IASI)  that is needed is within the CrIS BUFR file.  For CrIS it is 'CRISCS' for IASI it is 'IASIL1CS' so both are independent of the NSST dump files.   

For both, the values are in radiance units so the CRTM planck function needs to be called to convert them to brightness temperatures.

**Comment by RussTreadon-NOAA** [comment]
> The VIIRS information (or AVHRR for IASI) that is needed is within the CrIS BUFR file. For CrIS it is 'CRISCS' for IASI it is 'IASIL1CS' so both are independent of the NSST dump files.
> 
> For both, the values are in radiance units so the CRTM planck function needs to be called to convert them to brightness temperatures.

Thanks for the clarification.  Could we encounter the situation that either the CrIS or IASI bufr dump files do not contain the expected VIIRS or AVHRR information?

**Comment by wx20jjung** [comment]
Russ,

Thanks for continuing to ask questions!  This is helping me to develop something which will be suitable for operations. 

To answer your latest question directly, if the viirs information is missing in the cris bufr, the various derived values are set to zero and CADS responds appropriately.  

The current failure is due to a missing viirs coefficient file.  In read_cris.f90, if the cris coefficient file is missing, it causes a hard failure.  Here is an excerpt of the code.

 if ( sc(1)%sensor_id(1:4) == 'cris' )then
     sensorindex_cris = 1
  else
     write(6,*)'READ_CRIS: ***ERROR*** sensorindex_cris not set  NO CRIS DATA USED'
     write(6,*)'READ_CRIS: We are looking for ', sc(1)%sensor_id, '   TERMINATE PROGRAM EXECUTION'
     call stop2(71)
  end if

I have similar code for viirs.
!  find imager sensorindex.
  sensorindex_imager = 0
  if ( sc(2)%sensor_id(1:4) == 'viir' )then
     sensorindex_imager = 2
  else
     write(6,*)'READ_CRIS: ***ERROR*** sensorindex_imager not set  NO CRIS DATA USED'
     write(6,*)'READ_CRIS: We are looking for ', sc(2)%sensor_id, '   TERMINATE PROGRAM EXECUTION'
     call stop2(71)
  end if

The call stop2() causes the gsi abort.

If I change the call stop2() to a flag  that will fill the various values with zero, it should stop the gsi from an abort and allow CADS to still work without the viirs information.  This same change can be applied to iasi.

**Comment by wx20jjung** [comment]
I put in changes I thought would work for the missing viirs coefficient file.  They did not work.  I traced the error message back to the CRTM itself.  I do not know how to code around it.  

My minimal static tests with the C192 global gsi were bit identical through both the 1-50 and 1-150 loop iterations on S4.  My changes are limited to CrIS and IASI channel use selections.  If the CrIS and IASI channel use counts at the beginning of the first outer loop are identical, my code should not change results.

**Comment by wx20jjung** [comment]
Added code to check for the existence of the imager (VIIRS and AVHRR) spectral coefficient files, similar to code in read_bufrtovs.f90.  If the file does not exist, disable the imager tests withing CADS.

The regression tests were run:
    Start 1: [=[global_3dvar]=]
    Start 2: [=[global_4dvar]=]
    Start 3: [=[global_4denvar]=]
    Start 4: [=[hwrf_nmm_d2]=]
    Start 5: [=[hwrf_nmm_d3]=]
    Start 6: [=[rtma]=]
    Start 7: [=[rrfs_3denvar_glbens]=]
    Start 8: [=[netcdf_fv3_regional]=]
    Start 9: [=[global_enkf]=]
1/9 Test #7: [=[rrfs_3denvar_glbens]=] ........***Failed  1812.36 sec
2/9 Test #8: [=[netcdf_fv3_regional]=] ........***Failed  3849.91 sec
3/9 Test #5: [=[hwrf_nmm_d3]=] ................   Passed  3860.44 sec
4/9 Test #3: [=[global_4denvar]=] .............   Passed  3947.95 sec
5/9 Test #4: [=[hwrf_nmm_d2]=] ................   Passed  3969.79 sec
6/9 Test #9: [=[global_enkf]=] ................   Passed  4068.23 sec
7/9 Test #2: [=[global_4dvar]=] ...............   Passed  4383.91 sec
8/9 Test #6: [=[rtma]=] .......................   Passed  4392.52 sec
9/9 Test #1: [=[global_3dvar]=] ...............   Passed  4670.07 sec

78% tests passed, 2 tests failed out of 9

Total Test time (real) = 4670.09 sec

The following tests FAILED:
          7 - [=[rrfs_3denvar_glbens]=] (Failed)
          8 - [=[netcdf_fv3_regional]=] (Failed)
Errors while running CTest

The 2 tests that failed did not pass the scalability tests.
The case has Failed the scalability test.
The slope for the update (12.584751 seconds per node) is less than that for the control (15.111556 seconds per node).
[Jim.Jung@hfe11 netcdf_fv3_regional_loproc_updat_vs_netcdf_fv3_regional_loproc_contrl]$

The case has Failed the scalability test.
The slope for the update (35.680726 seconds per node) is less than that for the control (41.582101 seconds per node).
[Jim.Jung@hfe11 rrfs_3denvar_glbens_loproc_updat_vs_rrfs_3denvar_glbens_loproc_contrl

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 ctests**

Clone `wx20jjung:CADS_for_Andrew` at [`084eafc`](https://github.com/wx20jjung/GSI/commit/084eafc56f023513a2c99e91ff260bb7efe146db) on Dogwood.  Note that [`084eafc`](https://github.com/wx20jjung/GSI/commit/084eafc56f023513a2c99e91ff260bb7efe146db) is one commit behind the head of NOAA-EMC/GSI `develop`.  Update working copy of `CADS_for_Andrew` with `develop`.  Execute `ush/build.sh` and run ctests with the following results
```
russ.treadon@dlogin08:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616/build> ctest -j 9
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #8: netcdf_fv3_regional ..............***Failed  482.93 sec
2/9 Test #9: global_enkf ......................   Passed  550.03 sec
3/9 Test #7: rrfs_3denvar_glbens ..............   Passed  605.74 sec
4/9 Test #5: hwrf_nmm_d3 ......................   Passed  797.62 sec
5/9 Test #4: hwrf_nmm_d2 ......................***Failed  1027.44 sec
6/9 Test #6: rtma .............................   Passed  1455.09 sec
7/9 Test #3: global_4denvar ...................***Failed  1562.14 sec
8/9 Test #2: global_4dvar .....................   Passed  1743.99 sec
9/9 Test #1: global_3dvar .....................***Failed  1925.09 sec

56% tests passed, 4 tests failed out of 9

Total Test time (real) = 1925.10 sec

The following tests FAILED:
          1 - global_3dvar (Failed)
          3 - global_4denvar (Failed)
          4 - hwrf_nmm_d2 (Failed)
          8 - netcdf_fv3_regional (Failed)
Errors while running CTest
```
All the ctests failures are for the same reason:  the _loproc_updat_ (`wx20jjung:CADS_for_Andrew`) and _loproc_contrl_ (`develop`) analysis results differ.

The initial total penalty and gradient for _updat_ and _contrl_ are identical.  Differences are first evident in the initial step size.   The initial step size differences are small.  They appear to be at the level of `real(8)` numerical round off as shown below
- global_3dvar:  _updat_ has `2.159184180013205445E+00`, _contrl_ has `2.159184180013172583E+00`.  First 13 digits identical.
- global_4denvar:  _updat_ has `1.057506532852621861E+00`, _contrl_ has `1.057506532852622527E+00`.  First 15 digits identical.
- hwrf_nmm_d2:  _updat_ has `4.451070172038970263E+00`, _contrl_ has `4.451070172038968487E+00`.  First 14 digits identical.

The netcdf_fv3_regional difference show up later in the first outer loop minimization.  Minimization printout is identical between _updat_ and _contrl_ for the first two iterations.   Step size differences occur on the third iteration

_updat_ has `9.447501367888225809E-01`, _contrl_ has `9.447501367888222479E-01`.  First 15 digits identical.

The ctests were rerun on Dogwood using the `emc.global` account.   Results, including the failed ctests` are identical to those obtained using `russ.treadon`.

WCOSS2 ctests for @jderber-NOAA 's PR #594 found similar non-reproducible result behavior for the global_4denvar ctest.

It's not clear why _updat_ and _contrl_ analysis results differ on WCOSS2 for the above failed ctests.

Dogwood ctests run in `/lfs/h2/emc/ptmp/russ.treadon/pr616`.   This is a scrubbed disk so run directories will eventually be removed by the system.

**Comment by RussTreadon-NOAA** [comment]
**Orion ctests**

Repeat WCOSS2 test on Orion with the following ctest results
```
Orion-login-3:/work2/noaa/da/rtreadon/git/gsi/pr616/build$ ctest -j 9
Test project /work2/noaa/da/rtreadon/git/gsi/pr616/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #9: global_enkf ......................   Passed  488.28 sec
2/9 Test #8: netcdf_fv3_regional ..............   Passed  603.20 sec
3/9 Test #4: hwrf_nmm_d2 ......................   Passed  607.43 sec
4/9 Test #5: hwrf_nmm_d3 ......................***Failed  977.32 sec
5/9 Test #7: rrfs_3denvar_glbens ..............   Passed  1026.55 sec
6/9 Test #6: rtma .............................   Passed  1330.72 sec
7/9 Test #3: global_4denvar ...................   Passed  1802.49 sec
8/9 Test #2: global_4dvar .....................   Passed  1982.44 sec
9/9 Test #1: global_3dvar .....................   Passed  1982.52 sec

89% tests passed, 1 tests failed out of 9

Total Test time (real) = 1983.15 sec

The following tests FAILED:
          5 - hwrf_nmm_d3 (Failed)
Errors while running CTest
Output from these tests are in: /work2/noaa/da/rtreadon/git/gsi/pr616/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```
The run directory for the ctests is `/work/noaa/stmp/rtreadon/pr616`.  

Examination of the `hwrf_nmm_d3` failure shows it to be due to
```
The runtime for hwrf_nmm_d3_loproc_updat is 325.159779 seconds.  This has exceeded maximum allowable threshold time of 314.678823 seconds,
resulting in Failure time-thresh of the regression test.
```
Indeed the _loproc_updat_ wall time is considerably larger than that for _loproc_contrl_
```
hwrf_nmm_d3_hiproc_contrl/stdout:The total amount of wall time                        = 76.586430
hwrf_nmm_d3_hiproc_updat/stdout:The total amount of wall time                        = 75.040523
hwrf_nmm_d3_loproc_contrl/stdout:The total amount of wall time                        = 262.232353
hwrf_nmm_d3_loproc_updat/stdout:The total amount of wall time                        = 325.159779
```
Orion jobs show greater run to run wall time variability given compute and file system load.  One would need to rerun the `hwrf_nmm_d3` test several times to develop robust timing statistics.

**Comment by RussTreadon-NOAA** [comment]
**Hera ctests**

Repeat WCOSS2 test on Hera with the following ctest results
```
Hera(hfe05):/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr616/build$ ctest -j 9
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr616/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #8: netcdf_fv3_regional ..............   Passed  1349.64 sec
2/9 Test #4: hwrf_nmm_d2 ......................***Failed  1594.44 sec
3/9 Test #5: hwrf_nmm_d3 ......................   Passed  1622.05 sec
4/9 Test #7: rrfs_3denvar_glbens ..............   Passed  1658.57 sec
5/9 Test #9: global_enkf ......................***Failed  1869.97 sec
6/9 Test #6: rtma .............................   Passed  2140.68 sec
7/9 Test #2: global_4dvar .....................   Passed  2595.55 sec
8/9 Test #3: global_4denvar ...................***Failed  2772.04 sec
9/9 Test #1: global_3dvar .....................   Passed  2827.05 sec

67% tests passed, 3 tests failed out of 9

Total Test time (real) = 2827.18 sec

The following tests FAILED:
          3 - global_4denvar (Failed)
          4 - hwrf_nmm_d2 (Failed)
          9 - global_enkf (Failed)
Errors while running CTest
Output from these tests are in: /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr616/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```
The run directory for the ctests is `/scratch1/NCEPDEV/stmp2/Russ.Treadon/pr616`

The `global_4denvar` failure is due to 
```
The runtime for global_4denvar_loproc_updat is 494.397753 seconds.  This has exceeded maximum allowable threshold time of 490.363205 seconds,
resulting in Failure time-thresh of the regression test.
```
A check of the _updat_ and _contrl_ wall times for this test shows _updat_ taking almost 50 seconds longer with the low task count configuration.
```
global_4denvar_hiproc_contrl/stdout:The total amount of wall time                        = 356.083494
global_4denvar_hiproc_updat/stdout:The total amount of wall time                        = 369.191703
global_4denvar_loproc_contrl/stdout:The total amount of wall time                        = 445.784732
global_4denvar_loproc_updat/stdout:The total amount of wall time                        = 494.397753
```
As with Orion, Hera job wall times can vary with system load.   The `global_4denvar` test would need to be run multiple times to obtain robust timing statistics.

The `hwrf_nmm_d2` failure is also due to timing statistics
```
The runtime for hwrf_nmm_d2_loproc_updat is 163.308538 seconds.  This has exceeded maximum allowable threshold time of 144.742514 seconds,
resulting in Failure time-thresh of the regression test.
```
Once again we see the _loproc_updat_ taking noticeably longer to run than the _loproc_contrl_
```
hwrf_nmm_d2_hiproc_contrl/stdout:The total amount of wall time                        = 103.877277
hwrf_nmm_d2_hiproc_updat/stdout:The total amount of wall time                        = 94.759669
hwrf_nmm_d2_loproc_contrl/stdout:The total amount of wall time                        = 120.618762
hwrf_nmm_d2_loproc_updat/stdout:The total amount of wall time                        = 163.308538
```
Interestingly, the _hiproc_updat_ ran faster than the _hiproc_contrl_.  More runs are needed to obtain robust timing statistics.

Two checks, both time related, generated failures for `global_enkf`
```
The runtime for global_enkf_loproc_updat is 111.000574 seconds.  This has exceeded maximum allowable threshold time of 108.124989 seconds,
resulting in Failure timethresh of the regression test.

The runtime for global_enkf_hiproc_updat is 100.901296 seconds.  This has exceeded maximum allowable threshold time of 97.395091 seconds,
resulting in Failure timethresh2 of the regression test.
```
While the _updat_ wall times are greater than the _contrl_ wall times, nothing anomalous jumps out.
```
global_enkf_hiproc_contrl/stdout:The total amount of wall time                        = 88.540992
global_enkf_hiproc_updat/stdout:The total amount of wall time                        = 100.901296
global_enkf_loproc_contrl/stdout:The total amount of wall time                        = 98.295445
global_enkf_loproc_updat/stdout:The total amount of wall time                        = 111.000574
```

**Comment by RussTreadon-NOAA** [comment]
**Summary**

The WCOSS2 non-reproducible results do not occur on Orion or Hera.  This is similar to findings reported in PR #590.  

The situation in PR #590 is even stranger.  Non-reproducbility was not found by all WCOSS2 users.  This is why PR #616 was run on WCOSS2 using both emc.global and russ.treadon.   WCOSS2 PR #616 ctests results are consistent between both users.

It's not clear why running the same code on WCOSS2 can yield non-reproducible results when running the same code on other machines does not.  Something odd happens on WCOSS2.  This _oddness_ may originate in user environment or ctest job configuration errors and _**not**_ system errors.

**Comment by RussTreadon-NOAA** [comment]
Build `CADS_for_Andrew` `gsi.x` in debug mode by setting `BUILD_TYPE=DEBUG` in `ush/build.sh`.   The motivation for doing so was the hope that debug might identify reason(s) why `CADS_for_Andrew` does not reproduce `develop` on WCOSS2.

global_3dvar loproc_updat job aborted with the following traceback
```
forrtl: severe (408): fort: (3): Subscript #1 of the array TEMPERATURE has value 0 which is less than the lower bound of 1

Image              PC                Routine            Line        Source
gsi.x              0000000007A611EF  Unknown               Unknown  Unknown
gsi.x              0000000004F277FD  read_iasi_                943  read_iasi.f90
gsi.x              0000000001A2F6C2  read_obsmod_mp_re        1730  read_obs.F90
```
Line 943 is the `temperature(i)` line from the `read_iasi.f90` loop below
```
!          Put satinfo defined channel temperatures into data array                                                                   
           do l=1,satinfo_nchan
              i = bufr_index(l)
              data_all(l+nreal,itx) = temperature(i)   ! brightness temerature                                                        
           end do
```
I see elsewhere in the code where we check `bufr_index` before using it
```
!          Check for reasonable temperature values                                                                                    
           iskip = 0
           skip_loop: do i=1,satinfo_nchan                                                                                            
              if ( bufr_index(i) == 0 ) cycle skip_loop
              bufr_chan = bufr_index(i)
              if(temperature(bufr_chan) <= tbmin .or. temperature(bufr_chan) > tbmax ) then
                 temperature(bufr_chan) = min(tbmax,max(tbmin,temperature(bufr_chan)))
                 if(iuse_rad(ioff+i) >= 0)iskip = iskip + 1
              endif
           end do skip_loop
```
Seems we need similar logic in the line 943 loop ... or is there a different way to handle this?

This error is **_not_** related to changes in this PR.  I add it here FYI since it may have bearing on `gsi.x` results.

Tag @ADCollard for awareness.

**Comment by jderber-NOAA** [comment]
Russ,

That change is already in my #594 update.

I think the issues are coming from the mpl_allreduce not being reproducible over different numbers of processors.  Working on partial fix now.  I don't understand why this has not been an issue before (unless some changes were made that I don't know about).

**Comment by RussTreadon-NOAA** [comment]
> Russ,
> 
> That change is already in my #594 update.
> 
> I think the issues are coming from the mpl_allreduce not being reproducible over different numbers of processors. Working on partial fix now. I don't understand why this has not been an issue before (unless some changes were made that I don't know about).

Great!  Thank you for [fixing this problem](https://github.com/NOAA-EMC/GSI/pull/594/files#diff-7039c8b1387d31150377e06d6e9f70c3a8cdb758ad26638311dea7d5407fd05f) in `read_iasi.f90`.  I am not aware of any changes to WCOSS2 mpi stuff ... but something may have slipped in.  Not sure.

**Comment by jderber-NOAA** [comment]
Russ,

I think the solution is as simple as changing the stp array in stpcalc.f90 (and a few zero_quads to zero).  Testing more complicated solution and then I will test this solution.

**Comment by wx20jjung** [comment]
Russ,

I put in a similar if statement to what is in read_cris.f90.  The section
now looks like this:
           do l=1,satinfo_nchan
              i = bufr_index(l)
              if ( bufr_index(l) /=0 ) then
                data_all(l+nreal,itx) = temperature(i)   ! brightness
temerature
              else
                data_all(l+nreal,itx) = tbmin
              endif
           end do

I also removed unused variables within my changes as identified by the
debug option.  My single gdasanal reproduced results on S4.  My changes are
pushed back up to CADS_for_Andrew.

Let me know if you want to run tests on this change.  When you are done, I
would like to merge the 2 changes I am behind and run some more tests on S4.

Jim

**Comment by RussTreadon-NOAA** [comment]
Thank you @wx20jjung for cleaning up the code.   

Your branch is now two commits behind the head of `develop`.  Please update to the current head of `develop` when you get a chance.   

Your branch sets the `fix` submodule hash as [99f147c](https://github.com/NOAA-EMC/GSI-fix/tree/99f147cc7a55032b329bcd4f738cabd28b129295).  This hash does not exist.  `develop` currently points at [6a42a29](https://github.com/NOAA-EMC/GSI-fix/tree/6a42a29dbbc9fca3453cc9e829601185555890b9).   Is there a reason you can not use the `fix` that `develop` points at?

**Comment by wx20jjung** [comment]
I do not know why my fix directory is out of sync.  I do not know how to fix it.

CADS_for_Andrew should be up to date except for the fix directory.
Jim

**Comment by RussTreadon-NOAA** [comment]
Much to my surprise I can push changes to your branch.   I updated the `fix` submodule hash in `wx20jjung:CADS_for_Andrew` to point at [6a42a29](https://github.com/NOAA-EMC/GSI-fix/tree/6a42a29dbbc9fca3453cc9e829601185555890b9).   Done at ad6c01111.

**Comment by wx20jjung** [comment]
Thanks Russ.  I should be up to date now.

**Comment by ADCollard** [comment]
@wx20jjung @RussTreadon-NOAA Thanks for your hard work getting the branch to this stage.  I will take a look.

**Comment by RussTreadon-NOAA** [comment]
@wx20jjung , when you have time would you update `wx20jjung:CADS_for_Andrew` with the current head of the authoritative GSI `develop`?   We may need do this a few more times before this PR is approved and merged into develop.

**Comment by wx20jjung** [comment]
CADS_for_Andrew is updated and pushed back to github.  There were no
conflicts.  I will be cycling the new executables within my low resolution
global-workflow.

**Comment by wx20jjung** [comment]
I am getting 2 errors with this merge.  The first is consistent with previous error with the enkf.x (EUPD) but is originating from enkfgdaseobs.  The files generated by enkfgdaseobs are smaller than the previous working version. 
-rwxr-x---  1 jimj domain users  447744000 Sep 14 23:16 enkfgdas.t00z.cnvstat.ensmean.new
-rwxr-x---  1 jimj domain users 1269893120 Sep 14 21:50 enkfgdas.t00z.cnvstat.ensmean.old

-rwxr-x---  1 jimj domain users  583198720 Sep 14 22:46 enkfgdas.t00z.obsinput.ensmean.new
-rwxr-x---  1 jimj domain users  595322880 Sep 14 21:38 enkfgdas.t00z.obsinput.ensmean.old

-rwxr-x---  1 jimj domain users 3968829440 Sep 14 23:17 enkfgdas.t00z.radstat.ensmean.new
-rwxr-x---  1 jimj domain users 4162058240 Sep 14 21:50 enkfgdas.t00z.radstat.ensmean.old

A similar error is found in the dayfile:
 2:    79          cris-fsr_n21  num_obs_tot=   1937164
41:  **   ERROR: The specified variable 'Obs_Time' does not exist!
41:  ** Failed to read NetCDF4.
40:  **   ERROR: The specified variable 'Obs_Time' does not exist!
40:  ** Failed to read NetCDF4.

The second error is also part of the enkf.  This error is in enkfgdaseobs:
 0:  Failed to create directory dir.0000 for PE 0000
(etc)
Yet the directories exist.  This is the part of obsmod.F90 creating the error.
#ifdef __INTEL_COMPILER
             l_mkdir_stat = MAKEDIRQQ(trim(loc_dirname))
             if(.not. l_mkdir_stat) then
                write(6, *) "Failed to create directory ", trim(loc_dirname), " for PE ", loc_pe_name
                call stop2(678)
             endif
#else

When the call stop2(678) is commented out, enkfgdaseobs runs to completion.
I am using the intel compiler 2022.1, called by build.sh
Are these errors only occurring on S4?

**Comment by RussTreadon-NOAA** [comment]
What are the hashes of your working copy of g-w and gsi?  Are there any local changes in either?  It's hard to troubleshoot without being able to log onto S4 to examine HOMEgfs, EXPDIR, and ROTDIR.   While the problem may indeed be in the GSI, this question should be first posted in a g-w issue, not a GSI PR.

**Comment by wx20jjung** [comment]
The global workflow is:
commit cdea83a44f571edbb56652f5b65339fbd55645f6
Merge: b9a5228 b5d173f
Author: David Huber ***@***.***>
Date:   Wed Apr 26 20:12:30 2023 +0000

The GSI is from my merge this AM
commit d8bf8c9265f3eaf899346f1e569ef92b6c27512e
Merge: ad6c011 c46f590
Author: wx20jjung ***@***.***>
Date:   Thu Sep 14 13:50:16 2023 +0000

    Merge remote-tracking branch 'emc/develop' into CADS_for_Andrew

I am sure there are local changes in the global-workflow as I doubt Dave
pushed everything back.

There are similarities with my previous merge.  The previous version had
errors with ozone files.  This version has problems with CrIs.  The
directory generation error (MAKEDIRQQ) is new.

**Comment by RussTreadon-NOAA** [comment]
Two comments

1. Apr 26 is an old snapshot of g-w.
2. `wx20jjung:CADS_for_Andrew` now contains the Intel 2022 update.   While `gsi_s4.lua` has been updated to intel/2022.1, I never tested this on S4.  I do not have a S4 account.   I believe Dave tested the intel/2022.1 build on S4 but I can't vouch for this.   You mention `MAKEDIRQQ`.  This was an intel/2022 addition.

I would reach out to Dave and go from there.  Additional work may be needed to get the GSI to work on S4 and/or your workflow needs to be updated.

**Comment by wx20jjung** [comment]
Start 1: [=[global_3dvar]=]
    Start 2: [=[global_4dvar]=]
    Start 3: [=[global_4denvar]=]
    Start 4: [=[hwrf_nmm_d2]=]
    Start 5: [=[hwrf_nmm_d3]=]
    Start 6: [=[rtma]=]
    Start 7: [=[rrfs_3denvar_glbens]=]
    Start 8: [=[netcdf_fv3_regional]=]
    Start 9: [=[global_enkf]=]
1/9 Test #7: [=[rrfs_3denvar_glbens]=] ........   Passed  4213.14 sec
2/9 Test #3: [=[global_4denvar]=] .............   Passed  4252.83 sec
3/9 Test #9: [=[global_enkf]=] ................   Passed  4259.42 sec
4/9 Test #8: [=[netcdf_fv3_regional]=] ........   Passed  4574.56 sec
5/9 Test #4: [=[hwrf_nmm_d2]=] ................   Passed  4631.30 sec
6/9 Test #5: [=[hwrf_nmm_d3]=] ................   Passed  4638.50 sec
7/9 Test #6: [=[rtma]=] .......................   Passed  4993.78 sec
8/9 Test #1: [=[global_3dvar]=] ...............   Passed  5093.16 sec
9/9 Test #2: [=[global_4dvar]=] ...............   Passed  5886.27 sec

100% tests passed, 0 tests failed out of 9

Total Test time (real) = 5886.29 sec

Output is available on hera at /scratch1/NCEPDEV/stmp2/Jim.Jung/update

File: src/gsi/qcmod.f90 [hunk 1]
```diff
@@ -2262,55 +2292,141 @@ subroutine qc_irsnd(nchanl,is,ndat,nsig,ich,sea,land,ice,snow,luse,goessndr,   &
...
+             cluster_bt, chan_stdev, model_bt, i_flag_cloud, cldp )
 
-  end do
-  if ( lcloud > 0 ) then  ! If cloud detected, reject channels affected by it.
+  else
+     call emc_legacy_cloud_detect(nchanl,nsig,tsavg5,trop5,prsltmp,tvp,ts,tbc,temp,varinv_use,lcloud,cloudp,cldp)
+
+  endif
+
+! Translate CADS cloudy/clear channels to GSI required infomation.
```
Comment (ADCollard) [inline src/gsi/qcmod.f90]: "information"

File: src/gsi/read_cris.f90 [hunk 2]
```diff
@@ -447,6 +500,9 @@ subroutine read_cris(mype,val_cris,ithin,isfcalc,rmesh,jsatid,gstime,&
               bufr_chan_test(:)=0
            endif    ! allocation if
 
+!JAJ           call ufbint(lnbufr,gcrchn_val,1,1,iret, '{GCRCHN}')
+!JAJ      if (gcrchn_val /= 12.0_r_kind) write(*,*) 'JAJ gcrchn', gcrchn_val,iret
+
```
Comment (ADCollard) [inline src/gsi/read_cris.f90]: Remove comments

File: src/gsi/setuprad.f90 [hunk 3]
```diff
@@ -937,10 +957,72 @@ subroutine setuprad(obsLL,odiagLL,lunin,mype,aivals,stats,nchanl,nreal,nobs,&
           total_cloud_cover = tcc(1)
           cld = total_cloud_cover
         else
+
+!  If not allsky
```
Comment (ADCollard) [inline src/gsi/setuprad.f90]: What does this comment mean?

File: src/gsi/setuprad.f90 [hunk 4]
```diff
@@ -937,10 +957,72 @@ subroutine setuprad(obsLL,odiagLL,lunin,mype,aivals,stats,nchanl,nreal,nobs,&
...
+          if ((iasi_cads .and. iasi) .or. (cris_cads .and. cris)) then
+               call destroy_crtm
+               itmp1_cads = len(trim(obstype))
+               itmp2_cads = len(trim(isis))
+             if ( iasi ) then
+               isis_cads = 'avhrr3'//isis(itmp1_cads+1:itmp2_cads)
+               obstype_cads = 'avhrr'
+               nchanl_cads = 3   ! CRTM channels 3 - 5
+             elseif ( cris ) then
+!!               isis_cads = 'viirs-m'//isis(itmp1+1:itmp2)
```
Comment (ADCollard) [inline src/gsi/setuprad.f90]: Remove comments?

Comment (wx20jjung) [reply src/gsi/setuprad.f90]: I removed the various comments except the last one (isis_cads = 'viirs-m'.......
This line will replace the following lines when the satellite id for viirs becomes consistent with cris.  Similar comments exist within read_cris.f90

**Review by ADCollard — APPROVED** [review]
I made a visual inspection of the code and all seems to be as it should be.   I also confirmed that all ctests pass.   I am approving with the understanding that we can make minor adjustments as testing proceeds.

**Comment by RussTreadon-NOAA** [comment]
@wx20jjung , GSI `develop` was updated this morning.   Please update `wx20jjung:CADS_for_Andrew` with the current head of `develop` and we'll schedule this PR for merger into `develop`.

**Comment by RussTreadon-NOAA** [comment]
**Hera ctests**
Build `wx20jjung:CADS_for_Andrew` at [93d68b5](https://github.com/wx20jjung/GSI/commit/93d68b52e9d97c39770311a520470d641f1c2d0e).  Run ctests with following results
```
Hera(hfe11):/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr616/build$ ctest -j 9
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr616/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #5: hwrf_nmm_d3 ......................   Passed  497.59 sec
2/9 Test #7: rrfs_3denvar_glbens ..............   Passed  551.83 sec
3/9 Test #4: hwrf_nmm_d2 ......................   Passed  608.25 sec
4/9 Test #8: netcdf_fv3_regional ..............   Passed  610.72 sec
5/9 Test #9: global_enkf ......................   Passed  1084.35 sec
6/9 Test #6: rtma .............................   Passed  1213.35 sec
7/9 Test #3: global_4denvar ...................   Passed  1609.83 sec
8/9 Test #2: global_4dvar .....................   Passed  1743.23 sec
9/9 Test #1: global_3dvar .....................   Passed  1849.03 sec

100% tests passed, 0 tests failed out of 9

Total Test time (real) = 1849.04 sec
```

**Comment by RussTreadon-NOAA** [comment]
**Orion ctests**
Build the current head of `wx20jjung:CADS_for_Andrew` on Orion and run ctests with following results
```
Orion-login-2:/work2/noaa/da/rtreadon/git/gsi/pr616/build$ ctest -j 9
Test project /work2/noaa/da/rtreadon/git/gsi/pr616/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #8: netcdf_fv3_regional ..............***Failed  487.70 sec
2/9 Test #5: hwrf_nmm_d3 ......................   Passed  498.59 sec
3/9 Test #4: hwrf_nmm_d2 ......................   Passed  610.72 sec
4/9 Test #9: global_enkf ......................***Failed  616.49 sec
5/9 Test #7: rrfs_3denvar_glbens ..............   Passed  669.52 sec
6/9 Test #6: rtma .............................   Passed  1331.51 sec
7/9 Test #3: global_4denvar ...................   Passed  1683.27 sec
8/9 Test #2: global_4dvar .....................   Passed  1922.61 sec
9/9 Test #1: global_3dvar .....................   Passed  1983.09 sec

78% tests passed, 2 tests failed out of 9

Total Test time (real) = 1983.11 sec

The following tests FAILED:
kf.x` wall times in the `global_enkf` test
          8 - netcdf_fv3_regional (Failed)
          9 - global_enkf (Failed)
```
A check of the `netcdf_fv3_regional` and `global_enkf` tests find that both failures were due to the timing scalability check.  Examination of the `netcdf_fv3_regional` `gsi.x` wall times did not find any anomalous behavior.
```
netcdf_fv3_regional_hiproc_contrl/stdout:The total amount of wall time                        = 67.925528
netcdf_fv3_regional_hiproc_updat/stdout:The total amount of wall time                        = 64.686219
netcdf_fv3_regional_loproc_contrl/stdout:The total amount of wall time                        = 86.976721
netcdf_fv3_regional_loproc_updat/stdout:The total amount of wall time                        = 77.317182
```
A similar comment applies for `enkf.x` wall times in the `global_enkf` test
```
global_enkf_hiproc_contrl/stdout:The total amount of wall time                        = 64.727793
global_enkf_hiproc_updat/stdout:The total amount of wall time                        = 66.543622
global_enkf_loproc_contrl/stdout:The total amount of wall time                        = 109.663246
global_enkf_loproc_updat/stdout:The total amount of wall time                        = 96.058297
```
Nothing egregious jumps out in the timings.   Neither the `netcdf_fv3_regional` nor the `global_enkf` fails are viewed as being fatal.

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 ctests**
Build the current head of `wx20jjung:CADS_for_Andrew` on Cactus and run ctests with following results
```
russ.treadon@clogin07:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616/build> ctest -j 9
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616/build
    Start 1: global_3dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 8: netcdf_fv3_regional
    Start 2: global_4dvar
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 9: global_enkf
    Start 5: hwrf_nmm_d3
1/9 Test #8: netcdf_fv3_regional ..............***Failed  662.94 sec
2/9 Test #9: global_enkf ......................   Passed  731.64 sec
3/9 Test #7: rrfs_3denvar_glbens ..............   Passed  785.05 sec
4/9 Test #5: hwrf_nmm_d3 ......................***Failed  913.35 sec
5/9 Test #4: hwrf_nmm_d2 ......................***Failed  966.12 sec
6/9 Test #6: rtma .............................   Passed  1388.76 sec
7/9 Test #2: global_4dvar .....................   Passed  1682.39 sec
8/9 Test #1: global_3dvar .....................***Failed  1683.30 sec
9/9 Test #3: global_4denvar ...................***Failed  1742.09 sec

44% tests passed, 5 tests failed out of 9

Total Test time (real) = 1742.51 sec

The following tests FAILED:
          1 - global_3dvar (Failed)
          3 - global_4denvar (Failed)
          4 - hwrf_nmm_d2 (Failed)
          5 - hwrf_nmm_d3 (Failed)
          8 - netcdf_fv3_regional (Failed)
```

All failures except `hwrf_nmm_d3` are due to non-reproducible results.   

`global_3dvar`
The initial total penalties and gradients are identical between the _updat_ and _contrl_.  Differences arise in the first iteration step size calculation.  The step sizes are identical for 14 to 19 of the printed digits.  This appears to be a numerical roundoff issue.

`global_4denvar`
The initial total penalties and gradients are identical between the _updat_ and _contrl_.  Differences arise in the first iteration step size calculation.  The step sizes are identical for 15 to 19 of the printed digits.  This appears to be a numerical roundoff issue.

`hwrf_nmm_d2`
The initial total penalties and gradients are identical between the _updat_ and _contrl_.  Differences arise in the first iteration step size calculation.  The step sizes are identical for 14 to 19 of the printed digits.  This appears to be a numerical roundoff issue.

`hwrf_nmm_d3`
This ctest fails due to the timing scalability check.   Examination of the `gsi.x` wall times shows the _loproc_contrl_ running noticeably longer than the _updat_ 
```
hwrf_nmm_d3_hiproc_contrl/stdout:The total amount of wall time                        = 53.862719
hwrf_nmm_d3_hiproc_updat/stdout:The total amount of wall time                        = 57.323576
hwrf_nmm_d3_loproc_contrl/stdout:The total amount of wall time                        = 70.830697
hwrf_nmm_d3_loproc_updat/stdout:The total amount of wall time                        = 55.830777
```

`netcdf_fv3_regional`
The initial total penalties are identical between the _updat_ and _contrl_.   Differences arise in the first iteration gradient.  15 of the printed 19 digits are identical.   This appears to be a numerical roundoff issue.

The non-reproducible results from the WCOSS2 tests is troubling.  Interestingly, we do not see this behavior on Orion or Hera.  The Orion and Hera builds use intel/2022 compiler whereas the WCOSS2 build still uses intel/19.

**Comment by RussTreadon-NOAA** [comment]
A check of the _updat_ and _contrl_ `stdout` files shows that the _updat_ `stdout` is 3x larger than _contrl_.  This is a significant 
increase.   

The `wx20jjung:CADS_for_Andrew` code adds many lines of `CLOUD DETECTION` printout.   We should either (a) limit this runtime printout to a single mpi rank or (b) restrict this printout to `verbose=.true.` blocks.

File: src/gsi/cads.f90 [hunk 5]
```diff
@@ -0,0 +1,2064 @@
...
+    READ(INIU1,nml=Cloud_Detect_Coeffs,IOSTAT=IOS)
+    IF (IOS /= 0) THEN
+      CALL CADS_Abort('PROBLEM READING '//TRIM(CL__InstrumentName)//&
+                     'CLOUD DETECTION FILE')
+!    ELSE
+!      WRITE(*,'(3X,A)') TRIM(CL__InstrumentName) // &
+!           ' CLOUD DETECTION FILE READ OK'
+    ENDIF
+  ELSE
+    WRITE(*,'(3X,A)') 'NO '//TRIM(CL__InstrumentName) // &
```
Comment (RussTreadon-NOAA) [inline src/gsi/cads.f90]: Limit this printout to a single task or only execute when `verbose=.true.`

Comment (RussTreadon-NOAA) [reply src/gsi/cads.f90]: While [`1196943`](https://github.com/NOAA-EMC/GSI/pull/616/commits/1196943318f109734e03078b4cf8bf8aa9ea082d) places the CADS printout inside a an `if verbose` block, the subroutine call to `CADS_Setup_Cloud` is placed before `gsi.x` reads the `SETUP` namelist.   See the following code from `gsimod.F90`
```
  call gsi_nstcoupler_init_nml
  call init_radaruse_directDA
  call CADS_Setup_Cloud

 if(mype==0) write(6,*)' at 0 in gsimod, use_gfs_stratosphere,nems_nmmb_regional = ', &
                       use_gfs_stratosphere,nems_nmmb_regional


! Read user input from namelists.  All processor elements                                                                                               
! read the namelist input.  SGI MPI FORTRAN does not allow                                                                                              
! all tasks to read from standard in (unit 5).  Hence, open                                                                                             
! namelist to different unit number and have each task read                                                                                             
! namelist file.                                                                                                                                        
#ifdef ibm_sp
! Initialize table of instruments and data types                                                                                                        
  read(5,setup)
```
Thus, the default value of `verbose=.false.` is always used.  We do not see CADS printout even when `verbose=.true.`

The call to `CADS_Setup_Cloud` needs to be after namelist `SETUP` is read if we want `verbose=.true.` to toggle on CADS printout.

**Comment by wx20jjung** [comment]
Using mype for the write statements does not give consistent results.  Some
instruments may not use a specific pe.  These output statements are
generally for developers and the initial setup.  I will remove them.

**Comment by RussTreadon-NOAA** [comment]
`verbose=.true.` runs show _updat_ and _contrl_ `gsi.x` generate comparable amounts of run time output.  The same comment applies to `verbose=.false.` runs of `gsi.x`.  This is expected given the changes committed at [`d9284b0`](https://github.com/NOAA-EMC/GSI/pull/616/commits/d9284b06c372b62233672f87d996981a70a4cb35).

The difference between _updat_ and _contrl_ analysis results on WCOSS2 (Cactus) is troubling.   Operations runs on WCOSS2.  It's important to understand and document why a PR alters analysis results.   

Can you, @wx20jjung , think of any reasons WCOSS2 analysis results would differ?   Have we changed the order or precision of calculations in `wx20jjung:CADS_for_Andrew` with respect to `develop`?

**Comment by wx20jjung** [comment]
The CADS software, when used, should only change the clear/cloudy channel
use for CrIS and IASI.  The profile selection for CrIS and IASI has not
changed.  The imager information (VIIRS and AVHRR) for CADS was added to
the data_all array from the read_iasi/cris which is written for setuprad.
If there were errors here, all the machines would show differences.  The
quality control procedures, calls to the CRTM and beyond have not changed.
Everything I added uses r_kind or i_kind so byte size should be consistent.

I will run a comparison of develop and CADS_for_Andrew in my
global-workflow to see if I get differences. I have not done this since the
compiler version change. If I can't reproduce these differences on S4, I
don't know how I can help.

**Comment by ADCollard** [comment]
@wx20jjung @RussTreadon-NOAA I will dig into these differences on WCOSS2

**Comment by wx20jjung** [comment]
My single cycle test of develop and CADS_for_Andrew on S4 generated
identical answers.

**Comment by RussTreadon-NOAA** [comment]
Back to square one after updating my working copy of `wx20jjung:CADS_for_Andrew` to [f07a4e9](https://github.com/NOAA-EMC/GSI/pull/616/commits/f07a4e95d864695bacac6db9d448895502ade691).  WCOSS2 _contrl_ (`develop`) and _updat_ (`wx20jjung:CADS_for_Andrew`) results differ in the minimization.

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 tests**
Extensive testing and debugging on WCOSS2 (Cactus) has not definitively identified a reason for different analysis results between `gsi.x` built from `wx20jjung:CADS_for_Andrew` and `develop` for select ctests.  The initial total penalties are identical to 19 printed digits.  The initial gradients differ in the 16th of 19 printed digits.

Identical analysis results can be obtained on WCOSS2 between the two branches in the following situations
- build both branches in debug mode (`BUILD_TYPE=Debug`) on Cactus using intel/19 modules
- build both branches in release mode (`BUILD_TYPE=Release`) on Acorn using Mark Potts' intel/2022 spack-stack modules

Are we dealing with an intel/19 compiler optimization issue?

**Comment by RussTreadon-NOAA** [comment]
**`emc_legacy_cloud_detect` question**

Comparison of `emc_legacy_cloud_detect` in `wx20jjung:CADS_for_Andrew` with comparable code in subroutine `qc_irsnd` in `develop` makes me to wonder if what's in `emc_legacy_cloud_detect` is correct.

Variable `cloudp` is an output variable in `emc_legacy_cloud_detect`.  `cloudp` is potentially updated every time we enter the `prsltmp(k) > trop5` block in the k loop.   The `cldp` variable, another output variable, is inside a deeper if test.  We have the following in `emc_legacy_cloud_detect`
```
        if (abs(sum2) < tiny_r_kind) sum2 = sign(tiny_r_kind,sum2)
        cloudp=min(max(sum/sum2,zero),one)
        sum=zero
        do i=1,nchanl
           if(varinv_use(i) > tiny_r_kind)then
              tmp=tbc(i)-cloudp*dtb(i)
              sum=sum+tmp*tmp*varinv_use(i)
           end if
        end do
        if(sum < sum3)then
           sum3=sum
           lcloud=k
           cldp=r10*prsltmp(k)
        end if
```

Looking at the comparable code in `develop` `qcmod.f90` we find that `cld` functions in the same role as `cloudp`.   However, `develop` sets `cld` inside the same if block as `cldp`.  `develop` has
```
        cloudp=min(max(sum/sum2,zero),one)
        sum=zero
        do i=1,nchanl
           if(varinv_use(i) > tiny_r_kind)then
              tmp=tbc(i)-cloudp*dtb(i)
              sum=sum+tmp*tmp*varinv_use(i)
           end if
        end do                                                                                                                                  
        if(sum < sum3)then
           sum3=sum
           lcloud=k
           cld=cloudp
           cldp=r10*prsltmp(k)
        end if
```

Should we refactor `emc_legacy_cloud_detect` as
```
russ.treadon@clogin03:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616test/src/gsi> git diff qcmod.f90
diff --git a/src/gsi/qcmod.f90 b/src/gsi/qcmod.f90
index 058ce5020..904aa7e11 100644
--- a/src/gsi/qcmod.f90
+++ b/src/gsi/qcmod.f90
@@ -2617,7 +2617,7 @@ subroutine qc_irsnd(nchanl,is,ndat,nsig,ich,sea,land,ice,snow,luse,goessndr,airs
 
 end subroutine qc_irsnd
 
-subroutine emc_legacy_cloud_detect(nchanl,nsig,tsavg5,trop5,prsltmp,tvp,ts,tbc,temp,varinv_use,lcloud,cloudp,cldp)
+subroutine emc_legacy_cloud_detect(nchanl,nsig,tsavg5,trop5,prsltmp,tvp,ts,tbc,temp,varinv_use,lcloud,cld,cldp)
 
 !$$$ subprogram documentation block
 !               .      .    .
@@ -2645,7 +2645,7 @@ subroutine emc_legacy_cloud_detect(nchanl,nsig,tsavg5,trop5,prsltmp,tvp,ts,tbc,t
 !     
 ! output argument list:
 !     lcloud       - model layer of cloud
-!     cloudp       - derived cloud amount
+!     cld          - derived cloud amount
 !     cldp         - model layer pressure (hPa) of cloud 
 !
 ! attributes:
@@ -2661,14 +2661,14 @@ implicit none
 integer(i_kind),                 intent(in   ) :: nchanl, nsig
 integer(i_kind),                 intent(  out) :: lcloud
 real(r_kind),                    intent(in   ) :: tsavg5, trop5
-real(r_kind),                    intent(  out) :: cloudp, cldp
+real(r_kind),                    intent(  out) :: cld, cldp
 real(r_kind), dimension(nchanl), intent(in   ) :: tbc, ts, varinv_use
 real(r_kind), dimension(nsig,nchanl), intent(in   ) :: temp
 real(r_kind), dimension(nsig),   intent(in   ) :: tvp, prsltmp
 
 integer(i_kind) :: i, k, kk
 
-real(r_kind) :: sum, sum2, sum3, tmp
+real(r_kind) :: sum, sum2, sum3, tmp, cloudp
 real(r_kind),dimension(nchanl) :: dtb
 
   sum3=zero
@@ -2677,6 +2677,7 @@ real(r_kind),dimension(nchanl) :: dtb
   end do
   sum3=0.75_r_kind*sum3
   lcloud=0
+  cld=zero
   cldp=r10*prsltmp(1)
 
   do k=1,nsig
@@ -2709,6 +2710,7 @@ real(r_kind),dimension(nchanl) :: dtb
         if(sum < sum3)then
            sum3=sum
            lcloud=k
+           cld=cloudp
            cldp=r10*prsltmp(k)
         end if
      end if
```

**Comment by RussTreadon-NOAA** [comment]
**`crtm_interface` question**

`wx20jjung:CADS_for_Andrew` adds the `radiance` block below into a threaded section of `crtm_interface.f90`

```
!$omp parallel do  schedule(dynamic,1) private(i) &                                                                                                
!$omp private(total_od,k,kk,m,term,ii,cwj)                                                                                                         
    do i=1,nchanl
!   Zero jacobian and transmittance arrays                                                                                                         
       do k=1,nsig
         omix(k,i)=zero
         temp(k,i)=zero
         ptau5(k,i)=zero
         wmix(k,i)=zero
       end do

       radiance(i)=rtsolution(i,1)%radiance
       do k=msig, 1, -1
          radiance_overcast = rtsolution(i,1)%upwelling_overcast_radiance(k)
          radiance_ratio = abs(radiance_overcast/radiance(i))
          if (radiance_ratio < 0.99_r_kind) then
            chan_level(i) = atmosphere(1)%pressure(k) / r10                                                                                        
            exit
          endif
       enddo
```

I think `radiance` was declared as an array to allow for distinct `radiance(i)` when threading as a function of `i`.  Variables `radiance_overcast` and `radiance_ratio` remain shared in the threaded loop.   Is this safe?

We could change `radiance` to a scalar and add it along with the other two radiance scalars to the `omp private` declaration.  The factored code would look like
```
russ.treadon@clogin03:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616test/src/gsi> git diff crtm_interface.f90
diff --git a/src/gsi/crtm_interface.f90 b/src/gsi/crtm_interface.f90
index 34ff4d230..b2fec8805 100644
--- a/src/gsi/crtm_interface.f90
+++ b/src/gsi/crtm_interface.f90
@@ -1151,11 +1151,11 @@ subroutine call_crtm(obstype,obstime,data_s,nchanl,nreal,ich, &
   real(r_kind):: sno00,sno01,sno10,sno11,secant_term
   real(r_kind):: hwp_total,theta_700,theta_sfc,hs
   real(r_kind):: dlon,dlat,dxx,dyy,yy,zz,garea
-  real(r_kind):: radiance_overcast, radiance_ratio
+  real(r_kind):: radiance, radiance_overcast, radiance_ratio
   real(r_kind),dimension(0:3):: wgtavg
   real(r_kind),dimension(nsig,nchanl):: omix
   real(r_kind),dimension(nsig,nchanl,n_aerosols_jac):: jaero
-  real(r_kind),dimension(nchanl) :: uwind_k,vwind_k,radiance
+  real(r_kind),dimension(nchanl) :: uwind_k,vwind_k
   real(r_kind),dimension(msig+1) :: prsi_rtm
   real(r_kind),dimension(msig)  :: prsl_rtm
   real(r_kind),dimension(msig)  :: auxq,auxdp
@@ -2222,7 +2222,7 @@ subroutine call_crtm(obstype,obstime,data_s,nchanl,nreal,ich, &
     chan_level = zero
 
 !$omp parallel do  schedule(dynamic,1) private(i) &
-!$omp private(total_od,k,kk,m,term,ii,cwj)
+!$omp private(total_od,k,kk,m,term,ii,cwj,radiance,radiance_overcast,radiance_ratio)
     do i=1,nchanl
 !   Zero jacobian and transmittance arrays
        do k=1,nsig
@@ -2232,10 +2232,10 @@ subroutine call_crtm(obstype,obstime,data_s,nchanl,nreal,ich, &
          wmix(k,i)=zero
        end do
 
-       radiance(i)=rtsolution(i,1)%radiance
+       radiance=rtsolution(i,1)%radiance
        do k=msig, 1, -1
           radiance_overcast = rtsolution(i,1)%upwelling_overcast_radiance(k)
-          radiance_ratio = abs(radiance_overcast/radiance(i))
+          radiance_ratio = abs(radiance_overcast/radiance)
           if (radiance_ratio < 0.99_r_kind) then
             chan_level(i) = atmosphere(1)%pressure(k) / r10
             exit
```
This is a more thread safe approach.

**Comment by RussTreadon-NOAA** [comment]
**`setuprad.f90` question**

We have a CADS if-block inside the big n loop over the observations in `setuprad.f90`.   Each call to `setuprad` is for a different `obstype` and `isis` combination.  
```
! Loop over data in this block                                                                                                                     
  call dtime_setup()
  do n = 1,nobs
!    Extract analysis relative observation time.                                                                                                   
     dtime = data_s(itime,n)

...

!  Generate model derived imager values for IASI or CrIS for CADS                                                                                  

          if ((iasi_cads .and. iasi) .or. (cris_cads .and. cris)) then
               call destroy_crtm
               itmp1_cads = len(trim(obstype))
               itmp2_cads = len(trim(isis))
             if ( iasi ) then
               isis_cads = 'avhrr3'//isis(itmp1_cads+1:itmp2_cads)
               obstype_cads = 'avhrr'
               nchanl_cads = 3   ! CRTM channels 3 - 5                                                                                             
             elseif ( cris ) then
!!               isis_cads = 'viirs-m'//isis(itmp1+1:itmp2) When naming convention becomes standarized with CrIS                                   
               if ( isis == 'cris-fsr_npp' ) isis_cads = 'viirs-m_npp'
               if ( isis == 'cris-fsr_n20' ) isis_cads = 'viirs-m_j1'
               if ( isis == 'cris-fsr_n21' ) isis_cads = 'viirs-m_j2'
               obstype_cads = 'viirs-m'
               nchanl_cads = 5   !CRTM channels 12 - 16                                                                                            
             endif
             allocate(data_s_cads(nreal+nchanl_cads),ich_cads(nchanl_cads),tsim_cads(nchanl_cads),emissivity_cads(nchanl_cads), &
                    chan_level_cads(nchanl_cads),ptau5_cads(nsig,nchanl_cads), ts_cads(nchanl_cads),emissivity_k_cads(nchanl_cads), &
                    temp_cads(nsig,nchanl_cads),wmix_cads(nsig,nchanl_cads), jacobian_cads(nsigradjac,nchanl_cads))

             jc = 0
             do k=1,jpch_rad
               if (isis_cads == nusis(k)) then
                 jc = jc +1
                 ich_cads(jc) = k
               endif
             end do

             data_s_cads = data_s(1:nreal+nchanl_cads,n)
             call init_crtm(init_pass,-99,mype,nchanl_cads,nreal,isis_cads,obstype_cads,radmod)

             call call_crtm(obstype_cads,dtime,data_s_cads(:),nchanl_cads,nreal,ich_cads, &
                tvp,qvp,qs,clw_guess,ciw_guess,rain_guess,snow_guess,prsltmp,prsitmp, &
                trop5,tzbgr,dtsavg,sfc_speed, &
                tsim_cads,emissivity_cads,chan_level_cads,ptau5_cads,ts_cads,emissivity_k_cads, &
                temp_cads,wmix_cads,jacobian_cads,error_status)

!  Transfer imager data to arrays for qc_irsnd                                                                                                     

             imager_cluster_fraction = data_s(32:38,n)
             imager_cluster_bt(1,:) = data_s(39:45,n)
             imager_cluster_bt(2,:) = data_s(46:52,n)
             imager_chan_stdev = data_s(53:54,n)
             imager_model_bt = tsim_cads(nchanl_cads-1:nchanl_cads)

             deallocate(data_s_cads,ich_cads,tsim_cads,emissivity_cads, &
                      chan_level_cads,ptau5_cads, ts_cads,emissivity_k_cads, &
                      temp_cads,wmix_cads, jacobian_cads)
              call destroy_crtm

!  Re-initialize the crtm for the current instrument                                                                                               
              call init_crtm(init_pass,iwrmype,mype,nchanl,nreal,isis,obstype,radmod)

            endif  ! end of section for colocated imagers,      
```

Three questions.  

1. Each entry into `setuprad` is for a unique `obstype` and `isis` combination.  Given this, can we move some of the CADS setup stuff before the big `do n` loop over all the observations?

2. Before entering the CADS block `crtm_init` has been called using `radmod`.  The code references `radmod%` component. 
 When we call `crtm_init` from inside the CADS block, we reuse `radmod`.   Before we exit the CADS block we call `crtm_init` again with `radmod`.  Is is safe to reuse and reset `radmod` inside the CADS block?  Would it be safer to declare and use a new variable, say `radmod_cads` inside the CADS block?

3.    In the CADS block we load `data_s_cads` with a subset of values from `data_s`.   We call `call_crtm` with `data_s_cads`.  After this we load `imager_*` arrays with values from `data_s`
```
             data_s_cads = data_s(1:nreal+nchanl_cads,n)
             call init_crtm(init_pass,-99,mype,nchanl_cads,nreal,isis_cads,obstype_cads,radmod)

             call call_crtm(obstype_cads,dtime,data_s_cads(:),nchanl_cads,nreal,ich_cads, &
                tvp,qvp,qs,clw_guess,ciw_guess,rain_guess,snow_guess,prsltmp,prsitmp, &
                trop5,tzbgr,dtsavg,sfc_speed, &
                tsim_cads,emissivity_cads,chan_level_cads,ptau5_cads,ts_cads,emissivity_k_cads, &
                temp_cads,wmix_cads,jacobian_cads,error_status)

!  Transfer imager data to arrays for qc_irsnd                                                                                                     

             imager_cluster_fraction = data_s(32:38,n)
             imager_cluster_bt(1,:) = data_s(39:45,n)
             imager_cluster_bt(2,:) = data_s(46:52,n)
             imager_chan_stdev = data_s(53:54,n)
```
   Should we load `data_s_cads` into the `imager_*` arrays instead of `data_s`?

**Comment by jderber-NOAA** [comment]
In addition to Russ's "crtm_interface question" above, I wonder if the determination of chan_level should be surrounded by an if statement since I don't believe this variable is used unless cads is going to be called.

**Comment by jderber-NOAA** [comment]
In qc_irsnd, the call to cloud_aerosol_detection can be moved out of it's current location into the following if statement.  The call to the legacy code can also be moved to the following if (else) statement.  This will make the if-then-else that it is currently in only about defining the input parameters and makes it so that the routine is only called once.  Can any of the legacy routine be moved to the else part of the code to reduce computation?

**Comment by jderber-NOAA** [comment]
Comment for ich5 and ich7 wrong.

 ich5   = 5   !4
  ich6   = 6   !6
  ich7   = 7   !4

**Comment by jderber-NOAA** [comment]
The change of the line

(hirs .and. (j == ich8 )) .or.

to 

               (hirs  .and. (j == ich3 .or. j == ich4 .or. j == ich5 .or.    &
                                  j == ich6 .or. j == ich7 .or. j == ich8 )) .or. &

has the potential to change the results for the legacy qc.

**Comment by jderber-NOAA** [comment]
In read_bufrtovs routine, you are adding a lot of elements to the output array.  It looks to me that some of the locations are not used such as maxinfo+24, maxinfo+25, maxinfo+20, maxinfo+21...  The size of this array should be kept as small as possible since it uses a lot of memory if there is a lot of data.

**Comment by jderber-NOAA** [comment]
Doesn't seem to me that the location in 

         if(dval_use) then
              data_all(32+cads_info,itx)= val_cris
              data_all(33+cads_info,itx)= itt
           end if

is correct.  Seems like it would depend on maxinfo.

Similar in read_iasi.

**Comment by jderber-NOAA** [comment]
Seems like a bunch of code changes that are in read_iasi and read_prepbufr are not in read_airs.

**Comment by jderber-NOAA** [comment]
The lines 

  if (abi2km .and. regional) then
     abi2km_bc = zero
     abi2km_bc(2) = 233.5_r_kind
     abi2km_bc(3) = 241.7_r_kind
     abi2km_bc(4) = 250.5_r_kind
  end if

Should be at the beginning of setuprad so that these values are not reset for each abi observations and that the array does not ever go out of bounds (when nchanl < 4).  That code should be in the trunk.  The resetting of these values in your code should be removed.

**Comment by jderber-NOAA** [comment]
I agree with Russ 100% that the resetting of the CRTM should be avoided and another way of doing this should be found.

**Comment by RussTreadon-NOAA** [comment]
NOAA-EMC/GSI `develop` was updated several times over the past few days.  When you have time, please update `wx20jjung:CADS_for_Andrew` to the current head, [`fae4bbf`](https://github.com/NOAA-EMC/GSI/commit/fae4bbfbb1124fe3ceced4c3639a53172ad2db26), of `develop`

**Comment by RussTreadon-NOAA** [comment]
Thank you @wx20jjung for bringing `CADS_for_Andrew` up to date with the current head of `develop`.  Thank you also for the other changes you made in response to reviewer comments.  

I installed a fresh clone of `CADS_for_Andrew` on Cactus along with a fresh clone of `develop`.  Both were built and ctests runs.   The following ctests fail due to different final analyses

- netcdf_fv3_regional - while initial `o-g 01` `fort.207` printout is identical, the initial radiance penalty in `fort.220` and the initial radiance penalty in the `J Global` `stdout` table differ between `develop` and `CADS_for_Andrew`.  Differences occur in the 16th of 19 printed digits for the `J Global` table and 18th of 18 printed digits in `fort.220`.
- hwrf_nmm_d2 - the initial `J Global` printout is identical.  Differences show up in the stepsize for the first iteration of the first outer loop.  Differences occur in the 15th of 19 printed digits.
- global_3dvar - initial radiance penalties differ in the 4th of 19 printed digits.  This is true in `fort.207`, the initial `J Global` table from `stdout`, and `fort.220`. 

The global_3dvar differences are the most alarming.   A diff of `CADS_for_Andrew` and `develop` `fort.207 shows `o-g 01` differences for the following sensor_satellites
```
russ.treadon@clogin07:/lfs/h2/emc/ptmp/russ.treadon/pr616/tmpreg_global_3dvar> diff global_3dvar_loproc_contrl/fort.207 global_3dvar_loproc_updat/
fort.207 |grep "o-g 01"                                                                                                                          
< o-g 01 rad  n18       avhrr           1560457         2319         1073    358.99       358.99      0.33457      0.33457    
< o-g 01 rad  metop-b   avhrr           2306689         2162         1112    308.53       308.53      0.27746      0.27746    
> o-g 01 rad  n18       avhrr           1560457         2319         1101    376.97       376.97      0.34239      0.34239    
> o-g 01 rad  metop-b   avhrr           2306689         2162         1180    346.16       346.16      0.29336      0.29336    
< o-g 01 rad  n19       avhrr           1580140         2412         1082    365.54       365.54      0.33783      0.33783    
> o-g 01 rad  n19       avhrr           1580140         2412         1150    387.79       387.79      0.33721      0.33721    
```

Have you run ctests on other platforms?

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 global_3dvar**

Run the following test
- change diagnostic output to binary for global_3dvar
- add `write(300+mype,*)` statements to `setuprad.f90` in order to easily view contents of task specific diagnostics.  Do this for both `CADS_for_Andrew` and `develop`
- change number of outer loops to 1 for global_3dvar
- rebuild `develop` and `CADS_for_Andrew`   
- run global_3dvar ctest
- compare `fort.3*` files.   Difference found in `diagbuf(25)`.   For IR sensors `diagbuf(25)` corresponds to 
```
!          Note:  The following quantities are not computed for all sensors                                                                       
           if (.not.microwave) then
              diagbuf(25)  = cld                              ! cloud fraction (%)                                                                
              diagbuf(26)  = cldp                             ! cloud top pressure (hPa)               
```                                           
 
`cld` is computed in `qc_avhrr` (file `qcmod.f90`) for avhrr and viirs data.  

Compare `qc_avhrr` between `CADS_for_Andrew` and `develop`.  Notice that `develop` uses a local variable `cloudp` for internal calculations.   `cloudp` is loaded into output variable `cld` when certain conditions are satisfied.    `CADS_for_Andrew` does not use `cloudp`.  It uses `cld` for internal calculations.

Modify `CADS_for_Andrew` `qc_avhrr` to mimic `develop` behavior.   Rebuild and rerun global_3dvar ctest.   With the modified `qc_avhrr` the `CADS_for_Andrew` and `develop` initial radiance penalties are identical for all printed digits.

The analysis results differ.  The first iteration step size differs in the 15th of 19 printed digits.  The intial total penalty and gradients are identical between `CADS_for_Andrew` and `develop`.

**_We need to examine `qc_avhrr` in `CADS_for_Andrew`.   Do we expect `CADS_for_Andrew` to yield different QC for avhrr and viirs when CADS is off?_**

**Comment by ADCollard** [comment]
@RussTreadon-NOAA Is it possible to add @erinjones2 as a reviewer for this?  She does not appear to be part of this project, even though she has a [current PR](https://github.com/NOAA-EMC/GSI/pull/587).

I just think it would be useful for here to have visibility of these changes at least.

**Comment by RussTreadon-NOAA** [comment]
@erinjones2 , @ADCollard would like to add you as a reviewer of this PR.  To do so I need to invite you as a collaborator.  Let me know if you don't receive an invitation.

**Comment by RussTreadon-NOAA** [comment]
**Dogwood test**

Build `wx20jjung:CADS_for_Andrew` on Dogwood following production switch.  Run netcdf_fv3_regional.  Confirm non-reproducible results ... just like Cactus.

Do the following:
- manually bring `wx20jjung:CADS_for_Andrew` up to date with current head of NOAA-EMC/GSI `develop`
- revert PR #616 changes to `read_airs.f90` and `read_bufrtovs.f90`.   Jim said these files should not change. 

Recompile and rerun netcdf_fv3_regional.  Non-reproducible results still present.

Do the following as the next set of changes:
- create subroutine `cads_run` to encapsulate CADS code added to `setuprad.f90`.   add `cads_run` to `cads.f90`
- recompile and rerun netcdf_fv3_regional

ctest still failed but this time the failure is due to timing scalability.  A check of the wall times did not find any anomalous behavior.  More importantly, the CADS code reproduced the `develop` analysis.  A big caveat here is that it's very likely that the CADS option does not work in the modified code.   I have no way to test the CADS option.

The modified code has been rsync'd from Dogwood to Hera `/scratch2/NCEPDEV/stmp1/Russ.Treadon/pr616`

```
Hera(hfe07):/scratch2/NCEPDEV/stmp1/Russ.Treadon/pr616$ git status
On branch CADS_for_Andrew
Your branch is up to date with 'origin/CADS_for_Andrew'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/gsi/cads.f90
        modified:   src/gsi/cplr_get_fv3_regional_ensperts.f90
        modified:   src/gsi/gsi_rfv3io_mod.f90
        modified:   src/gsi/qcmod.f90
        modified:   src/gsi/read_airs.f90
        modified:   src/gsi/read_bufrtovs.f90
        modified:   src/gsi/setupps.f90
        modified:   src/gsi/setuprad.f90
        modified:   src/gsi/setupspd.f90
```

Run all 9 ctests on Dogwood with the following results

```
russ.treadon@dlogin03:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616/build> ctest -j 9
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616/build
    Start 8: netcdf_fv3_regional
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 9: global_enkf
1/9 Test #8: netcdf_fv3_regional ..............***Failed  483.70 sec
2/9 Test #5: hwrf_nmm_d3 ......................   Passed  552.66 sec
3/9 Test #7: rrfs_3denvar_glbens ..............   Passed  605.16 sec
4/9 Test #4: hwrf_nmm_d2 ......................   Passed  606.31 sec
5/9 Test #9: global_enkf ......................   Passed  608.68 sec
6/9 Test #6: rtma .............................   Passed  1149.21 sec
7/9 Test #3: global_4denvar ...................   Passed  1382.56 sec
8/9 Test #1: global_3dvar .....................   Passed  1502.18 sec
9/9 Test #2: global_4dvar .....................   Passed  1562.14 sec

89% tests passed, 1 tests failed out of 9

Total Test time (real) = 1562.27 sec

The following tests FAILED:
          8 - netcdf_fv3_regional (Failed)
```
The netcdf_fv3_regional failure is due to
```
The case has Failed the scalability test.
The slope for the update (.827337 seconds per node) is less than that for the control (2.138150 seconds per node).
```
The wall times, however, do not look unreasonable
```
russ.treadon@dlogin03:/lfs/h2/emc/ptmp/russ.treadon/pr616/tmpreg_netcdf_fv3_regional> grep wall */stdout
netcdf_fv3_regional_hiproc_contrl/stdout:The total amount of wall time                        = 61.996823
netcdf_fv3_regional_hiproc_updat/stdout:The total amount of wall time                        = 63.060270
netcdf_fv3_regional_loproc_contrl/stdout:The total amount of wall time                        = 64.134973
netcdf_fv3_regional_loproc_updat/stdout:The total amount of wall time                        = 63.722140
```

**Comment by wx20jjung** [comment]
Russ,

I made these OMP changes you requested.

**Comment by wx20jjung** [comment]
> **`setuprad.f90` question**
> 
> We have a CADS if-block inside the big n loop over the observations in `setuprad.f90`. Each call to `setuprad` is for a different `obstype` and `isis` combination.
> 
> ```
> ! Loop over data in this block                                                                                                                     
>   call dtime_setup()
>   do n = 1,nobs
> !    Extract analysis relative observation time.                                                                                                   
>      dtime = data_s(itime,n)
> 
> ...
> 
> !  Generate model derived imager values for IASI or CrIS for CADS                                                                                  
> 
>           if ((iasi_cads .and. iasi) .or. (cris_cads .and. cris)) then
>                call destroy_crtm
>                itmp1_cads = len(trim(obstype))
>                itmp2_cads = len(trim(isis))
>              if ( iasi ) then
>                isis_cads = 'avhrr3'//isis(itmp1_cads+1:itmp2_cads)
>                obstype_cads = 'avhrr'
>                nchanl_cads = 3   ! CRTM channels 3 - 5                                                                                             
>              elseif ( cris ) then
> !!               isis_cads = 'viirs-m'//isis(itmp1+1:itmp2) When naming convention becomes standarized with CrIS                                   
>                if ( isis == 'cris-fsr_npp' ) isis_cads = 'viirs-m_npp'
>                if ( isis == 'cris-fsr_n20' ) isis_cads = 'viirs-m_j1'
>                if ( isis == 'cris-fsr_n21' ) isis_cads = 'viirs-m_j2'
>                obstype_cads = 'viirs-m'
>                nchanl_cads = 5   !CRTM channels 12 - 16                                                                                            
>              endif
>              allocate(data_s_cads(nreal+nchanl_cads),ich_cads(nchanl_cads),tsim_cads(nchanl_cads),emissivity_cads(nchanl_cads), &
>                     chan_level_cads(nchanl_cads),ptau5_cads(nsig,nchanl_cads), ts_cads(nchanl_cads),emissivity_k_cads(nchanl_cads), &
>                     temp_cads(nsig,nchanl_cads),wmix_cads(nsig,nchanl_cads), jacobian_cads(nsigradjac,nchanl_cads))
> 
>              jc = 0
>              do k=1,jpch_rad
>                if (isis_cads == nusis(k)) then
>                  jc = jc +1
>                  ich_cads(jc) = k
>                endif
>              end do
> 
>              data_s_cads = data_s(1:nreal+nchanl_cads,n)
>              call init_crtm(init_pass,-99,mype,nchanl_cads,nreal,isis_cads,obstype_cads,radmod)
> 
>              call call_crtm(obstype_cads,dtime,data_s_cads(:),nchanl_cads,nreal,ich_cads, &
>                 tvp,qvp,qs,clw_guess,ciw_guess,rain_guess,snow_guess,prsltmp,prsitmp, &
>                 trop5,tzbgr,dtsavg,sfc_speed, &
>                 tsim_cads,emissivity_cads,chan_level_cads,ptau5_cads,ts_cads,emissivity_k_cads, &
>                 temp_cads,wmix_cads,jacobian_cads,error_status)
> 
> !  Transfer imager data to arrays for qc_irsnd                                                                                                     
> 
>              imager_cluster_fraction = data_s(32:38,n)
>              imager_cluster_bt(1,:) = data_s(39:45,n)
>              imager_cluster_bt(2,:) = data_s(46:52,n)
>              imager_chan_stdev = data_s(53:54,n)
>              imager_model_bt = tsim_cads(nchanl_cads-1:nchanl_cads)
> 
>              deallocate(data_s_cads,ich_cads,tsim_cads,emissivity_cads, &
>                       chan_level_cads,ptau5_cads, ts_cads,emissivity_k_cads, &
>                       temp_cads,wmix_cads, jacobian_cads)
>               call destroy_crtm
> 
> !  Re-initialize the crtm for the current instrument                                                                                               
>               call init_crtm(init_pass,iwrmype,mype,nchanl,nreal,isis,obstype,radmod)
> 
>             endif  ! end of section for colocated imagers,      
> ```
> 
> Three questions.
> 
>     1. Each entry into `setuprad` is for a unique `obstype` and `isis` combination.  Given this, can we move some of the CADS setup stuff before the big `do n` loop over all the observations?
> 
>     2. Before entering the CADS block `crtm_init` has been called using `radmod`.  The code references `radmod%` component.
>        When we call `crtm_init` from inside the CADS block, we reuse `radmod`.   Before we exit the CADS block we call `crtm_init` again with `radmod`.  Is is safe to reuse and reset `radmod` inside the CADS block?  Would it be safer to declare and use a new variable, say `radmod_cads` inside the CADS block?
> 
>     3. In the CADS block we load `data_s_cads` with a subset of values from `data_s`.   We call `call_crtm` with `data_s_cads`.  After this we load `imager_*` arrays with values from `data_s`
> 
> 
> ```
>              data_s_cads = data_s(1:nreal+nchanl_cads,n)
>              call init_crtm(init_pass,-99,mype,nchanl_cads,nreal,isis_cads,obstype_cads,radmod)
> 
>              call call_crtm(obstype_cads,dtime,data_s_cads(:),nchanl_cads,nreal,ich_cads, &
>                 tvp,qvp,qs,clw_guess,ciw_guess,rain_guess,snow_guess,prsltmp,prsitmp, &
>                 trop5,tzbgr,dtsavg,sfc_speed, &
>                 tsim_cads,emissivity_cads,chan_level_cads,ptau5_cads,ts_cads,emissivity_k_cads, &
>                 temp_cads,wmix_cads,jacobian_cads,error_status)
> 
> !  Transfer imager data to arrays for qc_irsnd                                                                                                     
> 
>              imager_cluster_fraction = data_s(32:38,n)
>              imager_cluster_bt(1,:) = data_s(39:45,n)
>              imager_cluster_bt(2,:) = data_s(46:52,n)
>              imager_chan_stdev = data_s(53:54,n)
> ```
> 
> Should we load `data_s_cads` into the `imager_*` arrays instead of `data_s`?

As per our discussion, I have moved the allocate and deallocate statements outside of the main loop.  I’ve added tests for the SpcCoeff and TauCoeff file existence.  I’ve also added tests to accommodate j1/n20 and j2/n21 file names for VIIRS.  There is also a test now for the existence of the VIIRS/AVHRR information.  If it doesn’t exist, the imager values are all set to zero and the CRTM calls are not made.
Question 1)  Yes, I moved several tests and the allocate/deallocate statements outside of the loop.
Question 2)  I tested this scenario with radmod as-is and with radmod_cads.  Both produced identical results on S4.  The code now has radmod_cads for my work.
Question 3)  The imager (AVHRR/VIIRS) information is co-located onto the IASI/CrIS footprint.  CADS requires the model derived brightness temperature of the imager on this footprint.  This is why the first 31 entries for data_s are put into data_s_cads.  Once the brightness temperature is calculated, the data_s_cads array is no longer needed.   I can’t just use data_s because the imager and sounder channels are very different and I also have the cads, dval, and nsst info that is not needed. The imager_cluster_fraction, imager_cluster_bt and imager_chan_stdev are in the BUFR file, sent through setuprad and qcmod, to CADS.

**Comment by wx20jjung** [comment]
John,
Chan_level now has a CADS if statement around the loop.

The cloud parameter calculations and channel accept/reject statements have been restructured to an if – then – else statement.

There should be no changes to read_bufrtovs.  I replaced it with the develop version.

The dval hardwired codes in both read_cris and read_iasi now use maxinfo plus cads_info plus the dval increment.

Read_cris and read_iasi have specific mnemonics in the BUFR file for the imager information.  The code added to these routines is to use this information within CADS.  CADS does not require co-located imager information but it is very helpful.  AIRS does have an imager but the BUFR file does not have the mnemonics for these data.  In the case where imager data is not available, CADS does not run these specific cloud tests.

I replaced the abi2km to its original form.   This code (in its original form) causes an array out of bounds error.  
real(r_kind),dimension(nchanl) :: abi2km_bc
nchanl =3.  I do not see where the indexing is changed from1-3 to 2-4.  So this statement is out of bounds. 
abi2km_bc(4) = 250.5_r_kind
Running the code in debug mode flags this.  
I do not see where abi2km is used anywhere else in the gsi.

**Comment by RussTreadon-NOAA** [comment]
Change this PR to draft mode while we investigate non-reproducible results with respect to `develop` on WCOSS2.

**Comment by wx20jjung** [comment]
Putting the subroutine into the CADS module created a dependency circular loop so the compiler would not build it.  I then moved the subroutine into its own module.  This had problems as well with the crtm_interface module.  The various "save" statements create problems. I deduced there can only be one instance of the crtm on a task at a time.

I put the CADS_imager  code before the main NOBS loop in setuprad.  I had to move the read for data_s and dtime up within setuprad in order for this to work.  The code seems to be working as I expect.  My static tests on S4 are identical and the updated unit tests worked on Hera yesterday.

If this still does not pass the WCOSS tests, I will try putting the CADS_imager code in a subroutine but it will have to be called from this same location (before the main nobs loop) in setuprad.

**Comment by wx20jjung** [comment]
I put the model equivalent brightness temperature calculations in a subroutine.  This subroutine is called before the large "1 to nobs" loop in setuprad.  The new subroutine, cads_imager_calc, was added to the bottom of the module rad_setup.  My tests on S4 continue to be bit identical.  These changes also passed all of the unit tests on Hera.  

My tests on S4 have now moved to the time when CrIS_NPP band 1 failed.  CADS is printing out the following message:

**CADS_Detect_Cloud - WARNING: CHANNELS NOT FOUND CYCLING BAND: **

There is a message for each profile for each outer loop.  Because of the instrument failure, there are ~40,000 messages per cycle,  This message does not exist under normal operations.  There are a few options if this is a problem.  I can remove the write statement from CADS or I can remove the comment from:
 if( iskip >= 10 ) cycle read_loop
in read_cris.f90 and reject the instrument at the read.

**Comment by ADCollard** [comment]
ctests with the latest version are still failing on WCOSS2.

```
Test project /lfs/h2/emc/da/noscrub/andrew.collard/git/GSI_CADS/build
    Start 1: global_4denvar
1/7 Test #1: global_4denvar ...................***Failed  1326.30 sec
    Start 2: rtma
2/7 Test #2: rtma .............................   Passed  969.50 sec
    Start 3: rrfs_3denvar_glbens
3/7 Test #3: rrfs_3denvar_glbens ..............   Passed  485.34 sec
    Start 4: netcdf_fv3_regional
4/7 Test #4: netcdf_fv3_regional ..............***Failed  483.08 sec
    Start 5: hafs_4denvar_glbens
5/7 Test #5: hafs_4denvar_glbens ..............***Failed   60.27 sec
    Start 6: hafs_3denvar_hybens
6/7 Test #6: hafs_3denvar_hybens ..............***Failed   60.20 sec
    Start 7: global_enkf
7/7 Test #7: global_enkf ......................   Passed  610.49 sec

43% tests passed, 4 tests failed out of 7

Total Test time (real) = 3995.64 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          4 - netcdf_fv3_regional (Failed)
          5 - hafs_4denvar_glbens (Failed)
          6 - hafs_3denvar_hybens (Failed)
```

I will dig to see if there is anything else we can do

**Comment by ADCollard** [comment]
> I put the model equivalent brightness temperature calculations in a subroutine. This subroutine is called before the large "1 to nobs" loop in setuprad. The new subroutine, cads_imager_calc, was added to the bottom of the module rad_setup. My tests on S4 continue to be bit identical. These changes also passed all of the unit tests on Hera.
> 
> My tests on S4 have now moved to the time when CrIS_NPP band 1 failed. CADS is printing out the following message:
> 
> **CADS_Detect_Cloud - WARNING: CHANNELS NOT FOUND CYCLING BAND: **
> 
> There is a message for each profile for each outer loop. Because of the instrument failure, there are ~40,000 messages per cycle, This message does not exist under normal operations. There are a few options if this is a problem. I can remove the write statement from CADS or I can remove the comment from: if( iskip >= 10 ) cycle read_loop in read_cris.f90 and reject the instrument at the read.

@wx20jjung I think getting rid of these error messages would be good.  Move the comment from the read_loop.

**Comment by wx20jjung** [comment]
All of the CADS cloud detection channels for CrIS instruments are in band 1 (chans 1-713).  Band 1 has failed for CrIS_NPP.  I changed the logic in read_cris.f90 to reflect this.  If the cris_cads flag is true and band 1 is missing, the profile is rejected.   If cris_cads is false, nothing has changed.  CADS does not use bands 2 or 3 for cloud detection so having band 2 missing from CrIS_NPP does not compromise its performance.  I also added the verbose flag in front of the various write statements in CADS to limit the log file output.

**Comment by RussTreadon-NOAA** [comment]
**Additional WCOSS2 tests**

1. Commenting out the zeroing of the `imager_*` arrays in `setuprad.f90` results in non-reproducible results.   Seems we need to retain
```
! If using CADS setup arrays and calculate imager BTs                                                                                     
  imager_cluster_fraction = zero                                                                                                        
  imager_cluster_bt = zero                                                                                                              
  imager_chan_stdev = zero                                                                                                              
  imager_model_bt = zero                                                                                                                
  if ((iasi_cads .and. iasi) .or. (cris_cads .and. cris)) then
    call cads_imager_calc(obstype,isis,nobs,nreal,nchanl,nsig,data_s,init_pass,mype, &
                             imager_cluster_fraction,imager_cluster_bt,imager_chan_stdev, imager_model_bt)
  endif ! using cads                                                       
```                                                               

2. Reverting `cloudp, cld` changes in subroutine `qc_geocsr` did not result in any failed tests.  Does this mean the changes `qc_geoscr` are not necessary?   I don't know.  We should consult someone more familar with the inner workings of this routine.

**Comment by wx20jjung** [comment]
Russ,

1) The alternative to this would be to comment out the else portion at the
end of subroutine cads_imager_calc (at the bottom of cads.f90).
   else
     imager_cluster_fraction(1:7,1:nobs) = zero
     imager_cluster_bt(1:2,1:7,1:nobs) = zero
     imager_chan_stdev(1:2,1:nobs) = zero
     imager_model_bt(1:2,1:nobs) = zero

As you stated earlier, this should be redundant.  I am testing some of your
other changes and will try removing this code later tonight.  I will be
surprised if S4 complains.  I do have concerns about radmod with these
changes.  The radmod structure is an intent(in) to init_crtm().  The
comments say it contains all-sky and aerosol information.  Seems to not be
necessary for infrared sensors yet.

2)  The results of this change should be identical.  In this case it is the
addition of a local variable and makes this section of code similar to code
in qc_avhrr.

**Comment by RussTreadon-NOAA** [comment]
@wx20jjung , good news ... `wx20jjung:CADS_for_Andrew` at 7e250a6d4 reproduces the current head of NOAA-EMC/GSI `develop`.   All seven ctests pass on WCOSS2 (Cactus)

```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  483.45 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  485.38 sec
3/7 Test #7: global_enkf ......................   Passed  610.67 sec
4/7 Test #2: rtma .............................   Passed  968.40 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1210.82 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1270.59 sec
7/7 Test #1: global_4denvar ...................   Passed  1382.47 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1382.48 sec
```

Does 7e250a6d4  still work OK when you exercise CADS?

FYI:  The run directory for the WCOSS2 (Cactus) ctests is `/lfs/h2/emc/ptmp/russ.treadon/pr616`.   Each ctest runs in a directory whose name identifies the test.  For example, `tmpreg_global_4denvar` contains five directories
- global_4denvar_hiproc_contrl - develop `gsi.x` using high task count
- global_4denvar_hiproc_updat - wx20jjung:CADS_for_Andrew `gsi.x using high task count
- global_4denvar_loproc_contrl - develop `gsi.x` using low task count
- global_4denvar_loproc_updat - wx20jjung:CADS_for_Andrew `gsi.x` using low task count
- tmpreg_global_4denvar - ctest checks

**Comment by wx20jjung** [comment]
Everything looks OK with CADS for IASI.  I want to look deeper into the
CrIS stats on the few test days I have.  I should be able to confirm this
by tomorrow.

**Comment by wx20jjung** [comment]
My CADS tests with CrIS also look OK.  Please restart the pull request.

**Comment by RussTreadon-NOAA** [comment]
Install `develop` at [47f35ee](https://github.com/NOAA-EMC/GSI/commit/47f35eea5f1d3f9b85cc78b841536d723bea83e2) and `wx20jjung:CADS_for_Andrew` at [7e250a6](https://github.com/wx20jjung/GSI/commit/7e250a6d419866827fe0214905a51ec9d066bbc4) on Cactus (WCOSS2), Hera, and Orion.  Run standard suite of ctests with the following results:

**WCOSS2**
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  486.16 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  490.00 sec
3/7 Test #7: global_enkf ......................   Passed  610.44 sec
4/7 Test #2: rtma .............................   Passed  969.24 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1221.35 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1274.56 sec
7/7 Test #1: global_4denvar ...................   Passed  1394.79 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1394.92 sec
```
**Hera**
```
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr616/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  544.02 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  609.05 sec
3/7 Test #7: global_enkf ......................   Passed  930.06 sec
4/7 Test #6: hafs_3denvar_hybens ..............   Passed  1409.20 sec
5/7 Test #2: rtma .............................   Passed  1513.33 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1585.25 sec
7/7 Test #1: global_4denvar ...................   Passed  1915.20 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1915.23 sec
```
**Orion**
```
Test project /work2/noaa/da/rtreadon/git/gsi/pr616/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  482.62 sec
2/7 Test #7: global_enkf ......................   Passed  487.91 sec
3/7 Test #3: rrfs_3denvar_glbens ..............   Passed  605.08 sec
4/7 Test #2: rtma .............................   Passed  970.50 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1336.18 sec
6/7 Test #5: hafs_4denvar_glbens ..............***Failed  1517.68 sec
7/7 Test #1: global_4denvar ...................   Passed  1561.88 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) = 1561.89 sec

The following tests FAILED:
          5 - hafs_4denvar_glbens (Failed)
```
The `hafs_4denvar_glbens` test failed the runtime check
```
The runtime for hafs_4denvar_glbens_loproc_updat is 414.226832 seconds.  This has exceeded maximum allowable threshold time of 409.701244 seconds,
resulting in Failure time-thresh of the regression test.
```
Rerun `hafs_4denvar_glbens`.  The rerun passed
```
Test project /work2/noaa/da/rtreadon/git/gsi/pr616/build
    Start 5: hafs_4denvar_glbens
1/1 Test #5: hafs_4denvar_glbens ..............   Passed  1517.25 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 1517.33 sec
```

All ctests pass on WCOSS2 (Cactus), Hera, and Orion.

**Review by RussTreadon-NOAA — DISMISSED** [review]
ctests pass on WCOSS2 (Cactus), Hera, and Orion.   This is an expected results since CADS is off by default.   @wx20jjung confirms that CADS code is working as intended when activated.

Approve.

**Comment by RussTreadon-NOAA** [comment]
@wx20jjung , this PR can be scheduled for merger into `develop` pending approval from two peer reviews.   Please follow up with peer reviewers.

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA @wx20jjung I will review this PR if you can add me as a reviewer.

**Comment by RussTreadon-NOAA** [comment]
> @RussTreadon-NOAA @wx20jjung I will review this PR if you can add me as a reviewer.

Thank you @DavidHuber-NOAA .  You've been added as a reviewer.

File: src/gsi/qcmod.f90 [hunk 6]
```diff
@@ -2101,13 +2112,14 @@ subroutine qc_irsnd(nchanl,is,ndat,nsig,ich,sea,land,ice,snow,luse,goessndr,   &
...
 !     cenlat       - latitude of observation
+!     cenlon       - longitude of observation
 !     frac_sea     - fraction of grid box covered with water
 !     pangs        - solar zenith angle
 !     trop5        - tropopause pressure
 !     zasat        - satellite zenith angle
 !     tzbgr        - Tz over water
 !     tsavg5       - surface skin temperature
-!     tbc          - simulated - observed BT with bias correction
+!     tsim         - simulated - observed BT with bias correction
```
Comment (DavidHuber-NOAA) [inline src/gsi/qcmod.f90]: `tbc` is still defined as an input.  Has its definition changed?

File: src/gsi/qcmod.f90 [hunk 7]
```diff
@@ -2142,47 +2158,61 @@ subroutine qc_irsnd(nchanl,is,ndat,nsig,ich,sea,land,ice,snow,luse,goessndr,   &
...
 
-  logical,                            intent(in   ) :: sea,land,ice,snow,luse,goessndr, cris, hirs
+  logical,                            intent(in   ) :: sea,land,ice,snow,luse,goessndr,airs,cris,hirs,iasi
   logical,                            intent(inout) :: zero_irjaco3_pole
   integer(i_kind),                    intent(in   ) :: nsig,nchanl,ndat,is
   integer(i_kind),dimension(nchanl),  intent(in   ) :: ich
   integer(i_kind),dimension(nchanl),  intent(inout) :: id_qc
   integer(i_kind),dimension(nchanl),  intent(in   ) :: kmax
-  real(r_kind),                       intent(in   ) :: zsges,cenlat,frac_sea,pangs,trop5
+  real(r_kind),                       intent(in   ) :: zsges,cenlat,cenlon,frac_sea,pangs,trop5
```
Comment (DavidHuber-NOAA) [inline src/gsi/qcmod.f90]: `cenlon` isn't used.

File: src/gsi/read_cris.f90 [hunk 8]
```diff
@@ -756,12 +820,12 @@ subroutine read_cris(mype,val_cris,ithin,isfcalc,rmesh,jsatid,gstime,&
               bufr_chan = bufr_index(i)
               if(temperature(bufr_chan) <= tbmin .or. temperature(bufr_chan) >= tbmax ) then
                  temperature(bufr_chan) = tbmin
-                 if(iuse_rad(ioff+i) >= 0) iskip = iskip + 1
+                 if(iuse_rad(ioff+i) >= 0 .or. (cris_cads .and. sc_index(i) < 714)) iskip = iskip + 1
```
Comment (DavidHuber-NOAA) [inline src/gsi/read_cris.f90]: A named constant instead of `714` would be preferred here.

File: src/gsi/read_cris.f90 [hunk 9]
```diff
@@ -301,46 +322,89 @@ subroutine read_cris(mype,val_cris,ithin,isfcalc,rmesh,jsatid,gstime,&
...
+     sensorlist_imager = 'viirs-m_n21'
+     inquire(file=trim(spc_filename), exist=imager_coeff)
+     if ( .not. imager_coeff ) spc_filename = trim(crtm_coeffs_path)//'viirs-m_j2.SpcCoeff.bin'
+     sensorlist_imager = 'viirs-m_j2'
+  endif   
+  inquire(file=trim(spc_filename), exist=imager_coeff)
+  if ( imager_coeff ) then
+     allocate( sensorlist(2))
+     sensorlist(1) = sis
+!    sensorlist(2) = 'viirs-m_'//trim(jsatid)        !when viirs naming conventions becomes standardized
```
Comment (DavidHuber-NOAA) [inline src/gsi/read_cris.f90]: Perhaps just add a `TODO` to the beginning of this comment.

File: src/gsi/read_cris.f90 [hunk 10]
```diff
@@ -301,46 +322,89 @@ subroutine read_cris(mype,val_cris,ithin,isfcalc,rmesh,jsatid,gstime,&
      'SAID YEAR MNTH DAYS HOUR MINU SECO CLATH CLONH SAZA BEARAZ SOZA SOLAZI'
 
 ! Load spectral coefficient structure  
-  sensorlist(1)=sis
   quiet=.not. verbose
+
+  imager_coeff = .false. 
+!  spc_filename = trim(crtm_coeffs_path)//'viirs-m_'//trim(jsatid)//'.SpcCoeff.bin'  ! when viirs naming convention becomes standarized
```
Comment (DavidHuber-NOAA) [inline src/gsi/read_cris.f90]: Perhaps add a TODO to this comment

**Review by DavidHuber-NOAA — CHANGES_REQUESTED** [review]
Just  a few cleanups.

File: src/gsi/read_cris.f90 (hunk 10 above)
Comment (wx20jjung) [reply src/gsi/read_cris.f90]: The definition of tbc is correct.  The definition of tsim was changed to simulated brightness temperature.

Cenlon was removed from the argument list of qc_irsnd in both qcmod.f90 and setuprad.f90.

In read_cris.f90 714 was changed to the parameter band_2_start.  "TODO"s were added to the VIIRS statements.

**Comment by RussTreadon-NOAA** [comment]
`wx20jjung:CADS_for_Andrew` at af803552c installed on WCOSS2 (Cactus), Hera, and Orion.  ctests run with the following results

**WCOSS2 (Cactus)**
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  482.87 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  484.54 sec
3/7 Test #7: global_enkf ......................   Passed  608.61 sec
4/7 Test #2: rtma .............................   Passed  969.17 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1149.69 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1209.48 sec
7/7 Test #1: global_4denvar ...................   Passed  1321.96 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1321.97 sec
```

**Hera**
```
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr616/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  1026.77 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  1029.59 sec
3/7 Test #7: global_enkf ......................   Passed  1478.18 sec
4/7 Test #2: rtma .............................   Passed  2473.79 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  2482.62 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  2545.05 sec
7/7 Test #1: global_4denvar ...................   Passed  2573.92 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 2573.93 sec
```

**Orion**
```
Test project /work2/noaa/da/rtreadon/git/gsi/pr616/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  486.48 sec
2/7 Test #7: global_enkf ......................   Passed  621.16 sec
3/7 Test #3: rrfs_3denvar_glbens ..............***Failed  668.74 sec
4/7 Test #2: rtma .............................   Passed  969.89 sec
5/7 Test #1: global_4denvar ...................   Passed  1622.81 sec
6/7 Test #6: hafs_3denvar_hybens ..............   Passed  2293.37 sec
7/7 Test #5: hafs_4denvar_glbens ..............***Failed  2474.81 sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) = 2474.82 sec

The following tests FAILED:
          3 - rrfs_3denvar_glbens (Failed)
          5 - hafs_4denvar_glbens (Failed)
```
The rrfs_3denvar_glbens failure is due to the run time check
```
The runtime for rrfs_3denvar_glbens_loproc_updat is 173.359698 seconds.  This has exceeded maximum allowable threshold time of 166.973230 seconds,
resulting in Failure time-thresh of the regression test.
```
This is not a fatal failure.

The hafs_4denvar_glbens failure is due to the run time check
```
The runtime for hafs_4denvar_glbens_loproc_updat is 666.779203 seconds.  This has exceeded maximum allowable threshold time of 504.336197 seconds,
resulting in Failure time-thresh of the regression test.
```
This is not a fatal failure.

**Review by RussTreadon-NOAA — APPROVED** [review]
Approve.

**Review by DavidHuber-NOAA — APPROVED** [review]
Looks good, thanks @wx20jjung!

Approve.

**Comment by RussTreadon-NOAA** [comment]
@wx20jjung , GSI PR #624 has been merged into `develop`.   This PR updates the GSI build to spack-stack on non-production machines.   We should bring this update into `wx20jjung:CADS_for_Andrew`.   

I can rerun ctests on WCOSS2 after you update your branch.  PR #624 should not impact this PR but it's best to confirm by rerunning the ctests.  Would you please run ctests on Hera after you update your branch.   Do you ever run on Orion?

**Comment by wx20jjung** [comment]
I merged the latest develop branch with CADS_for_Andrew on S4 and the gsi
now fails.  I suspect this is an S4 issue but I need to back out of it, at
least on S4.  I will merge my CADS_for_Andrew copy on Hera and try the
crests there.

I have an orion account  but do not have allocations similar to WCOSS.

**Comment by RussTreadon-NOAA** [comment]
The S4 failure is unexpected.   @DavidHuber-NOAA , PR #624 was tested on S4, right?

I merged the current head of `develop` into my working copy of `CADS_for_Andrew` on Cactus.  WCOSS2 ctests results below

```
russ.treadon@clogin03:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr616_update/build> tail -f stdout_ctest.txt 
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............***Failed  483.39 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  485.31 sec
3/7 Test #7: global_enkf ......................   Passed  607.82 sec
4/7 Test #2: rtma .............................   Passed  967.37 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1209.49 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1209.60 sec
7/7 Test #1: global_4denvar ...................   Passed  1322.06 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) = 1322.06 sec

The following tests FAILED:
          4 - netcdf_fv3_regional (Failed)
Errors while running CTest
```
The `netcdf_fv3_regional` is due to 
```
The memory for netcdf_fv3_regional_loproc_updat is 289288 KBs.  This has exceeded maximum allowable memory of 191276 KBs,
resulting in Failure memthresh of the regression test.
```
The loproc_updat  task 0 memory usage is indeed noticeably higher than the contrl
```
netcdf_fv3_regional_hiproc_contrl/stdout:The maximum resident set size (KB)                   = 358996
netcdf_fv3_regional_hiproc_updat/stdout:The maximum resident set size (KB)                   = 362660
netcdf_fv3_regional_loproc_contrl/stdout:The maximum resident set size (KB)                   = 173888
netcdf_fv3_regional_loproc_updat/stdout:The maximum resident set size (KB)                   = 289288
```

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA Yes, #624 was tested in the global workflow on S4 at C96/C48 deterministic/ensemble resolutions.

**Comment by RussTreadon-NOAA** [comment]
Thank you @DavidHuber-NOAA for the confirmation.  Jim's failure is puzzling.

**Comment by DavidHuber-NOAA** [comment]
@wx20jjung @RussTreadon-NOAA The issue on S4 is that the wrong modules are being loaded at runtime.  Since the job is running within the global-workflow, it is still loading hpc-stack modules (e.g. hdf5/1.10.6), which is causing the crash.  You are welcome to try and merge in `git@github.com:DavidHuber-NOAA/global-workflow -b feature/spack-stack` OR just copy over the `module_base.s4.lua` and `versions/run.s4.ver` files.

**Comment by wx20jjung** [comment]
These files are in gw_ss ?

**Comment by DavidHuber-NOAA** [comment]
@wx20jjung Yes, though I forgot that there are a few version files you will need to copy.  You may be better off just copying over the contents of `/data/users/dhuber/gw_ss/versions/{build.,run.}*` and `/data/users/dhuber/gw_ss/modulefiles/*`.  Also, you may need to copy over the job script `gw_ss/jobs/rocoto/anal.sh`, which removes a module kludge.

**Comment by wx20jjung** [comment]
I am not able to run my internal CADS cycle tests as my global-workflow is not compatible (yet) with these changes.  I did run the ctests on hera.  Here are the results.

    Start 1: [=[global_4denvar]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 2: [=[rtma]=]
    Start 7: [=[global_enkf]=]
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 4: [=[netcdf_fv3_regional]=]
1/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  726.39 sec
2/7 Test #3: [=[rrfs_3denvar_glbens]=] ........   Passed  729.70 sec
3/7 Test #7: [=[global_enkf]=] ................   Passed  1185.37 sec
4/7 Test #2: [=[rtma]=] .......................   Passed  1573.52 sec
5/7 Test #6: [=[hafs_3denvar_hybens]=] ........   Passed  1582.41 sec
6/7 Test #5: [=[hafs_4denvar_glbens]=] ........   Passed  1702.54 sec
7/7 Test #1: [=[global_4denvar]=] .............   Passed  1852.18 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1852.19 sec

**Comment by RussTreadon-NOAA** [comment]
**Orion ctests**
Manually merged the head of `develop` into `wx20jjung:CADS_for_Andrew`.  Build updated working copy on Orion and run ctests with the following results
```
Test project /work2/noaa/da/rtreadon/git/gsi/pr616_update/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  484.67 sec
2/7 Test #7: global_enkf ......................   Passed  489.37 sec
3/7 Test #3: rrfs_3denvar_glbens ..............   Passed  607.09 sec
4/7 Test #2: rtma .............................   Passed  970.90 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1396.86 sec
6/7 Test #1: global_4denvar ...................***Failed  1502.96 sec
7/7 Test #5: hafs_4denvar_glbens ..............***Failed  1637.40 sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) = 1637.42 sec

The following tests FAILED:
          1 - global_4denvar (Failed)
          5 - hafs_4denvar_glbens (Failed)
```

The `global_4denvar` test failed due to the runtime check
```
The runtime for global_4denvar_hiproc_updat is 307.642959 seconds.  This has exceeded maximum allowable threshold time of 304.149277 seconds,
resulting in Failure of timethresh2 the regression test.
```
The wall times do not look anomalous given high run to run variability on Orion, especially when running in the `/work` fileset.
```
global_4denvar_hiproc_contrl/stdout:The total amount of wall time                        = 276.499343
global_4denvar_hiproc_updat/stdout:The total amount of wall time                        = 307.642959
global_4denvar_loproc_contrl/stdout:The total amount of wall time                        = 373.393028
global_4denvar_loproc_updat/stdout:The total amount of wall time                        = 390.099795
```

The `hafs_4denvar_glbens` test failed for the same reason
```
The runtime for hafs_4denvar_glbens_hiproc_updat is 300.890503 seconds.  This has exceeded maximum allowable threshold time of 293.352983 seconds,
resulting in Failure of timethresh2 the regression test.
```
Again, the wall times to not look anomalous given high run to run variability on Orion
```
hafs_4denvar_glbens_hiproc_contrl/stdout:The total amount of wall time                        = 266.684530
hafs_4denvar_glbens_hiproc_updat/stdout:The total amount of wall time                        = 300.890503
hafs_4denvar_glbens_loproc_contrl/stdout:The total amount of wall time                        = 429.190717
hafs_4denvar_glbens_loproc_updat/stdout:The total amount of wall time                        = 433.160648
```

@wx20jjung , would you please update `wx20jjung:CADS_for_Andrew` with the current head of `develop`?

**Comment by wx20jjung** [comment]
I am getting the following error.  Can anyone help to resolve this?

***@***.*** GSI_CADS]$ git push origin CADS_for_Andrew
Counting objects: 56, done.
Delta compression using up to 48 threads.
Compressing objects: 100% (29/29), done.
Writing objects: 100% (30/30), 8.76 KiB | 0 bytes/s, done.
Total 30 (delta 19), reused 0 (delta 0)
remote: Resolving deltas: 100% (19/19), completed with 14 local objects.
To https://github.com/wx20jjung/GSI.git
 ! [remote rejected] CADS_for_Andrew -> CADS_for_Andrew (refusing to allow
a Personal Access Token to create or update workflow
`.github/workflows/gcc.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/wx20jjung/GSI.git'

**Comment by RussTreadon-NOAA** [comment]
@wx20jjung , not sure what the problem is.  Try the following

1. create a new directory. `mkdir update`
2. cd into the new directory.  `cd update`
3. `git clone --recursive https://github.com/wx20jjung/GSI.git .`
4. `git checkout CADS_for_Andrew`
5. `git submodule sync`
6. `git submodule update`
7. `git remote add upstream https://github.com/NOAA-EMC/GSI`
8. `git remote -v` ... make sure you see something like what's on the GSI [GS User Information wiki](https://github.com/NOAA-EMC/GSI/wiki/GSI-User-Information) under _Updating your Fork when the Official Repository is Updated_
9. `git remote update`   If you see a `fix` submodule error, ignore it.
10. `git merge upstream/develop`    This merges the authoritative `develop` into the working copy of your branch.  The merge command opens an editor.  Accept the provided commit log message. Exit the editor.   You should see something like the below

```
(gdasapp) Orion-login-3:/work/noaa/da/rtreadon/git/gsi/update$ git merge upstream/develop
hint: Waiting for your editor to close the file... PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
Display localhost:27.0 unavailable, simulating -nw
Merge made by the 'recursive' strategy.
 .github/workflows/gcc.yml          |  31 +++++++++++----------
 .github/workflows/intel.yml        |  47 +++++++++++++++++++-------------
 ci/spack.yaml                      |   4 +--
 modulefiles/gsi_cheyenne.gnu.lua   |  36 ++++++++++++------------
 modulefiles/gsi_cheyenne.intel.lua |  32 +++++++++++++---------
 modulefiles/gsi_common.lua         |  16 ++++++-----
 modulefiles/gsi_gaea.lua           |  24 ++++++++++------
 modulefiles/gsi_hera.gnu.lua       |  22 +++++++--------
 modulefiles/gsi_hera.intel.lua     |  21 ++++++--------
 modulefiles/gsi_hercules.lua       |  26 ++++++++++++++++++
 modulefiles/gsi_jet.lua            |  22 ++++++---------
 modulefiles/gsi_orion.lua          |  21 ++++++--------
 modulefiles/gsi_s4.lua             |  23 +++++++---------
 modulefiles/gsi_wcoss2.lua         |  28 ++++++++++++++++++-
 regression/regression_param.sh     | 137 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------
 regression/regression_var.sh       |  19 +++++++++----
 ush/detect_machine.sh              |   2 ++
 ush/module-setup.sh                |   7 +++++
 ush/sub_hercules                   | 170 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ush/sub_orion                      |   2 ++
 20 files changed, 485 insertions(+), 205 deletions(-)
 create mode 100644 modulefiles/gsi_hercules.lua
 create mode 100755 ush/sub_hercules
(gdasapp) Orion-login-3:/work/noaa/da/rtreadon/git/gsi/update$
```

Your local copy of `CADS_for_Andrew` is now update to date with `develop.   Push your updated working copy back to your repo.

11. `git push origin CADS_for_Andrew`

**Comment by wx20jjung** [comment]
I did this both on hera and s4.  I continue to get the same error.

**Comment by DavidHuber-NOAA** [comment]
@wx20jjung It looks like you are having trouble with your authentication.  You can try changing to ssh authentication:
```
git set-url origin git@github.com:wx20jjung/GSI.git
git push origin CADS_for_Andrew
```
This assumes you have an SSH key in your GitHub profile.  If this fails, you can follow [this guide to get set up](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account#adding-a-new-ssh-key-to-your-account).

**Comment by RussTreadon-NOAA** [comment]
1.  Very strange.  How did you update your branch with `develop` before?
2.  I didn't think I could push to your branch, but I tried `git push origin CADS_for_Andrew` and it worked

```
Orion-login-3:/work/noaa/da/rtreadon/git/gsi/update$ git push origin CADS_for_Andrew
Enumerating objects: 80, done.
Counting objects: 100% (56/56), done.
Delta compression using up to 80 threads
Compressing objects: 100% (18/18), done.
Writing objects: 100% (30/30), 8.04 KiB | 316.00 KiB/s, done.
Total 30 (delta 22), reused 18 (delta 11), pack-reused 0
remote: Resolving deltas: 100% (22/22), completed with 11 local objects.
To https://github.com/wx20jjung/GSI.git
   af803552c..88bf2ec52  CADS_for_Andrew -> CADS_for_Andrew
```

Your branch is now up to date with `develop`.

**Comment by RussTreadon-NOAA** [comment]
Please update the working copy of your branch and ensure that everything looks correct.

**Comment by RussTreadon-NOAA** [comment]
@wx20jjung , we can schedule this PR for merger into `develop` upon completion of the following two items
1. your confirmation that `wx20jjung:CADS_for_Andrew` at [88bf2ec](https://github.com/wx20jjung/GSI/commit/88bf2ec52c6a63612b0446d5a75bd63742ca0654) is acceptable
2. peer review and approval from either Andrew or Erin.  Would you please reach out to them?

**Review by ADCollard — APPROVED** [review]
