### PR TITLE
GitHub Issue NOAA-EMC/GSI#442. Bug fix of reading in radar level2 bufr

### LINKED ISSUE #442: Bug fix of reading in radar level2 bufr
NAM-GSI abort in Aug 2019 and Nov 2021 due to failure of reading in level2 radar bufr with error message:

min,max num_radars=          14          25
  index error in radar_bufr_read_all -- program stops --            0 KPAH
 ****STOP2****  ABORTING EXECUTION w/code=          99

The bug was found in building radar master table and finding the radar name index. In a special case, radar PAHG is happen to next to radar KLZK. The master table will be ...KLZ**KPAH**G...,  GSI then consider KPAH (radar name) is already available in the master radar table. This is caused GSI abort.

The bug is fixed by using a new function "locindex" to replace "index" to avoid the error of searching radar station name.

### PR DESCRIPTION
**Pull request by ShunLiu-NOAA**
NAM-GSI abort in Aug 2019 and Nov 2021 due to failure of reading in level2 radar bufr with error message:

min,max num_radars= 14 25
index error in radar_bufr_read_all -- program stops -- 0 KPAH
STOP2 ABORTING EXECUTION w/code= 99

The bug was found in building radar master table and finding the radar name index. In a special case, radar PAHG is happen to next to radar KLZK. The master table will be ...KLZKPAHG..., GSI then consider KPAH (radar name) is already available in the master radar table. This is caused GSI abort.

The bug is fixed by using a new function "locindex" to replace "index" to avoid the error of searching radar station name.

### CODE REVIEW

**Comment by MichaelLueken** [comment]
@ShunLiu-NOAA Your PR includes five commits rather than a single commit.  To correct this, please use the following commands:

- git reset --hard HEAD~1
- git reset --hard HEAD~1
- git reset --hard HEAD~1
- git reset --hard HEAD~1
- git remote add upstream https://github.com/NOAA-EMC/GSI.git
- git remote update
- git rebase upstream/develop
- git checkout readl2_bug_fix
- git checkout master
- git merge --squash readl2_bug_fix
- `git commit -m "GitHub Issue NOAA-EMC/GSI#442. Bug fix of reading in radar level2 bufr."`
- git push origin master --force

Once these steps have been completed, please let me know who you would like for me to assign to your PR as reviewers.

**Comment by ShunLiu-NOAA** [comment]
Thank you Mike.
I got message below. Is there anything wrong here?


(base) [Shun.Liu@hfe12 gsi] pwd
/scratch2/NCEPDEV/fv3-cam/save/Shun.Liu/gsi/GSI/src/gsi
(base) [Shun.Liu@hfe12 gsi] git merge --squash readl2_bug_fix
Squash commit -- not updating HEAD
Automatic merge went well; stopped before committing as requested
(base) [Shun.Liu@hfe12 gsi] git branch
* master
  readl2_bug_fix

**Comment by MichaelLueken** [comment]
> Thank you Mike. I got message below. Is there anything wrong here?
> 
> (base) [Shun.Liu@hfe12 gsi] pwd /scratch2/NCEPDEV/fv3-cam/save/Shun.Liu/gsi/GSI/src/gsi (base) [Shun.Liu@hfe12 gsi] git merge --squash readl2_bug_fix Squash commit -- not updating HEAD Automatic merge went well; stopped before committing as requested (base) [Shun.Liu@hfe12 gsi] git branch
> 
> * master
>   readl2_bug_fix

@ShunLiu-NOAA 

No, there is nothing wrong.  While using the squash merge, git won't commit the changes.  This is why the following line in the instructions is to use:

`git commit -m "GitHub Issue NOAA-EMC/GSI#442. Bug fix of reading in radar level2 bufr."`

which will commit the modified file with the required commit message.

**Comment by ShunLiu-NOAA** [comment]
Thanks. Just completed the last step.

**Comment by MichaelLueken** [comment]
> Thanks. Just completed the last step.

@ShunLiu-NOAA Did the final push succeed?  Both the PR and your fork's master branch still have the five commit messages rather than a single commit.  When doing the push, please ensure that you are using:

git push origin master --force

otherwise the push won't happen.

**Comment by ShunLiu-NOAA** [comment]
Thanks. Mike. Here it is.
(base) [Shun.Liu@hfe12 gsi] git push origin master --force
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 80 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 784 bytes | 196.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/ShunLiu-NOAA/GSI
 + 96c7990a...35ebd6a1 master -> master (forced update)

**Comment by MichaelLueken** [comment]
Thanks, @ShunLiu-NOAA!  The commit is good to go.

File: src/gsi/read_l2bufr_mod.f90 [hunk 1]
```diff
@@ -1054,4 +1056,16 @@ SUBROUTINE invtllv(ALM,APH,TLMO,CTPH0,STPH0,TLM,TPH)
   TPH=ASIN(CTPH0*SPH+STPH0*CC)
   return
 END SUBROUTINE invtllv
+FUNCTION locindex(stnall,nstr,stn)
+  character(4)::stnall(nstr)
+  character(4)::stn
+  integer:: i,locindex,nstr
```
Comment (MichaelLueken) [inline src/gsi/read_l2bufr_mod.f90]: All integer declarations require a length (i.e., integer(i_kind):: i,locindex,nstr)

File: src/gsi/read_l2bufr_mod.f90 [hunk 2]
```diff
@@ -1054,4 +1056,16 @@ SUBROUTINE invtllv(ALM,APH,TLMO,CTPH0,STPH0,TLM,TPH)
   TPH=ASIN(CTPH0*SPH+STPH0*CC)
   return
 END SUBROUTINE invtllv
+FUNCTION locindex(stnall,nstr,stn)
```
Comment (MichaelLueken) [inline src/gsi/read_l2bufr_mod.f90:1060]: All subroutines and functions require implicit none

File: src/gsi/read_l2bufr_mod.f90 [hunk 3]
```diff
@@ -1054,4 +1056,16 @@ SUBROUTINE invtllv(ALM,APH,TLMO,CTPH0,STPH0,TLM,TPH)
...
+  character(4)::stnall(nstr)
+  character(4)::stn
+  integer:: i,locindex,nstr
+  do i=1,nstr
+     locindex=index(stnall(i),stn)
+     if(locindex>0) then
+      locindex=i
+      exit
+     end if
```
Comment (MichaelLueken) [inline src/gsi/read_l2bufr_mod.f90]: Please ensure at least two-space indentation for if statements.

**Review by TingLei-NOAA — APPROVED** [review]
Good to me!  Thanks

File: src/gsi/read_l2bufr_mod.f90 (hunk 1 above)
Comment (MichaelLueken) [inline src/gsi/read_l2bufr_mod.f90]: Please ensure to include intent of passed variables:

integer(i_kind), intent(in):: nstr
character(4),intent(in)::stnall(nstr)
character(4),intent(in)::stn

integer(i_kind):: i,locindex

**Review by xyzemc — APPROVED** [review]

**Review by MichaelLueken — CHANGES_REQUESTED** [review]
Hi @ShunLiu-NOAA, I have completed my review of your bug fix.  Overall, everything looks good.  However, I noted a few issues with the new locindex function.  Please add `implicit none` to the function.  Please give the intent (i.e., intent(in)) for passed variables.  Please ensure that integer declarations include length (i.e., integer(i_kind)).  Please ensure that lines 1066 and 1067 are indented at least two spaces.

Once these modifications are made, please use:

git add read_l2bufr_mod.f90
git commit --amend
git push origin master --force

to commit and push the updated function to your branch.  After this is completed, I should be able to submit this work to the review committee.

Please let me know if you encounter any issues.

**Review by MichaelLueken — APPROVED** [review]
Thanks, @ShunLiu-NOAA, for addressing my concerns!  Everything looks good.

**Comment by ShunLiu-NOAA** [comment]
Mike,

Thank you for reviewing this.

Shun

**Comment by MichaelLueken** [comment]
The due date for feedback from the review committee has past, so I will now give final approval to these changes and merge them to the authoritative develop branch.
