### PR TITLE
fix for problems in ctests using debug mode of GSI release/rrfs1.0.0 

### LINKED ISSUE #860: problems running debug mode GSI on wcoss2 for release/rrfs1.0.0
This issue is to document the problems and fixes (if any) when we run GSI/release/rrfs.1.0.0 in debug mode on wcoss2 as @ShunLiu-NOAA suggested.
This branch is being used for rrfs real time jobs. 

The first problem was found when running the hafs ctests--hafs_3denvar_hybens  and the error was :
```
forrtl: error (182): floating invalid - possible uninitialized real/complex variable
.....
gsi.x              00000000037BD800  combine_radobs_           137  combine_radobs.f90
````
Use the combine_radobs.f90 in the current develop branch of EMC GSI, we got the same errors. 
Investigation reveal it was because data_all_in is not initialized/defined for all elements
```
!$omp parallel do private(kk,k,l)
     do kk=1,ndata
        k=nloc(kk)
        if(k > 0)then
           do l=1,nele
              data_all_in(l,kk)=data_all(l,k)
           end do
        else
           do l=1,nele
             data_all_in(l,kk)=zero
           end do
        end if

     end do
     deallocate(nloc)
!tracing codes
     do j = 1, ndata
       do i = 1, nele
           if (.not. ieee_is_finite(data_all_in(i,j))) then
                       write(6,*) " data_all_in(", i, ",", j, ") is NaN or Inf. Value =", data_all_in(i,j)
                end if
                                end do
                                end do**


     call mpi_reduce(data_all_in,data_all,nele*ndata,mpi_rtype,mpi_sum,&  ! line 137 pointed in the error messages
          mype_root,mpi_comm_sub,ierror)
     deallocate(data_all_in)

```
The above tracing print would give messages as :
```
 data_all_in(         639 ,          98 ) is NaN or Inf. Value =                     NaN
```
So, for safety data_all_in should be first initialized to zeros ( in fact, it should be done so in all same cases). 
The first question is that current combine_radobs.f90 is the version in GSI develop branch.  Should we update the one in develop branch and then the release/rffs1.0.0 to check from it?  or shall we just update this rrfs release branch.  A more general question is that the GSI develop branch contains some fixes as recently added by Russ, shall the rrfs branch be updated accordingly even those bugs would maybe not have impacts in rrfs runs? 
@ShunLiu-NOAA  since this is a hafs tests, I would also at hafs developers @BinLiu-NOAA @XuLu-NOAA @JingCheng-NOAA

### PR DESCRIPTION
**Pull request by TingLei-NOAA**
This is a draft PR to show fix for problems when running ctests using debug mode built GSI at rrfs.1.0.0.

Resolves #860 

Now the working ctests for this implementation are
```
Test project /lfs/h2/emc/da/noscrub/Ting.Lei/dr-emc-gsi-release_debug/GSI/build
  Test #1: global_4denvar
  Test #2: rtma
  
  Test #4: netcdf_fv3_regional
  Test #5: hafs_4denvar_glbens
  Test #6: hafs_3denvar_hybens
  Test #7: global_enkf
````
With this PR,  the update runs of all  ctests (except for global_enkf) successfully ran to completion.  
The global_enkf issue (a known issue) has  been investigated at  https://github.com/NOAA-EMC/GSI/issues/776.
Also, letkf is not used in the current rrfs workflow. 
Hence, the following tests would be to use real cases from current rrfsv1 to test the GSI::gsi and GSI :: regional EnKF

### CODE REVIEW

**Comment by TingLei-NOAA** [comment]
Using this PR built with the release mode in comparison with the rrfs1.0.0 result,  it is found both GSI::gsi and GSI::enkf produced identical results. But this PR is significantly faster for GSI:: gsi while slower for GSI::enkf. 
They are maybe caused by the real time situations.  But I would do some optimization for the changes for enkf.

**Comment by ShunLiu-NOAA** [comment]
@TingLei-daprediction, could you give a number of how slow it is for GSI:enkf?

**Comment by TingLei-NOAA** [comment]
In the  runs I already have, the PR Enkf used time 631 S while the control used 545s. 
Update, in a second run , the PR Enkf used 581 s, still longer than the previous control 's.

**Comment by TingLei-NOAA** [comment]
@ShunLiu-NOAA @hu5970  To avoid the additional computational time, I have removed the additional mpi_barrier as the work-around to prevent that runtime error with debug mode GSI::enkf.  I also did some optimization of the openmp directive in the changes to avoid "false sharing".   The current PR shows using less time in the recent two runs for the control and the PR. Hence, I think this PR is ready to be reviewed before merging. 
For the incorporation of the recent GSI::gsi optimization ([issue 879](https://github.com/NOAA-EMC/GSI/issues/879), I would suggest we use a different PR because that  optimization commit (by including merging with then-current develop branch) has all the changes in the develop branch which can't be singled out by "git cherry-pick" easily and hence would be more effort-consuming.

**Comment by ShunLiu-NOAA** [comment]
Thank you @TingLei-NOAA . We need another ISSURE/PR for GSI optimization test.

**Comment by TingLei-NOAA** [comment]
@ShunLiu-NOAA  I had opened the issue https://github.com/NOAA-EMC/GSI/issues/879.

**Comment by TingLei-NOAA** [comment]
@ShunLiu-NOAA   The numbers you asked for:  now,(skipped the writing of ensemble step ), the PR used the clock time 505 seconds while the control (RRFS1.0.0) used 519 seconds. 
The ensemble write-out step was skipped because I want to avoid real time env impacts on the speeding up. The IO step is most vulnerable to them.

**Comment by TingLei-NOAA** [comment]
@ShunLiu-NOAA  An update for the runs of the complete EnKF (with the step of ensemble output0.  The PR used 590 seconds  and the control 561 Seconds. They also produced the identical results by comparison the min/max of the ensemble increament mean   in their standard output .     The difference of the clock time should come from the real time system conditions. 
I think this PR is ready for reviewing .

**Comment by ShunLiu-NOAA** [comment]
Thank you Ting.

File: src/enkf/enkf.f90 [hunk 1]
```diff
@@ -191,6 +191,8 @@ subroutine enkf_update()
 integer(i_kind) nanal,nn,nnn,nobm,nsame,nn1,nn2,oz_ind,nlev,dbz_ind
 real(r_single),dimension(nlevs_pres):: taperv
 logical lastiter, kdgrid, kdobs
+real(r_single) :: meanval
+integer(i_kind):: j
```
Comment (SamuelDegelia-NOAA) [inline src/enkf/enkf.f90]: Is this integer `j` used anywhere?

File: src/gsi/combine_radobs.f90 [hunk 2]
```diff
@@ -62,6 +62,7 @@ subroutine combine_radobs(mype_sub,mype_root,&
   real(r_kind),allocatable,dimension(:):: data_crit_min
   real(r_kind),allocatable,dimension(:,:):: data_all_in
   integer(i_kind),allocatable,dimension(:):: icrit_min,icrit,nloc
+  integer(i_kind):: i,j
```
Comment (SamuelDegelia-NOAA) [inline src/gsi/combine_radobs.f90]: Same comment. Are `i` or `j` used anywhere?

Comment (TingLei-NOAA) [reply src/gsi/combine_radobs.f90]: @SamuelDegelia-NOAA , Thanks. I will remove them.

File: src/gsi/combine_radobs.f90 [hunk 3]
```diff
@@ -74,7 +75,7 @@ subroutine combine_radobs(mype_sub,mype_root,&
 
      nread=0
      if (mype_sub==mype_root) nread = ncounts1
-     if (ncounts1 == 0)return
+     if (ncounts1 <= 0)return
```
Comment (SamuelDegelia-NOAA) [inline src/gsi/combine_radobs.f90:77]: Just curious, can `ncounts1` ever be less than zero?

**Comment by SamuelDegelia-NOAA** [comment]
Had a couple of minor comments but overall the changes make sense and look good to me!

File: src/gsi/combine_radobs.f90 (hunk 3 above)
Comment (TingLei-NOAA) [reply src/gsi/combine_radobs.f90:77]: This is a change I incorporated from the current develop branch.

**Review by GangZhao-NOAA — APPROVED** [review]
Hi Ting,
The modifications look good to me.
Thank you!
-Gang

**Review by hu5970 — APPROVED** [review]

**Review by SamuelDegelia-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
@TingLei-NOAA , what is the status of this PR?  Should we keep it open, merge it, or close it?

**Comment by TingLei-NOAA** [comment]
@RussTreadon-NOAA  This is up to @ShunLiu-NOAA 's decision.  We have some concerns on the rrfs1.0.0 (the base of this PR) 's behavior (slower than expected) recently found on wcoss2.  This delayed this PR 's merging into rrfs1.0.0.

**Comment by RussTreadon-NOAA** [comment]
Thank you. @TingLei-NOAA , for the update.

**Comment by ShunLiu-NOAA** [comment]
@RussTreadon-NOAA I am going to test this PR again with real time parallel to check if it is slower than the current version.

**Comment by RussTreadon-NOAA** [comment]
Thank you @ShunLiu-NOAA for testing.  

Taking a step back, does the RRFS GSI we are preparing to send to NCO successfully run the RRFS in debug mode?   

- If _yes_, there is less need to merge the changes in this PR into [`NOAA-EMC:release/rrfs.v1.0.0`](https://github.com/NOAA-EMC/GSI/tree/release/rrfs.v1.0.0).
- If _no_, do the changes in this PR allow the debug `gsi.x` successfully run the RRFS in debug mode?
  - If _yes_, we need these changes or a variant of them in  [`NOAA-EMC:release/rrfs.v1.0.0`](https://github.com/NOAA-EMC/GSI/tree/release/rrfs.v1.0.0).
  - If _no_, we need to identify and fix the reason(s) for debug RRFS `gsi.x` failure(s).

**Comment by ShunLiu-NOAA** [comment]
> Thank you @ShunLiu-NOAA for testing.
> 
> Taking a step back, does the RRFS GSI we are preparing to send to NCO successfully run the RRFS in debug mode?
> 
> * If _yes_, there is less need to merge the changes in this PR into [`NOAA-EMC:release/rrfs.v1.0.0`](https://github.com/NOAA-EMC/GSI/tree/release/rrfs.v1.0.0).
> * If _no_, do the changes in this PR allow the debug `gsi.x` successfully run the RRFS in debug mode?
>   
>   * If _yes_, we need these changes or a variant of them in  [`NOAA-EMC:release/rrfs.v1.0.0`](https://github.com/NOAA-EMC/GSI/tree/release/rrfs.v1.0.0).
>   * If _no_, we need to identify and fix the reason(s) for debug RRFS `gsi.x` failure(s).

Yes. RRFS GSI will be sent to NCO. This PR is to ensure RRFS GSI is can run in debug mode. I tested this PR with RRFS parallel on WCOSS2. It performs as expected. We will merge the change to rrfs1.0.0.
